def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Rough clean of entire building": T(
 "A rough clean of the entire building is the first construction cleaning phase, done after framing, drywall and MEP rough-in. It removes bulk debris, heavy dust and slab residue from every floor before finish trades begin.",
 "If rough-stage dust and debris are left, they get sealed behind ceilings, ground into new flooring and pulled into ductwork. Every later phase costs more because of it.",
 "Crews work top floor down, removing debris first, then HEPA vacuuming and scraping slabs, so dust from upper floors does not fall onto floors already cleaned.",
 ["Total square footage and floor count", "Trades that must be complete before the rough clean", "Debris removal route and container plan", "Slab scraping and HEPA vacuuming requirements"],
 ["Starting before drywall finishing is done means repeating the work.", "A rough clean is not detail cleaning; set expectations with the owner."],
 [("What does a rough clean include?", "Bulk debris removal, slab scraping, HEPA vacuuming of floors, sills and openings, and clearing mechanical rooms and shafts."),
  ("How is a rough clean priced?", "Usually by square foot or by crew-day, based on debris volume, floors and access."),
  ("Is a rough clean required by specs?", "Many specs call for progress cleaning that covers it. It is also a practical step before finishes."),
  ("Can the rough clean be skipped on small projects?", "Sometimes, on small tenant spaces, if trades clean as they go. It usually makes the final clean harder.")]),
"Rough clean by floor or phase": T(
 "A rough clean by floor or phase cleans one floor, wing or area at a time as it is released by drywall and MEP trades, rather than waiting for the whole building.",
 "Large projects rarely finish rough-in everywhere at once. Phasing the rough clean lets finish trades start sooner in each released area.",
 "Crews follow the GC's release schedule, cleaning each area completely and documenting it as ready before the next trade enters.",
 ["Phase or floor release schedule", "Area sizes", "Documentation of released areas", "Crew availability for multiple mobilizations"],
 ["Multiple mobilizations can cost more; agree on pricing per phase.", "Adjacent active areas can re-soil cleaned ones."],
 [("Why phase a rough clean?", "So finish trades can start in each area as soon as it is ready."),
  ("Does phasing cost more?", "It can, due to more mobilizations, but it often saves schedule time."),
  ("How are phases defined?", "By floors, wings or zones in the GC's schedule."),
  ("How do you keep a cleaned phase clean?", "With barriers, mats and coordination with active trades nearby.")]),
"Interior wall stud bay vacuuming before close-in": T(
 "Interior wall stud bay vacuuming before close-in removes debris, dust, scraps and trash from inside open stud walls before drywall is hung on the second side.",
 "Debris sealed inside walls stays there for the life of the building: it can harbor pests, rattle, block cable pulls and create odors. Once the wall is closed, it is too late.",
 "Crews vacuum the bottom track and each stud cavity with HEPA crevice tools and pick out larger debris by hand, coordinating with insulation and inspection schedules.",
 ["Linear feet of walls to close", "Close-in inspection schedule", "Insulation installation timing", "Areas with low-voltage or plumbing in walls"],
 ["Do not disturb insulation, wiring or plumbing in the cavity.", "Food waste and trash in walls attracts pests."],
 [("Why clean inside walls before drywall goes on?", "Debris sealed in walls can attract pests, cause odors and get in the way of future work."),
  ("When is stud bay cleaning done?", "After MEP rough-in and inspection, before the second side of drywall."),
  ("What is found in stud bays?", "Drywall scraps, screws, food wrappers, bottles and wire clippings are common."),
  ("Who cleans stud bays?", "Often the drywall contractor or a cleanup crew hired by the GC.")]),
"Slab scraping of drywall mud and joint compound": T(
 "Slab scraping of drywall mud and joint compound removes hardened mud drips and patches from concrete slabs after taping and finishing, so flooring can be installed on a flat surface.",
 "Hardened joint compound under flooring creates bumps, telegraphs through vinyl and carpet, and prevents adhesive from bonding.",
 "Crews scrape with long-handled floor scrapers, HEPA vacuum the residue and spot-clean stubborn areas, keeping water to a minimum so mud does not smear.",
 ["Floor areas receiving new flooring", "Amount of mud on slabs", "Flooring installer's slab requirements", "Dust control"],
 ["Wet scrubbing mud can smear it into a film.", "Scraping can damage sealed or polished concrete; adjust tools."],
 [("Why scrape drywall mud off the slab?", "Bumps of mud under flooring show through and affect adhesion."),
  ("When is slab scraping done?", "After drywall finishing and before flooring installation."),
  ("Can a floor scrubber remove drywall mud?", "Scraping first works better; scrubbing mud often smears it."),
  ("Who scrapes the slab?", "The drywall contractor or cleanup crew, depending on the contract.")]),
"Slab scraping of overspray and drips": T(
 "Slab scraping of overspray and drips removes paint, primer, texture and coating drips and splatter from concrete slabs before floor finishes are installed or before polished concrete is exposed.",
 "Paint drips under flooring cause bumps and adhesion problems. On exposed or polished concrete, overspray is a visible defect.",
 "Crews scrape with sharp floor scrapers and razor tools held flat, then treat remaining marks with removers matched to the floor and paint type.",
 ["Flooring plans and exposed concrete areas", "Paint and coating types", "Concrete finish: raw, sealed or polished", "Testing of removers"],
 ["Aggressive scraping can gouge polished concrete.", "Solvent removers can discolor sealers; test first."],
 [("How do you remove paint drips from a concrete floor?", "Scrape carefully and use a remover suited to the paint and floor finish."),
  ("Why remove overspray before flooring?", "It creates bumps and can prevent adhesives from bonding."),
  ("Is overspray on polished concrete hard to remove?", "It needs gentle methods so the polish is not damaged."),
  ("Who pays for overspray removal?", "Often the painting contractor, depending on the contract.")]),
"Window sill and opening rough wipe": T(
 "A window sill and opening rough wipe removes heavy debris and dust from window sills, frames and rough openings during the rough clean, before trim and final finishes.",
 "Sills collect drywall dust, screws and debris that scratch frames and glass later. Clearing them early protects window finishes.",
 "Crews vacuum sills and frame channels with HEPA crevice tools and wipe heavy dust with damp cloths, leaving detailed cleaning for the final clean.",
 ["Number of windows and openings", "Frame finishes", "Debris in channels", "Timing with trim installation"],
 ["Do not scrape glass during rough cleaning.", "Protect frames from tools and debris."],
 [("Why clean window sills during the rough clean?", "Debris left on sills can scratch frames and glass later."),
  ("Is the rough wipe the same as window cleaning?", "No. Final window cleaning happens at the end of the job."),
  ("What is a rough opening?", "The framed wall opening that receives a window or door."),
  ("Should window channels be vacuumed?", "Yes, debris in channels can affect operation and drainage.")]),
"Rough clean of mechanical and electrical rooms": T(
 "A rough clean of mechanical and electrical rooms removes debris, packaging and heavy dust from equipment rooms after major equipment and rough-in are installed.",
 "Equipment rooms collect packaging, scraps and dust that can be drawn into new equipment. They are also inspected by fire officials and commissioning agents.",
 "Crews remove debris and packaging, HEPA vacuum floors and accessible surfaces, and stay clear of energized and operating equipment.",
 ["Rooms and equipment installed", "Access and lockout status", "Debris volume", "Commissioning schedule"],
 ["No cleaning inside energized equipment.", "Coordinate access with the electrical and mechanical contractors."],
 [("Why clean mechanical rooms early?", "Dust and debris can be pulled into new equipment and filters."),
  ("Can cleaners work in electrical rooms?", "Only on non-invasive cleaning with permission, never inside energized equipment."),
  ("What debris is common in mechanical rooms?", "Packaging, pipe and duct scraps, insulation and dust."),
  ("Who allows access to equipment rooms?", "The GC and the responsible trade.")]),
"Rough clean of shafts and chases": T(
 "A rough clean of shafts and chases removes debris and dust from vertical shafts, pipe chases and duct shafts before they are closed or before final equipment is installed.",
 "Debris dropped in shafts collects at the bottom, blocks future access and can become a fire or pest issue. Elevator shafts and pits have their own inspection requirements.",
 "Specialist crews access shafts from approved openings with fall protection, removing debris and vacuuming dust before close-up.",
 ["Shaft types and locations", "Access points and fall protection", "Elevator shaft coordination", "Close-up schedule"],
 ["Shaft work requires fall protection and trained crews.", "Elevator hoistways are controlled by the elevator contractor."],
 [("Why clean shafts before closing them?", "Debris in closed shafts is very hard to remove later."),
  ("Is shaft cleaning dangerous?", "It can be, because of fall hazards. It requires fall protection and trained crews."),
  ("Who cleans elevator shafts?", "Only with the elevator contractor's control and lockout."),
  ("What is a pipe chase?", "An enclosed vertical or horizontal space for piping.")]),
"Rough clean of plenum above ceiling before grid close": T(
 "A rough clean of the plenum above the ceiling removes debris, scraps and dust from the space above the ceiling grid before tiles are installed and the ceiling is closed.",
 "Debris left above ceilings falls on tiles and through openings, and dust in return-air plenums is pulled into the HVAC system.",
 "Crews remove debris from the top of ducts, pipes and the grid, and HEPA vacuum heavy dust, coordinating with the ceiling installer and above-ceiling inspection.",
 ["Ceiling area and plenum type", "Above-ceiling inspection timing", "Debris volume", "Lift or ladder access"],
 ["Do not damage ceiling grid or wires.", "Return-air plenums need extra care to keep dust out of the HVAC."],
 [("What is a ceiling plenum?", "The space between the ceiling and the structure above, often used for return air."),
  ("Why clean above the ceiling before tiles go in?", "Debris and dust there fall on tiles and get pulled into the HVAC."),
  ("When is plenum cleaning done?", "After above-ceiling inspection and before tile installation."),
  ("Who cleans above the ceiling?", "Trades or a cleanup crew hired by the GC.")]),
"Removal of sticker and label backing debris": T(
 "Removal of sticker and label backing debris collects the paper and plastic liners, tags and labels that installers peel off fixtures, doors and equipment.",
 "Label backings are small, slippery and everywhere. They stick to floors, clog vacuums and end up under new flooring if not picked up.",
 "Crews pick up label debris by hand and vacuum during rough and progress cleans, focusing on areas where fixtures and doors were installed.",
 ["Areas with recent installations", "Timing", "Debris collection", "Flooring schedules"],
 ["Label debris under flooring creates bumps.", "Backings stick to wet floors."],
 [("Why pick up label backings?", "They are slippery, clog vacuums and get trapped under flooring."),
  ("Where does label debris come from?", "Doors, fixtures, appliances and equipment installations."),
  ("Is label debris part of rough cleaning?", "Yes, it is collected during rough and progress cleaning."),
  ("Who leaves label debris?", "Installers, which is why GCs often hire cleanup crews.")]),
"Rough clean of exterior perimeter": T(
 "A rough clean of the exterior perimeter removes debris, packaging, scraps and windblown trash from around the building footprint during construction.",
 "Perimeter debris blows into neighbors' property and storm drains, blocks exterior work and gives a poor impression to owners and the public.",
 "Crews walk the perimeter, pick up debris, clear building edges for exterior trades and check storm drain protection.",
 ["Perimeter length and site areas", "Exterior trade schedules", "Storm drain protection", "Debris disposal"],
 ["Do not remove erosion control measures.", "Watch for nails and sharp debris in soil."],
 [("Why clean the building perimeter during construction?", "To prevent windblown debris and keep exterior work areas clear."),
  ("How often should the perimeter be cleaned?", "Weekly or more on windy or busy sites."),
  ("Does perimeter cleaning help with storm water compliance?", "Yes, by keeping debris out of drains."),
  ("Who handles perimeter cleanup?", "The GC, often through cleanup crews.")]),
}
