def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Fine drywall dust removal from all horizontal surfaces": T(
 "Fine drywall dust removal from all horizontal surfaces captures the powdery gypsum and joint compound dust that settles on every ledge, sill, counter, shelf and top surface after drywall sanding.",
 "Drywall dust is fine enough to stay airborne and re-settle for days. Missed horizontal surfaces are where it keeps coming from, which is why buildings look dusty again a week after the final clean.",
 "Crews work top to bottom with HEPA vacuums and damp microfiber, changing cloths often so dust is lifted off the surface rather than pushed into a film.",
 ["Every horizontal surface type to include: ledges, sills, counters, shelves, tops", "Heights and access", "Sequence with ceiling and light fixture cleaning", "Inspection standard, such as a white-glove check"],
 ["Wiping with a dirty or dry cloth smears gypsum into a white film.", "Dusting before sanding is finished means doing it twice."],
 [("Why does drywall dust keep showing up after cleaning?", "It was moved instead of captured. HEPA vacuuming and damp microfiber remove it; dry dusting puts it back in the air."),
  ("What is the best way to remove drywall dust?", "HEPA vacuum first, then wipe with damp microfiber, working top to bottom."),
  ("How many times does drywall dust need to be cleaned?", "Often twice: once after sanding and again at final clean."),
  ("Does drywall dust damage finishes?", "It can scratch soft finishes if wiped dry, and it clogs HVAC filters.")]),
"Fine dust removal from vertical wall surfaces": T(
 "Fine dust removal from vertical wall surfaces removes the dust film that clings to painted walls, wallcoverings, panels and tile after construction.",
 "Dust clings to walls because of static and texture, and it shows in raking light or as smudges when someone touches the wall.",
 "Crews use flat microfiber mops or dusters on poles, top to bottom, with HEPA vacuums for textured surfaces, and avoid wetting fresh paint.",
 ["Wall finishes and areas", "Heights and access", "Paint cure time", "Lighting conditions at inspection"],
 ["Rubbing fresh paint can burnish it.", "Textured walls need vacuuming, not wiping."],
 [("Do walls need dusting after construction?", "Yes. Dust clings to walls and shows in raking light."),
  ("How do you dust a wall without streaking it?", "Use clean, dry or barely damp microfiber and change pads often."),
  ("Can fresh paint be wiped?", "Only gently. Most paint needs time to cure before washing."),
  ("Is wall dusting part of final clean?", "It should be included in a detailed final clean.")]),
"Fine dust removal from window frames and mullions": T(
 "Fine dust removal from window frames and mullions cleans dust from the face, edges and channels of window frames, storefront mullions and glazing stops.",
 "Frames hold dust in channels and corners that drifts onto glass as soon as it is cleaned. Dirty mullions make clean glass look dirty.",
 "Crews vacuum channels and corners with HEPA crevice tools, wipe frames with damp microfiber and clean frames before glass so dust does not fall onto clean panes.",
 ["Number of windows and storefront bays", "Frame finish: anodized, painted or vinyl", "Channel and weep hole debris", "Coordination with window cleaning"],
 ["Abrasive pads damage anodized and painted frames.", "Debris in weep holes affects drainage."],
 [("Should window frames be cleaned before the glass?", "Yes. Clean frames first so dust does not fall onto clean glass."),
  ("What is a mullion?", "The vertical or horizontal frame member between panes of glass."),
  ("Can window frames be scratched by cleaning?", "Yes, by abrasive pads or debris dragged across them."),
  ("Why clean weep holes?", "They drain water from the frame. Blocked weep holes can cause leaks.")]),
"Fine dust removal from door tops and frame heads": T(
 "Fine dust removal from door tops and frame heads cleans the top edges of doors, frame heads, closers and hardware where dust collects out of sight.",
 "Door tops are hidden dust shelves that inspectors check by running a finger along them. Dust there also falls whenever the door swings.",
 "Crews wipe door tops, frame heads and closers with damp microfiber from a step ladder, checking each door as part of a door-by-door checklist.",
 ["Number of doors", "Hardware such as closers and stops", "Heights", "Checklist documentation"],
 ["Do not adjust closers or hardware.", "Fire door labels must stay in place."],
 [("Why clean the tops of doors?", "Dust collects there and falls when the door moves. Inspectors check it."),
  ("Is door top cleaning part of final clean?", "Yes, on a thorough final clean."),
  ("Should door closers be cleaned?", "Their exterior should be wiped, without adjusting them."),
  ("How do you check door tops?", "Many inspectors run a gloved finger along the top edge.")]),
"Fine dust removal from light switch and outlet plates": T(
 "Fine dust removal from light switch and outlet plates cleans dust, paint and fingerprints from cover plates, switches and receptacles without removing them or exposing wiring.",
 "Cover plates are touched constantly and show dust, fingerprints and paint. Paint-covered plates are a frequent punch item.",
 "Crews wipe plates with a barely damp microfiber cloth, never spraying liquid toward openings, and note paint-covered or damaged plates for replacement.",
 ["Number of devices", "Paint on plates", "Damaged plates", "Electrical safety rules"],
 ["Never spray liquid onto switches or receptacles.", "Do not remove cover plates."],
 [("How do you clean outlet covers safely?", "With a barely damp cloth, never spraying liquid, and without removing the plate."),
  ("Should paint-covered outlet plates be cleaned or replaced?", "Light paint can be cleaned. Heavily painted plates are usually replaced by the electrician."),
  ("Are outlet plates part of final clean?", "Yes."),
  ("Why are switch plates dirty in new buildings?", "Painters and trades touch them constantly.")]),
"Fine dust removal from cabinets and casework interiors": T(
 "Fine dust removal from cabinets and casework interiors vacuums and wipes the inside of cabinets, drawers, shelves and casework boxes after installation.",
 "Owners and inspectors open cabinets and drawers. Dust, screws and packaging inside them make a new building look unfinished.",
 "Crews remove debris and packaging, HEPA vacuum corners and shelf pin holes, then wipe with damp microfiber suited to the finish.",
 ["Number of cabinets and drawers", "Finishes", "Hardware and shelf pins", "Protective film on interiors"],
 ["Excess water damages particleboard edges.", "Do not adjust hinges or slides."],
 [("Do cabinet interiors need cleaning in a new building?", "Yes, they collect dust, screws and packaging during construction."),
  ("How do you clean inside new cabinets?", "Vacuum corners and holes, then wipe with damp microfiber."),
  ("What is found inside new cabinets?", "Dust, sawdust, screws, shelf pins and packaging."),
  ("Who cleans cabinet interiors?", "The cleaning contractor during final clean.")]),
"Fine dust removal from fire extinguisher cabinets": T(
 "Fine dust removal from fire extinguisher cabinets cleans the interior, glass and frame of recessed and surface-mounted cabinets without moving or disturbing the extinguisher's tag and seal.",
 "Fire extinguisher cabinets are checked during fire inspections and collect dust, labels and paint. Their glass shows every smudge.",
 "Crews wipe the cabinet frame, door glass and interior with damp microfiber and remove labels from the glass, leaving the extinguisher, tag and pin untouched.",
 ["Number of cabinets", "Extinguisher installation status", "Glass or acrylic doors", "Inspection date"],
 ["Do not remove extinguisher tags or pins.", "Acrylic doors scratch easily."],
 [("Do fire extinguisher cabinets need cleaning?", "Yes, they are visible and checked during inspections."),
  ("Can the extinguisher be removed to clean the cabinet?", "Only if needed and replaced exactly as found, with tags and seals intact."),
  ("What cleaner is safe for acrylic cabinet doors?", "Mild soap and water, not ammonia or solvents."),
  ("Are extinguisher cabinets part of final clean?", "Yes.")]),
"Fine dust removal from signage and wayfinding": T(
 "Fine dust removal from signage and wayfinding cleans room signs, directional signs, ADA tactile signs and graphics without damaging raised characters, Braille or printed surfaces.",
 "Signage is part of the finished interior and must stay legible. Tactile signs have raised text and Braille that can be damaged by scraping.",
 "Crews wipe signs with soft microfiber and mild cleaners, using soft brushes on tactile areas, and remove protective films without lifting graphics.",
 ["Sign count and types", "Protective films", "Tactile and Braille signs", "Graphics and vinyl lettering"],
 ["Solvents can damage vinyl graphics and printed finishes.", "Do not scrape Braille or raised characters."],
 [("How should ADA signs be cleaned?", "Gently, with mild cleaners and soft cloths, without scraping raised characters or Braille."),
  ("Do signs come with protective film?", "Many do, and it is removed at final clean."),
  ("Can vinyl lettering be cleaned with solvents?", "No. Solvents can lift or damage vinyl."),
  ("Is signage part of final clean?", "Yes.")]),
"Fine dust removal from electronics and low-voltage devices": T(
 "Fine dust removal from electronics and low-voltage devices cleans dust from the exterior of displays, card readers, cameras, sensors, thermostats and other installed devices.",
 "Fine dust can affect sensors, camera lenses and cooling vents. Devices also have sensitive surfaces that liquid cleaners can damage.",
 "Crews use dry microfiber, soft brushes and low-suction HEPA vacuums on vents, never spraying liquids onto devices, and avoid pressing buttons or changing settings.",
 ["Device types and locations", "Owner or integrator restrictions", "Screens and lenses", "Areas with active systems"],
 ["Do not spray liquids on devices.", "Do not change settings or press buttons."],
 [("How do you clean electronic devices after construction?", "With dry microfiber, soft brushes and gentle vacuuming, never spraying liquid."),
  ("Can construction dust damage electronics?", "It can clog vents and affect sensors."),
  ("Should touchscreens be cleaned with glass cleaner?", "Only with the manufacturer's approved cleaner."),
  ("Who cleans low-voltage devices?", "Cleaning crews clean exteriors; integrators handle internals.")]),
"Fine dust removal from server and IT rooms": T(
 "Fine dust removal from server and IT rooms cleans floors, walls, cable trays and equipment exteriors in IT rooms using HEPA vacuums and antistatic methods.",
 "Dust in IT rooms is drawn into servers and network equipment, where it affects cooling and reliability.",
 "Trained crews work with IT approval, HEPA vacuuming floors and surfaces, wiping exteriors with antistatic microfiber and never opening equipment.",
 ["Room access and IT approval", "Equipment installed and active", "Antistatic requirements", "Floor type"],
 ["Never use liquids near active equipment.", "Do not disconnect or move cables."],
 [("Why is dust a problem in server rooms?", "It is drawn into equipment and affects cooling and reliability."),
  ("Can a regular cleaning crew clean an IT room?", "Only trained crews with IT approval should."),
  ("What is antistatic cleaning?", "Cleaning with tools and products that reduce static discharge."),
  ("Should server room floors be mopped?", "Only with very little moisture and approved products.")]),
"Concrete dust removal after grinding or saw cutting": T(
 "Concrete dust removal after grinding or saw cutting captures the fine, silica-containing dust and slurry left by concrete grinding, coring, saw cutting and chipping.",
 "Concrete dust contains crystalline silica, which is regulated by OSHA. It is also abrasive and spreads through the building if not captured.",
 "Crews use HEPA vacuums and wet methods, never dry sweeping or compressed air, collect slurry for proper disposal and keep it out of drains.",
 ["Areas where concrete work occurred", "Dust or slurry", "Silica exposure controls", "Disposal of slurry"],
 ["Dry sweeping or blowing concrete dust is restricted under OSHA's silica standard.", "Slurry should not be washed into drains."],
 [("Is concrete dust hazardous?", "Yes. It contains respirable crystalline silica, which OSHA regulates."),
  ("How do you clean up concrete dust safely?", "With HEPA vacuums and wet methods, not dry sweeping or compressed air."),
  ("What is concrete slurry?", "The wet mix of water and fine concrete from wet cutting or grinding."),
  ("Can slurry go down the drain?", "No. It should be collected and disposed of properly.")]),
"Silica-aware housekeeping cleanup": T(
 "Silica-aware housekeeping cleanup is construction cleaning done with methods that keep crystalline silica dust out of the air: wet sweeping, HEPA vacuuming and approved sweeping compounds instead of dry sweeping, brushing or compressed air.",
 "OSHA's construction silica standard restricts dry sweeping and compressed-air cleaning where they could expose workers to silica. Concrete, masonry, stone and some joint compounds all contain it.",
 "Crews plan housekeeping around the work producing silica dust, use HEPA vacuums and wet methods, and bag collected dust carefully.",
 ["Silica-producing work on site", "Housekeeping methods", "Respiratory protection if required", "Waste disposal"],
 ["Dry sweeping and compressed air are restricted where they could expose workers to silica.", "Collected dust must be handled without creating a cloud."],
 [("What is silica-aware housekeeping?", "Cleaning methods that avoid putting silica dust in the air."),
  ("Is dry sweeping allowed on construction sites?", "Not where it could contribute to silica exposure, unless safer methods are not feasible."),
  ("What materials contain silica?", "Concrete, masonry, stone, tile and some joint compounds."),
  ("Is HEPA vacuuming required for silica?", "It is one of the methods the standard names as an alternative to dry sweeping.")]),
"Dust re-clean after late-trade work": T(
 "A dust re-clean after late-trade work re-cleans areas that were already cleaned but got dusty again when a trade came back for punch work, touch-ups, cutting or installations.",
 "Late-trade work is almost guaranteed on every project. Without a planned re-clean, the building fails the owner walk even though the final clean was done.",
 "Crews re-clean only the affected areas, using HEPA vacuums and microfiber, and document which trade caused the re-clean so it can be back-charged if needed.",
 ["Re-clean pricing in the contract", "Areas affected and responsible trade", "Documentation for back-charges", "Timing before inspection"],
 ["Without agreed re-clean pricing, disputes are likely.", "Late trades should protect clean areas, but often do not."],
 [("Why do buildings need re-cleaning after the final clean?", "Trades return for punch work and create new dust and debris."),
  ("Who pays for re-cleaning?", "It depends on the contract. GCs often back-charge the trade responsible."),
  ("How can re-cleans be reduced?", "By finishing punch work before the final clean and protecting cleaned areas."),
  ("Is re-cleaning included in a final clean price?", "Not usually. It should be priced separately.")]),
"Dust containment barrier cleanup and removal": T(
 "Dust containment barrier cleanup and removal takes down plastic sheeting, zipper doors and temporary walls used to contain dust, without releasing the dust collected on them.",
 "Containment barriers hold dust on their surfaces. Pulling them down carelessly releases it into clean areas, undoing the protection.",
 "Crews HEPA vacuum and mist barrier surfaces, fold sheeting inward to trap dust, bag it and then clean the floor and walls where the barrier stood.",
 ["Barrier locations and sizes", "Dust conditions", "Disposal", "Cleaning of floor and wall after removal"],
 ["Pulling down dusty plastic releases dust into clean areas.", "Tape residue from barriers needs cleaning."],
 [("How do you remove dust barriers without spreading dust?", "Vacuum and mist the surface, fold it inward and bag it."),
  ("What is a zip wall?", "A temporary dust barrier system with poles and plastic sheeting."),
  ("Do barriers leave tape residue?", "Often, on floors, walls and ceilings."),
  ("Who removes containment barriers?", "The trade that installed them or the cleanup crew.")]),
"Negative air zone final cleaning": T(
 "Negative air zone final cleaning is the detailed clean of a contained work area under negative air pressure before the containment comes down and the space rejoins the building.",
 "Areas under negative air contain the most dust. If containment is removed before they are cleaned, the dust spreads into the occupied building.",
 "Crews clean inside containment while negative air machines run, top to bottom with HEPA vacuums and damp wiping, before barriers are removed.",
 ["Contained area and size", "Negative air machines and filters", "Clearance requirements", "Barrier removal sequence"],
 ["Do not turn off negative air until the area is cleaned.", "Healthcare projects may require visual or particle clearance."],
 [("What is negative air pressure in construction?", "Air is exhausted from the work area through HEPA filters so dust cannot escape."),
  ("When is the negative air zone cleaned?", "Before containment is removed and negative air is turned off."),
  ("Is negative air cleaning used in hospitals?", "Yes, as part of infection control during construction."),
  ("Who cleans inside containment?", "Trained cleaning crews or the contractor responsible for containment.")]),
"Occupied-building renovation dust control cleaning": T(
 "Occupied-building renovation dust control cleaning keeps dust from a renovation out of the occupied spaces around it, cleaning both inside the work zone and along the paths people and materials travel.",
 "Tenants, patients, students or shoppers continue using the building during work. Dust escaping the work zone causes complaints, health concerns and lost business.",
 "Crews clean transit routes, entry points and adjacent spaces frequently, maintain sticky mats and barriers, and HEPA vacuum and damp-wipe outside the work zone.",
 ["Work zone and adjacent occupied areas", "Material and worker transit routes", "Cleaning frequency", "Occupant communication"],
 ["Dust complaints can stop work; respond quickly.", "Healthcare work follows infection control requirements."],
 [("How is dust controlled during an occupied renovation?", "With containment, negative air, sticky mats and frequent cleaning outside the work zone."),
  ("Who cleans the occupied areas during renovation?", "A dedicated cleaning crew coordinated with the contractor."),
  ("What are sticky mats?", "Adhesive mats at exits that pull dust off shoes and wheels."),
  ("Is occupied renovation cleaning done at night?", "Often, to avoid disruption.")]),
"Air scrubber filter change and unit wipe-down": T(
 "Air scrubber filter change and unit wipe-down replaces pre-filters and HEPA filters in portable air scrubbers and negative air machines and cleans the units' exteriors.",
 "Loaded filters reduce airflow and dust capture. Dusty units also shed dust when they are moved.",
 "Crews turn off units, bag used filters inside the work zone, install new filters per the manufacturer and wipe unit exteriors before moving them.",
 ["Number of units", "Filter types and stock", "Change schedule", "Disposal of used filters"],
 ["Used filters must be bagged carefully to avoid releasing dust.", "Units should be off during filter changes."],
 [("How often should air scrubber filters be changed?", "Pre-filters often, and HEPA filters according to the manufacturer and dust load."),
  ("What is an air scrubber?", "A portable unit that filters air through HEPA filters."),
  ("Can dirty filters reduce air scrubber performance?", "Yes, they restrict airflow."),
  ("Who changes air scrubber filters?", "The contractor responsible for dust control, or a cleaning crew.")]),
}
