def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Open ceiling deck cleaning": T(
 "Open ceiling deck cleaning removes construction dust, overspray and debris from the exposed metal or concrete deck above a space with no finished ceiling. It is done from lifts near the end of construction, before floors get their final clean and before merchandise or furniture arrives.",
 "In an open-ceiling building the deck is part of the finished room. Dust left on it drifts down onto new floors, fixtures and food areas for months and is the first thing a sharp-eyed owner notices when they look up.",
 "Crews work in lift-sized bays from the far wall toward the exit, vacuuming deck flutes with HEPA attachments on extension wands rather than blowing or brushing dust down. Painted decks get only dry or barely damp microfiber so the finish is not streaked.",
 ["Total deck area in square feet and the height to the underside of the deck", "Deck type: painted metal, galvanized, acoustic or concrete", "Lift type, who supplies it and floor loading limits for the slab", "Whether MEP runs, joists and fixtures in the same zone are included"],
 ["Overspray from ceiling paint often hides under dust; vacuuming will not remove it and it should be priced separately if the spec calls for a uniform finish.", "Lifts must travel on protected floors. Unprotected polished concrete or new VCT can be marked by lift tires."],
 [("How do you clean an exposed metal deck without making a mess below?", "Capture the dust where it sits. Crews use HEPA vacuums with brush heads on extension poles from a lift and cover finished surfaces below. Dry brushing or blowing simply moves the dust to the floor and fixtures."),
  ("Is it worth cleaning a painted deck that looks clean from the floor?", "Usually yes. Dust that is invisible from 25 feet still falls as fixtures vibrate and HVAC cycles. Retail and food tenants often find it on product within weeks if the deck is skipped."),
  ("When should the deck be cleaned in the construction sequence?", "After all overhead trades, including sprinkler, electrical and HVAC balancing, are done above that area, and before the final floor clean. Cleaning before the last overhead trade leaves usually means paying twice."),
  ("Can the deck be cleaned in sections while other work continues?", "Yes. Large buildings are typically cleaned in bays or column lines that match the lift plan, so other trades can keep working in areas that are not under the lift.")]),
"Exposed structural steel beam cleaning": T(
 "Exposed structural steel beam cleaning removes dust, mill scale flakes, overspray and debris from steel beams and girders that remain visible in the finished space. It covers top flanges, webs and bottom flanges and is usually done at final clean from lifts.",
 "The top flange of every beam is a long dust shelf. In open-ceiling stores, restaurants and lobbies that dust falls in visible streaks onto floors and tables as soon as the HVAC starts moving air.",
 "Top flanges are vacuumed first with HEPA brush heads, then webs and bottom flanges are wiped with damp microfiber. Primed or painted steel gets plain water or a pH-neutral solution, never solvents that could soften fresh coatings.",
 ["Linear feet of beam and typical beam depth", "Height to the top flange and lift access along each line", "Coating type: primer, finish paint or intumescent fireproofing", "Whether connection plates and bracing are included"],
 ["Intumescent fireproofing paint on beams must not be scrubbed or wetted heavily; it is a fire-rated coating and damage has to be repaired by the coating applicator.", "Beam tops are rarely visible from below, so ask for photo verification at each line."],
 [("Why is there so much dust on top of new steel beams?", "The top flange is flat and catches everything that rises during construction: drywall sanding dust, concrete cutting dust and spray-applied finishes. Nothing else in the building collects as much per foot."),
  ("Can beams be wiped with a wet rag?", "The webs and bottom flanges can be damp-wiped once the heavy dust is vacuumed off. Starting with a wet rag on a dusty flange turns the dust into mud streaks."),
  ("Is beam cleaning included in a standard final clean?", "Often it is not written in. If the beams are exposed in the finished design, list them as a separate overhead line item so the cleaning bid includes lifts and labor."),
  ("How do you prove beam tops were cleaned?", "Ask for before-and-after photos taken from the lift at representative points along each beam line. It is the simplest way to verify a surface no one can see from the floor.")]),
"Bar joist cleaning": T(
 "Bar joist cleaning removes construction dust and debris from the open-web steel joists that support the roof or floor deck. Each joist has top and bottom chords and diagonal web members, so cleaning means working around many small surfaces from a lift.",
 "Bar joists are everywhere in warehouses, big-box stores and gyms. Their open webs trap dust on dozens of short ledges per joist, and that dust sheds onto racking, merchandise and court floors.",
 "Crews vacuum chords and web members with narrow HEPA crevice and brush tools, working one joist space at a time so nothing falls into a section already cleaned. Damp microfiber follows only where the joist is painted and the finish allows it.",
 ["Number of joists, span length and joist spacing", "Clear height to the bottom chord", "Joist finish: shop primer, painted or galvanized", "Bridging, bracing and attached hangers included or excluded"],
 ["Joist bridging and hanger rods create snag points for vacuum hoses; crews must avoid loading or bending them.", "Do not hang tools, lines or lights from joists without the structural engineer or GC's approval."],
 [("What is a bar joist?", "An open-web steel joist made of top and bottom chords connected by a zigzag of web members. It is the lightweight framing seen in most warehouse and retail ceilings."),
  ("How long does it take to clean bar joists?", "It depends on joist count, height and how dirty they are. The open web makes it slower per square foot than a flat deck, so joists are often priced by the joist space or bay."),
  ("Should joists and deck be cleaned at the same time?", "Yes. They are cleaned from the same lift position, deck first and then joists, which avoids moving the lift twice through the same bay."),
  ("Do joists need cleaning again after the building opens?", "In dusty environments like warehouses and stores they do. Quarterly or semiannual high dusting keeps the buildup from becoming a visible problem.")]),
"Wood truss and glulam cleaning": T(
 "Wood truss and glulam cleaning removes dust and debris from exposed timber trusses, glued-laminated beams and heavy timber framing. It uses dry and low-moisture methods that protect stained, sealed or natural wood finishes.",
 "Exposed wood structure is a design feature in churches, restaurants, schools and lobbies. Dust dulls the finish and settles in checks and joints, and water or strong cleaners can raise grain, stain or strip the coating.",
 "Crews HEPA vacuum with soft brush heads along the grain, then use dry microfiber or lightly damp cloths with a wood-safe cleaner only where the finish is sealed. Bare or oiled wood is cleaned dry.",
 ["Truss count, beam lengths and exposed faces", "Wood finish: stained, clear coat, oiled or unfinished", "Steel connectors and hardware included", "Height and lift access around pews, seating or fixed furniture"],
 ["Unfinished or oiled timber absorbs water and cleaners and can stain permanently.", "Steel knife plates and bolts on timber connections may have different coatings than the wood and need their own method."],
 [("Can exposed wood beams be washed?", "Sealed and clear-coated beams can be damp-wiped carefully. Unfinished, oiled or rough-sawn timber should be cleaned dry with HEPA vacuums and soft brushes to avoid water staining."),
  ("What is glulam?", "Glued-laminated timber: structural beams made from layers of lumber bonded together. It is common in exposed architectural framing."),
  ("Why do wood ceilings look dull after construction?", "Fine drywall and sanding dust settle into the grain and texture. Careful vacuuming along the grain usually restores the finish without chemicals."),
  ("Who cleans wood ceilings in a new church or restaurant?", "A cleaning contractor with lift access and experience with wood finishes. It is usually part of the overhead scope at final clean.")]),
"Gymnasium rafter cleaning": T(
 "Gymnasium rafter cleaning removes dust, debris and lost balls from the joists, trusses, deck and equipment above a gym floor. It is done from lifts that are set up to protect the finished wood or sport floor.",
 "Gym ceilings are high, hard to reach and directly above an expensive floor. Dust falling from rafters scratches the floor finish during play and lands on bleachers and equipment.",
 "Crews work from lifts with non-marking tires and floor protection under every outrigger and wheel path, HEPA vacuuming rafters, deck and lights. Debris such as stuck balls is removed by hand rather than knocked down.",
 ["Gym size and clear height", "Floor type and required protection: maple, rubber or synthetic", "Basketball goals, divider curtains, scoreboards and lights to work around", "Timing relative to floor sanding and finishing"],
 ["Lifts on a finished maple floor need approved protection; point loads can dent wood.", "Retractable goals and divider curtains have motors and cables; crews must not use them as supports."],
 [("When should gym rafters be cleaned in a new school?", "Before the final screen and recoat or finish coats on the gym floor if possible, and always before the final floor clean. Dust from above ruins fresh floor finish."),
  ("Can you clean rafters without damaging the gym floor?", "Yes, with non-marking tires, floor protection boards under lifts and careful routing. The floor contractor's protection requirements should be in the plan."),
  ("How often should gym rafters be cleaned?", "Many schools do it once a year during summer maintenance, before floors are recoated."),
  ("Do balls stuck in the rafters get removed?", "Yes, it is a common part of the job. Crews retrieve them by hand from the lift instead of knocking them loose.")]),
"Warehouse ceiling dust removal": T(
 "Warehouse ceiling dust removal is overhead cleaning of the deck, joists, lights and MEP in a distribution center or warehouse, usually 28 to 40 feet or more above the slab. It is done before racking is loaded or with racking protected.",
 "Dust overhead in a warehouse ends up on stored product, packaging and conveyors. Food, pharmaceutical and e-commerce operations are audited for it, and it is far easier to clean before racking is full.",
 "Crews use boom lifts and HEPA vacuum systems with long hoses, working aisle by aisle. Where racking is already installed, product and rack tops are covered and work follows the operator's traffic plan.",
 ["Building square footage and clear height", "Racking layout and whether it is loaded", "Lift type allowed on the slab and any floor sealer restrictions", "Night, weekend or operating-hours constraints"],
 ["Boom lifts near loaded racking need spotters and exclusion zones.", "Never use leaf blowers in a warehouse; dust settles on product and violates many customer audit standards."],
 [("How do you clean a 40-foot warehouse ceiling?", "With boom lifts, long HEPA hoses and brush heads, working in aisles and bays. Dust is captured at the surface, not blown down onto the slab and racking."),
  ("Is it better to clean the ceiling before racking goes in?", "Much better. An empty building gives free lift access and nothing to protect below, which shortens the job significantly."),
  ("Do food warehouses need overhead cleaning?", "Yes. Food safety audits look for dust and debris above stored product and food zones, and overhead areas are a common finding."),
  ("Can warehouse high dusting be done while operating?", "Yes, usually on nights or weekends, with exclusion zones around lifts and product covered below the work area.")]),
"Retail store ceiling dust capture": T(
 "Retail store ceiling dust capture is overhead cleaning in an open-ceiling store: deck, joists, ducts, lights and signage. It is timed after overhead construction ends and before fixtures are stocked so dust never lands on merchandise.",
 "Dust that falls on folded apparel, electronics and packaged goods becomes damaged inventory and customer complaints. Retailers often cannot reschedule a grand opening, so overhead cleaning has a hard deadline.",
 "HEPA capture from lifts, working from the back of house toward the entrance, with fixtures covered when they are already installed. Crews coordinate with the merchandising schedule so cleaning stays ahead of product.",
 ["Sales floor square footage and ceiling height", "Fixture status: installed, wrapped or not yet delivered", "Merchandise delivery and set dates", "Signage, lighting and graphics hung from the structure"],
 ["Once merchandise is set, lifts need floor protection and product must be covered, which slows the work.", "Hanging signage may be installed by a separate vendor; confirm whether it is in scope."],
 [("When should the ceiling be cleaned in a new store?", "After overhead trades finish and before fixtures are stocked. If fixtures arrive early, they should be covered during overhead cleaning."),
  ("Why is there dust on merchandise in a new store?", "Usually because overhead cleaning was skipped or done by blowing dust down. As the HVAC runs, dust falls from the deck and structure onto product."),
  ("Can a store ceiling be cleaned at night after opening?", "Yes. Overnight high dusting with covered fixtures is common in operating stores."),
  ("Is ceiling cleaning included in a store opening clean?", "Only if written into the scope. For open-ceiling stores, it should be a specific line item.")]),
"Exposed concrete ceiling cleaning": T(
 "Exposed concrete ceiling cleaning removes dust, form release residue, overspray and debris from cast-in-place or precast concrete ceilings and soffits that stay visible in the finished space.",
 "Exposed concrete is porous and textured, so dust and spray drift lodge in it. Stains from form oil, rust or water are visible against a raw concrete finish and can be permanent if cleaned the wrong way.",
 "HEPA vacuuming with brush heads comes first, then low-moisture spot cleaning with a pH-neutral cleaner on sealed concrete. Acidic cleaners are avoided because they etch concrete and can change its color.",
 ["Ceiling area and whether it is sealed or raw", "Known stains: rust, form oil, water marks or overspray", "Embedded conduit, inserts and anchors to work around", "Lift access and protection of floors below"],
 ["Water and cleaners can leave tide marks on raw concrete; test in an inconspicuous spot.", "Stain removal on architectural concrete may need a concrete restoration specialist."],
 [("Can you wash a raw concrete ceiling?", "Lightly, and only after testing. Raw concrete absorbs water and can show tide marks. HEPA vacuuming and dry methods are the safest first step."),
  ("How do you remove rust stains from a concrete ceiling?", "With a rust remover formulated for concrete, tested first. Strong acids can etch the surface and change its color, so restoration specialists sometimes handle it."),
  ("Is sealed concrete easier to clean?", "Yes. A sealer keeps dust and stains on the surface, so damp microfiber and neutral cleaners usually work."),
  ("What is form release residue?", "Oil or chemical left on concrete from the forms used to cast it. It can attract dust and leave dark patches.")]),
"Acoustic deck and sound panel dusting": T(
 "Acoustic deck and sound panel dusting removes dust from perforated acoustic metal deck, suspended baffles, clouds and fabric-wrapped sound panels without damaging their absorptive surfaces.",
 "Acoustic products work because they are porous or perforated, and those openings catch fine construction dust. Wet cleaning or rough handling can stain fabric, crush fiber cores or clog perforations.",
 "Dry HEPA vacuuming with soft brush heads at low suction for fabric and fiber panels; hanging baffles are steadied by hand so cables are not loaded. No liquids on fabric or mineral fiber.",
 ["Panel type: perforated deck, felt baffles, fabric-wrapped or wood", "Count and size of baffles or clouds", "Suspension method and height", "Manufacturer cleaning instructions"],
 ["Fabric panels can stain from any liquid; spot treatment needs the manufacturer's approved method.", "Suspended baffles swing easily; pulling on them can loosen cable grips."],
 [("How do you clean acoustic ceiling baffles?", "With a soft brush vacuum attachment and light, steady passes while the baffle is held still. No water or spray cleaners on felt or fabric baffles."),
  ("Can perforated acoustic deck be vacuumed?", "Yes. HEPA vacuuming with a brush head removes surface dust without pushing it further into the perforations."),
  ("Will cleaning hurt the acoustic performance?", "Proper dry cleaning should not. Painting, wetting or crushing the panel can."),
  ("Who cleans acoustic clouds in an office or school?", "The overhead cleaning crew at final clean, using lifts and soft vacuum tools.")]),
"Spray-applied fireproofing area light dusting": T(
 "Spray-applied fireproofing area light dusting is careful removal of loose dust from surfaces near or below sprayed fire-resistive material, without touching, scraping or wetting the fireproofing itself. It is only done with the GC's approval.",
 "Spray-applied fireproofing is a life-safety system. Damaging it means repairs, inspection and possibly a code violation. Some older buildings also have fireproofing that may contain asbestos, which must not be disturbed.",
 "This is routed only to qualified specialists under a defined procedure: HEPA vacuuming of adjacent surfaces with the hose kept off the fireproofing, no contact cleaning, and stop-work if any damage or suspect material is found.",
 ["Confirmation of fireproofing type and that it is not asbestos-containing", "Defined surfaces to be cleaned and surfaces to be left alone", "Written GC approval and inspection status of the fireproofing", "Procedure for reporting damage"],
 ["Never scrape, brush or wet spray-applied fireproofing; repairs must be made by the fireproofing applicator and inspected.", "In renovations of older buildings, suspect fireproofing must be tested before any work near it."],
 [("Can you clean spray-applied fireproofing?", "No. The fireproofing itself should be left alone. Only nearby surfaces are cleaned, carefully, so the fire-resistive material is not damaged."),
  ("Why is fireproofing overhead work conditional?", "Because damage affects fire safety and code compliance, and older materials may contain asbestos. It needs approval and a defined procedure."),
  ("What happens if fireproofing gets damaged during cleaning?", "Work stops, the GC is notified and the fireproofing contractor repairs it, usually followed by inspection."),
  ("Does fireproofing make overhead dust worse?", "It can shed fine particles if disturbed, which is one more reason to keep vacuum tools and lifts clear of it.")]),
"Mezzanine underside cleaning": T(
 "Mezzanine underside cleaning removes dust and debris from the bottom of a mezzanine deck, its beams, joists, lights and sprinkler lines, along with the supporting columns.",
 "The space under a mezzanine is usually working space: stockrooms, offices or production areas. Dust from the underside falls directly on people and product below, and the low clearance makes it easy to overlook.",
 "Crews use scissor lifts or rolling platforms sized to the clearance and HEPA vacuum the deck underside, framing and fixtures, then damp-wipe columns and bracing.",
 ["Mezzanine footprint and clearance below", "Structure type: bar joist, steel beam or wood", "Items stored below that need covering", "Lights, sprinkler and conduit under the deck"],
 ["Low clearance limits lift choice; check heights before scheduling equipment.", "Grating mezzanines let dust fall through from above; clean the top surface first."],
 [("Why clean under a mezzanine if no one sees it?", "Because people and product are directly below it. Dust from the underside falls onto workstations and stock."),
  ("What equipment is used under a low mezzanine?", "Small scissor lifts, rolling platforms or extension poles, depending on the clearance."),
  ("Should the top of the mezzanine be cleaned first?", "Yes, especially if it is grating or has gaps. Clean top to bottom so nothing falls onto a cleaned surface."),
  ("Is mezzanine cleaning part of warehouse turnover?", "It should be. It is often missed because it is neither the main ceiling nor the floor.")]),
"Atrium and lobby high ceiling cleaning": T(
 "Atrium and lobby high ceiling cleaning removes dust and smudges from tall ceilings, feature lighting, glass and architectural elements in multistory lobbies and atriums, where access is limited and the space is highly visible.",
 "Atriums are designed to impress, and they are where tenants, guests and owners form their first impression. Their height and finishes make them one of the hardest spaces in a building to clean safely.",
 "Specialists plan access with articulating lifts, spider lifts or rope access as the space allows, protect finished floors and stone, and clean feature fixtures and ceilings with methods matched to each material.",
 ["Atrium height and footprint", "Access options: lift path, floor load limits or rope access points", "Feature lighting, glass and specialty ceiling materials", "Hours when the lobby can be closed or partly closed"],
 ["Stone and terrazzo lobby floors need load spreading under lifts.", "Rope access or tall lifts require trained crews and fall-protection plans; route only to qualified providers."],
 [("How do you clean a three-story atrium ceiling?", "With articulating or spider lifts that fit the floor and access paths, or rope access where lifts cannot reach. The method depends on height, floor load and obstructions."),
  ("Can atrium cleaning be done while the building is open?", "Usually after hours, with the area cordoned off. Lift work over occupants is avoided."),
  ("What is a spider lift?", "A compact tracked lift with outriggers that spread its load, used where large lifts cannot fit or floors cannot carry them."),
  ("Who cleans the feature chandelier in a lobby?", "Overhead specialists using lifts, with methods matched to the fixture's materials and manufacturer guidance.")]),
"Skylight well and light shaft cleaning": T(
 "Skylight well and light shaft cleaning removes dust and debris from the drywall or panel walls, trim and ledges of the shaft between a skylight and the ceiling, plus the interior face of the skylight.",
 "Skylight wells are designed to bring light in, and dust or debris in the well shows as shadows and dirty streaks. Construction debris also collects on the lip where the curb meets the glazing.",
 "Crews clean from a lift or ladder, top to bottom: skylight glazing interior first, then shaft walls and trim, then the ceiling opening edge, using HEPA vacuums and damp microfiber.",
 ["Number and size of skylight wells and shaft depth", "Interior glazing material: glass or polycarbonate", "Ledge or curb conditions with debris", "Access height"],
 ["Polycarbonate skylights scratch easily; use only soft cloths and approved cleaners.", "Do not lean ladders or lifts against skylight frames."],
 [("What is a skylight well?", "The shaft between the skylight on the roof and the opening in the ceiling below. It is usually finished with drywall or panels."),
  ("Should the skylight glass be cleaned with the well?", "The interior face is cleaned with the well. The exterior face is part of exterior glass or roof cleaning."),
  ("Can polycarbonate skylights be cleaned like glass?", "No. They scratch more easily and can be damaged by some glass cleaners. Use mild soap, water and soft cloths."),
  ("Why do skylight wells look dirty in new buildings?", "Construction dust settles on the shaft ledges and glazing, and debris collects at the curb. It shows clearly because light shines through it.")]),
"Duct exterior cleaning": T(
 "Duct exterior cleaning removes construction dust, overspray and labels from the outside of exposed ductwork: spiral round, rectangular and oval duct, fittings and hangers. The duct interior is not opened.",
 "Exposed duct is a finished design element in open-ceiling spaces. Its top surface collects dust, and when the HVAC starts, vibration sheds that dust onto floors and fixtures.",
 "HEPA vacuuming of the top and sides with brush heads, then damp microfiber with a pH-neutral cleaner on painted or galvanized surfaces. Duct labels and tape are removed only if the spec calls for it.",
 ["Linear feet of exposed duct and approximate diameters", "Finish: galvanized, painted or double-wall", "Height and lift access along runs", "Whether hangers, straps and fittings are included"],
 ["Duct interior cleaning is a separate regulated specialty; exterior crews do not open ducts.", "Fresh duct paint can be softened by solvents; use only water-based cleaners."],
 [("Is duct exterior cleaning the same as duct cleaning?", "No. Duct exterior cleaning cleans the outside of exposed ductwork. Duct cleaning usually means cleaning the inside of the system, which is a specialty under NADCA standards."),
  ("Why does exposed duct look dusty soon after opening?", "Dust on the top surface that was not cleaned is shaken loose by airflow and vibration, then settles again in visible bands."),
  ("Can spiral duct be cleaned without scratching it?", "Yes, with soft brushes and microfiber. Abrasive pads leave visible marks on galvanized and painted duct."),
  ("Should duct labels be removed?", "Only if the spec or owner wants them removed. Some labels identify systems for maintenance and should stay.")]),
"Fabric duct sock cleaning": T(
 "Fabric duct sock cleaning removes construction dust from the outside of textile air dispersion ducts, and coordinates removal and laundering when the manufacturer recommends it.",
 "Fabric ducts are porous by design, and construction dust can clog them or discolor them. Many manufacturers recommend laundering, and the wrong cleaning method can damage the fabric or its coating.",
 "Surface dust is removed with low-suction HEPA vacuuming. If the fabric is dirty, crews follow the manufacturer's procedure, which often means taking sections down and sending them for laundering.",
 ["Fabric duct length, diameter and suspension type", "Manufacturer and cleaning instructions", "Whether takedown and reinstallation are included", "Laundering vendor and turnaround time"],
 ["Do not spray cleaners on fabric duct; follow the manufacturer's laundering instructions.", "Takedown and rehanging may need the mechanical contractor."],
 [("Can fabric ductwork be washed?", "Many fabric duct systems can be removed and laundered according to the manufacturer's instructions. Check the product's care guide first."),
  ("Why is fabric duct used?", "It distributes air evenly and quietly, and is common in gyms, warehouses, food plants and open offices."),
  ("Does construction dust hurt fabric duct?", "It can clog pores, reduce airflow performance and discolor the fabric if it is not removed."),
  ("Who reinstalls fabric duct after laundering?", "Usually the mechanical contractor or the cleaning crew following the manufacturer's suspension instructions.")]),
"Overhead piping exterior cleaning": T(
 "Overhead piping exterior cleaning removes dust, overspray and labels from exposed plumbing, gas, process and hydronic piping, insulation jackets and hangers in open-ceiling and mechanical spaces.",
 "Pipe runs are long and stacked, so they hold a surprising amount of dust. In food facilities, dirty overhead piping above prep or storage areas is an inspection finding.",
 "HEPA vacuum with brush heads, then damp microfiber on painted pipe and PVC jacketing. Insulation is vacuumed gently without compressing it. Pipe identification labels are left in place.",
 ["Linear feet of piping by system", "Insulated versus bare pipe and jacket types", "Height and access", "Gas and process lines that require special care"],
 ["Do not step on, hang from or lean on piping or hangers.", "Pipe identification labels and flow arrows are required; do not remove them."],
 [("Should pipe labels be removed during cleaning?", "No. Pipe identification and flow arrows are required for safety and maintenance. Clean around them."),
  ("Can insulated pipes be wiped?", "PVC or metal jacketing can be damp-wiped. Exposed fiberglass insulation should only be vacuumed gently."),
  ("Why does overhead piping matter in a kitchen?", "Dust and debris above food prep and storage can fall into food. Health inspectors look up."),
  ("Is overhead piping cleaned with the ductwork?", "Usually yes, in the same lift pass, to save time and equipment.")]),
"Sprinkler pipe exterior dusting": T(
 "Sprinkler pipe exterior dusting removes construction dust from the outside of fire sprinkler mains and branch lines, keeping clear of sprinkler heads and never loading or striking the piping.",
 "Painted red sprinkler mains in open ceilings collect visible dust, and dust falling from them lands on everything below. But sprinkler systems are life-safety equipment, so cleaning must not damage or obstruct them.",
 "Light HEPA vacuuming and dry microfiber along mains and branch lines, with heads avoided entirely. Nothing is hung from or rested on sprinkler pipe.",
 ["Linear feet of sprinkler main and branch line", "Pipe finish: painted or black steel", "Sprinkler head type and count in the area", "Height and access"],
 ["Never paint, tape, wet or cover sprinkler heads; damaged or painted heads must be replaced by a licensed fire sprinkler contractor.", "Do not use sprinkler pipe as a support for lifts, hoses or tools."],
 [("Is it safe to clean fire sprinkler pipes?", "Yes, when done gently from a lift with vacuums and dry cloths, without touching the heads or loading the pipe."),
  ("Why are sprinkler pipes dusty in new buildings?", "They are horizontal and usually installed early, so they collect dust from every trade that follows."),
  ("What happens if a sprinkler head gets bumped?", "Work stops and the fire sprinkler contractor inspects it. A damaged head can leak or fail to operate correctly."),
  ("Can sprinkler pipe be painted to cover dirt?", "Painting is outside cleaning scope. Heads must never be painted, and any painting of piping is a specification decision for the GC.")]),
"Sprinkler head careful dusting": T(
 "Sprinkler head careful dusting removes light surface dust from fire sprinkler heads and escutcheons using minimal-contact methods. Heads with paint, damage or heavy contamination are reported, not cleaned.",
 "Sprinkler heads must remain unobstructed and undamaged to work. Dust buildup is unsightly, but aggressive cleaning can break the bulb or move the deflector, which affects fire protection.",
 "Only qualified crews perform it, using a soft brush or very low-suction vacuum near the head, no liquids and no pressure. Anything beyond light surface dust is documented and referred to the fire sprinkler contractor.",
 ["Head types: pendant, upright, sidewall or concealed", "Number of heads and access height", "Reporting procedure for painted or damaged heads", "Fire sprinkler contractor contact"],
 ["NFPA 25 maintenance standards call for replacing heads that are painted, corroded, damaged or loaded with debris; cleaning crews do not attempt to restore them.", "Concealed sprinkler cover plates can come off; do not press on them."],
 [("Can sprinkler heads be cleaned?", "Only very lightly, with minimal contact. Heads that are heavily loaded, painted or damaged should be replaced by a fire sprinkler contractor, not cleaned."),
  ("What does a dusty sprinkler head mean?", "Usually just construction dust. It should be removed gently or reported, because heavy loading can affect how a head responds."),
  ("Why not use a cleaner on sprinkler heads?", "Liquids and chemicals can corrode parts or damage the glass bulb, and pressure can move the deflector."),
  ("Who is responsible for damaged sprinkler heads?", "The fire sprinkler contractor repairs them, and the GC determines who pays based on what caused the damage.")]),
"Cable tray exterior dusting": T(
 "Cable tray exterior dusting removes construction dust and debris from the rails, rungs and bottoms of overhead cable trays without disturbing the cables inside.",
 "Cable tray is open by design, so dust and construction debris collect inside it and on its rails. In data and telecom spaces, dust can work its way into equipment; in open ceilings it is simply visible.",
 "HEPA vacuuming of tray rails and accessible surfaces, with debris like wire clippings removed by hand. Cables are not pulled, moved or wiped with liquids.",
 ["Linear feet and tray type: ladder, ventilated trough or wire basket", "Whether cables are installed", "Height and access", "Low-voltage or IT areas with special requirements"],
 ["Never pull or step on cables or tray; coordinate with the electrical or low-voltage contractor.", "Wire basket tray edges can be sharp; crews need cut-resistant gloves."],
 [("Is cleaning inside a cable tray allowed?", "Light vacuuming and removing loose debris is usually allowed. Moving or disturbing cables should be left to the electrical or low-voltage contractor."),
  ("Why clean cable trays?", "They collect dust and debris that sheds onto finished spaces and can be drawn into IT equipment."),
  ("What kind of debris is found in cable trays?", "Wire clippings, cable ties, packaging and drywall dust are common."),
  ("Is cable tray cleaning part of a data center clean?", "Yes, as part of a critical-environment clean done by trained crews.")]),
"Conduit run dusting": T(
 "Conduit run dusting removes dust and overspray from exposed electrical conduit, boxes and supports on walls and ceilings, including clusters of parallel runs in open-ceiling spaces.",
 "Conduit is often installed in bundles that create long dusty ledges. In exposed designs, painted conduit is a finish element, and dust on it is as visible as dust on the ceiling.",
 "HEPA brush vacuuming along each run with damp microfiber follow-up on painted conduit. Junction boxes and covers are wiped, never opened.",
 ["Linear feet of exposed conduit and number of parallel runs", "Painted or bare EMT and rigid conduit", "Height and access", "Junction boxes and fixture whips included"],
 ["Do not open electrical boxes or touch conductors.", "Painted conduit may have fresh paint that should not be scrubbed."],
 [("Do you need an electrician to clean conduit?", "No. Cleaning the outside of conduit and box covers is cleaning work. Opening boxes or touching wiring is not."),
  ("Why is conduit dusty in open ceilings?", "Like pipes and ducts, conduit runs are horizontal ledges that collect dust from every trade working overhead."),
  ("Can painted conduit be cleaned?", "Yes, with damp microfiber and neutral cleaners once the paint has cured."),
  ("Is conduit cleaned at the same time as the ceiling?", "Yes, it is cleaned in the same lift pass as the deck, joists and other MEP.")]),
"Unit heater exterior cleaning": T(
 "Unit heater exterior cleaning removes dust and debris from the housing, louvers and fan guards of suspended gas or electric unit heaters in warehouses, garages, shops and back-of-house areas.",
 "Unit heaters hang high and are installed early, so they collect heavy dust. When they fire for the first time, dust on the heat exchanger area can smoke and smell, and louvers spread dust across the room.",
 "With power off and locked out by the authorized trade, crews HEPA vacuum the housing, louvers and fan guard, then damp-wipe the exterior. Internal burners and heat exchangers are left to the mechanical contractor.",
 ["Number of units and mounting height", "Gas or electric and lockout responsibility", "Louvers, guards and hangers included", "Access around racking or equipment"],
 ["Units must be off and cool before cleaning, with lockout handled by the authorized trade.", "Internal combustion components are serviced only by the mechanical contractor."],
 [("Why do unit heaters smell when first turned on?", "Construction dust burning off the heat exchanger and housing. Cleaning the exterior and louvers before startup reduces it."),
  ("Can a cleaning crew clean inside a unit heater?", "No. Internal parts belong to the mechanical contractor. Cleaning crews handle the exterior only."),
  ("Should unit heaters be off during cleaning?", "Yes, off, cool and locked out by the authorized trade."),
  ("Where are unit heaters common?", "Warehouses, loading docks, garages, shops and back rooms of stores.")]),
"Overhead exhaust fan exterior cleaning": T(
 "Overhead exhaust fan exterior cleaning removes dust and debris from wall and ceiling exhaust fans, their grilles, guards and housings in restrooms, kitchens, warehouses and mechanical spaces.",
 "Exhaust fans pull air across their grilles, so dust builds up fast and is visible. In kitchens and restrooms, dirty exhaust grilles are a common inspection note.",
 "With fans off, crews vacuum grilles and guards with HEPA brush heads and damp-wipe housings. Grilles that are designed to be removed are cleaned and reinstalled.",
 ["Fan types and counts", "Removable versus fixed grilles", "Heights and access", "Lockout responsibility for larger fans"],
 ["Large exhaust fans must be locked out before guards are touched.", "Kitchen exhaust hoods and grease ducts are a separate regulated specialty."],
 [("Do restroom exhaust fans need cleaning at turnover?", "Yes. Their grilles collect drywall dust during construction and show it clearly."),
  ("Is kitchen exhaust fan cleaning the same as hood cleaning?", "No. Hood and grease duct cleaning is regulated under NFPA 96 and done by certified contractors."),
  ("Should exhaust fans be turned off before cleaning?", "Yes, and larger fans should be locked out by the authorized trade."),
  ("Can exhaust grilles be removed for cleaning?", "If they are designed to be removed, yes, and they are reinstalled afterward.")]),
"HVLS ceiling fan cleaning": T(
 "HVLS ceiling fan cleaning removes dust from the large-diameter, high-volume low-speed fans used in warehouses, gyms, barns and big-box stores. Blades, hub, motor housing and guy wires are included.",
 "HVLS fans move huge volumes of air, so dust on their blades is thrown across the space. Dust buildup can also affect balance and make the fan wobble.",
 "With the fan locked out, crews clean blades from a lift, working blade by blade with HEPA vacuums and damp microfiber, without bending blades or loading the mount.",
 ["Number of fans and blade diameter", "Mounting height and lift access", "Lockout responsibility", "Manufacturer cleaning guidance"],
 ["The fan must be locked out; a fan that turns during cleaning is a serious hazard.", "Blades are aligned at the factory; do not bend or put weight on them."],
 [("How do you clean a 24-foot ceiling fan?", "Locked out, from a lift, one blade at a time, using vacuums and damp cloths. Blades are not bent or loaded."),
  ("Why do big warehouse fans wobble?", "Uneven dust buildup and damage are common causes. Cleaning can help; persistent wobble needs the fan installer."),
  ("How often should HVLS fans be cleaned?", "Usually during scheduled high dusting, often once or twice a year depending on dust levels."),
  ("Do HVLS fans spread dust?", "Yes. Dust on blades is distributed across the space, which is why they belong in the overhead scope.")]),
"Ceiling fan cleaning": T(
 "Ceiling fan cleaning removes construction dust from standard commercial and residential ceiling fans, including blades, motor housings, light kits and downrods.",
 "When a dusty ceiling fan is turned on for the first time, it throws dust onto freshly cleaned floors, furniture and counters. It is a classic final-clean miss.",
 "With the fan off, crews hold each blade steady and wipe with damp microfiber, sliding a cover or bag over blades where helpful to keep dust from falling. Light kit glass is cleaned separately.",
 ["Number of fans and mounting heights", "Light kits and glass shades included", "Ladder or lift access", "Fan finishes that need special cleaners"],
 ["Turn fans off and let them stop before cleaning; never stop blades by hand.", "Avoid bending blades or brackets, which causes wobble."],
 [("Why clean ceiling fans before the final floor clean?", "Because turning on a dusty fan throws dust onto everything below. Clean high before low."),
  ("What is the best way to clean fan blades?", "Hold the blade steady and wipe with damp microfiber or slide a cloth sleeve along it so the dust is captured instead of falling."),
  ("Are fan light kits included?", "They should be. Glass shades and bulbs collect the same dust."),
  ("Do apartment ceiling fans need cleaning at turnover?", "Yes. They are part of a unit final clean and one of the first things residents notice.")]),
"High-bay light fixture cleaning": T(
 "High-bay light fixture cleaning removes dust and debris from the housings, lenses and reflectors of high-mounted LED or HID fixtures in warehouses, gyms, stores and manufacturing spaces.",
 "Dust on high-bay lenses reduces light output, and dust on housing tops falls when fixtures warm up and cool down. Lighting is also checked during commissioning and owner walks.",
 "Fixtures are de-energized as required, then HEPA vacuumed on top and wiped with dry or barely damp microfiber on lenses. Plastic lenses get only manufacturer-approved cleaners.",
 ["Fixture count, type and mounting height", "Lens material: glass, acrylic or polycarbonate", "Lift access around racking or equipment", "Power-off coordination"],
 ["Some plastic lenses are damaged by ammonia and solvent cleaners.", "Do not disturb fixture aiming or sensors."],
 [("Does cleaning light fixtures make the room brighter?", "Yes. Dust on lenses blocks light, so cleaning restores some output, especially in dusty spaces."),
  ("Can LED high bays be cleaned while on?", "Exterior wiping is sometimes allowed, but de-energizing is safer and is required by many owners. Follow the electrical contractor's direction."),
  ("What cleaner is safe for plastic light lenses?", "Mild soap and water or the manufacturer's recommended cleaner. Avoid ammonia and solvents."),
  ("Are occupancy sensors on fixtures cleaned?", "Gently wiped only. Sensors should not be moved or re-aimed.")]),
"Pendant and suspended light cleaning": T(
 "Pendant and suspended light cleaning removes construction dust from decorative and linear pendants, their shades, diffusers, cables and canopies, usually in offices, restaurants and retail spaces.",
 "Pendants hang in sightlines over tables, counters and desks. Dust on their tops and shades is visible, and anything that falls lands where people eat and work.",
 "Crews steady each pendant by hand, vacuum tops with soft HEPA brushes, then clean shades with methods matched to the material: glass, metal, fabric or acrylic.",
 ["Pendant count, sizes and materials", "Mounting height and access over furniture", "Fragile or specialty fixtures", "Manufacturer care guidance"],
 ["Do not pull or swing pendants by their cables; it can loosen connections or knock them out of level.", "Fabric shades should be cleaned dry."],
 [("How do you clean a pendant light without moving it?", "Hold it steady with one hand while cleaning with the other, using a soft brush vacuum and microfiber."),
  ("Can glass pendant shades be removed for cleaning?", "If they are designed to be removed, yes. Many decorative shades are cleaned in place to avoid breakage."),
  ("Why clean pendants before the dining room opens?", "Dust from pendants falls onto tables and food. They are also highly visible to guests."),
  ("Do fabric pendants need special cleaning?", "Yes. Use a soft dry brush or low-suction vacuum, not liquid.")]),
"Linear light fixture and lens cleaning": T(
 "Linear light fixture and lens cleaning removes dust, fingerprints and debris from recessed and surface-mounted troffers, linear LED fixtures and their diffusers in ceilings and walls.",
 "Recessed fixtures in finished ceilings are installed before the final cleaning, and installers' fingerprints and dust on lenses show clearly when the lights are on.",
 "Lenses and diffusers are wiped with dry or damp microfiber, inside surfaces are vacuumed if the lens opens easily, and trim edges are cleaned without pushing on ceiling tiles.",
 ["Fixture count and type", "Lens type: acrylic, polycarbonate, parabolic louver or open", "Whether lenses are removable", "Ceiling height and access"],
 ["Pushing up on ceiling tiles beside fixtures can crack tiles or shift the grid.", "Some diffusers scratch easily; use soft cloths only."],
 [("Should troffer lenses be removed for cleaning?", "Only if they are designed to open and dust is inside. Surface wiping is usually enough at turnover."),
  ("Why do new light fixtures have fingerprints?", "Installers handle lenses and trims during installation. Fingerprints show as smudges when lights are on."),
  ("Can linear fixtures be cleaned with glass cleaner?", "Many plastic lenses should not be. Use mild soap and water or the manufacturer's cleaner."),
  ("Is light fixture cleaning part of final clean?", "Yes. Lenses and trims are standard final clean items in finished ceilings.")]),
"Chandelier and decorative fixture cleaning": T(
 "Chandelier and decorative fixture cleaning removes dust and fingerprints from crystal, glass, metal and specialty decorative fixtures in lobbies, ballrooms, restaurants and hospitality spaces.",
 "Decorative fixtures are often the most expensive light fixtures in a building and the focal point of the room. Careless cleaning can break crystals, tarnish finishes or loosen parts.",
 "Specialists clean in place from lifts or scaffolding, piece by piece with cotton gloves and approved cleaners, or follow the manufacturer's disassembly procedure for heavily soiled fixtures.",
 ["Fixture size, weight, height and materials", "Manufacturer care instructions", "Access method and floor protection", "Whether disassembly is permitted"],
 ["Crystal and glass parts break easily; never spray cleaner directly onto electrical components.", "Some finishes, like antique brass, should not be polished."],
 [("How do you clean a crystal chandelier?", "Piece by piece, with gloves and an appropriate glass cleaner, or by carefully removing crystals for washing when the manufacturer allows."),
  ("Should a chandelier be turned off during cleaning?", "Yes. Power off and cool before cleaning, and never spray liquid into sockets."),
  ("Who cleans chandeliers in hotels?", "Specialists with lift access and experience with decorative fixtures."),
  ("How long does chandelier cleaning take?", "It depends on size and detail. Large crystal fixtures can take several hours each.")]),
"Track lighting cleaning": T(
 "Track lighting cleaning removes dust from track rails, heads, lenses and power feeds in retail, gallery, restaurant and office spaces.",
 "Track heads are aimed at products, art or displays, so dust and fingerprints show in the light pattern. Cleaning must not change the aim the lighting designer set.",
 "Crews wipe rails and heads with damp microfiber and lenses with appropriate cleaners, holding each head steady so its aim does not move.",
 ["Linear feet of track and number of heads", "Lens types and accessories", "Height and access over displays", "Aiming that must not be disturbed"],
 ["Moving track heads changes the lighting design; hold heads steady.", "Track heads may be hot if recently on."],
 [("Will cleaning track lights change their aim?", "It should not. Crews hold heads steady while cleaning so the designer's aiming is preserved."),
  ("Why clean track lighting in a new store?", "Dust on lenses dims the light and shows in the beam on merchandise."),
  ("Can track lights be cleaned while on?", "It is safer to turn them off and let them cool."),
  ("Do track rails need cleaning?", "Yes. Rails collect dust like any other ledge.")]),
"Exit sign and emergency light cleaning": T(
 "Exit sign and emergency light cleaning removes dust, overspray and labels from exit signs, emergency light units and combination fixtures so they are clean and clearly visible at inspection.",
 "Exit signs and emergency lights are life-safety devices checked during fire inspections. They must be visible and legible, and overspray or labels on the face can be a problem.",
 "Faces and housings are wiped with damp microfiber and appropriate cleaners. Test buttons and indicators are left untouched, and units are never disconnected.",
 ["Number of exit signs and emergency units", "Mounting heights", "Overspray or label removal needed", "Inspection date"],
 ["Do not press test buttons repeatedly or disconnect units.", "Painted-over exit signs may need replacement by the electrical contractor."],
 [("Do exit signs need cleaning before inspection?", "They should be clean and fully legible. Overspray or labels on the face can draw an inspector's attention."),
  ("Can paint overspray be removed from an exit sign?", "Often, carefully, with a plastic blade and mild remover. Heavy paint may require replacement."),
  ("Who maintains emergency lights after cleaning?", "The facility or electrical contractor tests and maintains them. Cleaners only clean the exterior."),
  ("Are exit signs part of final clean?", "Yes, they are a standard final clean item.")]),
"Clerestory and upper window cleaning": T(
 "Clerestory and upper window cleaning cleans interior and exterior glass of high windows and clerestory bands that are above normal reach, plus frames and sills.",
 "High windows let in daylight that shows every smudge and streak. They are often missed because they need lifts or poles and are not visible until the space is lit by daylight.",
 "Crews use pure-water poles where possible, or lifts for scraping and detail work, cleaning frames and sills first so debris does not fall on clean glass.",
 ["Number and size of upper windows", "Interior, exterior or both", "Access method: pole, lift or rope", "Construction debris on glass"],
 ["Water-fed poles cannot remove paint or labels; detail work needs a lift.", "Exterior upper glass may require fall protection and qualified crews."],
 [("How are high windows cleaned inside a building?", "With water-fed poles for routine cleaning and lifts when debris must be removed by hand."),
  ("What is a clerestory window?", "A band of windows high on a wall, above eye level, used to bring daylight into a space."),
  ("Are upper windows part of construction window cleaning?", "They should be. Confirm they are listed in the window cleaning scope."),
  ("Do clerestories need exterior cleaning too?", "Yes, usually from the roof or a lift, depending on the building.")]),
"Elevated signage and banner cleaning": T(
 "Elevated signage and banner cleaning removes dust and fingerprints from high-mounted signs, wayfinding, department signs, banners and graphics in stores, airports, stadiums and warehouses.",
 "Overhead signs are meant to be read from a distance, and dust or smudges on them look neglected. They are also hung from structure where dust from above settles on them.",
 "Crews clean signs from lifts with methods matched to the material: damp microfiber on acrylic and metal, dry brushing on fabric banners, and care not to shift hanging hardware.",
 ["Number, size and material of signs and banners", "Mounting heights and suspension methods", "Illuminated signs and electrical components", "Who installed them and warranty concerns"],
 ["Do not lean on or pull suspended signs.", "Illuminated signs should be off while cleaned."],
 [("Who cleans hanging store signs?", "The overhead cleaning crew, usually during store opening cleaning or scheduled high dusting."),
  ("Can fabric banners be cleaned in place?", "Light dust can be removed with a soft brush vacuum. Stains usually require removal and professional cleaning."),
  ("Do illuminated signs need special care?", "Yes, they should be off, and liquids kept away from electrical parts."),
  ("How often should overhead signs be cleaned?", "Usually with routine high dusting, often quarterly or semiannually.")]),
"Upper wall ledge and soffit cleaning": T(
 "Upper wall ledge and soffit cleaning removes dust and debris from high ledges, bulkheads, soffits, column caps and architectural reveals that are above normal reach.",
 "Ledges and soffits are flat surfaces near the ceiling that collect dust quietly. In lobbies and stores they are visible from balconies, escalators and stairs.",
 "Crews HEPA vacuum ledge tops and damp-wipe faces from ladders, poles or lifts, cleaning top to bottom so dust does not fall onto finished walls.",
 ["Linear feet of ledges and soffits", "Heights and access", "Finish materials", "Ledges visible from upper floors"],
 ["Ledges near lights may be warm; let fixtures cool.", "Avoid streaking painted soffits with dirty water."],
 [("Why are upper ledges so dusty?", "They are flat and high, so dust settles on them and no one sees it until it falls."),
  ("Are ledges part of the final clean?", "They should be. List high ledges and soffits in the scope, because some crews only clean what they can reach."),
  ("How do you clean ledges you cannot see from the floor?", "From a lift or ladder, vacuuming first, with a quick photo check."),
  ("Do soffits need washing or just dusting?", "Usually dusting and spot cleaning. Full washing is only needed for heavy soil.")]),
"Top of walk-in cooler box dusting": T(
 "Top of walk-in cooler box dusting removes dust and debris from the top panels of walk-in coolers and freezers, including condensing units and lines located on top of the box.",
 "The top of a walk-in is a hidden dust shelf in a food facility. Health inspectors and food safety auditors check it, and debris there can attract pests.",
 "Crews access the top safely from a ladder or lift, remove debris by hand, HEPA vacuum panels and damp-wipe with food-safe cleaners. Refrigeration components are left to the refrigeration contractor.",
 ["Number of walk-in boxes and panel area on top", "Clearance between box top and ceiling", "Refrigeration equipment on top", "Food-safe products required"],
 ["Do not walk on cooler tops unless the manufacturer confirms they can carry the load.", "Refrigeration lines and coils belong to the refrigeration contractor."],
 [("Do health inspectors check the top of walk-in coolers?", "Many do. It is a common place for dust, debris and pest activity."),
  ("Can you stand on top of a walk-in cooler?", "Only if the manufacturer confirms it is rated for foot traffic. Most crews work from a ladder or lift."),
  ("What is on top of a walk-in cooler?", "Often condensing units, refrigerant lines and electrical conduit, plus debris from construction."),
  ("Is walk-in top cleaning a construction or maintenance task?", "Both. It should be done at turnover and then routinely.")]),
"Top of millwork and display dusting": T(
 "Top of millwork and display dusting removes construction dust from the tops of tall cabinets, shelving, display fixtures, reception desks and casework that are above eye level.",
 "Tall millwork tops collect dust that no one sees until it falls onto stocked shelves or counters. It is a common miss in retail, hospitality and offices.",
 "Crews HEPA vacuum and damp-wipe tops from ladders, starting before shelves are stocked so dust does not fall onto merchandise or files.",
 ["Tall cabinets, displays and shelving to include", "Heights and access", "Finish materials", "Stocking schedule"],
 ["Dust falls onto stocked shelves if tops are cleaned too late.", "Avoid scratching high-gloss tops with gritty cloths."],
 [("Why clean the tops of tall cabinets?", "Dust collects there during construction and falls onto shelves, counters and products later."),
  ("When should display fixture tops be cleaned?", "Before merchandise or stock is placed."),
  ("Are millwork tops part of a final clean?", "On a complete scope, yes."),
  ("Can high-gloss millwork scratch during cleaning?", "Yes, if dust is wiped dry. Vacuum first, then wipe with clean, damp microfiber.")]),
"Quarterly high dusting program": T(
 "A quarterly high dusting program is scheduled overhead cleaning four times a year for an operating building: deck, structure, ducts, pipes, lights and signs, usually done overnight or outside business hours.",
 "Overhead dust returns after opening. Quarterly cleaning keeps it from building into visible streaks and falling onto product, and it fits retail and food facility audit cycles.",
 "Each visit follows a mapped route through the building, with HEPA capture, fixture covering and photo documentation, so every quarter covers the same surfaces consistently.",
 ["Building map and overhead zones", "Visit dates and allowed working hours", "Covering requirements for product and equipment", "Reporting and photo documentation format"],
 ["Skipping a quarter can double the next visit's workload.", "Operating sites need lift exclusion zones and coordination with store or plant management."],
 [("What does a quarterly high dusting program include?", "Scheduled overhead cleaning of the deck, structure, ducts, pipes, lights and signs four times a year, with documentation."),
  ("Is quarterly high dusting enough?", "For most retail and warehouse spaces it is. Very dusty operations or food facilities may need more frequent service."),
  ("Who runs quarterly high dusting programs?", "Our partner program, Above Eye Level Cleaning, focuses on recurring overhead work."),
  ("Can high dusting be scheduled around business hours?", "Yes. It is usually done overnight or before opening.")]),
"Semiannual overhead cleaning program": T(
 "A semiannual overhead cleaning program schedules overhead dust removal twice a year, a common rhythm for offices, schools, churches and lower-dust retail spaces.",
 "Twice-yearly cleaning keeps dust from accumulating to the point where it becomes visible or falls, at a lower cost than quarterly service.",
 "Visits are scheduled at predictable times, often before peak seasons or audits, with the same mapped surfaces and documented results each time.",
 ["Overhead surfaces and zones", "Preferred months and hours", "Access equipment", "Documentation needs"],
 ["Dustier environments may outgrow a semiannual schedule.", "Seasonal heating or cooling changes can kick up dust between visits."],
 [("When is semiannual high dusting enough?", "In offices, churches, schools and low-dust retail. Warehouses and food facilities often need more."),
  ("When should semiannual cleaning be scheduled?", "Often before the busy season, before audits, or around school breaks."),
  ("Does semiannual cleaning include lights and vents?", "Yes, it covers all overhead surfaces in the agreed scope."),
  ("Can a semiannual program change to quarterly?", "Yes, if dust levels or audit requirements call for it.")]),
"Annual deep overhead cleaning": T(
 "Annual deep overhead cleaning is a once-a-year, full overhead clean that covers every surface above eye level, often timed with shutdowns, school summers or inventory periods.",
 "Some buildings only need overhead cleaning once a year, and others need a yearly deep reset in addition to lighter routine cleaning. It prevents years of buildup.",
 "Crews plan the full building ahead of time, staging lifts by zone and capturing dust with HEPA systems, with detailed documentation for the facility's records.",
 ["Complete overhead surface inventory", "Shutdown or low-activity window", "Equipment and staging plan", "Documentation and reporting"],
 ["A year of buildup takes longer to clean than the same area cleaned quarterly.", "Plan around operational shutdowns well in advance."],
 [("What is the difference between annual and routine high dusting?", "Annual cleaning is usually deeper and broader, covering everything overhead once a year."),
  ("When do schools schedule annual overhead cleaning?", "Usually in summer, when buildings are empty."),
  ("Is annual cleaning enough for a food facility?", "Usually not. Food facilities typically need more frequent overhead cleaning."),
  ("How long does an annual deep overhead clean take?", "It depends on building size and buildup. Large facilities may take several shifts.")]),
"Pre-audit overhead cleaning for food facilities": T(
 "Pre-audit overhead cleaning prepares food plants, commissaries, grocery back rooms and food warehouses for third-party food safety audits by removing dust, debris and residue from overhead structures and equipment.",
 "Food safety auditors look up. Overhead dust, flaking paint and debris above food zones are common findings that can cost points or trigger corrective actions.",
 "Crews clean from the top down in food-safe sequence, using food-safe products, covering exposed product and equipment, and documenting areas cleaned for the audit file.",
 ["Audit date and scheme requirements", "Food zones and production schedules", "Approved chemicals list", "Documentation format for the audit file"],
 ["Only food-safe products approved by the facility may be used.", "Production must be stopped or product covered in areas being cleaned."],
 [("What overhead areas do food safety auditors check?", "Ceilings, beams, pipes, ducts, lights and the tops of equipment and walk-ins above food areas."),
  ("How far ahead of an audit should overhead cleaning happen?", "Close enough that dust has not returned, but with time to fix anything found. Many facilities schedule it one to two weeks before."),
  ("Can overhead cleaning be done during production?", "Usually not above exposed product. It is scheduled during sanitation shifts or shutdowns."),
  ("Who provides overhead cleaning documentation for audits?", "The cleaning contractor provides a record of areas cleaned, dates and products used.")]),
"Overnight high dusting in operating stores": T(
 "Overnight high dusting in operating stores cleans overhead surfaces after closing so the store opens the next morning without disruption. Lifts, covers and crews are out before the doors open.",
 "Stores cannot close for overhead cleaning, and lifts over shoppers are unsafe. Overnight work keeps sales going while overhead dust is removed.",
 "Crews work zone by zone after close, covering merchandise and fixtures, HEPA vacuuming overhead surfaces and removing covers before opening.",
 ["Store hours and overnight access", "Zones and sequence", "Covering requirements for merchandise", "Store management contact and sign-off"],
 ["Crews must finish and clear lifts before opening.", "Covering and uncovering merchandise takes time and must be planned."],
 [("How does overnight high dusting work?", "Crews arrive after close, cover merchandise, clean overhead surfaces zone by zone, uncover and leave before opening."),
  ("Is overnight high dusting more expensive?", "Night labor can cost more, but it avoids lost sales and keeps shoppers safe."),
  ("Will merchandise get dusty during overnight cleaning?", "Not if it is properly covered and dust is captured with HEPA equipment."),
  ("How long does overnight high dusting take?", "Usually one or more nights, depending on store size.")]),
}
