def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Spot cleaning of painted walls": T(
 "Spot cleaning of painted walls removes fingerprints, scuffs, smudges and small marks from new paint without damaging the finish or leaving shiny patches.",
 "Painted walls collect marks from every trade that touches them, and fingerprints and scuffs are among the most common punch items on any owner walk.",
 "Crews start with damp microfiber, then a pH-neutral cleaner, and only then a lightly used melamine sponge, testing first so flat and eggshell paints are not burnished.",
 ["Paint sheen and cure date", "Areas and wall heights", "Touch-up paint availability", "Punch list items"],
 ["Scrubbing flat paint leaves shiny spots that are worse than the mark.", "Some marks need touch-up paint, not cleaning."],
 [("How do you clean scuffs off new paint without damaging it?", "Gently, starting with water and microfiber, then a neutral cleaner, testing in an inconspicuous spot."),
  ("Why does cleaning leave shiny spots on walls?", "Rubbing flat or matte paint burnishes it. Use light pressure and the gentlest method."),
  ("When should marks be painted instead of cleaned?", "When cleaning would damage the finish or the mark does not come off."),
  ("Is wall spot cleaning part of final clean?", "Yes, it is a standard final clean item.")]),
"Full wall washing": T(
 "Full wall washing cleans entire wall surfaces top to bottom, typically on durable finishes like semi-gloss paint, epoxy, FRP or tile, where dust film or overspray covers whole walls.",
 "Some spaces, such as kitchens, restrooms, healthcare rooms and back-of-house areas, need walls cleaned completely, not just spot-cleaned, before occupancy.",
 "Crews work bottom-up with cleaning solution to prevent streaking and top-down for rinsing, using two-bucket systems and changing water often.",
 ["Wall areas and finishes", "Paint cure time", "Cleaning solution compatibility", "Protection of floors and outlets"],
 ["Not all paints are washable; check the paint specification.", "Water near outlets and switches must be controlled."],
 [("Can all painted walls be washed?", "No. Only washable paints that have cured should be washed fully."),
  ("Why wash walls bottom to top?", "Washing from the bottom prevents dirty drips from streaking dry areas below."),
  ("Which spaces need full wall washing?", "Kitchens, restrooms, healthcare and back-of-house areas often do."),
  ("How long before new paint can be washed?", "It depends on the paint; many need weeks to fully cure.")]),
"Wallcovering and vinyl wall cleaning": T(
 "Wallcovering and vinyl wall cleaning removes dust, adhesive smears and marks from commercial vinyl wallcovering, textiles and specialty wall finishes using methods the manufacturer allows.",
 "Wallcovering paste squeezes out at seams and dries shiny, and textile wallcoverings stain easily. The wrong cleaner can remove pattern or texture.",
 "Crews remove paste residue with damp sponges and approved cleaners, clean vinyl with mild solutions and treat textile wallcoverings only with dry or manufacturer-approved methods.",
 ["Wallcovering type and manufacturer", "Seams with paste residue", "Areas and heights", "Approved cleaning methods"],
 ["Textile wallcoverings can water-stain.", "Solvents can damage vinyl and inks."],
 [("How do you remove wallpaper paste from vinyl wallcovering?", "With warm water and a damp sponge, rinsing often, before it fully hardens if possible."),
  ("Can fabric wallcoverings be washed?", "Usually not. They need dry cleaning methods or manufacturer-approved products."),
  ("Why do wallcovering seams look shiny?", "Dried paste residue. It needs careful removal."),
  ("Who cleans paste off new wallcovering?", "The installer should, but final cleaning crews often finish the job.")]),
"Wall protection and corner guard cleaning": T(
 "Wall protection and corner guard cleaning removes film, adhesive, dust and marks from crash rails, bumper guards, corner guards and wall protection panels in healthcare, schools and back-of-house areas.",
 "Wall protection ships with protective film and adhesive residue, and its textured surfaces hold dust. It is checked in healthcare inspections.",
 "Crews remove protective film, clean adhesive with removers safe for vinyl and PVC, and wipe rails and guards with damp microfiber.",
 ["Linear feet of rails and guards", "Protective films", "Material type", "Healthcare cleaning requirements"],
 ["Solvents can damage PVC and acrylic covers.", "Do not loosen mounting hardware."],
 [("What is wall protection?", "Rails, guards and panels that protect walls from carts and equipment."),
  ("How do you clean crash rails?", "With damp microfiber and mild cleaners, removing film and residue."),
  ("Are corner guards cleaned at final clean?", "Yes."),
  ("Why is wall protection common in hospitals?", "Carts and beds constantly hit walls in healthcare buildings.")]),
"Acoustic wall panel vacuuming": T(
 "Acoustic wall panel vacuuming removes dust from fabric-wrapped, felt and perforated acoustic wall panels with soft brush attachments and low suction, without liquids.",
 "Acoustic panels absorb sound because they are porous, and that same porosity traps dust. Liquids stain fabric and can damage the core.",
 "Crews vacuum panels with soft brush heads, top to bottom, and refer stains to the manufacturer's spot-cleaning method.",
 ["Panel count and size", "Fabric type", "Stains and marks", "Manufacturer guidance"],
 ["Water stains fabric panels.", "High suction can pull fabric loose."],
 [("How do you clean fabric acoustic panels?", "With a soft brush vacuum attachment. Spots are treated only with approved methods."),
  ("Can acoustic panels be wiped?", "Fabric panels should not be wiped with liquids."),
  ("Why do acoustic panels collect dust?", "Their porous surfaces absorb sound and trap dust."),
  ("Who cleans acoustic panels?", "The cleaning contractor at final clean.")]),
"Wood wall panel and slat cleaning": T(
 "Wood wall panel and slat cleaning removes dust and fingerprints from wood veneer panels, slat walls and wood feature walls using finish-safe methods.",
 "Wood walls are feature elements, and slat walls trap dust between every slat. Water and harsh cleaners can damage wood finishes.",
 "Crews vacuum slat gaps with soft crevice tools and wipe faces with dry or barely damp microfiber and wood-safe cleaners.",
 ["Wall area and wood finish", "Slat spacing", "Acoustic backing behind slats", "Fingerprints and marks"],
 ["Excess water raises grain and damages finishes.", "Acoustic felt behind slats can stain if wet."],
 [("How do you clean a wood slat wall?", "Vacuum between the slats and wipe the faces with barely damp microfiber."),
  ("Can wood veneer walls be cleaned with all-purpose cleaner?", "Use only wood-safe cleaners suited to the finish."),
  ("Why do slat walls get so dusty?", "The gaps between slats trap dust."),
  ("Are wood walls part of final clean?", "Yes.")]),
"Stone and tile wall cleaning": T(
 "Stone and tile wall cleaning removes grout haze, dust, setting material and marks from tiled and stone-clad walls in restrooms, lobbies, showers and feature areas.",
 "Wall tile often has grout haze and thinset smears that are visible in raking light. Natural stone is sensitive to acidic cleaners.",
 "Crews clean with pH-neutral cleaners on stone and appropriate haze removers on ceramic and porcelain, testing first and rinsing thoroughly.",
 ["Tile and stone types", "Grout type", "Haze or residue present", "Sealer status"],
 ["Acids etch marble, limestone and travertine.", "Unsealed stone absorbs cleaners and stains."],
 [("How do you clean a new tile wall?", "Remove haze with a remover suited to the tile and grout, then clean with neutral cleaner."),
  ("Can stone walls be cleaned with vinegar?", "No. Vinegar is acidic and can etch marble and limestone."),
  ("Is grout haze on walls common?", "Yes, especially on textured tile."),
  ("Should stone walls be sealed?", "Many natural stones are sealed by the installer; ask before cleaning.")]),
"Marker board and whiteboard wall cleaning": T(
 "Marker board and whiteboard wall cleaning removes film, dust, marks and adhesive from whiteboards, glass boards and writable wall coatings before first use.",
 "New boards often have protective film, dust or marks from installers. Wrong cleaners can damage writable surfaces and cause ghosting.",
 "Crews remove film carefully, clean with the board manufacturer's recommended cleaner and wipe trays and frames.",
 ["Board types and sizes", "Protective films", "Manufacturer cleaners", "Trays and frames"],
 ["Abrasive cleaners damage writable surfaces.", "Some coatings need cure time before use."],
 [("How should a new whiteboard be cleaned?", "Remove the film and use the manufacturer's recommended cleaner."),
  ("Can glass cleaner be used on whiteboards?", "Only if the manufacturer allows it."),
  ("What is ghosting on a whiteboard?", "Faint marks left after erasing, often from improper cleaning or markers."),
  ("Do writable wall coatings need special care?", "Yes, follow the coating manufacturer's instructions.")]),
"Stainless and metal wall panel cleaning": T(
 "Stainless and metal wall panel cleaning removes film, fingerprints, adhesive and streaks from stainless steel, aluminum and metal composite panels on interior walls, elevator lobbies and kitchens.",
 "Metal panels show every fingerprint and streak, and the wrong cleaner or wiping direction leaves visible marks.",
 "Crews remove protective film, clean adhesive with metal-safe removers, wash with neutral cleaner and finish with the grain.",
 ["Panel areas and metal type", "Protective film", "Finish direction", "Adhesive residue"],
 ["Chloride cleaners and steel wool can cause stainless to rust.", "Wiping against the grain leaves streaks."],
 [("How do you clean stainless steel wall panels without streaks?", "Clean with neutral cleaner, rinse, dry and wipe with the grain."),
  ("Why should steel wool never be used on stainless?", "It can leave particles that rust and scratch the surface."),
  ("When should protective film be removed from metal panels?", "At final clean, not too late, as heat makes adhesive harder to remove."),
  ("Are metal composite panels cleaned the same way?", "Similar methods apply; follow the manufacturer's guidance.")]),
"Acoustic ceiling tile spot cleaning": T(
 "Acoustic ceiling tile spot cleaning removes fingerprints, smudges and light marks from lay-in ceiling tiles using dry sponges, erasers and low-moisture methods.",
 "Installers handle tiles with dirty hands and fingerprints show clearly. Water-based cleaning can stain mineral fiber tiles.",
 "Crews use dry cleaning sponges and art gum erasers first, then very light low-moisture cleaners only on tiles rated for them, and flag damaged tiles for replacement.",
 ["Ceiling area and tile type", "Marks and stains present", "Attic stock for replacements", "Access"],
 ["Water and liquid cleaners can leave rings on mineral fiber tiles.", "Pressing up on tiles can crack them or shift the grid."],
 [("How do you remove fingerprints from ceiling tiles?", "With dry cleaning sponges or erasers, avoiding liquids."),
  ("Can water stains on ceiling tiles be cleaned?", "Usually not. Stained tiles are typically replaced."),
  ("Is it cheaper to replace or clean ceiling tiles?", "For heavy marks, replacement from attic stock is often easier."),
  ("Who replaces damaged ceiling tiles?", "The ceiling installer, usually during punch.")]),
"Ceiling grid cleaning": T(
 "Ceiling grid cleaning removes dust, fingerprints and overspray from the exposed metal tees of a suspended ceiling system.",
 "Grid shows fingerprints and dust clearly, especially on white grid near lights. Dirty grid is a common punch item.",
 "Crews wipe grid with damp microfiber and mild cleaners, holding the grid steady so tiles are not dislodged.",
 ["Ceiling area and grid finish", "Overspray", "Access", "Coordination with tile cleaning"],
 ["Pushing on grid can dislodge tiles.", "Solvents can damage grid paint."],
 [("How do you clean ceiling grid?", "Wipe with damp microfiber and mild cleaner, holding it steady."),
  ("Why is ceiling grid dirty in new buildings?", "Installers and above-ceiling trades handle it."),
  ("Can paint overspray be removed from grid?", "Often, with careful use of removers that will not damage the grid finish."),
  ("Is grid cleaning part of final clean?", "Yes.")]),
"Drywall ceiling and soffit cleaning": T(
 "Drywall ceiling and soffit cleaning removes dust, cobwebs and marks from painted gypsum ceilings, bulkheads and soffits.",
 "Hard-lid ceilings show dust lines along edges and fingerprints near access panels. Dust on ceilings also falls onto clean floors.",
 "Crews dust ceilings with microfiber pole mops before floors are cleaned and spot-clean marks with gentle methods.",
 ["Ceiling area and heights", "Paint sheen", "Access panels and fixtures", "Sequence before floor cleaning"],
 ["Flat ceiling paint burnishes easily.", "Heavy marks may need touch-up painting."],
 [("Do drywall ceilings need cleaning after construction?", "Yes, they collect dust and fingerprints."),
  ("When should ceilings be cleaned?", "Before walls and floors, because dust falls."),
  ("Can ceiling marks be cleaned or should they be painted?", "Light marks can be cleaned; heavy marks need touch-up."),
  ("How are high drywall ceilings cleaned?", "With pole tools or lifts.")]),
"Wood and specialty ceiling cleaning": T(
 "Wood and specialty ceiling cleaning removes dust from linear wood, baffle, perforated wood, metal mesh and specialty ceiling systems with methods matched to each material.",
 "Specialty ceilings are often feature elements in lobbies and restaurants. They are expensive, hard to reach and easy to damage.",
 "Crews vacuum with soft brushes and wipe only where the finish allows, following the ceiling manufacturer's care guidance.",
 ["Ceiling system and finish", "Manufacturer guidance", "Height and access", "Removable panels"],
 ["Wood ceilings can water-stain.", "Panels may come loose if pushed."],
 [("How are wood ceilings cleaned?", "With soft brush vacuuming and, if sealed, barely damp microfiber."),
  ("What is a linear wood ceiling?", "A ceiling made of parallel wood slats or planks."),
  ("Can specialty ceiling panels be removed for cleaning?", "Some can; follow manufacturer instructions."),
  ("Who cleans feature ceilings?", "Cleaning crews with lift access and care for specialty finishes.")]),
"Metal ceiling panel cleaning": T(
 "Metal ceiling panel cleaning removes dust, fingerprints and film from metal pan, linear metal and perforated metal ceiling systems.",
 "Metal ceilings show fingerprints and smudges, and perforations hold dust.",
 "Crews remove film, vacuum perforated panels and wipe surfaces with mild cleaners, handling panels with gloves.",
 ["Panel type and finish", "Perforations and acoustic backing", "Access", "Film removal"],
 ["Fingerprints from bare hands show; wear gloves.", "Wetting acoustic backing behind perforations can stain it."],
 [("How do you clean perforated metal ceiling panels?", "Vacuum with soft brushes and wipe without soaking the backing."),
  ("Why do metal ceilings show fingerprints?", "Their smooth, often light finishes show oils from hands."),
  ("Do metal ceiling panels have protective film?", "Some do, and it is removed at final clean."),
  ("Are metal ceilings common in healthcare?", "Yes, because they are durable and cleanable.")]),
"Ceiling diffuser and grille face cleaning": T(
 "Ceiling diffuser and grille face cleaning removes dust, overspray and smudges from supply diffusers, return grilles and registers on ceilings and walls.",
 "Diffusers collect construction dust and show dark streaks once the HVAC runs. They are an early sign of dirty air to owners.",
 "Crews vacuum and wipe diffuser faces and blades with microfiber, and coordinate with the mechanical contractor before removing any diffuser.",
 ["Number of diffusers and grilles", "Removable or fixed", "Overspray present", "Coordination with HVAC balancing"],
 ["Do not change damper or blade settings set by the balancer.", "Interior duct cleaning is a separate specialty."],
 [("Why are new air vents dirty?", "Construction dust settles on them and the airflow streaks it."),
  ("Is diffuser cleaning the same as duct cleaning?", "No. Diffuser face cleaning is surface cleaning; duct cleaning is a specialty."),
  ("Can diffusers be removed for cleaning?", "Only with the mechanical contractor's coordination."),
  ("Should diffusers be cleaned before HVAC balancing?", "Ideally, cleaning should not change balanced settings; coordinate timing.")]),
"Access panel cleaning": T(
 "Access panel cleaning removes dust, fingerprints and overspray from ceiling and wall access doors, including their frames and hardware.",
 "Access panels are opened by trades during construction and get fingerprints and smudges. They also collect dust on their frames.",
 "Crews wipe panel faces and frames with damp microfiber and check that panels are fully closed after cleaning.",
 ["Number of access panels", "Finishes", "Fingerprints and overspray", "Locking hardware"],
 ["Do not leave panels open.", "Painted panels may need touch-up."],
 [("Why are access panels dirty?", "Trades open them repeatedly with dirty hands."),
  ("Are access panels cleaned at final clean?", "Yes."),
  ("What if an access panel is painted shut?", "Report it so the painter or trade can free it."),
  ("Do access panels need to stay closed?", "Yes, especially fire-rated panels.")]),
}
