def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Door face cleaning": T(
 "Door face cleaning removes dust, fingerprints, labels, pencil marks and smudges from both faces of wood, metal, laminate and glass doors.",
 "Doors are touched by everyone and inspected closely. Factory labels, handling marks and overspray on door faces are frequent punch items.",
 "Crews remove labels, clean faces with finish-safe cleaners and microfiber, and check both sides of every door against a door schedule.",
 ["Door count by type and finish", "Labels and protective films", "Overspray or adhesive", "Door schedule for tracking"],
 ["Wood door finishes can be damaged by harsh cleaners.", "Do not remove fire rating labels."],
 [("How should new wood doors be cleaned?", "With mild, wood-safe cleaners and soft cloths."),
  ("Why are door faces a common punch item?", "They collect fingerprints, labels and marks from trades."),
  ("Should door labels be removed?", "Factory stickers yes; fire rating labels no."),
  ("Are both sides of doors cleaned?", "Yes, plus edges and tops.")]),
"Door frame and jamb cleaning": T(
 "Door frame and jamb cleaning removes dust, overspray, caulk smears and fingerprints from hollow metal and wood frames, jambs, stops and hinges.",
 "Frames are painted on site and often get overspray, caulk and fingerprints. Dust in hinge areas and stops is easy to miss.",
 "Crews wipe frames and stops, clean hinges and strike plates and remove light overspray with plastic blades and mild removers.",
 ["Number of frames", "Frame finish", "Overspray and caulk", "Hinges and strikes"],
 ["Solvents can soften fresh paint.", "Fire labels on frames must remain."],
 [("What is a door jamb?", "The vertical sides of a door frame."),
  ("Why do door frames get overspray?", "They are often painted near walls and other finishes."),
  ("Should hinges be cleaned?", "Yes, they collect dust and paint."),
  ("Are frame fire labels important?", "Yes. Do not remove or paint over them.")]),
"Door hardware polishing": T(
 "Door hardware polishing cleans and finishes levers, knobs, pulls, hinges, closers and locksets so they are free of fingerprints, paint, film and residue.",
 "Hardware is touched first and judged first. Paint on hardware, film left on finishes and fingerprints are classic punch items.",
 "Crews remove film and paint carefully, clean with finish-appropriate products and avoid polishes that strip lacquered or specialty finishes.",
 ["Hardware finishes", "Paint on hardware", "Protective film", "Closers and electrified hardware"],
 ["Some metal polishes strip protective lacquer.", "Do not adjust closers or electrified hardware."],
 [("How do you remove paint from door hardware?", "Carefully, with plastic tools and mild removers safe for the finish."),
  ("Can brass hardware be polished?", "Only if it is unlacquered. Lacquered brass should only be cleaned."),
  ("Should hardware film be removed at final clean?", "Yes."),
  ("Why avoid abrasive pads on hardware?", "They scratch finishes.")]),
"Door kick and push plate polishing": T(
 "Door kick and push plate polishing cleans protective plates on doors, removing film, adhesive, fingerprints and scuffs from stainless, brass or plastic plates.",
 "Kick and push plates are installed late and are often still covered in film or adhesive at turnover. Stainless plates show fingerprints immediately.",
 "Crews remove film and adhesive, clean with neutral cleaners and finish stainless with the grain.",
 ["Number and types of plates", "Film and adhesive", "Finish direction", "Door finish around plates"],
 ["Adhesive removers can damage door finishes around plates.", "Abrasives scratch stainless."],
 [("What is a kick plate?", "A protective plate at the bottom of a door that prevents damage."),
  ("How do you clean stainless kick plates?", "With neutral cleaner, then wipe with the grain."),
  ("Do push plates come with film?", "Often, and it should be removed at final clean."),
  ("Are kick plates part of final clean?", "Yes.")]),
"Door vision lite cleaning": T(
 "Door vision lite cleaning cleans the glass panels set into doors, including both faces, the glazing stops and labels.",
 "Vision lites are looked through constantly, so smudges, labels and glazing compound are noticed. Fire-rated glass may have required markings.",
 "Crews remove labels, clean glass with appropriate cleaners and wipe stops, leaving any required fire rating etching untouched.",
 ["Number of vision lites", "Glass type: fire-rated, tempered or wired", "Labels and glazing compound", "Stops and frames"],
 ["Fire-rated glass markings must remain.", "Wired glass edges can be sharp if damaged."],
 [("What is a door vision lite?", "A glass panel in a door that lets people see through it."),
  ("Should labels on vision lites be removed?", "Temporary labels yes; permanent fire rating marks no."),
  ("Is fire-rated glass cleaned differently?", "It is cleaned normally, but markings must not be removed."),
  ("Are vision lites part of final clean?", "Yes.")]),
"Overhead coil and roll-up door cleaning": T(
 "Overhead coil and roll-up door cleaning removes dust, overspray and debris from coiling doors, their curtains, guides, hoods and bottom bars.",
 "Coiling doors collect dust in their slats and guides, and debris in guides can affect operation. They are used constantly at docks and service areas.",
 "Crews clean the curtain in sections as the door is operated by authorized staff, vacuum guides and wipe hoods without lubricating or adjusting anything.",
 ["Number and size of doors", "Operation by authorized personnel", "Guides and hoods", "Fire doors and their requirements"],
 ["Do not operate doors without authorization.", "Fire-rated coiling doors have release mechanisms that must not be disturbed."],
 [("How do you clean a roll-up door?", "Clean the curtain in sections while the door is moved by authorized staff."),
  ("Why clean the door guides?", "Debris in guides can affect how the door runs."),
  ("Are fire-rated rolling doors cleaned the same way?", "Their release mechanisms must not be disturbed."),
  ("Who adjusts roll-up doors?", "The door contractor, not the cleaning crew.")]),
"Sectional and dock door cleaning": T(
 "Sectional and dock door cleaning cleans overhead sectional doors, their panels, windows, tracks, seals and dock shelters at loading docks.",
 "Dock doors take heavy dirt from trucks and weather. Dirty panels and windows look neglected, and debris in tracks affects operation.",
 "Crews wash panels and windows, vacuum tracks and clean seals and shelters with methods that do not damage weatherstripping.",
 ["Number of doors and size", "Windows in panels", "Seals and dock shelters", "Operation by authorized staff"],
 ["Do not adjust springs or cables.", "Harsh cleaners can damage weather seals."],
 [("What is a sectional door?", "An overhead door made of panels that roll up on tracks."),
  ("Are dock shelters cleaned?", "Yes, they collect debris and grime."),
  ("Should door springs be touched during cleaning?", "No. They are under high tension."),
  ("How often are dock doors cleaned?", "At turnover and then as part of maintenance.")]),
"Revolving door cleaning": T(
 "Revolving door cleaning details the glass wings, canopy, drum enclosure, floor and sweeps of manual or automatic revolving doors.",
 "Revolving doors are the front door of many buildings and are highly visible. They have tight spaces and moving parts that need careful cleaning.",
 "Crews clean with the door secured, working wing by wing on glass and metal and vacuuming the floor ring and sweeps.",
 ["Door type: manual or automatic", "Glass and metal finishes", "Floor and sweep condition", "Security and lockout"],
 ["Automatic doors must be switched off by authorized staff.", "Do not adjust sweeps or sensors."],
 [("How is a revolving door cleaned?", "Wing by wing with the door secured, including glass, metal and floor."),
  ("Are automatic revolving doors dangerous to clean?", "They must be turned off by authorized staff first."),
  ("Why clean revolving door sweeps?", "Debris in sweeps affects performance and appearance."),
  ("Is revolving door cleaning a specialty?", "It needs care and coordination, so it is often handled by experienced crews.")]),
"Automatic sliding door track cleaning": T(
 "Automatic sliding door track cleaning removes debris, dust and grit from floor tracks, sensors and glass of automatic entrance doors.",
 "Debris in floor tracks can stop doors from closing or cause service calls. Sensors covered in dust can misread.",
 "Crews vacuum tracks, wipe sensors gently and clean glass, with the door powered off or in manual mode by authorized staff.",
 ["Number of doors", "Track type", "Sensor locations", "Power or mode control"],
 ["Do not adjust sensors or door settings.", "Doors must be off or in a safe mode during cleaning."],
 [("Why do automatic doors stop working after construction?", "Debris in tracks or dust on sensors is a common cause."),
  ("How do you clean a sliding door track?", "Vacuum debris and wipe the track, with the door secured."),
  ("Can cleaning damage door sensors?", "Wiping gently with a dry cloth should not."),
  ("Who services automatic doors?", "The door contractor.")]),
"Fire door label-safe cleaning": T(
 "Fire door label-safe cleaning cleans fire-rated doors and frames without removing, painting over or damaging their fire rating labels.",
 "Fire inspectors check that doors and frames have legible rating labels. A removed or painted label can mean replacing the door or getting it re-labeled.",
 "Crews locate labels before cleaning, clean around them and report any labels that are missing, painted or damaged.",
 ["Fire-rated door locations", "Label locations on doors and frames", "Paint on labels", "Reporting procedure"],
 ["Never remove or scrape fire labels.", "Painted labels must be reported, not cleaned aggressively."],
 [("Where is the fire label on a door?", "Usually on the hinge edge of the door and on the frame."),
  ("What if a fire label is painted over?", "Report it. The GC may need to arrange for relabeling."),
  ("Can fire doors be cleaned normally?", "Yes, while protecting the labels."),
  ("Why do fire labels matter?", "They show the door is rated for fire resistance.")]),
"Door threshold and sweep cleaning": T(
 "Door threshold and sweep cleaning removes debris, mortar, sealant and dirt from thresholds, saddles, door sweeps and bottom seals.",
 "Thresholds collect mortar, sealant and grit from construction. Dirty sweeps let air and water in and look unfinished.",
 "Crews scrape and clean thresholds, vacuum sweeps and wipe metal surfaces, taking care not to damage seals.",
 ["Number of thresholds", "Materials", "Sealant and mortar residue", "Door sweeps and seals"],
 ["Scraping can damage threshold finishes.", "Do not pull or adjust sweeps."],
 [("What is a door threshold?", "The strip at the bottom of a doorway between floors."),
  ("Why clean door sweeps?", "Debris prevents a good seal and looks unfinished."),
  ("How is mortar removed from a threshold?", "Carefully, with scrapers and appropriate removers."),
  ("Are thresholds part of final clean?", "Yes.")]),
"Cabinet interior and exterior detailing": T(
 "Cabinet interior and exterior detailing fully cleans casework: faces, edges, doors, interiors, shelves, hardware and toe kicks.",
 "Cabinets are opened, touched and inspected more than almost any other finish. Dust, labels and fingerprints on cabinets are always noticed.",
 "Crews vacuum interiors, remove labels and film, wipe exteriors with finish-safe cleaners and detail edges, hardware and toe kicks.",
 ["Cabinet count and finishes", "Interiors and shelves", "Hardware and film", "Toe kicks"],
 ["Excess water damages particleboard edges.", "Ammonia cleaners damage some finishes."],
 [("What does cabinet detailing include?", "Interiors, exteriors, edges, hardware and toe kicks."),
  ("How should laminate cabinets be cleaned?", "With mild cleaners and soft cloths."),
  ("Do cabinet doors need cleaning on both sides?", "Yes."),
  ("Why clean toe kicks?", "They collect dust and are seen at floor level.")]),
"Drawer interior vacuum and wipe": T(
 "Drawer interior vacuum and wipe cleans the inside of every drawer, including corners, slides and drawer boxes, removing dust, sawdust and debris.",
 "Drawers are among the first things owners and residents open. Construction dust and debris inside them make a space feel unfinished.",
 "Crews open each drawer, vacuum corners with crevice tools and wipe with damp microfiber, checking slides are free of debris.",
 ["Number of drawers", "Drawer box material", "Slide types", "Shelf liners"],
 ["Do not remove drawers from slides unless designed to.", "Excess moisture can swell wood boxes."],
 [("Do drawers need to be cleaned in a new building?", "Yes, they collect dust and debris."),
  ("How do you clean drawer corners?", "With a crevice tool and damp cloth."),
  ("Can debris affect drawer slides?", "Yes, it can make drawers stick."),
  ("Are drawers part of final clean?", "Yes.")]),
"Countertop cleaning by material": T(
 "Countertop cleaning by material cleans counters with methods matched to their surface: quartz, granite, marble, solid surface, laminate, stainless, concrete or wood.",
 "Each countertop material has its own sensitivities. Using the same cleaner on every counter can etch stone, dull quartz or damage wood.",
 "Crews identify each counter type from the finish schedule and use the matching cleaner, testing residue removal methods first.",
 ["Finish schedule with counter materials", "Residues present", "Sealer status", "Manufacturer care guides"],
 ["Acids etch marble and limestone.", "Strong alkalis can dull quartz."],
 [("Why does countertop material matter for cleaning?", "Different materials react differently to cleaners."),
  ("What is the safest general countertop cleaner?", "A pH-neutral cleaner is safe on most surfaces."),
  ("How do you find out what the counter is made of?", "Check the finish schedule or ask the GC."),
  ("Do countertops need to be sealed after cleaning?", "Some natural stone needs periodic sealing.")]),
"Quartz and solid surface countertop cleaning": T(
 "Quartz and solid surface countertop cleaning removes dust, adhesive, sealant and marks from engineered quartz and acrylic solid surface counters.",
 "Quartz and solid surface are durable but can be dulled or discolored by strong chemicals, solvents and abrasive pads.",
 "Crews use pH-neutral cleaners and soft cloths, remove adhesive with plastic blades and approved removers, and avoid high-pH and solvent cleaners.",
 ["Counter areas", "Adhesive and sealant residue", "Manufacturer guidance", "Seams"],
 ["High-pH cleaners and solvents can discolor quartz.", "Abrasive pads can dull solid surface."],
 [("What cleaner is safe for quartz?", "A pH-neutral cleaner and soft cloth."),
  ("Can solid surface counters be repaired if scratched?", "Often yes, by a fabricator."),
  ("How do you remove adhesive from quartz?", "With a plastic blade and approved remover."),
  ("Why avoid bleach on quartz?", "It can discolor the resin.")]),
"Natural stone countertop cleaning": T(
 "Natural stone countertop cleaning cleans granite, marble, quartzite, limestone and soapstone counters with stone-safe, pH-neutral products.",
 "Marble and limestone etch easily with acids, and porous stones absorb oils and stain. One wrong cleaner can leave permanent marks.",
 "Crews clean with stone-safe neutral cleaners, test residue removers first and report etching or stains to the GC rather than trying aggressive fixes.",
 ["Stone types", "Sealer status", "Residues", "Fabricator contact"],
 ["Vinegar and acidic cleaners etch marble and limestone.", "Unsealed stone stains easily."],
 [("Can granite be cleaned with any cleaner?", "Use a stone-safe, pH-neutral cleaner."),
  ("What is etching on marble?", "Dull marks caused by acids dissolving the surface."),
  ("Should stone counters be sealed?", "Many natural stones should be sealed periodically."),
  ("Who repairs stone counter damage?", "The fabricator or a stone restoration specialist.")]),
"Laminate countertop cleaning": T(
 "Laminate countertop cleaning removes dust, adhesive, labels and marks from plastic laminate counters, edges and backsplashes.",
 "Laminate is durable but can be scratched by abrasives and swollen at seams by excess water.",
 "Crews use mild cleaners and soft cloths, remove labels and adhesive carefully and keep water away from seams.",
 ["Counter areas", "Seams and edges", "Labels and adhesive", "Backsplashes"],
 ["Water at seams can swell the substrate.", "Abrasives scratch laminate."],
 [("How do you clean laminate countertops?", "With mild cleaners and soft cloths."),
  ("Can laminate seams be damaged by water?", "Yes, water can swell the particleboard underneath."),
  ("How is adhesive removed from laminate?", "With mild removers and plastic tools."),
  ("Are laminate counters common in commercial buildings?", "Yes, in offices, schools and break rooms.")]),
"Reception and service desk detailing": T(
 "Reception and service desk detailing cleans front desks, transaction counters and service stations, including surfaces, panels, glass, hardware and cable openings.",
 "The reception desk is the first thing visitors see. It often combines several materials and gets fingerprints and dust from installation of equipment.",
 "Crews detail each material with appropriate cleaners, vacuum cable grommets and drawers, and clean glass screens and signage.",
 ["Desk materials", "Glass or acrylic screens", "Cable openings and drawers", "Equipment installed"],
 ["Do not unplug equipment.", "Acrylic screens scratch easily."],
 [("Why is reception desk cleaning important?", "It is the first impression for visitors."),
  ("How are acrylic sneeze guards cleaned?", "With mild soap and soft cloths, not ammonia."),
  ("Do cable openings need cleaning?", "Yes, they collect dust."),
  ("Is the desk cleaned before equipment is installed?", "Ideally, with a touch-up after.")]),
"Shelving and adjustable shelf cleaning": T(
 "Shelving and adjustable shelf cleaning cleans shelves, standards, brackets and shelf pin holes in storage rooms, offices, libraries and retail.",
 "Shelves are often installed early and collect dust that will end up on stored items. Pin holes trap dust.",
 "Crews vacuum shelves and standards, wipe surfaces and remove labels, working top shelf down.",
 ["Shelving count and type", "Standards and brackets", "Labels", "Items stored"],
 ["Do not overload shelves while cleaning.", "Brackets can loosen if bumped."],
 [("How are shelves cleaned after construction?", "Vacuum, then wipe from the top shelf down."),
  ("Why clean shelf standards?", "Dust collects in slots and pin holes."),
  ("Are storage room shelves part of final clean?", "Yes."),
  ("Should shelves be cleaned before stocking?", "Yes.")]),
"Closet rod and shelf cleaning": T(
 "Closet rod and shelf cleaning cleans closet shelves, rods, brackets, walls and floors in offices, apartments, hotels and dormitories.",
 "Closets are opened by residents and guests and often skipped by crews. Dust and debris there are noticed.",
 "Crews vacuum shelves, wipe rods and brackets, clean walls and floors and check closet doors.",
 ["Number of closets", "Shelving type", "Doors and tracks", "Floor type"],
 ["Wire shelving can trap dust in every wire.", "Sliding door tracks collect debris."],
 [("Do closets need final cleaning?", "Yes, they are opened by residents and guests."),
  ("How are wire shelves cleaned?", "Vacuum and wipe each section."),
  ("Should closet door tracks be cleaned?", "Yes, debris affects operation."),
  ("Are closets part of a unit final clean?", "Yes.")]),
"Trim, casing and crown molding cleaning": T(
 "Trim, casing and crown molding cleaning removes dust, caulk smears, paint drips and fingerprints from door casings, window trim and crown molding.",
 "Trim has many small ledges and profiles that hold dust. Caulk and paint on trim are common punch items.",
 "Crews dust profiles with microfiber, remove caulk smears carefully and spot-clean painted trim gently.",
 ["Linear feet of trim and crown", "Paint and caulk residue", "Profiles", "Heights"],
 ["Scrubbing fresh paint damages it.", "Caulk smears may need touch-up rather than removal."],
 [("Why is crown molding dusty?", "Its top edge is a ledge that collects dust."),
  ("How are caulk smears on trim removed?", "Carefully, with plastic tools and mild removers."),
  ("Is trim cleaning part of final clean?", "Yes."),
  ("Should trim be dusted before floors?", "Yes, clean high before low.")]),
"Baseboard and wall base cleaning": T(
 "Baseboard and wall base cleaning removes dust, adhesive, paint and scuffs from wood baseboards, rubber cove base and tile base along every wall.",
 "Base is at the junction of floor and wall, where dust and debris collect. Adhesive squeeze-out on rubber base and paint on wood base are common punch items.",
 "Crews vacuum along the base, wipe with damp microfiber, and remove adhesive and paint with base-safe products.",
 ["Linear feet of base", "Base material", "Adhesive and paint residue", "Floor cleaning sequence"],
 ["Solvents can soften rubber base.", "Wet mops push dirt into base joints."],
 [("What is cove base?", "Rubber or vinyl wall base that curves out at the floor."),
  ("How is adhesive removed from rubber base?", "With mild removers safe for rubber."),
  ("Are baseboards cleaned before or after floors?", "Before final floor cleaning."),
  ("Why are baseboards a punch item?", "They collect dust, paint and scuffs.")]),
"Wood paneling and wainscot cleaning": T(
 "Wood paneling and wainscot cleaning removes dust and marks from wood panels, wainscoting and chair rails using wood-safe methods.",
 "Wood paneling shows dust in its grooves and marks on its face, and water can damage the finish.",
 "Crews dust grooves with soft brushes and wipe faces with barely damp microfiber and wood cleaners.",
 ["Panel area and finish", "Grooves and profiles", "Chair rails", "Marks"],
 ["Water can damage wood finishes.", "Silicone polishes can cause problems with future refinishing."],
 [("How is wood paneling cleaned?", "Dust grooves, then wipe with barely damp microfiber."),
  ("What is wainscoting?", "Paneling on the lower part of a wall."),
  ("Should polish be used on wood paneling?", "Usually not at turnover; follow the finish manufacturer."),
  ("Is wainscoting cleaned at final clean?", "Yes.")]),
"Handrail and guardrail cleaning": T(
 "Handrail and guardrail cleaning cleans stair and ramp handrails, guardrails, brackets and infill panels made of wood, metal, glass or cable.",
 "Handrails are touched by everyone and collect fingerprints, overspray and dust. Glass and cable infill are easy to miss.",
 "Crews wipe rails and brackets with appropriate cleaners and clean infill panels, checking both sides.",
 ["Linear feet of rail", "Materials", "Infill type", "Access on stairs"],
 ["Stair work needs stable footing.", "Wood rails may need wood-safe cleaners."],
 [("How often are handrails cleaned?", "At turnover, then frequently during operation."),
  ("Are guardrail infill panels cleaned?", "Yes, both sides."),
  ("How are stainless handrails cleaned?", "With neutral cleaner and wiping with the grain."),
  ("Why are handrails a focus?", "They are touched constantly.")]),
"Built-in bench and banquette cleaning": T(
 "Built-in bench and banquette cleaning cleans fixed seating in restaurants, lobbies and break areas, including upholstery, wood, metal and crevices.",
 "Banquettes trap crumbs, dust and construction debris in seams. They are seen by every guest.",
 "Crews vacuum crevices and upholstery and wipe hard surfaces with suitable cleaners.",
 ["Seating length", "Upholstery material", "Crevices", "Hard surfaces"],
 ["Water can stain some upholstery.", "Do not unscrew seat cushions unless designed to be removed."],
 [("What is a banquette?", "Built-in bench seating, common in restaurants."),
  ("How are banquette crevices cleaned?", "With crevice tools and vacuums."),
  ("Is upholstery cleaned at final clean?", "Vacuuming is standard; extraction is a separate item."),
  ("Why do banquettes collect debris?", "Their seams and crevices trap it.")]),
"Locker interior and exterior cleaning": T(
 "Locker interior and exterior cleaning cleans lockers in schools, gyms, workplaces and healthcare, including doors, shelves, hooks and number plates.",
 "Lockers often have film, labels and dust inside, and they are inspected by users on day one.",
 "Crews remove film and labels, vacuum and wipe interiors and clean exteriors with suitable cleaners.",
 ["Locker count", "Material", "Film and labels", "Benches"],
 ["Locks and mechanisms should not be forced.", "Painted metal can be scratched."],
 [("Do new lockers need cleaning?", "Yes, they have dust and film."),
  ("How are locker interiors cleaned?", "Vacuum and wipe."),
  ("Are locker room benches included?", "Usually yes."),
  ("Who removes locker labels?", "The cleaning crew at final clean.")]),
"Toilet partition and urinal screen cleaning": T(
 "Toilet partition and urinal screen cleaning removes film, labels, adhesive, fingerprints and dust from restroom stall partitions, doors, pilasters and urinal screens.",
 "Partitions often ship with protective film and labels. Their surfaces and hardware are inspected closely in restrooms.",
 "Crews remove film and labels, clean surfaces with material-appropriate cleaners and detail hardware and brackets.",
 ["Partition material", "Film and labels", "Hardware", "Pilaster shoes"],
 ["Solvents can damage plastic and powder-coat.", "Do not adjust door hardware."],
 [("How are toilet partitions cleaned?", "With cleaners matched to their material."),
  ("Do partitions come with film?", "Often, and it is removed at final clean."),
  ("What are pilaster shoes?", "Trim at the base of partition pilasters."),
  ("Are urinal screens cleaned the same way?", "Yes.")]),
"Window treatment and blind dusting": T(
 "Window treatment and blind dusting removes construction dust from blinds, shades, roller shades and their headrails and fascia.",
 "Blinds are installed late and catch dust from the final weeks of construction. They are hard to clean once dirty.",
 "Crews dust slats or shades with soft brush vacuums and microfiber and clean headrails without disturbing mechanisms.",
 ["Number and type of window treatments", "Fabric or slat", "Motorized systems", "Height"],
 ["Fabric shades can stain if wet.", "Do not operate motorized shades without permission."],
 [("How do you clean new blinds?", "Dust with soft brushes and microfiber."),
  ("Can roller shades be washed?", "Follow the manufacturer's instructions; many should only be dusted."),
  ("Are window treatments part of final clean?", "Yes."),
  ("Should blinds be installed before final clean?", "Ideally, so they are cleaned once.")]),
"Window sill and stool cleaning": T(
 "Window sill and stool cleaning details interior sills and stools, removing dust, debris, caulk, paint and labels at final clean.",
 "Sills are a horizontal surface at eye level that collect dust, debris and dead insects. They are inspected closely.",
 "Crews vacuum sills and corners and wipe with finish-safe cleaners, removing caulk and paint residue carefully.",
 ["Number of sills", "Material", "Caulk and paint residue", "Window frame cleaning sequence"],
 ["Solid surface and stone sills need appropriate cleaners.", "Do not damage caulk joints."],
 [("What is a window stool?", "The interior ledge at the bottom of a window."),
  ("Why are sills a focus at final clean?", "They are visible and collect dust and debris."),
  ("Are sills cleaned with windows?", "Usually as part of window and frame cleaning."),
  ("How is caulk removed from sills?", "Carefully, with plastic tools and mild removers.")]),
}
