def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Interior window cleaning": T(
 "Interior window cleaning at construction turnover cleans the inside face of every window, plus frames, sills and tracks, removing dust, labels, paint specks and fingerprints.",
 "Interior glass is seen every day by occupants, and construction residue on it shows in sunlight. It is one of the last finishing touches before an owner walk.",
 "Crews clean frames and sills first, scrape only where the glass type allows with fresh lubricated blades, then wash and squeegee the glass and detail edges.",
 ["Number and size of windows", "Glass types and coatings", "Labels and debris on glass", "Access and heights"],
 ["Scraping coated or tempered glass can cause scratches; check the glass type first.", "Cleaning before trades finish leads to re-cleaning."],
 [("When should interior windows be cleaned on a construction project?", "Near the end, after painting and caulking are complete and before the owner walk."),
  ("Is interior window cleaning included in final clean?", "Usually, but confirm it is in the scope."),
  ("Why do windows look streaky after cleaning?", "Residue from dirty water, too much soap or dust falling from frames."),
  ("Do window sills get cleaned with interior windows?", "Yes, frames and sills are cleaned first.")]),
"Exterior window cleaning": T(
 "Exterior window cleaning at construction turnover cleans the outside face of windows and frames, removing construction dust, stucco, paint, sealant and labels.",
 "Exterior glass collects the heaviest construction residue from stucco, painting, masonry and sealants. It determines how the building looks from the street.",
 "Crews choose access by height, clean frames first, remove debris with methods suited to the glass and finish with washing or pure-water rinsing.",
 ["Number of windows and floors", "Access: ground, ladder, lift or rope", "Residue types on glass", "Glass coatings"],
 ["Upper floors need fall protection and trained crews.", "Acidic masonry cleaners can etch glass and frames."],
 [("When are exterior windows cleaned?", "After exterior finishes are complete and scaffolding is removed."),
  ("How are exterior windows on upper floors cleaned?", "With lifts, swing stages or rope access, depending on the building."),
  ("Can stucco be removed from windows?", "Usually, with careful soaking and scraping where the glass allows."),
  ("Who cleans exterior windows at turnover?", "A construction window cleaning contractor.")]),
"Storefront glass cleaning": T(
 "Storefront glass cleaning cleans the large glass panels, doors and aluminum framing at a building's street level and entrances, inside and out.",
 "Storefronts are the most visible glass on most buildings. Labels, sealant and fingerprints on them are seen by everyone who walks in.",
 "Crews clean frames, remove labels and sealant smears, scrape where appropriate and wash glass inside and out, finishing door glass and hardware last.",
 ["Linear feet and height of storefront", "Doors and hardware", "Labels and sealant residue", "Frame finish"],
 ["Anodized aluminum frames can be stained by harsh cleaners.", "Storefront glass may be tempered and sensitive to scraping."],
 [("What is storefront glass?", "Aluminum-framed glass systems at ground level and entrances."),
  ("How often should storefront glass be cleaned?", "At turnover, then regularly during operation."),
  ("Can storefront frames be cleaned with glass cleaner?", "Mild cleaners are fine; avoid harsh chemicals on anodized finishes."),
  ("Why is storefront cleaning a priority?", "It is the first impression of the building.")]),
"Window label and sticker removal": T(
 "Window label and sticker removal takes off manufacturer labels, energy rating stickers and handling labels from new glass without scratching it or leaving adhesive.",
 "Every new window arrives with labels, and they are a standard final clean and punch item. Removing them badly leaves adhesive or scratches.",
 "Crews confirm whether inspectors need labels in place, peel labels slowly, and remove adhesive with glass-safe removers and lubricated blades where allowed.",
 ["Number of windows with labels", "Code inspection requirements for labels", "Glass coatings", "Adhesive removers"],
 ["Energy labels may need to stay until inspection.", "Dry scraping can scratch glass."],
 [("Should window stickers be removed before inspection?", "Ask the GC; energy labels sometimes must stay until the inspector sees them."),
  ("How do you remove adhesive from window labels?", "With glass-safe removers and careful, lubricated scraping."),
  ("Can heat help remove window stickers?", "Gentle warming can soften adhesive."),
  ("Who removes window labels?", "The cleaning crew at final clean.")]),
"Construction debris removal from glass": T(
 "Construction debris removal from glass takes off paint, stucco, plaster, tape, sealant and other construction residue from new glass using methods that protect the surface.",
 "Debris on glass is common on every project. Improper removal is a leading cause of scratched glass and disputes between GCs, glaziers and cleaners.",
 "Crews inspect the glass type, soak debris, use fresh, lubricated blades only where appropriate and document existing damage before starting.",
 ["Glass types and coatings", "Residues present", "Existing damage documentation", "Scratch waiver terms"],
 ["Dragging debris under a blade causes scratches.", "Some coated glass must never be scraped."],
 [("What causes scratches during window cleaning?", "Debris dragged under blades, dull blades, or scraping coated glass."),
  ("What is a glass scratch waiver?", "A contract clause addressing scratch liability during construction debris removal."),
  ("Should existing glass damage be documented?", "Yes, before cleaning begins."),
  ("Is debris removal from glass a specialty?", "It requires training and care, so experienced crews are best.")]),
"Concrete and mortar splatter removal from glass": T(
 "Concrete and mortar splatter removal from glass takes hardened cementitious splatter off windows and storefronts without etching the glass or damaging frames.",
 "Cement splatter bonds tightly to glass. Acidic removers can etch glass and stain aluminum, and dry scraping can scratch.",
 "Crews soften splatter by soaking, remove it mechanically with lubricated blades, and use cement removers only after testing and with frames protected.",
 ["Amount and location of splatter", "Glass and frame types", "Remover testing", "Frame protection"],
 ["Acidic removers can etch glass and frames.", "Rinse thoroughly so remover does not dry on surfaces."],
 [("How do you get concrete off windows?", "Soak it, remove it mechanically and use cement removers only after testing."),
  ("Can concrete permanently damage glass?", "Fresh splatter left for a long time and harsh removal methods can cause damage."),
  ("Do concrete removers damage window frames?", "Some can. Protect frames and rinse thoroughly."),
  ("Who removes concrete from new windows?", "Construction window cleaning specialists.")]),
"Window track and frame cleaning": T(
 "Window track and frame cleaning removes debris, dust, sealant and paint from window tracks, frames, weep holes and operable window hardware.",
 "Debris in tracks makes windows hard to operate and blocks drainage. Frames are visible and collect residue.",
 "Crews vacuum tracks and weep holes, wipe frames and hardware and check that operable windows open and close freely.",
 ["Window types and count", "Operable windows", "Weep holes", "Frame finishes"],
 ["Blocked weep holes cause leaks.", "Do not adjust window hardware."],
 [("Why clean window tracks?", "Debris affects operation and drainage."),
  ("What are weep holes?", "Openings that drain water from window frames."),
  ("How are window tracks cleaned?", "Vacuum, then wipe."),
  ("Are frames cleaned with glass?", "Yes, frames are cleaned first.")]),
"Window screen cleaning and installation": T(
 "Window screen cleaning and installation cleans insect screens and reinstalls them after window cleaning, checking that they fit properly.",
 "Screens collect dust and are often removed for construction and window cleaning. Missing or damaged screens are a punch item.",
 "Crews label screens by window, clean them with mild solution and soft brushes, let them dry and reinstall them.",
 ["Number of screens", "Labeling and storage", "Damage check", "Reinstallation"],
 ["Screens bend easily.", "Mixed-up screens may not fit."],
 [("How are window screens cleaned?", "With mild soap, soft brushes and gentle rinsing."),
  ("Why label screens?", "So each one goes back to its window."),
  ("Are damaged screens replaced by cleaners?", "Usually by the window contractor."),
  ("Is screen installation part of final clean?", "Often, when screens were removed.")]),
"Glass partition and interior glazing cleaning": T(
 "Glass partition and interior glazing cleaning cleans interior glass walls, office fronts, glass doors and back-painted glass, including frames and film graphics.",
 "Glass partitions show every fingerprint and streak, and many have film graphics or manifestations that are easily damaged.",
 "Crews clean frames, wash glass with glass cleaners safe for film graphics and avoid scraping across graphics or back-painted surfaces.",
 ["Partition areas", "Film graphics and manifestations", "Frame types", "Back-painted glass"],
 ["Blades can cut or lift film graphics.", "Back-painted glass coatings can be damaged from the back."],
 [("How are glass office walls cleaned?", "With glass cleaner and squeegees, avoiding graphics."),
  ("What are glass manifestations?", "Markings on glass that make it visible for safety."),
  ("Can you scrape near glass graphics?", "No, it can damage them."),
  ("What is back-painted glass?", "Glass with paint on the back face, often used as wall finish.")]),
"Glass railing and balustrade cleaning": T(
 "Glass railing and balustrade cleaning cleans both faces of glass guardrail panels, their clamps, shoe channels and top rails.",
 "Glass railings are in highly visible places like atriums, stairs and balconies. Fingerprints and debris in shoe channels are noticed.",
 "Crews clean from safe positions, both sides of each panel, and vacuum shoe channels.",
 ["Panel count and heights", "Access on both sides", "Shoe channel debris", "Fall protection"],
 ["Working near open edges requires fall protection.", "Do not loosen clamps."],
 [("How are glass railings cleaned?", "Both sides of each panel, with care at open edges."),
  ("What is a shoe channel?", "The base channel that holds glass panels."),
  ("Do glass railings need fall protection to clean?", "Sometimes, depending on the location."),
  ("Are glass railings part of final clean?", "Yes.")]),
"Shower glass and enclosure cleaning": T(
 "Shower glass and enclosure cleaning removes labels, silicone haze, dust and water spots from new shower doors, panels and their hardware.",
 "Shower glass is installed late, often with silicone haze and labels. Water spots and hard water appear quickly after first use.",
 "Crews remove labels and silicone residue carefully, clean glass and hardware with non-acidic cleaners and dry with squeegees.",
 ["Number of enclosures", "Glass coatings", "Silicone residue", "Hardware finishes"],
 ["Some shower glass has protective coatings that harsh cleaners damage.", "Do not disturb fresh silicone joints."],
 [("How is silicone haze removed from shower glass?", "With careful scraping and silicone removers safe for glass."),
  ("Can shower glass coatings be damaged?", "Yes, by abrasive or harsh cleaners."),
  ("Are shower doors cleaned at final clean?", "Yes."),
  ("How do you prevent water spots?", "Dry the glass after cleaning.")]),
"Mirror cleaning and edge detailing": T(
 "Mirror cleaning and edge detailing cleans mirrors and their edges, frames and clips, without letting liquid get behind the mirror where it damages the silvering.",
 "Mirrors are installed late, have labels and smudges, and show every streak. Liquid behind the edges causes black edges over time.",
 "Crews spray cleaner onto cloths rather than mirrors, wipe edges carefully and remove labels with mirror-safe methods.",
 ["Number and size of mirrors", "Frames and clips", "Labels", "Restroom mirrors"],
 ["Liquid behind mirror edges damages silvering.", "Ammonia cleaners can damage some mirror edges."],
 [("Why do mirror edges turn black?", "Moisture and cleaners attack the silver backing at the edge."),
  ("How should mirrors be cleaned?", "Spray cleaner onto the cloth, not the mirror."),
  ("Are mirror labels removed at final clean?", "Yes."),
  ("Can mirrors be scraped?", "Carefully, only for small debris.")]),
"Display case and showcase glass cleaning": T(
 "Display case and showcase glass cleaning cleans retail, museum and food display cases, including glass, shelves, frames and interiors.",
 "Display cases hold merchandise and food; dust and fingerprints inside them are visible and affect sales and inspection.",
 "Crews clean interiors before stocking, wipe glass shelves and frames, and clean exterior glass last.",
 ["Number of cases", "Lighting inside", "Food or merchandise", "Glass and frame types"],
 ["Lighting in cases may be hot.", "Food cases need food-safe cleaners."],
 [("When should display cases be cleaned?", "Before stocking, then touched up."),
  ("Are refrigerated food cases cleaned the same way?", "With food-safe cleaners and care for refrigeration."),
  ("Do display case interiors get cleaned?", "Yes."),
  ("Who cleans showcases in a new store?", "The cleaning crew during store opening.")]),
"Skylight cleaning": T(
 "Skylight cleaning cleans the interior and exterior faces of skylights and their frames, removing construction dust, debris and roofing residue.",
 "Skylights bring light into a space, and dirt on them is magnified. Roofing work leaves debris and residue on exterior skylight glass.",
 "Crews clean exteriors from the roof with fall protection and interiors from lifts, using methods suited to glass or plastic glazing.",
 ["Number and size of skylights", "Glass or polycarbonate", "Roof access and fall protection", "Interior heights"],
 ["Skylights are fall hazards on roofs; use protection.", "Polycarbonate scratches easily."],
 [("How are skylights cleaned?", "Exteriors from the roof with fall protection, interiors from lifts."),
  ("Can polycarbonate skylights be cleaned like glass?", "No, they need gentle cleaners and soft cloths."),
  ("Why are skylights dirty after construction?", "Roofing work and dust leave residue."),
  ("Are skylights a fall hazard?", "Yes, they must be protected during roof work.")]),
"Curtain wall cleaning": T(
 "Curtain wall cleaning at turnover cleans large exterior glass and metal wall systems on mid- and high-rise buildings, using qualified access methods.",
 "Curtain walls define the building's appearance. Cleaning them requires specialized access, fall protection and knowledge of coated glass and metal finishes.",
 "Qualified crews use building maintenance units, swing stages, rope access or lifts, cleaning glass and metal with approved products and documenting existing damage.",
 ["Building height and facade area", "Access method and anchorage", "Glass coatings and metal finishes", "Fall protection and permits"],
 ["Only trained, insured crews should perform high access work.", "Coated glass and metal finishes need approved cleaners."],
 [("What is a curtain wall?", "A non-structural exterior glass and metal wall system."),
  ("How is a curtain wall cleaned?", "With swing stages, building maintenance units, rope access or lifts."),
  ("Why is curtain wall cleaning conditional?", "It requires specialized access, training and insurance."),
  ("Can curtain wall metal be damaged by cleaners?", "Yes, use approved cleaners.")]),
"High-rise exterior glass cleaning": T(
 "High-rise exterior glass cleaning cleans windows on tall buildings using rope access, swing stages or building maintenance units, by certified crews with fall-protection plans.",
 "High-rise window work is one of the most hazardous cleaning tasks. It requires engineered anchors, trained crews and specific insurance.",
 "Only qualified specialists are introduced, with verified training, insurance and a written plan that matches the building's anchorage.",
 ["Building height", "Anchorage and access systems", "Crew certifications", "Insurance and permits"],
 ["Never use uncertified anchors.", "Weather limits work."],
 [("Who cleans high-rise windows?", "Specialized contractors trained in rope access or suspended platforms."),
  ("What is rope access window cleaning?", "Cleaning from ropes anchored to the roof, by trained technicians."),
  ("Are roof anchors required for window cleaning?", "Yes, rated anchors or equipment are required."),
  ("How does weather affect high-rise window cleaning?", "Wind and storms stop work for safety.")]),
"Hard water stain removal from glass": T(
 "Hard water stain removal from glass removes mineral deposits left on windows by sprinklers, rain runoff, concrete or masonry wash water.",
 "Mineral deposits etch glass over time. Fresh deposits come off much more easily than old ones.",
 "Crews test mineral removers on a small area, use non-scratching pads where suitable and rinse thoroughly, documenting any etching that cannot be removed.",
 ["Extent and age of deposits", "Glass type and coatings", "Source of water", "Remover testing"],
 ["Old deposits may have etched the glass permanently.", "Some removers are acidic and need careful handling."],
 [("What causes hard water stains on windows?", "Minerals left behind when water evaporates."),
  ("Can hard water stains be removed?", "Fresh ones usually can; old ones may have etched the glass."),
  ("How can hard water stains be prevented?", "Redirect sprinklers and clean glass regularly."),
  ("Is hard water stain removal a specialty?", "It needs experience and careful product use.")]),
"Glass scratch assessment and documentation": T(
 "Glass scratch assessment and documentation inspects new glass for scratches, chips and defects before or after cleaning and records them with photos and locations.",
 "Scratch disputes are common between glaziers, GCs and cleaners. Documentation before cleaning shows what was already there.",
 "Crews inspect glass in proper light, mark locations on drawings and photograph defects, sharing the report with the GC.",
 ["Glass areas to inspect", "Lighting conditions", "Documentation format", "Reporting to GC and glazier"],
 ["Inspection angle and light affect what is visible.", "Not all defects are scratches; some are manufacturing defects."],
 [("Why document glass before cleaning?", "To show what defects existed before cleaning."),
  ("How are glass scratches documented?", "With photos and locations on drawings."),
  ("Who pays for scratched glass?", "It depends on the cause and contract."),
  ("What is the standard for viewing glass defects?", "Industry standards specify viewing distance and lighting.")]),
"Glass protective film removal": T(
 "Glass protective film removal takes off temporary protective films applied to glass during construction, and removes any adhesive residue left behind.",
 "Films protect glass during construction, but left too long in sun and heat they bake on and leave residue.",
 "Crews peel film at the right angle and speed, remove residue with glass-safe products and dispose of film properly.",
 ["Glass with film", "Film age and sun exposure", "Residue removal", "Timing"],
 ["Baked-on film is hard to remove.", "Blades can scratch while removing residue."],
 [("When should glass protective film be removed?", "Near the end of construction, before it bakes on."),
  ("Why does film leave residue?", "Heat and UV make the adhesive bond harder."),
  ("How is film residue removed?", "With glass-safe adhesive removers."),
  ("Who removes window film?", "The glazier or cleaning crew, depending on the contract.")]),
"Pure-water fed-pole window cleaning": T(
 "Pure-water fed-pole window cleaning uses deionized or reverse-osmosis water delivered through a brush on an extension pole to clean windows up to several stories without ladders or detergents.",
 "Pure water dries spot-free, so little or no chemical is needed, and pole work reduces ladder risk for low- and mid-rise windows.",
 "Crews scrub and rinse glass and frames with pure water from the ground or a roof, using pole systems instead of ladders where possible.",
 ["Window heights", "Water source and purification", "Residue on glass", "Access from ground"],
 ["Pure water does not remove paint, labels or stucco; detail work is needed first.", "Water runoff should be controlled."],
 [("What is pure-water window cleaning?", "Cleaning with purified water that dries without spots."),
  ("Does pure-water cleaning use soap?", "Usually not."),
  ("How high can water-fed poles reach?", "Several stories, depending on the system."),
  ("Can pure water remove construction debris?", "No, debris must be removed first.")]),
}
