def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Concrete floor auto-scrubbing": T(
 "Concrete floor auto-scrubbing cleans large concrete slabs with walk-behind or ride-on scrubbers that apply solution, scrub and vacuum up the dirty water in one pass.",
 "Mop-and-bucket cleaning on a large slab just spreads dirty water around. Auto-scrubbers clean faster and recover the water, leaving the floor cleaner and dry.",
 "Crews choose pads and a neutral or mild alkaline cleaner suited to the slab finish, overlap passes, and edge by hand where the machine cannot reach.",
 ["Square footage and slab finish", "Water source and disposal", "Machine size versus aisle widths", "Edges and corners"],
 ["Aggressive pads can scratch sealed or polished concrete.", "Dirty recovery water must not go into storm drains."],
 [("What is an auto-scrubber?", "A floor machine that scrubs and vacuums up solution in one pass."),
  ("Is auto-scrubbing better than mopping?", "Yes, on large floors it cleans better and recovers the dirty water."),
  ("What pad should be used on concrete?", "It depends on the finish; softer pads for sealed or polished floors."),
  ("Where does scrubber wastewater go?", "To a sanitary drain where permitted, not storm drains.")]),
"Warehouse floor scrubbing": T(
 "Warehouse floor scrubbing cleans distribution center and warehouse slabs with ride-on scrubbers, removing construction dust, tire marks, debris and residue before racking and operations.",
 "Warehouse slabs are huge and need to be clean for safe forklift traffic, product storage and customer audits.",
 "Crews sweep first, then scrub with ride-on machines in planned lanes, treating marks and stains separately.",
 ["Slab area and finish", "Racking status", "Marks and stains", "Water access and disposal"],
 ["Wet floors are slippery for forklifts; control traffic.", "Racking reduces machine access."],
 [("How are warehouse floors cleaned after construction?", "Swept, then scrubbed with ride-on machines."),
  ("Should warehouse floors be cleaned before racking?", "Yes, it is much easier."),
  ("How often are warehouse floors scrubbed?", "At turnover, then on a schedule during operations."),
  ("Do tire marks come off warehouse floors?", "Usually, with the right pads and cleaners.")]),
"Sealed concrete floor cleaning": T(
 "Sealed concrete floor cleaning cleans concrete that has a sealer or coating, using neutral cleaners and soft pads that do not damage the sealer.",
 "Sealers protect concrete and give it a finish. Harsh cleaners and aggressive pads can dull or strip them.",
 "Crews use neutral cleaners and soft pads, scrubbing and recovering water, and test any spot treatment first.",
 ["Sealer type", "Area", "Stains and marks", "Manufacturer guidance"],
 ["Solvents can soften some sealers.", "Aggressive pads dull sealer finish."],
 [("How is sealed concrete cleaned?", "With neutral cleaners and soft pads."),
  ("Can cleaning remove concrete sealer?", "Harsh chemicals and aggressive pads can."),
  ("How do you know if concrete is sealed?", "Water beads on many sealed surfaces; check with the GC."),
  ("Does sealed concrete need resealing?", "Periodically, depending on traffic.")]),
"Polished concrete maintenance clean": T(
 "A polished concrete maintenance clean cleans polished and densified concrete floors with neutral cleaners and polishing pads that keep the shine.",
 "Polished concrete is a finish; the wrong cleaner or pad dulls it, and grit scratches it.",
 "Crews dust mop or vacuum grit first, then auto-scrub with neutral cleaner and diamond-impregnated maintenance pads where recommended.",
 ["Polished area", "Polishing level", "Grit control", "Manufacturer pads and cleaners"],
 ["Acidic cleaners etch polished concrete.", "Grit acts like sandpaper on polished floors."],
 [("How do you clean polished concrete?", "Remove grit, then scrub with neutral cleaner and recommended pads."),
  ("Why is polished concrete dull after cleaning?", "Residue, wrong cleaners or wrong pads."),
  ("Can polished concrete be waxed?", "Typically it is not waxed; it is maintained with pads and cleaners."),
  ("Do acids hurt polished concrete?", "Yes, they etch it.")]),
"Concrete polishing": T(
 "Concrete polishing grinds and polishes a concrete slab with progressively finer diamond tooling and densifier to create a durable, glossy finish. It is a flooring specialty, not routine cleaning.",
 "Polished concrete is a finish system with heavy equipment and silica dust control requirements. It must be done by qualified contractors.",
 "Concrete polishing specialists are routed only after review, with dust control equipment and silica compliance in place.",
 ["Slab condition and area", "Desired finish level", "Dust control and silica compliance", "Schedule before other trades"],
 ["Grinding creates silica dust; controls are required.", "Slab defects affect the result."],
 [("Is concrete polishing a cleaning service?", "No, it is a flooring specialty."),
  ("What is densifier?", "A chemical that hardens concrete surfaces."),
  ("Does concrete polishing create dust?", "Yes, it requires silica dust controls."),
  ("When is concrete polished in construction?", "Usually before walls and finishes, or late with protection.")]),
"Concrete grinding preparation": T(
 "Concrete grinding preparation grinds slabs to remove coatings, adhesives or high spots and to prepare surfaces for coatings or overlays. It is specialty work with silica controls.",
 "Coatings and overlays fail if the slab is not properly prepared. Grinding creates silica dust that must be controlled.",
 "Specialists use grinders with dust collection and HEPA vacuums, routed only after review.",
 ["Slab area and condition", "Coating or adhesive removal", "Dust control", "Surface profile required"],
 ["Silica dust controls are required.", "Grinding can damage embedded items."],
 [("Why grind concrete before coating?", "To create a surface the coating can bond to."),
  ("Does grinding create silica dust?", "Yes, controls are required."),
  ("Who grinds concrete?", "Flooring and concrete specialists."),
  ("Is grinding a cleaning task?", "No, it is surface preparation.")]),
"Curing compound residue removal": T(
 "Curing compound residue removal takes off the film left by curing compounds or cure-and-seal products on new concrete, so floors look uniform and coatings or flooring can bond.",
 "Curing compound residue can block adhesives and coatings and look patchy on exposed concrete.",
 "Crews identify the compound type and remove it with appropriate strippers and scrubbing, or refer heavy removal to grinding specialists.",
 ["Compound type", "Floor finish planned", "Area", "Stripper compatibility"],
 ["Some compounds need grinding to remove.", "Strippers must be rinsed thoroughly."],
 [("What is curing compound?", "A coating applied to fresh concrete to slow water loss."),
  ("Why remove curing compound?", "It can block flooring adhesives and coatings."),
  ("How is curing compound removed?", "With strippers and scrubbing or grinding."),
  ("Does all curing compound need removal?", "Only when it affects finishes.")]),
"Tire mark and forklift mark removal": T(
 "Tire mark and forklift mark removal cleans black marks left by lifts, forklifts and vehicles on concrete and resilient floors.",
 "Tire marks are common after lifts work on a floor, and they show clearly on light floors.",
 "Crews use cleaners and pads suited to the floor, testing first, and scrub marks before the general floor clean.",
 ["Floor type and finish", "Mark severity", "Areas affected", "Lift tire type in future"],
 ["Aggressive pads can damage floor finishes.", "Some marks are permanent on porous surfaces."],
 [("How are forklift marks removed from concrete?", "With degreasers and scrubbing pads suited to the floor."),
  ("Do non-marking tires prevent marks?", "They reduce them."),
  ("Can tire marks be removed from polished concrete?", "Usually, with gentle methods."),
  ("Who removes tire marks?", "The cleaning crew during floor cleaning.")]),
"Concrete stain and oil spot treatment": T(
 "Concrete stain and oil spot treatment removes oil, grease, hydraulic fluid and other stains from concrete floors.",
 "Oil stains on concrete look neglected and can be slippery. Concrete absorbs oil, so stains get harder to remove over time.",
 "Crews absorb fresh spills, then treat stains with degreasers or poultices and scrub, testing on sealed floors.",
 ["Stain types and age", "Floor finish", "Area", "Disposal of absorbents"],
 ["Some stains are permanent.", "Degreasers must not go into storm drains."],
 [("How are oil stains removed from concrete?", "With absorbents, degreasers and poultices."),
  ("Can old oil stains be removed?", "Often partly; some may be permanent."),
  ("What is a poultice?", "A paste that draws stains out of porous surfaces."),
  ("Do oil stains affect safety?", "They can be slippery.")]),
"Concrete efflorescence removal": T(
 "Concrete efflorescence removal cleans white, powdery salt deposits from concrete slabs, walls and foundations using cleaners suited to the surface.",
 "Efflorescence looks unfinished and comes back if the moisture source is not addressed.",
 "Crews dry-brush and vacuum loose salts, then use efflorescence cleaners tested on the surface and rinse thoroughly.",
 ["Area and surface type", "Moisture source", "Cleaner testing", "Rinse and disposal"],
 ["Acidic cleaners can etch or discolor concrete.", "Efflorescence may return if moisture continues."],
 [("What causes efflorescence on concrete?", "Water carrying salts to the surface and evaporating."),
  ("Will efflorescence come back?", "It can, if moisture continues."),
  ("How is efflorescence removed?", "Dry brushing, then appropriate cleaners."),
  ("Is efflorescence harmful?", "It is mostly cosmetic but signals moisture.")]),
"Rust stain removal from concrete": T(
 "Rust stain removal from concrete removes orange stains from rebar, metal objects, fertilizer or irrigation water on concrete floors and flatwork.",
 "Rust stains are common on new concrete where steel sat on it. They are noticeable and can be stubborn.",
 "Crews use rust removers formulated for concrete, test first and rinse thoroughly, protecting nearby surfaces.",
 ["Stain size and source", "Concrete finish", "Remover testing", "Nearby surfaces"],
 ["Strong acids etch concrete.", "Some deep stains will not fully come out."],
 [("What causes rust stains on concrete?", "Steel, fertilizer or iron-rich water."),
  ("Can rust stains be removed from concrete?", "Usually, with the right remover."),
  ("Do rust removers damage concrete?", "Strong acids can etch it; test first."),
  ("How can rust stains be prevented?", "Keep steel off finished concrete.")]),
"Paint and coating drip removal from concrete": T(
 "Paint and coating drip removal from concrete removes dried paint, primer, epoxy and coating drips from concrete floors at final clean.",
 "Drips on exposed concrete look unfinished, and on polished concrete they are especially visible.",
 "Crews scrape carefully and use removers suited to the coating and floor finish, testing first.",
 ["Coating types", "Floor finish", "Drip extent", "Remover testing"],
 ["Solvents can stain or soften sealers.", "Scraping can mark polished floors."],
 [("How do you remove paint from a concrete floor?", "Scrape and use removers suited to the paint."),
  ("Can epoxy drips be removed?", "Often, but cured epoxy is tough."),
  ("Who is responsible for paint drips?", "Often the painter, depending on the contract."),
  ("Do drips matter on concrete that will be covered?", "Yes, they cause bumps under flooring.")]),
"Joint and crack debris vacuuming": T(
 "Joint and crack debris vacuuming removes dust and debris from control joints, saw cuts and cracks in concrete floors before sealing or final cleaning.",
 "Debris in joints prevents joint fillers from bonding and keeps coming out as dust.",
 "Crews vacuum joints with crevice tools and HEPA vacuums, removing debris before joint filling or sealing.",
 ["Linear feet of joints", "Joint filling plans", "Debris", "Timing"],
 ["Debris in joints affects filler adhesion.", "Do not damage joint edges."],
 [("Why clean concrete control joints?", "Debris affects joint fillers and keeps releasing dust."),
  ("What is a control joint?", "A cut in concrete that controls where cracks form."),
  ("How are joints cleaned?", "With crevice tools and HEPA vacuums."),
  ("When is joint cleaning done?", "Before joint filling and final cleaning.")]),
"Densifier and guard application support": T(
 "Densifier and guard application support prepares and cleans concrete before densifiers or protective guards are applied, and cleans residue afterward.",
 "Densifiers and guards need a clean surface to work, and residue left after application looks blotchy.",
 "Crews clean and dry the floor before application and remove excess product per the manufacturer.",
 ["Product type", "Floor condition", "Application schedule", "Manufacturer instructions"],
 ["Residue left on the surface can look blotchy.", "Some products need precise application."],
 [("What is a concrete guard?", "A protective topical treatment on polished concrete."),
  ("Why clean before densifier application?", "Dirt affects absorption and appearance."),
  ("Who applies densifier?", "Usually the flooring or polishing contractor."),
  ("Can densifier residue be removed?", "Usually, if addressed promptly.")]),
"Epoxy floor preparation cleaning": T(
 "Epoxy floor preparation cleaning removes dust, oil and contaminants from slabs before epoxy or resinous coatings are applied.",
 "Coatings fail when applied over dust or oil. Preparation is the most important step for coating adhesion.",
 "Crews vacuum and degrease, then coordinate with the coating contractor's surface preparation requirements.",
 ["Coating type", "Slab condition", "Contaminants", "Coating contractor requirements"],
 ["Oil contamination causes coating failure.", "Surfaces must be dry before coating."],
 [("Why is surface prep important for epoxy?", "Epoxy needs a clean, sound surface to bond."),
  ("What contaminants affect epoxy?", "Dust, oil, curing compounds and moisture."),
  ("Who prepares floors for epoxy?", "The coating contractor, often with cleaning support."),
  ("Can epoxy be applied over sealed concrete?", "Usually only after the sealer is removed.")]),
"Epoxy and resinous floor cleaning": T(
 "Epoxy and resinous floor cleaning cleans epoxy, urethane and resinous floor coatings in garages, kitchens, labs, healthcare and industrial areas.",
 "Resinous floors are durable but can be dulled or damaged by harsh chemicals and aggressive pads.",
 "Crews use neutral or manufacturer-approved cleaners and soft pads, recovering water.",
 ["Coating type", "Texture or anti-slip finish", "Area", "Manufacturer guidance"],
 ["Aggressive pads can wear anti-slip textures.", "Some solvents soften coatings."],
 [("How are epoxy floors cleaned?", "With neutral cleaners and soft pads."),
  ("Can epoxy floors be scratched?", "Yes, by grit and aggressive pads."),
  ("Do epoxy floors need wax?", "Usually not."),
  ("Where are resinous floors used?", "Garages, kitchens, labs and industrial spaces.")]),
"Parking garage floor scrubbing": T(
 "Parking garage floor scrubbing cleans garage decks of construction dust, oil, tire marks and debris using ride-on scrubbers or pressure washing with water recovery.",
 "Garages collect construction dust and oil. Runoff from washing can carry pollutants into storm drains.",
 "Crews sweep, then scrub or wash with water recovery, blocking or protecting drains as required.",
 ["Garage size and levels", "Drain systems", "Water recovery", "Traffic control"],
 ["Wash water must not enter storm drains.", "Traffic coatings can be damaged by harsh methods."],
 [("How are parking garages cleaned after construction?", "Sweeping, then scrubbing or washing with recovery."),
  ("Can garage wash water go to storm drains?", "Generally no."),
  ("Do garage coatings need special care?", "Yes, avoid harsh methods."),
  ("How often are garages cleaned?", "At turnover and periodically.")]),
"VCT initial floor finish": T(
 "VCT initial floor finish prepares newly installed vinyl composition tile by removing the factory coating and adhesive residue, then applying multiple coats of floor finish.",
 "New VCT has a factory coating that floor finish does not bond to well. Skipping preparation leads to peeling finish and a floor that never looks right.",
 "Crews clean or strip the new tile per the manufacturer, rinse, apply sealer if required, and lay down several thin coats of finish with proper drying time.",
 ["Area of VCT", "Manufacturer initial maintenance instructions", "Number of finish coats", "Cure time before traffic"],
 ["Too-thick coats cause poor drying and soft finish.", "Traffic before cure damages the finish."],
 [("Why does new VCT need initial finish?", "Its factory coating must be prepared for floor finish to bond."),
  ("How many coats of finish go on new VCT?", "Often several thin coats; follow the specification."),
  ("When can traffic go on new floor finish?", "After it cures per the product instructions."),
  ("Is VCT finish the same as wax?", "Floor finish is commonly called wax.")]),
"VCT strip and refinish": T(
 "VCT strip and refinish removes old floor finish with a chemical stripper and applies new coats of finish, restoring worn or damaged VCT floors.",
 "Floor finish wears and yellows over time, and renovation work scuffs it. Stripping resets the floor.",
 "Crews apply stripper, scrub and recover it, rinse thoroughly, then apply new coats of finish.",
 ["Area", "Number of existing coats", "Stripper and finish products", "Downtime"],
 ["Strippers are strong chemicals; ventilate and use PPE.", "Residual stripper causes finish failure."],
 [("What does stripping a floor mean?", "Removing old floor finish with chemical stripper."),
  ("How often do VCT floors need stripping?", "Depending on traffic and maintenance, often once a year or less."),
  ("Can stripping damage VCT?", "Overly aggressive stripping can."),
  ("How long does a strip and refinish take?", "Often overnight or a day, depending on area.")]),
"VCT scrub and recoat": T(
 "VCT scrub and recoat deep-scrubs the top layers of floor finish and applies fresh coats without a full strip.",
 "Scrub and recoat restores appearance at lower cost and less downtime than stripping.",
 "Crews scrub with appropriate pads and cleaner, rinse, dry and apply new finish coats.",
 ["Area", "Finish condition", "Products", "Downtime"],
 ["Too many recoats build up and yellow.", "Edges need attention."],
 [("What is scrub and recoat?", "Scrubbing top coats of finish and applying new ones."),
  ("Is scrub and recoat cheaper than stripping?", "Usually yes."),
  ("When is a full strip needed?", "When finish is heavily worn or built up."),
  ("How often is scrub and recoat done?", "Often a few times a year in busy areas.")]),
"LVT and LVP manufacturer-approved cleaning": T(
 "LVT and LVP manufacturer-approved cleaning cleans luxury vinyl tile and plank using the products and methods the flooring manufacturer specifies, protecting the floor warranty.",
 "Many luxury vinyl floors should not be waxed or stripped, and some cleaners can damage the wear layer or void the warranty.",
 "Crews follow the manufacturer's maintenance guide: dust mop, neutral cleaner, approved pads.",
 ["Product and manufacturer", "Maintenance guide", "Area", "Adhesive residue"],
 ["Wax and strippers can void warranties.", "Excess water at seams can affect some products."],
 [("Can LVT be waxed?", "Most should not be; follow the manufacturer."),
  ("What cleaner is safe for LVT?", "A neutral cleaner approved by the manufacturer."),
  ("Can LVT warranties be voided by cleaning?", "Yes, by unapproved products or methods."),
  ("Is LVP the same as LVT?", "LVP is the plank format of luxury vinyl.")]),
"Sheet vinyl initial clean": T(
 "Sheet vinyl initial clean cleans newly installed sheet vinyl flooring, removing adhesive, seam sealer residue and construction dust.",
 "Sheet vinyl is common in healthcare and food areas. Adhesive and seam residue look bad and attract dirt.",
 "Crews remove adhesive with approved removers, scrub with neutral cleaner and follow the manufacturer's initial maintenance.",
 ["Area", "Manufacturer guidance", "Adhesive and seam residue", "Finish requirements"],
 ["Solvents can damage seams.", "Some sheet vinyls require no finish."],
 [("How is new sheet vinyl cleaned?", "Remove adhesive, then scrub with neutral cleaner."),
  ("Does sheet vinyl need floor finish?", "It depends on the product."),
  ("Where is sheet vinyl used?", "Healthcare, food areas and schools."),
  ("Can seams be damaged by cleaning?", "Yes, by solvents and harsh scrubbing.")]),
"Rubber floor initial cleaning": T(
 "Rubber floor initial cleaning prepares new rubber tile or sheet flooring by removing installation residue and the mold release film that rubber flooring often has from manufacturing.",
 "Rubber flooring can look blotchy until the initial cleaning removes factory residues. Solvents can damage rubber.",
 "Crews follow the manufacturer's initial cleaning procedure, typically with neutral cleaners and specific pads.",
 ["Area", "Manufacturer guidance", "Residues", "Pads and cleaners"],
 ["Solvents damage rubber.", "Some rubber floors should not be finished."],
 [("Why does new rubber flooring look blotchy?", "Factory residues need initial cleaning."),
  ("Can rubber floors be waxed?", "Follow the manufacturer; many should not be."),
  ("What cleaner is safe for rubber floors?", "Neutral cleaners."),
  ("Where are rubber floors used?", "Healthcare, schools, gyms and stairs.")]),
"Sports and gym floor rubber cleaning": T(
 "Sports and gym floor rubber cleaning cleans rubber athletic flooring in fitness centers and weight rooms, removing dust, adhesive and residue.",
 "Rubber athletic floors are textured and trap dust. The wrong cleaners can make them slippery or damage them.",
 "Crews vacuum and scrub with approved neutral cleaners, avoiding oily products.",
 ["Floor type and area", "Equipment placement", "Manufacturer guidance", "Adhesive residue"],
 ["Oily cleaners can make rubber slippery.", "Equipment may need to be moved."],
 [("How are rubber gym floors cleaned?", "Vacuum, then scrub with neutral cleaners."),
  ("Can rubber gym floors get slippery?", "Yes, from improper cleaners."),
  ("Are gym floors cleaned before equipment installation?", "Ideally yes."),
  ("Do rubber gym floors need finish?", "Usually not.")]),
"Linoleum and marmoleum initial care": T(
 "Linoleum and marmoleum initial care cleans new linoleum flooring with neutral cleaners, following the manufacturer's procedures for this natural material.",
 "Linoleum is made from natural materials and is sensitive to high-pH cleaners, which can damage it.",
 "Crews use neutral cleaners and follow the manufacturer's initial maintenance, which may include specific finishes.",
 ["Area", "Manufacturer guidance", "Factory finish", "Residues"],
 ["High-pH cleaners damage linoleum.", "Excess water can affect seams."],
 [("Is linoleum the same as vinyl?", "No, linoleum is made from natural materials."),
  ("What cleaner is safe for linoleum?", "A neutral cleaner."),
  ("Why avoid strong alkaline cleaners on linoleum?", "They can damage it."),
  ("Does linoleum need finish?", "Follow the manufacturer.")]),
"Static-dissipative floor cleaning": T(
 "Static-dissipative floor cleaning cleans ESD and static-control floors with cleaners that do not leave insulating residue, preserving the floor's electrical performance.",
 "Static-control floors protect sensitive electronics. Wax and residue-forming cleaners can stop them from working.",
 "Crews use manufacturer-approved cleaners only, avoid finishes unless specified and may coordinate testing.",
 ["Floor type and area", "Manufacturer cleaners", "Testing requirements", "Equipment in the space"],
 ["Wax and residue can block static dissipation.", "Use only approved products."],
 [("What is a static-dissipative floor?", "A floor that safely drains static electricity."),
  ("Can ESD floors be waxed?", "Usually not, unless a special finish is specified."),
  ("Where are ESD floors used?", "Electronics, labs and data areas."),
  ("How is ESD floor performance checked?", "With electrical resistance testing.")]),
"Adhesive residue removal from resilient floors": T(
 "Adhesive residue removal from resilient floors takes flooring adhesive off the face of new vinyl, LVT, rubber and linoleum floors after installation.",
 "Adhesive on the surface attracts dirt and leaves dark spots. The wrong remover can damage the floor.",
 "Crews use the adhesive manufacturer's recommended remover or mild options, testing first.",
 ["Adhesive type", "Floor type", "Extent", "Remover testing"],
 ["Solvents can damage resilient floors.", "Remove adhesive before it fully cures if possible."],
 [("How do you remove flooring adhesive from vinyl?", "With the recommended remover, tested first."),
  ("Why does adhesive turn black on floors?", "It traps dirt."),
  ("Who removes adhesive from new floors?", "The installer should, but cleaning crews often finish."),
  ("Can adhesive be removed after it cures?", "It is harder but often possible.")]),
"Scuff and heel mark removal": T(
 "Scuff and heel mark removal takes black marks and scuffs off resilient and hard floors without damaging the floor finish.",
 "Scuffs appear quickly during final construction activity and are noticed during walks.",
 "Crews use soft pads, tennis-ball tools or appropriate cleaners and buff lightly.",
 ["Floor type", "Mark extent", "Finish condition", "Timing"],
 ["Aggressive pads damage finish.", "Some marks need finish repair."],
 [("How are scuff marks removed?", "With soft pads or appropriate cleaners."),
  ("Do scuffs damage floor finish?", "They mark it; heavy scuffs may need recoating."),
  ("Why are floors scuffed after construction?", "Equipment, carts and shoes."),
  ("Is scuff removal part of final clean?", "Yes.")]),
"Burnishing": T(
 "Burnishing polishes finished resilient floors with a high-speed machine to restore shine between deeper maintenance cycles.",
 "Burnishing keeps finished floors glossy in high-traffic areas and makes them look new for openings and walks.",
 "Crews dust mop, then burnish with appropriate pads, using dust-control burnishers where possible.",
 ["Floor type and finish", "Area", "Equipment", "Dust control"],
 ["Burnishing without dust control creates fine dust.", "Not all floors should be burnished."],
 [("What is burnishing?", "High-speed polishing of floor finish."),
  ("How often should floors be burnished?", "It varies by traffic, from daily to monthly."),
  ("Can LVT be burnished?", "Follow the manufacturer's guidance."),
  ("Does burnishing create dust?", "It can; dust-control equipment helps.")]),
"Ceramic and porcelain tile initial clean": T(
 "Ceramic and porcelain tile initial clean removes grout residue, thinset, dust and haze from newly installed ceramic and porcelain tile floors and walls.",
 "Tile looks dull and cloudy until haze and residue are removed, and textured tiles hold residue.",
 "Crews use cleaners suited to tile and grout type, scrub with soft pads and rinse thoroughly.",
 ["Tile area and texture", "Grout type", "Haze or residue", "Sealer plans"],
 ["Some grouts are sensitive to acids.", "Textured tile needs brush scrubbing."],
 [("How are new tile floors cleaned?", "Remove haze and residue, then clean with neutral cleaner."),
  ("Is porcelain tile easy to clean?", "Yes, but textured tile holds residue."),
  ("Can acids be used on new tile?", "Only if the grout and tile allow it."),
  ("When can new tile be cleaned?", "After the grout has cured enough.")]),
"Grout haze removal": T(
 "Grout haze removal takes the cloudy film of cementitious grout off newly installed tile, using haze removers matched to the tile, grout and stone type.",
 "Haze makes new tile look dull and dirty. Once fully cured, it is much harder to remove, and the wrong remover can etch stone or damage grout.",
 "Crews identify tile and grout type, choose a compatible haze remover, apply with soft pads and rinse thoroughly. Non-acidic removers are used on calcareous stone.",
 ["Tile, stone and grout types", "Age of haze", "Remover compatibility", "Rinse water disposal"],
 ["Acidic removers etch marble, limestone and travertine.", "Epoxy grout haze needs different removers."],
 [("What is grout haze?", "A thin film of grout left on the tile surface."),
  ("How do you remove grout haze?", "With a haze remover suited to the tile and grout."),
  ("Can vinegar remove grout haze?", "It is acidic and can damage stone and some grouts."),
  ("When should grout haze be removed?", "After the grout cures enough, before it hardens completely.")]),
"Grout line deep cleaning": T(
 "Grout line deep cleaning scrubs grout joints to remove embedded soil and residue, restoring their original color.",
 "Grout is porous and absorbs dirt, and dirty grout makes the whole floor look dirty.",
 "Crews scrub with grout brushes or machines with suitable cleaners, then extract or rinse.",
 ["Area", "Grout type and color", "Sealer", "Cleaning method"],
 ["Harsh acids can damage grout.", "Unsealed grout re-soils quickly."],
 [("How is dirty grout cleaned?", "With grout brushes or machines and suitable cleaners."),
  ("Can grout color be restored?", "Cleaning often restores it; colorant is another option."),
  ("Why does grout get dirty?", "It is porous."),
  ("Should grout be sealed after cleaning?", "Often, to slow re-soiling.")]),
"Grout sealing": T(
 "Grout sealing applies a penetrating sealer to cementitious grout joints to reduce staining and make future cleaning easier.",
 "Unsealed grout absorbs spills and dirt. Sealing protects it, especially in kitchens and restrooms.",
 "Crews apply sealer after grout cures and is clean and dry, wiping excess from tile surfaces.",
 ["Grout type and cure time", "Area", "Sealer type", "Tile compatibility"],
 ["Excess sealer on tile can leave haze.", "Epoxy grout usually does not need sealing."],
 [("Should grout be sealed?", "Cementitious grout usually benefits from sealing."),
  ("When can grout be sealed?", "After it cures, per the product."),
  ("How long does grout sealer last?", "It varies; reapplication is periodic."),
  ("Does epoxy grout need sealing?", "Usually not.")]),
"Quarry tile cleaning": T(
 "Quarry tile cleaning cleans and degreases unglazed quarry tile floors in commercial kitchens and food areas.",
 "Quarry tile is porous and absorbs grease, and kitchens need clean, slip-resistant floors for health inspection.",
 "Crews scrub with degreasers and deck brushes or machines, then rinse and squeegee to drains.",
 ["Kitchen area", "Grease level", "Drains", "Sealer"],
 ["Grease makes floors slippery.", "Some degreasers damage grout."],
 [("What is quarry tile?", "An unglazed, durable tile common in commercial kitchens."),
  ("How are quarry tile floors degreased?", "With degreasers, deck brushes and rinsing."),
  ("Should quarry tile be sealed?", "Often, to resist grease."),
  ("Why is quarry tile used in kitchens?", "It is durable and slip resistant.")]),
"Natural stone floor initial clean": T(
 "Natural stone floor initial clean cleans newly installed marble, limestone, travertine, granite and slate floors with stone-safe products.",
 "Natural stone is sensitive to acids and absorbs stains. The first cleaning sets the tone for the floor's life.",
 "Crews use pH-neutral stone cleaners, soft pads and careful residue removal, and coordinate with sealing.",
 ["Stone types and finishes", "Sealer status", "Residues", "Manufacturer or fabricator guidance"],
 ["Acids etch calcareous stone.", "Unsealed stone stains easily."],
 [("How are new marble floors cleaned?", "With pH-neutral stone cleaners and soft pads."),
  ("Can grout haze be removed from marble?", "Only with non-acidic removers."),
  ("Should stone floors be sealed?", "Many should."),
  ("Who repairs etched stone?", "Stone restoration specialists.")]),
"Stone polishing and honing": T(
 "Stone polishing and honing uses abrasives and compounds to restore or change the finish of marble, terrazzo and other stone floors. It is restoration specialty work.",
 "Etched or scratched stone can only be fixed by honing and polishing, which requires skill and specialized equipment.",
 "Stone restoration specialists are routed only after review.",
 ["Stone type and condition", "Desired finish", "Area", "Downtime"],
 ["Improper honing can damage stone.", "Slurry must be managed."],
 [("What is stone honing?", "Grinding stone to a smooth, matte finish."),
  ("Can etched marble be repaired?", "Yes, by honing and polishing."),
  ("Is stone polishing a cleaning service?", "No, it is restoration."),
  ("Who polishes stone floors?", "Stone restoration specialists.")]),
"Terrazzo initial clean": T(
 "Terrazzo initial clean cleans newly installed terrazzo floors, removing residue and dust and preparing for sealing per the terrazzo contractor's guidance.",
 "Terrazzo is a premium floor, and wrong cleaners can damage its surface and sealer.",
 "Crews use neutral cleaners recommended for terrazzo and coordinate sealing with the installer.",
 ["Terrazzo type: cement or epoxy", "Sealer plans", "Residues", "Installer guidance"],
 ["Acids and high-alkaline cleaners damage cement terrazzo.", "Sealer timing matters."],
 [("What is terrazzo?", "A floor made of chips of marble or glass in cement or epoxy."),
  ("How is terrazzo cleaned?", "With neutral cleaners."),
  ("Does terrazzo need sealing?", "Usually yes."),
  ("Can terrazzo be damaged by cleaners?", "Yes, by acids and strong alkalis.")]),
"Terrazzo polishing": T(
 "Terrazzo polishing grinds and polishes terrazzo to restore its finish. It is restoration specialty work.",
 "Worn or damaged terrazzo can be restored by specialists, but improper polishing damages it.",
 "Terrazzo restoration specialists are routed only after review.",
 ["Terrazzo type", "Condition", "Area", "Downtime"],
 ["Improper grinding damages terrazzo.", "Slurry control is required."],
 [("Can old terrazzo be restored?", "Often, by grinding and polishing."),
  ("Is terrazzo polishing done by cleaners?", "No, by restoration specialists."),
  ("How long does terrazzo polishing take?", "It depends on area and condition."),
  ("Does terrazzo need to be sealed after polishing?", "Often.")]),
"Mosaic and specialty tile detailing": T(
 "Mosaic and specialty tile detailing cleans small-format mosaic, glass tile and decorative tile, removing grout haze and residue from many joints.",
 "Mosaics have many joints and small tiles that trap haze and residue. Glass tile scratches easily.",
 "Crews clean with soft pads and brushes, using haze removers compatible with glass and specialty tiles.",
 ["Tile type", "Grout type", "Haze extent", "Area"],
 ["Glass tile scratches easily.", "Some decorative tiles are sensitive to acids."],
 [("How are mosaic tiles cleaned?", "With soft brushes and compatible haze removers."),
  ("Can glass tile scratch?", "Yes, with abrasive pads."),
  ("Why is mosaic haze hard to remove?", "Many joints trap residue."),
  ("Is mosaic detailing part of final clean?", "Yes.")]),
"Thinset and mortar splatter removal": T(
 "Thinset and mortar splatter removal takes hardened setting material and mortar off tile and stone faces after installation.",
 "Thinset bonds firmly and dulls tile. Left until final clean, it is harder to remove.",
 "Crews soften and scrape carefully, then use compatible cleaners, testing first on stone.",
 ["Tile and stone types", "Extent", "Remover compatibility", "Rinse"],
 ["Scraping can scratch glazed tile.", "Acids can etch stone."],
 [("What is thinset?", "The cement-based adhesive used to set tile."),
  ("How is thinset removed from tile?", "Soften, scrape and clean with compatible products."),
  ("Who should remove thinset?", "The installer, or the cleaning crew at final clean."),
  ("Can thinset damage stone?", "Removal methods can, if acids are used.")]),
"Hardwood floor initial clean": T(
 "Hardwood floor initial clean cleans newly installed and finished solid hardwood floors, removing dust and residue with wood-safe, low-moisture methods.",
 "New wood finish is sensitive to water and chemicals and needs time to cure.",
 "Crews dust mop and vacuum, then clean with wood floor cleaners and barely damp microfiber.",
 ["Area", "Finish type and cure time", "Manufacturer guidance", "Protection removal"],
 ["Water damages wood.", "Cleaning before cure can damage finish."],
 [("How are new hardwood floors cleaned?", "Dust mop, vacuum, then damp microfiber with wood cleaner."),
  ("When can new hardwood finish be cleaned?", "After it cures, per the product."),
  ("Can hardwood floors be mopped?", "Only with barely damp mops."),
  ("Should rugs go on new wood floors right away?", "Wait for cure per the finish.")]),
"Engineered wood floor cleaning": T(
 "Engineered wood floor cleaning cleans engineered wood floors with methods that protect their factory finish and thin wear layer.",
 "Engineered wood has a thin wear layer and factory finish. Wrong cleaners can dull or damage it.",
 "Crews follow manufacturer guidance, using dry methods and wood cleaners.",
 ["Area", "Manufacturer", "Finish type", "Seams"],
 ["Water at seams can cause swelling.", "Some cleaners leave residue."],
 [("What is engineered wood?", "Wood flooring with a real wood top layer on plywood or HDF."),
  ("How is engineered wood cleaned?", "With dry methods and approved wood cleaners."),
  ("Can engineered wood be refinished?", "Sometimes, depending on wear layer thickness."),
  ("Is engineered wood sensitive to water?", "Yes, at seams.")]),
"Gym and athletic hardwood floor cleaning": T(
 "Gym and athletic hardwood floor cleaning cleans maple sport floors with methods approved by the floor manufacturer and sport flooring associations.",
 "Gym floors have specialized finishes and game lines. Wrong cleaners make them slippery or damage finish.",
 "Crews use approved gym floor cleaners and microfiber, keeping moisture minimal.",
 ["Floor area", "Finish system", "Game lines", "Approved products"],
 ["Wrong cleaners make floors slippery.", "Water damages maple."],
 [("How are gym floors cleaned?", "With approved cleaners and microfiber."),
  ("Can gym floors be mopped?", "Only with minimal moisture."),
  ("Why do gym floors get slippery?", "Residue from improper cleaners."),
  ("Who recoats gym floors?", "Floor finishing contractors.")]),
"Bamboo and cork floor cleaning": T(
 "Bamboo and cork floor cleaning cleans these natural flooring materials with low-moisture, pH-neutral methods recommended by the manufacturer.",
 "Bamboo and cork are sensitive to moisture and harsh cleaners.",
 "Crews dust mop and clean with barely damp microfiber and approved cleaners.",
 ["Area", "Manufacturer guidance", "Finish", "Moisture limits"],
 ["Excess water damages cork and bamboo.", "Harsh cleaners damage finishes."],
 [("How is cork flooring cleaned?", "Dust mop and barely damp microfiber."),
  ("Is bamboo flooring like hardwood?", "It is cleaned similarly."),
  ("Can cork floors get wet?", "Limit moisture."),
  ("Do cork floors need sealing?", "Many are sealed; follow the manufacturer.")]),
"Raised access floor cleaning": T(
 "Raised access floor cleaning cleans removable floor panels and the plenum below in data centers and offices, using HEPA vacuums and antistatic methods.",
 "Dust under raised floors is distributed through cooling air into equipment.",
 "Trained crews clean panels and the plenum with HEPA vacuums, lifting panels with proper tools.",
 ["Area", "Plenum depth", "Panel lifting", "Cable management"],
 ["Do not remove too many panels at once.", "Do not disturb cables."],
 [("What is a raised access floor?", "Removable panels over a plenum for cables and air."),
  ("Why clean under raised floors?", "Dust is distributed through cooling air."),
  ("Who cleans raised floors?", "Trained crews."),
  ("How are raised floor panels lifted?", "With suction lifters.")]),
"Entrance mat and grate cleaning": T(
 "Entrance mat and grate cleaning cleans recessed walk-off mats, grates and their pits, removing construction dirt and debris.",
 "Entrance systems trap dirt before it enters. Construction fills them with debris.",
 "Crews lift grates where possible, vacuum pits and clean mats.",
 ["Mat systems", "Pits", "Grate lifting", "Debris"],
 ["Grates are heavy.", "Pits can hold water."],
 [("What is a walk-off mat?", "Entrance matting that captures soil."),
  ("Why clean entrance mats after construction?", "They fill with debris."),
  ("Can grates be lifted?", "Many can, with care."),
  ("Do entrance mats need regular cleaning?", "Yes.")]),
"Stair tread and nosing cleaning": T(
 "Stair tread and nosing cleaning cleans stair treads, risers and nosings, including rubber, stone and metal nosings, removing dirt and adhesive.",
 "Stairs collect dirt and adhesive from construction, and nosings are safety features that must be visible.",
 "Crews clean top down, removing adhesive and scrubbing treads.",
 ["Number of stairs", "Tread material", "Nosing type", "Adhesive"],
 ["Wet stairs are slippery.", "Nosing color contrast must remain visible."],
 [("How are stairs cleaned?", "Top down, tread by tread."),
  ("What is a stair nosing?", "The front edge of a stair tread."),
  ("Why are nosings important?", "They help people see the step edge."),
  ("Are stairs part of final clean?", "Yes.")]),
}
