def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Construction carpet vacuuming": T(
 "Construction carpet vacuuming removes drywall dust, grit, threads and debris from newly installed carpet with commercial HEPA vacuums before turnover.",
 "New carpet traps fine construction dust deep in the pile. Ordinary vacuums blow it back into the air and leave the carpet looking gray and feeling gritty.",
 "Crews vacuum in slow overlapping passes with HEPA uprights or backpacks, edge along walls with crevice tools and empty or change bags often, because drywall dust fills them fast.",
 ["Carpet area and type: broadloom or tile", "Dust load from late trades", "Edges, stairs and corners", "Number of passes expected"],
 ["Drywall dust clogs vacuum filters quickly and reduces suction.", "Debris like screws can damage vacuum brush rolls; pick it up first."],
 [("Why does new carpet look dusty after vacuuming?", "Fine drywall dust needs slow, repeated passes with a HEPA vacuum. A single fast pass leaves much of it in the pile."),
  ("What kind of vacuum is best for construction dust in carpet?", "A commercial upright or backpack with sealed HEPA filtration, so fine dust is captured instead of exhausted."),
  ("Is vacuuming enough or does new carpet need extraction?", "Vacuuming is the minimum. Extraction is needed when there are stains, mud or heavy residue."),
  ("When should new carpet be vacuumed?", "After the last dusty trade finishes and after furniture installation, close to turnover.")]),
"Carpet extraction": T(
 "Carpet extraction cleans carpet by injecting a cleaning solution and immediately vacuuming it back out, removing embedded soil, mud and residue that vacuuming cannot reach.",
 "Construction leaves mud, drywall residue and spills in carpet. Extraction resets it before move-in, but over-wetting can cause odors, shrinkage and stains that come back.",
 "Crews pre-vacuum, pre-treat spots, extract with low-moisture settings and neutral-pH rinse agents, and use air movers to speed drying.",
 ["Carpet area and fiber type", "Manufacturer cleaning requirements", "Drying time before occupancy", "Water source and disposal"],
 ["Over-wetting can delaminate carpet backing or cause wicking.", "Residue left in carpet attracts new soil quickly."],
 [("What is carpet extraction?", "Cleaning that injects solution into carpet and vacuums it back out, often called hot water extraction."),
  ("How long does carpet take to dry after extraction?", "Usually a few hours with low-moisture methods and air movement."),
  ("Can extraction damage new carpet?", "Over-wetting or harsh chemicals can. Follow the carpet manufacturer's guidance."),
  ("Why do stains reappear after extraction?", "Residue or soil in the backing wicks back up as the carpet dries.")]),
"Carpet tile cleaning": T(
 "Carpet tile cleaning vacuums, spot-treats and, where needed, extracts modular carpet tiles, and identifies damaged tiles that should be swapped from attic stock.",
 "Carpet tile can be replaced one tile at a time, so badly stained tiles are often replaced rather than cleaned. Cleaning must not loosen tile adhesive.",
 "Crews vacuum thoroughly, spot-clean with low moisture and flag tiles for replacement instead of soaking them.",
 ["Carpet tile area", "Attic stock tiles available", "Stained or damaged tiles", "Adhesive system"],
 ["Excess moisture can release tile adhesive.", "Replacement tiles from a different dye lot may look different."],
 [("Is carpet tile cleaned differently from broadloom?", "The methods are similar, but damaged tiles can be replaced individually instead of cleaned."),
  ("Can carpet tiles be lifted to clean underneath?", "They can be lifted for replacement, but routine cleaning does not require it."),
  ("Why keep extra carpet tiles?", "Attic stock from the same dye lot allows invisible replacements."),
  ("Does moisture affect carpet tiles?", "Excess water can affect adhesive and backing.")]),
"Carpet spot and stain treatment": T(
 "Carpet spot and stain treatment removes individual spots such as paint, adhesive, coffee, mud and oil from carpet using spotters matched to the stain and fiber.",
 "Spots are the first thing noticed on new carpet. The wrong spotter can spread the stain, bleach the dye or leave a sticky residue that attracts dirt.",
 "Crews identify the stain, test spotters on hidden areas, blot instead of rubbing and rinse residue out.",
 ["Number and type of spots", "Carpet fiber", "Spotting kit", "Testing area"],
 ["Rubbing spreads stains and frays fibers.", "Some spotters cause color loss."],
 [("How do you remove paint from new carpet?", "Treat it promptly with a spotter suited to the paint type, blotting rather than rubbing."),
  ("Why shouldn't you rub carpet stains?", "Rubbing spreads the stain and damages fibers."),
  ("Can all carpet stains be removed?", "Many can, but some, like bleach spots, are permanent."),
  ("Should spotters be tested first?", "Yes, on a hidden area to check for color loss.")]),
"Drywall mud and paint removal from carpet": T(
 "Drywall mud and paint removal from carpet takes dried joint compound and paint drips out of new carpet without spreading them or damaging the fibers.",
 "Mud and paint land on carpet when it is installed before the last touch-ups. Wiping wet mud spreads it; dried mud can be crumbled out.",
 "Crews let mud dry, break it up and vacuum it, then treat residue with water and neutral spotters. Paint is treated with spotters suited to latex or oil paint.",
 ["Spots and drips locations", "Paint type", "Carpet fiber", "Touch-up schedule"],
 ["Wiping wet mud spreads it deeper.", "Solvents can damage carpet backing."],
 [("Should wet drywall mud on carpet be wiped up?", "No. Let it dry, then break it up and vacuum."),
  ("Can latex paint be removed from carpet?", "Usually, if treated before it fully cures."),
  ("Why does mud end up on carpet?", "Carpet is often installed before final drywall touch-ups."),
  ("How do you prevent paint on new carpet?", "Protect carpet until painting is finished.")]),
"Carpet seam and edge detailing": T(
 "Carpet seam and edge detailing vacuums and cleans along walls, base, transitions and seams where general vacuuming misses dust and debris.",
 "Dust collects along carpet edges and transitions, forming visible lines. Loose threads at seams look unfinished.",
 "Crews use crevice tools along edges, clean transition strips and trim loose fibers rather than pulling them.",
 ["Linear feet of edges", "Transitions", "Seams", "Loose fibers"],
 ["Pulling loose fibers can unravel carpet.", "Edge dust shows against base."],
 [("Why are carpet edges dirty after vacuuming?", "Most vacuums do not reach right to the wall."),
  ("Should loose carpet threads be pulled?", "No. Trim them to avoid unraveling."),
  ("What is a carpet transition?", "The strip where carpet meets another floor type."),
  ("Is edge detailing part of final clean?", "Yes.")]),
"Upholstery and furniture vacuuming": T(
 "Upholstery and furniture vacuuming removes construction dust from chairs, sofas, cushions and fabric furniture after installation.",
 "Furniture is often installed while dust is still settling, and dust on upholstery transfers to clothes.",
 "Crews vacuum fabric with upholstery tools, crevices with crevice tools and wipe hard furniture parts.",
 ["Furniture count and types", "Fabric types", "Hard surfaces", "Delivery packaging"],
 ["Some fabrics are delicate; use gentle tools.", "Do not remove manufacturer tags required by law."],
 [("Does new furniture need cleaning?", "Yes, it collects construction dust after delivery."),
  ("How is upholstery vacuumed?", "With upholstery tools and gentle passes."),
  ("Is furniture cleaning part of final clean?", "Usually after furniture installation."),
  ("Can furniture tags be removed?", "Required law tags should stay.")]),
"Upholstery extraction": T(
 "Upholstery extraction deep-cleans fabric furniture by injecting and extracting cleaning solution, removing stains and embedded soil.",
 "Stains on new furniture from construction or delivery need cleaning before occupancy.",
 "Crews check fabric cleaning codes, test and use low-moisture extraction with fast drying.",
 ["Fabric cleaning codes", "Furniture count", "Drying time", "Stains"],
 ["Some fabrics cannot be wet-cleaned.", "Over-wetting can cause water rings."],
 [("What are fabric cleaning codes?", "Codes like W, S, WS and X that tell which cleaning methods are safe."),
  ("Can all upholstery be extracted?", "No. Some fabrics require solvent or dry cleaning."),
  ("How long does upholstery take to dry?", "Usually a few hours."),
  ("Who cleans furniture stains?", "Upholstery cleaning specialists or trained crews.")]),
"Fabric panel and cubicle cleaning": T(
 "Fabric panel and cubicle cleaning vacuums and spot-cleans office workstation panels, removing dust, labels and marks.",
 "Cubicle panels are installed near the end and catch dust. Fabric panels absorb dust that falls into workspaces.",
 "Crews vacuum panels with soft brushes, spot-clean with low moisture and wipe hard parts.",
 ["Number of workstations", "Panel fabric", "Hard surfaces", "Labels"],
 ["Wet-cleaning panels can leave rings.", "Do not disconnect power or data."],
 [("How are cubicle panels cleaned?", "Vacuum, then spot-clean with low moisture."),
  ("Do workstations need cleaning after installation?", "Yes."),
  ("Can fabric panels be shampooed?", "Usually only spot cleaning is recommended."),
  ("Who cleans workstations?", "The cleaning crew after furniture installation.")]),
"Auditorium and theater seating cleaning": T(
 "Auditorium and theater seating cleaning cleans fixed seats, armrests, cup holders and the floor beneath every row in auditoriums, theaters and lecture halls.",
 "Hundreds of seats in rows trap dust and debris, and the floor under seats is hard to reach.",
 "Crews vacuum seats and under rows systematically and wipe hard parts.",
 ["Seat count", "Upholstery type", "Floor under seats", "Tablet arms and cup holders"],
 ["Folding mechanisms can pinch.", "Floor under seats is easy to miss."],
 [("How are theater seats cleaned?", "Row by row, vacuuming seats and floors."),
  ("Do theater seats need extraction?", "If stained, yes."),
  ("How long does auditorium cleaning take?", "It depends on seat count."),
  ("Why clean under seats?", "Debris collects there.")]),
}
