def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Toilet and urinal detailing": T(
 "Toilet and urinal detailing cleans new water closets and urinals inside and out, including bases, bolts caps, flush valves, seats and the floor and wall around them.",
 "Restrooms are inspected more closely than any other room, and new fixtures usually carry labels, dust, grout and caulk residue.",
 "Crews remove labels, clean with non-acidic products safe for vitreous china and chrome, and detail behind and under each fixture where inspectors look.",
 ["Fixture count", "Labels and residue", "Flush valves and chrome", "Floor and wall around fixtures"],
 ["Acid bowl cleaners can damage chrome and grout.", "Do not adjust flush valves."],
 [("How are new toilets cleaned?", "With non-acidic cleaners, removing labels and residue inside and out."),
  ("Why avoid acid cleaners on new restrooms?", "They can damage chrome, grout and some stone."),
  ("Do inspectors check behind toilets?", "Many do, so it should be detailed."),
  ("Who cleans new restroom fixtures?", "The cleaning crew at final clean.")]),
"Sink and faucet detailing": T(
 "Sink and faucet detailing cleans lavatories, faucets, drains, countertops around sinks and the underside of sinks, removing labels, film and residue.",
 "Sinks and faucets are touched first. Chrome shows water spots and fingerprints, and drains can hold construction debris.",
 "Crews remove labels and film, clean chrome with non-abrasive cleaners, check drains and dry surfaces.",
 ["Sink count and materials", "Faucet finishes", "Drains and aerators", "Under-sink areas"],
 ["Abrasives scratch chrome and specialty finishes.", "Do not disassemble faucets."],
 [("How do you clean new faucets?", "With non-abrasive cleaners and soft cloths, then dry."),
  ("Why are new faucets spotty?", "Water spots from testing and cleaning."),
  ("Are under-sink areas cleaned?", "Yes, they collect debris."),
  ("Are specialty faucet finishes cleaned differently?", "Yes, follow the manufacturer.")]),
"Restroom fixture sticker and label removal": T(
 "Restroom fixture sticker and label removal takes manufacturer labels and adhesive off toilets, sinks, urinals, accessories and partitions without scratching finishes.",
 "Labels on fixtures are almost always on the punch list. Scraping vitreous china or chrome with blades can scratch.",
 "Crews peel labels and use adhesive removers safe for china, chrome and powder coat.",
 ["Fixture labels", "Adhesive types", "Fixture finishes", "Removers"],
 ["Blades can scratch glazes and chrome.", "Solvents can damage plastics."],
 [("How are labels removed from toilets?", "Peel and use china-safe adhesive remover."),
  ("Can razor blades be used on fixtures?", "They can scratch; use carefully or avoid."),
  ("Why are fixture labels a punch item?", "They are visible and look unfinished."),
  ("Should fixture warranty labels be kept?", "Ask the GC; some info may be needed.")]),
"Caulk smear and silicone haze removal": T(
 "Caulk smear and silicone haze removal takes thin films and smears of sealant off surfaces around joints at sinks, tubs, counters, windows and fixtures.",
 "Silicone haze attracts dirt and looks smeary. It is hard to remove once cured, and the wrong method damages surfaces.",
 "Crews use plastic blades and silicone removers suited to the surface, without cutting into the caulk joint.",
 ["Locations of smears", "Surface types", "Caulk type", "Joint condition"],
 ["Cutting the joint can cause leaks.", "Solvents can damage some surfaces."],
 [("What is silicone haze?", "A thin film of silicone left around a caulk joint."),
  ("How is silicone haze removed?", "With silicone removers and plastic tools."),
  ("Can caulk be removed without damaging the joint?", "Yes, with care."),
  ("Who removes caulk smears?", "The installer or cleaning crew.")]),
"Shower and tub detailing": T(
 "Shower and tub detailing cleans new showers, tubs, valves, drains, tile walls and glass, removing grout haze, caulk smears, labels and debris.",
 "Showers combine many finishes in a small space and are checked closely in hotels, apartments and healthcare.",
 "Crews remove haze and residue with compatible products, detail fixtures and drains and dry surfaces.",
 ["Shower count", "Tile and stone types", "Glass and fixtures", "Drains"],
 ["Acrylic tubs scratch easily.", "Acid cleaners damage stone and grout."],
 [("How are new showers cleaned?", "Remove haze and residue, detail fixtures and drains."),
  ("Can acrylic tubs be scratched?", "Yes, avoid abrasives."),
  ("Why do shower drains need cleaning?", "Grout and debris collect there."),
  ("Are showers part of hotel PIP cleaning?", "Yes.")]),
"Restroom accessory cleaning": T(
 "Restroom accessory cleaning cleans soap dispensers, towel dispensers, toilet paper holders, grab bars, sanitary bins and baby changing stations.",
 "Accessories are installed late, often with film and labels, and are touched constantly.",
 "Crews remove film, clean stainless and plastic with suitable cleaners and check that dispensers are empty of packaging.",
 ["Accessory types and count", "Film and labels", "Finishes", "Packaging inside dispensers"],
 ["Stainless shows streaks if not wiped with the grain.", "Do not force dispenser locks."],
 [("What are restroom accessories?", "Dispensers, grab bars, holders and similar items."),
  ("Do dispensers come with packaging inside?", "Often, which should be removed."),
  ("How is stainless accessory cleaned?", "Neutral cleaner, wipe with the grain."),
  ("Are grab bars cleaned?", "Yes.")]),
"Hand dryer cleaning": T(
 "Hand dryer cleaning cleans the exterior, intake and outlet of electric hand dryers, removing film, dust and labels.",
 "Dust in dryer intakes is blown at users. Film and labels are common at turnover.",
 "Crews clean exteriors with suitable cleaners and vacuum intakes, never spraying into units.",
 ["Number of dryers", "Finishes", "Intakes and filters", "Labels"],
 ["Never spray liquid into dryers.", "Do not open units."],
 [("Do hand dryers need cleaning after construction?", "Yes, dust collects in intakes."),
  ("How are hand dryers cleaned?", "Wipe exteriors and vacuum intakes."),
  ("Can hand dryer filters be changed?", "By facility staff per the manufacturer."),
  ("Should liquid be sprayed on hand dryers?", "No.")]),
"Floor drain and trap primer area cleaning": T(
 "Floor drain and trap primer area cleaning removes grout, mortar, debris and dust from floor drains and their strainers in restrooms, kitchens and mechanical rooms.",
 "Floor drains collect construction debris. A clogged drain causes flooding at the first spill, and inspectors check them.",
 "Crews remove strainers, clear debris by hand and vacuum, and reinstall strainers.",
 ["Number of drains", "Strainer types", "Debris", "Areas"],
 ["Do not wash debris down drains.", "Report damaged drains."],
 [("Why clean floor drains after construction?", "Debris can clog them."),
  ("What is a trap primer?", "A device that keeps water in a drain trap."),
  ("Can debris be flushed down a floor drain?", "No, remove it."),
  ("Who checks drain function?", "The plumber.")]),
"Restroom tile and grout detailing": T(
 "Restroom tile and grout detailing cleans restroom floor and wall tile, removing grout haze, residue and dirt from tile and grout lines.",
 "Restroom tile and grout show haze, residue and dirt clearly, and grout stains easily.",
 "Crews remove haze with compatible products, scrub grout lines and rinse.",
 ["Tile and grout types", "Haze or residue", "Area", "Sealer status"],
 ["Acids damage some grouts.", "Unsealed grout stains."],
 [("How is restroom tile detailed?", "Remove haze, scrub grout, rinse."),
  ("Should restroom grout be sealed?", "Often."),
  ("Why does restroom grout darken?", "It absorbs dirt and moisture."),
  ("Is restroom tile part of final clean?", "Yes.")]),
"Drinking fountain and bottle filler cleaning": T(
 "Drinking fountain and bottle filler cleaning cleans the exterior, basins, spouts and grilles of drinking fountains and bottle filling stations.",
 "Fountains are used immediately after occupancy and must be clean. Construction dust and labels are common.",
 "Crews remove labels and film, clean basins and exteriors with food-safe cleaners and wipe spouts.",
 ["Units and types", "Finishes", "Labels", "Filter status"],
 ["Do not change filters unless authorized.", "Use food-safe products near spouts."],
 [("How are drinking fountains cleaned?", "With food-safe cleaners on basins and spouts."),
  ("Do bottle fillers have filters?", "Many do, maintained by facility staff."),
  ("Are fountains part of final clean?", "Yes."),
  ("Should fountains be flushed?", "Flushing is done by plumbers or facility staff.")]),
"Mop sink and janitor closet cleaning": T(
 "Mop sink and janitor closet cleaning cleans the custodial room, mop sink, shelving and floors so it is ready for the building's cleaning staff.",
 "Janitor closets are often used as trade storage during construction and left dirty.",
 "Crews remove debris, clean the mop sink and floors and wipe shelving.",
 ["Closet count", "Mop sink type", "Shelving", "Debris"],
 ["Trades often store materials there.", "Mop sinks collect grout and paint."],
 [("Why clean janitor closets?", "They are often used for trade storage."),
  ("What is a mop sink?", "A floor-level sink for custodial use."),
  ("Is janitor closet cleaning part of final clean?", "Yes."),
  ("Who uses janitor closets after turnover?", "Custodial staff.")]),
"Eyewash and emergency shower station cleaning": T(
 "Eyewash and emergency shower station cleaning cleans the exterior, bowls and covers of safety stations without interfering with their operation.",
 "Safety stations must be clean and ready. Construction dust can contaminate covers and bowls.",
 "Crews clean exteriors and bowls carefully; activation tests are done by facility staff.",
 ["Station count and types", "Covers", "Signage", "Testing responsibility"],
 ["Do not remove protective covers permanently.", "Testing is the facility's responsibility."],
 [("Who tests eyewash stations?", "Facility staff."),
  ("How are eyewash stations cleaned?", "Exteriors and bowls, gently."),
  ("Are eyewash stations part of final clean?", "Exteriors are."),
  ("Why keep eyewash covers clean?", "Contamination can affect users.")]),
"Plumbing fixture first-flush and aerator debris check": T(
 "A plumbing fixture first-flush and aerator debris check looks for debris in faucet aerators and fixtures after water service begins, coordinating cleaning or flushing with the plumber.",
 "New plumbing systems can carry debris that clogs aerators and reduces flow. Catching it early avoids complaints.",
 "Crews check aerators, clean them if allowed and report issues to the plumber.",
 ["Fixture count", "Plumber coordination", "Aerator types", "Reporting"],
 ["Do not disassemble fixtures without approval.", "Report persistent debris."],
 [("Why do new faucets have low flow?", "Debris in aerators."),
  ("Who flushes new plumbing systems?", "The plumber."),
  ("Can cleaners clean aerators?", "If allowed by the plumber."),
  ("What is an aerator?", "The screen at the faucet tip.")]),
}
