def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Commercial kitchen post-construction clean": T(
 "A commercial kitchen post-construction clean removes construction dust, debris, labels and residue from a new or remodeled restaurant or institutional kitchen so it is ready for equipment startup and health inspection.",
 "A kitchen cannot open until it passes health inspection. Dust on equipment, debris in drains and residue on food-contact surfaces are inspection failures, not cosmetic issues.",
 "Crews clean top down, from ceiling and hood exteriors to walls, equipment and floors, using food-safe, residue-free cleaners, and leave sanitizing to a separate, label-directed step.",
 ["Kitchen size and equipment list", "Health inspection date", "Specialty work by others: hood, ice machine, refrigeration", "Food-safe product requirements"],
 ["Dust on equipment before startup can be drawn into fans and compressors.", "Do not use solvent cleaners on food-contact surfaces."],
 [("What does a restaurant post-construction clean include?", "Ceilings, hood exteriors, walls, equipment exteriors, food-contact surfaces, floors, drains and restrooms, cleaned top down with food-safe products."),
  ("When should a new kitchen be cleaned?", "After equipment is installed and before the health inspection and equipment startup."),
  ("Who cleans the kitchen hood in a new restaurant?", "Hood exteriors are part of the clean; hood and duct interiors are cleaned by certified hood cleaning contractors."),
  ("Why does a new kitchen fail health inspection?", "Common reasons include dust overhead, debris in drains, dirty equipment and missing sanitation steps.")]),
"Stainless steel equipment exterior cleaning": T(
 "Stainless steel equipment exterior cleaning removes dust, fingerprints, adhesive and streaks from the outside of ranges, tables, refrigeration, sinks and other stainless kitchen equipment.",
 "Stainless shows every streak and fingerprint. Chloride cleaners and steel wool can cause rust spots that look like damage.",
 "Crews clean with neutral or stainless-specific cleaners, rinse, dry and finish with the grain, using non-scratch pads only.",
 ["Equipment list", "Protective film", "Adhesive residue", "Approved cleaners"],
 ["Bleach and chlorides can cause stainless to pit or rust.", "Steel wool leaves particles that rust."],
 [("How do you clean stainless steel without streaks?", "Clean with a neutral cleaner, rinse, dry and wipe in the direction of the grain."),
  ("Why does stainless steel rust?", "Chlorides, steel wool particles or damaged surfaces can cause rust spots on stainless."),
  ("Can bleach be used on stainless steel?", "It should be avoided, because chlorides can damage stainless."),
  ("Is stainless polish needed on new equipment?", "Usually not at turnover; a clean, dry surface wiped with the grain is enough.")]),
"Stainless steel protective film removal": T(
 "Stainless steel protective film removal peels the blue or white PVC film off new stainless equipment, panels and appliances and removes the adhesive left behind.",
 "Film left on stainless in a hot kitchen bakes on and leaves residue that is hard to remove and looks dirty.",
 "Crews peel film slowly, remove adhesive with stainless-safe removers and clean and dry the surface with the grain.",
 ["Equipment with film", "Age and heat exposure of film", "Adhesive removers", "Final wipe"],
 ["Film near heat sources bakes on quickly.", "Blades scratch stainless."],
 [("When should protective film be removed from kitchen equipment?", "Before equipment is fired up and as close to installation as practical, before heat bakes it on."),
  ("How do you remove adhesive left by stainless film?", "With a stainless-safe adhesive remover, then clean and dry the surface with the grain."),
  ("Why is old protective film hard to remove?", "Heat and time harden the adhesive."),
  ("Who removes equipment film in a new kitchen?", "The installer or the cleaning crew, depending on the contract.")]),
"Kitchen hood exterior cleaning": T(
 "Kitchen hood exterior cleaning cleans the outside surfaces of commercial kitchen hoods, including the canopy, edges, lights and accessible filter frames, without entering the hood plenum or ductwork.",
 "Hoods are the most visible equipment in a kitchen. Dust and film on them are seen by inspectors and owners.",
 "Crews clean exterior stainless with food-safe cleaners, wipe light lenses and leave filters and plenum interiors to certified hood cleaners.",
 ["Hood count and size", "Exterior surfaces", "Light fixtures", "Coordination with hood cleaning contractor"],
 ["Hood interiors and ducts are a regulated specialty.", "Fire suppression nozzles must not be disturbed."],
 [("Is hood exterior cleaning the same as hood cleaning?", "No. Exterior cleaning covers visible surfaces; hood and duct cleaning is regulated work under NFPA 96."),
  ("Can cleaning crews touch fire suppression nozzles?", "No. Suppression systems are serviced only by licensed contractors."),
  ("Should hood filters be cleaned at turnover?", "They should be clean and properly installed, often by the hood contractor."),
  ("Why clean hood exteriors before opening?", "They are visible and collect construction dust.")]),
"Kitchen exhaust hood and duct cleaning": T(
 "Kitchen exhaust hood and duct cleaning cleans the interior of commercial cooking hoods, plenums, grease ducts and exhaust fans to the standards of NFPA 96. It is regulated work for certified contractors.",
 "Grease in exhaust systems is a fire hazard. Fire codes and insurers require cleaning by qualified contractors, with documentation.",
 "Requests are routed only to certified hood cleaning contractors after review, and documentation is provided for the fire marshal and insurer.",
 ["Hood and duct system details", "Certification requirements", "Fire marshal and insurer documentation", "Access panels"],
 ["Only certified contractors should clean grease ducts.", "Access panels must be resealed properly."],
 [("Who is allowed to clean kitchen exhaust ducts?", "Certified hood cleaning contractors following NFPA 96 and local fire codes."),
  ("Does a new kitchen need hood cleaning?", "New systems should be clean before cooking; construction debris and dust may need removal."),
  ("What is NFPA 96?", "The fire code standard for ventilation control and fire protection of commercial cooking."),
  ("How often are kitchen exhaust systems cleaned?", "It depends on cooking volume, from monthly to annually, per fire code.")]),
"Walk-in cooler interior cleaning": T(
 "Walk-in cooler interior cleaning cleans the walls, ceiling, floor, shelving, door gaskets and evaporator housing exterior of new walk-in coolers before they are started and stocked.",
 "Dust and debris in a walk-in end up on food. Once the box is cold and stocked, cleaning is much harder.",
 "Crews vacuum and wipe panels, shelving and floors with food-safe cleaners, clean door gaskets and leave evaporator coils to refrigeration technicians.",
 ["Box size", "Shelving", "Floor type", "Refrigeration startup date"],
 ["Do not spray water into electrical components.", "Coils are serviced by refrigeration contractors."],
 [("When should a walk-in cooler be cleaned?", "Before it is started and stocked."),
  ("Can cleaning crews clean evaporator coils?", "No, refrigeration contractors handle coils."),
  ("Why clean door gaskets?", "Dirty or damaged gaskets affect the seal."),
  ("What cleaners are used in walk-ins?", "Food-safe cleaners.")]),
"Walk-in freezer interior cleaning": T(
 "Walk-in freezer interior cleaning cleans new freezer boxes before pull-down, including panels, floors, shelving, door heaters and gaskets.",
 "Once a freezer is cold, any moisture freezes and cleaning becomes difficult. Debris left inside freezes in place.",
 "Crews clean with minimal water and food-safe cleaners, dry surfaces thoroughly and coordinate with the refrigeration contractor before startup.",
 ["Freezer size", "Startup date", "Shelving", "Floor"],
 ["Leftover water freezes and creates ice hazards.", "Do not damage door heaters."],
 [("Why clean a freezer before startup?", "Once it is cold, cleaning is harder and moisture freezes."),
  ("Can wet cleaning be used in freezers?", "Minimal water, dried thoroughly."),
  ("Who starts up walk-in freezers?", "Refrigeration contractors."),
  ("Do freezer floors need special care?", "Yes, avoid leaving water.")]),
"Kitchen ceiling cleaning": T(
 "Kitchen ceiling cleaning removes dust and residue from kitchen ceilings, including washable ceiling tiles, gypsum, FRP or metal panels, and fixtures above food areas.",
 "Health inspectors look up. Dust above food prep areas can fall into food and is a common finding.",
 "Crews clean ceilings before walls and equipment, using food-safe cleaners and protecting surfaces below.",
 ["Ceiling material", "Fixtures", "Access over equipment", "Food-safe products"],
 ["Equipment below must be protected.", "Some ceiling tiles cannot be wet."],
 [("Why do health inspectors check kitchen ceilings?", "Dust and debris above food areas can contaminate food."),
  ("What ceiling materials are used in kitchens?", "Washable tiles, FRP, metal or painted gypsum."),
  ("Should kitchen ceilings be cleaned first?", "Yes, top down."),
  ("Can kitchen ceiling tiles be washed?", "Only washable types.")]),
"Food-contact surface pre-opening cleaning": T(
 "Food-contact surface pre-opening cleaning removes construction dust, residue and film from surfaces food touches, such as prep tables, cutting boards, shelves and equipment surfaces, before sanitizing.",
 "Food-contact surfaces must be clean before they can be sanitized; sanitizers do not work properly on dirty surfaces.",
 "Crews clean with food-safe detergents, rinse and leave surfaces ready for the sanitizing step.",
 ["Surfaces list", "Food-safe products", "Sanitizing responsibility", "Inspection date"],
 ["Solvents and non-food-safe cleaners must not be used.", "Cleaning does not equal sanitizing."],
 [("What is a food-contact surface?", "A surface food normally touches."),
  ("Do food surfaces need cleaning before sanitizing?", "Yes, sanitizers work only on clean surfaces."),
  ("What cleaners are used on food-contact surfaces?", "Food-safe detergents."),
  ("Who sanitizes food surfaces before opening?", "Restaurant staff or a contractor using registered sanitizers.")]),
"Food-contact surface sanitizing per label": T(
 "Food-contact surface sanitizing per label applies registered sanitizers at label concentrations and contact times to cleaned food-contact surfaces.",
 "Sanitizing must follow the product label to be effective and legal. Health inspectors check sanitizer concentrations.",
 "Trained crews use registered sanitizers, test concentration and follow label contact times and rinse instructions.",
 ["Sanitizer product", "Concentration testing", "Surfaces", "Documentation"],
 ["Incorrect concentration can be ineffective or unsafe.", "Only registered products may be used."],
 [("What is the difference between cleaning and sanitizing?", "Cleaning removes soil; sanitizing reduces microorganisms."),
  ("How is sanitizer concentration checked?", "With test strips."),
  ("Do sanitizers need rinsing?", "Follow the label."),
  ("Who can sanitize food surfaces?", "Trained staff using registered products.")]),
"Prep table and shelving cleaning": T(
 "Prep table and shelving cleaning cleans stainless prep tables, undershelves, wall shelves and storage racks in kitchens before opening.",
 "Prep tables are food-contact or near-food surfaces, and shelving holds stored food.",
 "Crews clean tops, undersides, legs and shelves with food-safe cleaners and dry surfaces.",
 ["Table and shelf count", "Finishes", "Food-safe products", "Undersides"],
 ["Sharp edges on shelving.", "Chlorides harm stainless."],
 [("Are prep table undersides cleaned?", "Yes, they collect dust."),
  ("What cleaners are used on prep tables?", "Food-safe cleaners."),
  ("Do wire shelves need cleaning?", "Yes."),
  ("Should prep tables be sanitized?", "Yes, after cleaning.")]),
"Dish area and dish machine exterior cleaning": T(
 "Dish area and dish machine exterior cleaning cleans dish tables, dish machine exteriors, sinks, racks and walls in the dish area.",
 "The dish area is wet and cleaned constantly once open. Construction debris there clogs drains and machines.",
 "Crews clean exteriors, tables and sinks, remove debris from drains and leave machine startup to the vendor.",
 ["Dish area equipment", "Drains", "Machine vendor coordination", "Walls"],
 ["Do not run dish machines without vendor setup.", "Debris can clog drains."],
 [("Who starts up a new dish machine?", "The vendor or service company."),
  ("Is the dish machine interior cleaned at turnover?", "Usually by the vendor at startup."),
  ("Why clean dish area drains?", "Debris causes clogs."),
  ("Are dish areas part of kitchen turnover?", "Yes.")]),
"Grease trap area cleaning": T(
 "Grease trap area cleaning cleans around grease interceptors and traps, including lids and floors. Pumping and interior servicing are done by licensed grease haulers.",
 "Grease traps must be accessible and clean for inspection. Construction debris can clog them before opening.",
 "Crews clean lids and surrounding floors and report debris for the plumber or hauler to remove.",
 ["Trap location", "Lid access", "Debris", "Hauler or plumber coordination"],
 ["Opening traps exposes odors and hazards.", "Pumping is done by licensed haulers."],
 [("Who pumps grease traps?", "Licensed grease haulers."),
  ("Why clean the grease trap area?", "Inspectors check access and cleanliness."),
  ("Can construction debris clog grease traps?", "Yes."),
  ("Are grease traps inspected before opening?", "Often.")]),
"Bar and beverage station cleaning": T(
 "Bar and beverage station cleaning cleans bar tops, back bars, sinks, beverage equipment, glass racks and shelving before opening.",
 "Bars are highly visible and serve food and drink. Dust and debris must be removed before stocking.",
 "Crews clean surfaces with food-safe cleaners, detail equipment exteriors and glass shelving and leave sanitizing per label.",
 ["Bar size", "Materials", "Equipment", "Glassware storage"],
 ["Stone bar tops need stone-safe cleaners.", "Beverage lines are cleaned by vendors."],
 [("Who cleans beverage lines?", "Beverage vendors or line cleaning services."),
  ("How are bar tops cleaned?", "With cleaners matched to the material."),
  ("Is the back bar cleaned?", "Yes."),
  ("Are bars sanitized before opening?", "Yes, after cleaning.")]),
"Ice machine exterior cleaning": T(
 "Ice machine exterior cleaning cleans the exterior, bin and surrounding area of ice machines.",
 "Ice machines must be clean; construction dust can enter vents.",
 "Crews wipe exteriors and vent grilles, leaving interior cleaning and sanitizing to service technicians.",
 ["Machine count", "Vents", "Bin exterior", "Service coordination"],
 ["Interior cleaning requires manufacturer procedures.", "Do not block vents."],
 [("Who cleans ice machine interiors?", "Service technicians."),
  ("Why clean ice machine vents?", "Dust affects performance."),
  ("Is the ice bin exterior cleaned?", "Yes."),
  ("Are ice machines checked by inspectors?", "Yes.")]),
"Ice machine interior cleaning and sanitizing": T(
 "Ice machine interior cleaning and sanitizing descales and sanitizes the inside of ice machines using manufacturer-approved chemicals and procedures.",
 "Ice is food, and ice machine interiors must be cleaned and sanitized following the manufacturer's procedure.",
 "Qualified technicians are routed after review.",
 ["Machine model", "Manufacturer procedure", "Approved chemicals", "Documentation"],
 ["Wrong chemicals damage machines.", "Procedures vary by model."],
 [("How often should ice machines be cleaned?", "Per the manufacturer, often every six months."),
  ("Who cleans ice machine interiors?", "Qualified technicians."),
  ("Why is ice machine sanitizing important?", "Ice is food and can be contaminated."),
  ("Do new ice machines need sanitizing?", "Yes, before first use.")]),
"Dry storage room cleaning": T(
 "Dry storage room cleaning cleans shelving, floors, walls and corners in food dry storage rooms before stocking.",
 "Dry storage must be clean and pest-free. Debris attracts pests.",
 "Crews vacuum and wipe shelving, clean floors and corners and check for debris.",
 ["Room size", "Shelving", "Corners", "Pest prevention"],
 ["Food debris attracts pests.", "Shelving should be off the floor."],
 [("Why clean dry storage before stocking?", "To prevent pests and contamination."),
  ("What is checked in dry storage?", "Cleanliness and pest signs."),
  ("Are corners cleaned?", "Yes."),
  ("Should shelving be off the floor?", "Yes.")]),
"Kitchen floor drain and trench drain cleaning": T(
 "Kitchen floor drain and trench drain cleaning removes debris, grout and mortar from kitchen floor drains, floor sinks and trench drains.",
 "Kitchen drains handle heavy water loads. Construction debris causes backups and odors.",
 "Crews remove grates, clear debris, vacuum and reinstall grates.",
 ["Drain types and count", "Grates", "Debris", "Plumber coordination"],
 ["Grates can be heavy.", "Do not wash debris into drains."],
 [("What is a floor sink?", "A drain receptor for equipment drains."),
  ("Why clean trench drains?", "Debris causes backups."),
  ("Who clears clogged drains?", "Plumbers."),
  ("Are drains checked at health inspection?", "Often.")]),
"FRP wall cleaning": T(
 "FRP wall cleaning cleans fiberglass reinforced plastic wall panels in kitchens, restrooms and food areas, removing dust, adhesive and residue.",
 "FRP is a cleanable surface required in food areas, but its texture traps dust and adhesive.",
 "Crews clean with non-abrasive, neutral cleaners and soft brushes, rinsing well.",
 ["Wall area", "Adhesive residue", "Trim and seams", "Cleaners"],
 ["Abrasives damage FRP surfaces.", "Solvents can damage FRP."],
 [("What is FRP?", "Fiberglass reinforced plastic wall panels."),
  ("How is FRP cleaned?", "With neutral cleaners and soft brushes."),
  ("Can FRP be pressure washed?", "Usually not."),
  ("Where is FRP used?", "Kitchens, restrooms and food areas.")]),
"FRP wall degreasing": T(
 "FRP wall degreasing removes grease and oily film from FRP panels in kitchens, using degreasers that do not damage the panel surface.",
 "Grease builds up quickly on kitchen walls, and FRP must stay cleanable for inspections.",
 "Crews use FRP-safe degreasers and soft brushes, then rinse.",
 ["Wall area", "Grease level", "Degreaser compatibility", "Rinse"],
 ["Strong solvents damage FRP.", "Grease makes floors slippery."],
 [("How is grease removed from FRP?", "With FRP-safe degreasers."),
  ("Why does FRP get greasy?", "Cooking vapors."),
  ("Can degreasers damage FRP?", "Some can."),
  ("How often should FRP be degreased?", "Regularly in kitchens.")]),
"FRP adhesive squeeze-out removal": T(
 "FRP adhesive squeeze-out removal takes off adhesive that squeezed out at panel seams and edges during installation.",
 "Adhesive squeeze-out looks unfinished and attracts dirt.",
 "Crews remove adhesive with plastic tools and adhesive-safe removers.",
 ["Seams and edges", "Adhesive type", "Remover", "Panel finish"],
 ["Solvents can damage FRP.", "Do not cut seams."],
 [("What is adhesive squeeze-out?", "Adhesive that squeezes out at seams."),
  ("How is FRP adhesive removed?", "With plastic tools and removers."),
  ("Who removes FRP adhesive?", "The installer or cleaning crew."),
  ("Does adhesive affect inspection?", "It can, if surfaces are not cleanable.")]),
"FRP trim and seam detailing": T(
 "FRP trim and seam detailing cleans the plastic or metal trim pieces and joints between FRP panels.",
 "Trim and seams trap dirt and adhesive.",
 "Crews clean trim with soft brushes and neutral cleaners.",
 ["Trim length", "Seam conditions", "Cleaners", "Damage"],
 ["Do not pull trim loose.", "Report gaps."],
 [("What is FRP trim?", "Pieces that join and finish FRP panels."),
  ("Why clean FRP seams?", "They trap dirt."),
  ("Are FRP seams sealed?", "Often."),
  ("Is trim cleaning part of kitchen turnover?", "Yes.")]),
"Insulated metal panel wall cleaning": T(
 "Insulated metal panel wall cleaning cleans metal-faced insulated panels used in coolers, freezers and food processing rooms.",
 "Metal panels in cold rooms collect dust and film, and must be clean for food safety.",
 "Crews clean with food-safe, non-abrasive cleaners, rinse and dry.",
 ["Panel area", "Finish", "Food-safe products", "Seams"],
 ["Abrasives scratch coatings.", "Moisture in seams can freeze."],
 [("Where are insulated metal panels used?", "Coolers, freezers and food plants."),
  ("How are metal panels cleaned?", "With food-safe, non-abrasive cleaners."),
  ("Can moisture damage panels?", "In seams, it can freeze."),
  ("Are panels inspected in food facilities?", "Yes.")]),
"Grocery store post-construction cleaning": T(
 "Grocery store post-construction cleaning prepares new or remodeled supermarkets for opening, covering sales floor, departments, refrigeration, back room, restrooms and exterior.",
 "Grocery openings are complex and on fixed dates, with food departments requiring food-safe cleaning.",
 "Crews phase cleaning by department turnover, using food-safe methods and high dusting.",
 ["Store size and departments", "Opening schedule", "Overhead areas", "Food-safe products"],
 ["Departments turn over at different times.", "Overhead dust can fall on product."],
 [("How long does a grocery store opening clean take?", "Several days to weeks, by department."),
  ("Is overhead cleaning part of grocery openings?", "It should be."),
  ("Who cleans grocery refrigeration?", "Cleaning crews clean exteriors and interiors; refrigeration contractors handle coils."),
  ("Do grocery openings require health inspection?", "Yes.")]),
"Refrigerated case detailing": T(
 "Refrigerated case detailing cleans grocery display cases, reach-ins and coffin cases inside and out, including shelves, glass doors and kick plates.",
 "Refrigerated cases display food and must be clean for inspections and customer appeal.",
 "Crews clean cases before startup or stocking, using food-safe cleaners and avoiding coils.",
 ["Case count and types", "Glass doors", "Shelves", "Startup schedule"],
 ["Coils are serviced by technicians.", "Water near electrical must be controlled."],
 [("How are refrigerated cases cleaned?", "Inside and out with food-safe cleaners."),
  ("When should cases be cleaned?", "Before startup and stocking."),
  ("Who cleans refrigeration coils?", "Technicians."),
  ("Are case kick plates cleaned?", "Yes.")]),
"Deli department finish cleaning": T(
 "Deli department finish cleaning prepares a grocery deli for opening, including service cases, prep areas, slicers' exteriors, walls and floors.",
 "Deli departments handle ready-to-eat food and are inspected closely.",
 "Crews clean top down with food-safe products and coordinate with equipment vendors.",
 ["Deli equipment", "Cases", "Prep areas", "Inspection date"],
 ["Slicers are cleaned by trained staff.", "Food-safe products only."],
 [("Who cleans deli slicers?", "Trained staff, per manufacturer."),
  ("Why is deli cleaning critical?", "Ready-to-eat food."),
  ("Are deli cases cleaned inside?", "Yes."),
  ("Is the deli inspected separately?", "Often.")]),
"Bakery department finish cleaning": T(
 "Bakery department finish cleaning prepares in-store bakeries for opening: ovens' exteriors, proofers, tables, racks, walls and floors.",
 "Bakeries combine flour dust and heat, and must be clean for inspections.",
 "Crews clean equipment exteriors and surfaces with food-safe products.",
 ["Equipment", "Racks", "Surfaces", "Inspection"],
 ["Oven interiors are handled by vendors.", "Flour dust accumulates quickly after opening."],
 [("Who cleans bakery ovens?", "Vendors or trained staff."),
  ("Are bakery racks cleaned?", "Yes."),
  ("Why clean bakery walls?", "Flour and dust accumulate."),
  ("Is bakery cleaning food-safe?", "Yes.")]),
"Meat and seafood department finish cleaning": T(
 "Meat and seafood department finish cleaning prepares cutting rooms, cases and coolers for opening.",
 "Meat rooms have strict sanitation requirements and are inspected closely.",
 "Crews clean with food-safe products, focusing on surfaces, drains and walls.",
 ["Cutting room", "Cases", "Drains", "Inspection"],
 ["Drains must be clear.", "Equipment is cleaned by trained staff."],
 [("Why are meat rooms cleaned carefully?", "Strict sanitation requirements."),
  ("Are cutting room drains cleaned?", "Yes."),
  ("Who sanitizes meat equipment?", "Trained staff."),
  ("Are meat cases cleaned before stocking?", "Yes.")]),
"Produce department finish cleaning": T(
 "Produce department finish cleaning prepares produce cases, misting systems' exteriors, tables and floors.",
 "Produce departments have wet cases and displays that need cleaning before opening.",
 "Crews clean cases and displays with food-safe products.",
 ["Cases", "Displays", "Misting", "Floors"],
 ["Misting systems are serviced by vendors.", "Wet floors are slippery."],
 [("How are produce cases cleaned?", "With food-safe products."),
  ("Who services misting systems?", "Vendors."),
  ("Are produce displays cleaned?", "Yes."),
  ("Why are produce floors slippery?", "Water.")]),
"Checkstand and conveyor cleaning": T(
 "Checkstand and conveyor cleaning cleans checkout counters, conveyor belts, scanners' exteriors and bagging areas.",
 "Checkstands are seen by every customer.",
 "Crews clean surfaces and belts, avoiding electronics.",
 ["Checkstand count", "Belts", "Electronics", "Bagging areas"],
 ["Do not spray electronics.", "Belts must not be cut."],
 [("How are conveyor belts cleaned?", "Wiped with appropriate cleaners."),
  ("Are scanners cleaned?", "Exteriors gently."),
  ("Are checkstands cleaned at opening?", "Yes."),
  ("Who services belts?", "Vendors.")]),
"Receiving and loading bay cleaning": T(
 "Receiving and loading bay cleaning cleans back-of-house receiving areas, docks and floors.",
 "Receiving areas collect debris from deliveries and construction.",
 "Crews sweep, scrub and clear debris.",
 ["Area", "Dock equipment", "Debris", "Drains"],
 ["Dock edges are fall hazards.", "Drains must be protected."],
 [("Why clean receiving areas?", "They collect debris."),
  ("Are dock levelers cleaned?", "Exteriors."),
  ("Is receiving inspected?", "Often."),
  ("Who cleans receiving?", "Cleaning crews.")]),
"Convenience store remodel cleanup": T(
 "Convenience store remodel cleanup cleans c-stores after remodels, often overnight, so the store can reopen quickly.",
 "C-stores operate around the clock and lose sales when closed.",
 "Crews work in phases, cleaning sales floors, coolers, food service and restrooms.",
 ["Store layout", "Phases", "Coolers", "Food service"],
 ["Fuel areas have safety rules.", "Food service needs food-safe products."],
 [("How fast can a c-store reopen after remodel cleaning?", "Often overnight."),
  ("Are cooler doors cleaned?", "Yes."),
  ("Is food service cleaned?", "Yes."),
  ("Are fuel areas cleaned?", "With safety rules.")]),
"Food plant post-construction cleaning": T(
 "Food plant post-construction cleaning prepares food processing facilities after construction, before sanitation and production startup.",
 "Food plants have strict sanitation requirements and audits.",
 "Specialist crews clean following plant procedures and food-safe products.",
 ["Plant areas", "Procedures", "Equipment", "Audits"],
 ["Plant sanitation procedures must be followed.", "Equipment is cleaned by trained staff."],
 [("Who cleans food plants after construction?", "Specialist crews."),
  ("Do food plants have audits?", "Yes."),
  ("Is overhead cleaning important?", "Yes."),
  ("Are sanitation procedures required?", "Yes.")]),
}
