def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Mechanical room cleaning": T(
 "Mechanical room cleaning removes construction debris, dust and packaging from boiler rooms, pump rooms and mechanical equipment rooms, cleaning floors, walls and equipment exteriors without touching controls.",
 "Mechanical rooms hold the building's most expensive equipment, and dust drawn into motors, filters and controls shortens its life. Commissioning agents and fire inspectors walk these rooms before turnover.",
 "Crews clear debris first, HEPA vacuum equipment tops and floors, then damp-wipe exteriors and pipe insulation jackets, keeping liquids away from motors, panels and controls.",
 ["Room list and equipment installed", "Access and lockout coordination with the mechanical contractor", "Floor finish, sealed or painted", "Commissioning and inspection dates"],
 ["Never adjust valves, switches or controls; leave equipment exactly as found.", "Housekeeping pads and floor drains often hold grout and debris that must be cleared, not washed down."],
 [("What is included in mechanical room cleaning after construction?", "Debris removal, HEPA vacuuming and damp wiping of equipment exteriors, piping, walls and floors, plus clearing floor drains, all without touching controls or opening equipment."),
  ("Why do commissioning agents care about clean mechanical rooms?", "Dust and debris can clog filters, coils and motors during testing, and a clean room makes leaks and labeling problems easy to spot."),
  ("Can a cleaning crew wipe down boilers and pumps?", "Crews can wipe the cool, de-energized exterior surfaces. Anything inside the equipment, and any energized or hot surface, is left to the mechanical contractor."),
  ("Should mechanical room floors be sealed before turnover?", "Many specs call for sealed or painted floors in mechanical rooms. Cleaning should be finished before any sealer goes down, and the sealer manufacturer's cleaning guidance followed afterward.")]),
"Electrical room non-invasive cleaning": T(
 "Electrical room non-invasive cleaning cleans the floors, walls and outside of enclosures in electrical rooms using dry and HEPA methods only, with no liquids near equipment and nothing opened.",
 "Electrical rooms collect drywall and concrete dust that can work into switchboards and panels. At the same time, they are among the most dangerous rooms in the building to clean.",
 "Only crews approved by the electrical contractor enter, under their rules. Floors are HEPA vacuumed and dry or barely damp mopped away from gear, and enclosure exteriors are dry-wiped only.",
 ["Permission and escort from the electrical contractor or owner", "Which surfaces may be cleaned", "Energized status of equipment", "Required PPE and approach limits"],
 ["No liquids, sprays or metal tools near electrical equipment.", "Never open panel doors or remove covers; that is electrical work."],
 [("Can a cleaning company clean an electrical room?", "Only non-invasive cleaning of floors, walls and the outside of enclosures, with the electrical contractor's permission and following their safety rules."),
  ("Why is water not allowed in electrical rooms?", "Liquids near energized equipment create shock and arc-flash hazards and can damage gear."),
  ("Who cleans inside switchgear and panels?", "Qualified electrical workers. Internal cleaning is maintenance work done de-energized by electricians."),
  ("Do inspectors check electrical rooms for debris?", "Yes. Stored materials and debris in front of panels violate required working clearances and are a common finding.")]),
"Equipment exterior wipe-down": T(
 "Equipment exterior wipe-down cleans the outer housings of installed building equipment such as water heaters, pumps, compressors, panels and appliances, removing dust, labels, overspray and fingerprints.",
 "New equipment is part of what the owner accepts at turnover. Dusty housings look neglected, and dust on vents and grilles affects cooling.",
 "Crews HEPA vacuum vents and grilles, wipe housings with damp microfiber and neutral cleaner, and leave nameplates and required labels in place.",
 ["Equipment list by room", "Required labels and nameplates to keep", "Energized or hot equipment", "Finishes: painted, stainless or plastic"],
 ["Do not remove nameplates, warning labels or inspection tags.", "Hot surfaces must cool before cleaning."],
 [("Should labels be removed from new equipment?", "Shipping and protective labels can come off, but nameplates, warning labels, and inspection tags must stay."),
  ("How is dust removed from equipment vents?", "With a HEPA vacuum and brush attachment, so dust is captured instead of pushed inside."),
  ("Can equipment be wiped while it is running?", "Only cool, safe exterior surfaces, and only where the responsible trade allows it. Many owners require equipment to be off."),
  ("Why does equipment need to be clean at turnover?", "The owner accepts it as new, and clean housings make leaks, damage and missing labels easy to see.")]),
"Air handler exterior cleaning": T(
 "Air handler exterior cleaning removes dust, overspray and debris from the outside casing, access doors and connections of air handling units, without opening the unit.",
 "Air handlers are usually set early and sit through months of construction dust. Dust on the casing near intakes and doors ends up inside the unit when it is opened for service.",
 "Crews HEPA vacuum the top and sides, wipe the casing and doors with damp microfiber, and leave filters, coils and internal sections to the mechanical contractor.",
 ["Number and size of units", "Indoor or rooftop location", "Access around the unit", "Coordination with filter changes"],
 ["Opening access doors is the mechanical contractor's decision.", "Do not step on unit casings or piping."],
 [("Is air handler exterior cleaning the same as cleaning the inside?", "No. Exterior cleaning covers only the outer casing. Coils, drain pans and internal sections are cleaned by mechanical or duct cleaning specialists."),
  ("Why clean the outside of an air handler?", "Dust on the casing gets pulled inside when access doors are opened and looks neglected at turnover."),
  ("When should air handler exteriors be cleaned?", "Near the end of construction, after dusty work in that area is finished and before filters are changed for occupancy."),
  ("Do air handlers have labels that must stay on?", "Yes. Nameplates, electrical warnings and service labels stay in place.")]),
"Air handler interior cleaning": T(
 "Air handler interior cleaning cleans the coils, drain pans, fan sections, plenums and internal surfaces of air handling units. It is specialty work performed by qualified HVAC cleaning contractors.",
 "If construction dust reached the inside of an air handler, it coats coils and drain pans, reduces efficiency and can affect indoor air quality from the first day of occupancy.",
 "Requests are routed only to qualified HVAC hygiene contractors after review, coordinated with the mechanical contractor and documented for the owner.",
 ["Evidence that internal contamination occurred", "Unit access and lockout", "Coil cleaning method and chemicals", "Documentation and verification"],
 ["Coil fins bend easily; improper methods damage them.", "Internal cleaning may affect equipment warranties if not coordinated."],
 [("When does a new air handler need internal cleaning?", "When construction dust or debris got inside because the unit ran without proper filtration or was left open."),
  ("Who cleans inside air handlers?", "Qualified HVAC cleaning contractors, coordinated with the mechanical contractor."),
  ("Can coil cleaning damage equipment?", "Yes, if the wrong pressure or chemicals are used. That is why it is specialist work."),
  ("Is air handler interior cleaning documented?", "It should be, with photos before and after, for the owner's records.")]),
"HVAC duct interior cleaning": T(
 "HVAC duct interior cleaning removes construction dust and debris from inside supply and return ductwork, usually following NADCA standards, when ducts were contaminated during construction.",
 "Ducts that were left uncapped or ran without filters during construction carry dust into occupied rooms for months. Cleaning them is far easier before ceilings close.",
 "Requests go only to qualified duct cleaning contractors after review. Work follows NADCA methods with source-removal equipment and documentation.",
 ["Evidence of contamination", "Duct types and access", "NADCA or project standard", "Before-and-after documentation"],
 ["Flexible and lined duct need different methods than sheet metal.", "Cleaning without proper containment spreads dust into the building."],
 [("Do new buildings need duct cleaning?", "Only when ducts were contaminated during construction. Well-protected duct systems usually do not."),
  ("What is NADCA?", "The National Air Duct Cleaners Association, which publishes standards for HVAC system cleaning."),
  ("How can duct contamination be prevented during construction?", "By capping open duct ends, storing duct clean, and not running the HVAC without proper filtration."),
  ("Who verifies duct cleaning?", "The duct contractor provides documentation; some owners also use independent inspection.")]),
"Rooftop unit exterior and curb cleaning": T(
 "Rooftop unit exterior and curb cleaning cleans the outside cabinets, curbs and surrounding roof area of rooftop HVAC units, removing construction debris, packaging and dust.",
 "Debris around rooftop units can blow into intakes, block condensate drains or damage the roof membrane.",
 "Crews work with roof fall protection, pick up debris, wipe cabinet exteriors and clear around curbs without walking on unprotected membrane.",
 ["Number of units", "Roof access and fall protection", "Roof membrane type", "Debris amount"],
 ["Fall protection is required on roofs.", "Sharp debris can puncture the roof membrane."],
 [("Why clean around rooftop units?", "Debris can be sucked into intakes, block drains or puncture the roof."),
  ("Who cleans rooftop unit coils?", "The mechanical contractor or HVAC service company."),
  ("Is roof work dangerous?", "Yes. Crews need fall protection and roof access plans."),
  ("Can cleaning crews walk on the roof?", "Only on approved paths and with protection for the membrane.")]),
"Generator and switchgear exterior cleaning": T(
 "Generator and switchgear exterior cleaning cleans the outside of emergency generators, enclosures and switchgear lineups under the direction of the electrical contractor. It is conditional work.",
 "Generators and switchgear are critical life-safety and power equipment, often energized or ready to start automatically.",
 "Requests are reviewed and routed only with the electrical contractor's approval, using dry methods and respecting automatic start hazards.",
 ["Equipment and energized status", "Electrical contractor approval", "Automatic start lockout", "Dry cleaning methods"],
 ["Generators can start automatically.", "Arc-flash boundaries must be respected."],
 [("Can cleaning crews clean a generator?", "Only the exterior, with approval and lockout from the responsible trade."),
  ("Why is switchgear cleaning conditional?", "It is energized, high-voltage equipment with serious hazards."),
  ("Who cleans inside switchgear?", "Qualified electrical workers."),
  ("Why are generators dangerous to clean?", "They can start automatically during a power event.")]),
"Fire pump and riser room cleaning": T(
 "Fire pump and riser room cleaning removes debris and dust from fire pump rooms and sprinkler riser rooms, cleaning floors, walls and the outside of pipes and valves without touching any fire protection equipment settings.",
 "Fire inspectors and the fire marshal inspect these rooms. Debris, stored materials and dusty valves are common findings.",
 "Crews remove debris, HEPA vacuum and damp-wipe surfaces, and leave all valves, gauges and controls untouched.",
 ["Rooms and equipment", "Inspection date", "Access", "Restrictions from fire protection contractor"],
 ["Never operate or move valves.", "Keep access to equipment clear."],
 [("What is a sprinkler riser room?", "The room where the fire sprinkler system's main valves and controls are located."),
  ("Do fire inspectors check riser rooms?", "Yes, for access, labeling and condition."),
  ("Can cleaners touch sprinkler valves?", "No. Valves are operated only by fire protection contractors."),
  ("Why keep riser rooms clear?", "Firefighters need immediate access.")]),
"Telecom and IDF/MDF room cleaning": T(
 "Telecom and IDF/MDF room cleaning cleans network and telecom rooms before equipment is activated, removing dust, debris and packaging with HEPA and antistatic methods.",
 "Network equipment is sensitive to dust. These rooms are also tight spaces where cable trays and racks collect debris.",
 "Crews clean with IT approval, HEPA vacuum floors and surfaces, wipe rack exteriors dry and leave cables untouched.",
 ["Room list", "IT approval", "Equipment status", "Antistatic requirements"],
 ["Do not disturb cables or patch panels.", "No liquids near active equipment."],
 [("What is an IDF room?", "An intermediate distribution frame room for networking on a floor."),
  ("What is an MDF room?", "The main distribution frame room, where main network connections come in."),
  ("Why clean telecom rooms?", "Dust affects network equipment."),
  ("Who allows telecom room cleaning?", "The IT team or low-voltage contractor.")]),
"Elevator machine room cleaning": T(
 "Elevator machine room cleaning removes debris and dust from elevator machine rooms with the elevator contractor's permission, cleaning floors and walls without touching equipment.",
 "Elevator inspectors require machine rooms to be clean and free of stored materials.",
 "Crews clean under the elevator contractor's rules and leave all equipment alone.",
 ["Elevator contractor permission", "Inspection date", "Access", "Debris"],
 ["Never touch elevator equipment.", "Rooms must not be used for storage."],
 [("Who controls elevator machine rooms?", "The elevator contractor until turnover."),
  ("Why must machine rooms be clean?", "Inspectors require it."),
  ("Can materials be stored in machine rooms?", "No."),
  ("Can cleaners touch elevator equipment?", "No.")]),
"Chiller and boiler exterior cleaning": T(
 "Chiller and boiler exterior cleaning cleans the outside of central plant equipment, removing dust and overspray without opening or adjusting equipment.",
 "Central plant equipment is large and visible during commissioning and owner tours.",
 "Crews clean cool, safe exterior surfaces with mechanical contractor approval.",
 ["Equipment", "Approval", "Hot surfaces", "Labels"],
 ["Hot surfaces cause burns.", "Do not touch controls."],
 [("Who cleans chiller interiors?", "Mechanical service contractors."),
  ("Can boilers be cleaned while hot?", "No, only cool surfaces."),
  ("Why clean central plant equipment?", "For commissioning and turnover."),
  ("Are labels left on?", "Yes.")]),
"Duct opening seal inspection and re-seal cleanup": T(
 "Duct opening seal inspection and re-seal cleanup checks that open duct ends, registers and returns are capped during construction, reports torn or missing caps and cleans debris around them.",
 "Uncapped ducts collect construction dust that later blows into finished rooms. Catching torn caps early prevents expensive duct cleaning.",
 "Crews walk the building on a schedule, report open or torn duct protection to the mechanical contractor and clean debris around openings.",
 ["Inspection frequency", "Reporting process", "Duct protection type", "Areas"],
 ["Only the mechanical contractor reseals ductwork.", "Do not remove caps to clean inside."],
 [("Why are duct openings capped during construction?", "To keep construction dust out of the HVAC system."),
  ("What happens if duct caps tear?", "Dust can get into ducts, which may require duct cleaning later."),
  ("Who reseals duct openings?", "The mechanical contractor."),
  ("Is duct protection part of LEED?", "Yes, it is part of construction IAQ management.")]),
"Return grille temporary filter media change": T(
 "Return grille temporary filter media change replaces the temporary filter material placed over return grilles when the HVAC runs during construction.",
 "If the HVAC runs during construction, temporary filters keep dust out of the system. Loaded filters stop working.",
 "Crews replace filter media on schedule or when loaded, bagging used media carefully.",
 ["Grille count", "Filter media type", "Change schedule", "Disposal"],
 ["Do not run HVAC without filters.", "Bag used media to avoid releasing dust."],
 [("Why put filters on return grilles during construction?", "To keep dust out of the HVAC system."),
  ("How often are temporary filters changed?", "When loaded or on a schedule."),
  ("What MERV rating is used?", "Many projects specify MERV 8 or higher."),
  ("Who changes temporary filters?", "The mechanical contractor or a cleaning crew.")]),
"Final HVAC filter replacement coordination": T(
 "Final HVAC filter replacement coordination schedules the change to new, permanent filters after final cleaning and before occupancy.",
 "Filters used during construction are loaded. New filters are required by green building standards before occupancy.",
 "Crews coordinate with the mechanical contractor so final cleaning finishes before filters are changed.",
 ["Filter change date", "Final cleaning schedule", "Filter types", "Documentation"],
 ["Changing filters before final cleaning wastes them.", "Filter changes are done by the mechanical contractor."],
 [("When should HVAC filters be replaced?", "After final cleaning and before occupancy."),
  ("Why replace filters before occupancy?", "Construction filters are loaded with dust."),
  ("Who replaces filters?", "The mechanical contractor."),
  ("Does LEED require new filters?", "Construction IAQ credits typically do.")]),
"Pre-flush-out final cleaning": T(
 "Pre-flush-out final cleaning completes the final clean before the building flush-out, so dust is removed before air is circulated through the system.",
 "Flushing out a dusty building spreads dust through the HVAC system.",
 "Crews schedule final cleaning before flush-out and coordinate with commissioning.",
 ["Flush-out schedule", "Final cleaning", "Commissioning", "Filters"],
 ["Flush-out before cleaning spreads dust.", "Schedule coordination is critical."],
 [("What is a building flush-out?", "Running HVAC with outdoor air to remove contaminants."),
  ("Why clean before flush-out?", "So dust is not spread."),
  ("Who schedules flush-out?", "The GC and commissioning agent."),
  ("Is flush-out required?", "On some green building projects.")]),
"Construction IAQ photo documentation": T(
 "Construction IAQ photo documentation records duct protection, housekeeping and cleaning with dated photos for green building submissions.",
 "Green building credits require proof that IAQ measures were followed, often photos on multiple dates.",
 "Crews photograph protection and cleaning on scheduled dates and organize them for submission.",
 ["Required dates", "Photo subjects", "Organization", "Submission"],
 ["Missing photos can cost the credit.", "Photos must be dated."],
 [("Why are IAQ photos needed?", "To document green building compliance."),
  ("How many dates are required?", "Often at least three."),
  ("What do IAQ photos show?", "Duct protection, housekeeping and cleaning."),
  ("Who submits IAQ documentation?", "The GC or LEED consultant.")]),
"Low-VOC product log for cleaning materials": T(
 "A low-VOC product log for cleaning materials lists the cleaning products used on the project, their data sheets and VOC content.",
 "Green building projects and owners may require documentation of cleaning products used.",
 "Crews keep a log of products with SDS and technical data.",
 ["Products used", "Data sheets", "VOC content", "Submission"],
 ["Product substitutions must be logged.", "Data sheets must be current."],
 [("What is a VOC?", "A volatile organic compound."),
  ("Why log cleaning products?", "For green building documentation."),
  ("What data sheets are needed?", "SDS and technical data."),
  ("Who keeps the product log?", "The cleaning contractor.")]),
}
