def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Store opening clean": T(
 "A store opening clean is the final clean of a new or remodeled retail store before it opens, covering the sales floor, fixtures, glass, fitting rooms, stockroom, restrooms and entry, timed around merchandise delivery.",
 "Opening dates are announced months in advance and rarely move. A store that opens dusty loses its first impression and damages merchandise.",
 "Crews clean overhead first, then fixtures before stocking, then floors and glass last, with a touch-up pass the day before opening.",
 ["Opening date and merchandise schedule", "Store size and ceiling type", "Fixture installation timeline", "Night or day work"],
 ["Merchandise set before overhead cleaning will collect falling dust.", "Last-minute trades often re-soil floors."],
 [("When should a store opening clean happen?", "In stages: overhead before fixtures, fixtures before merchandise, and floors and glass right before opening."),
  ("What is included in a store opening clean?", "Overhead, fixtures, glass, floors, fitting rooms, stockroom, restrooms and the entrance."),
  ("How long does a store opening clean take?", "From one day for a small shop to several days or shifts for a large store."),
  ("Who coordinates the store opening clean?", "Usually the GC, working with the retailer's opening team.")]),
"Gondola shelving detailing": T(
 "Gondola shelving detailing cleans freestanding retail aisle shelving: shelves, uprights, base decks, kick plates and price channels, before products are stocked.",
 "Gondolas are installed late and covered in dust, labels and fingerprints. Once stocked, they are almost impossible to clean thoroughly.",
 "Crews work top shelf to base, vacuum price channels and wipe all surfaces with damp microfiber and neutral cleaner.",
 ["Linear feet of gondola", "Number of shelves", "Price channels and accessories", "Stocking schedule"],
 ["Do not remove or rearrange shelves set by the fixture installer.", "Sharp edges on shelf brackets."],
 [("What is gondola shelving?", "Freestanding, double-sided retail shelving units used in aisles."),
  ("When should gondolas be cleaned?", "After installation and before stocking."),
  ("Are price channels cleaned?", "Yes, they trap dust and debris."),
  ("Who installs gondolas?", "Fixture installers, usually before cleaning.")]),
"Wall fixture and slatwall cleaning": T(
 "Wall fixture and slatwall cleaning cleans slatwall panels, grid walls, wall standards and display fixtures mounted to walls in retail stores.",
 "Slatwall grooves trap dust, and wall fixtures are at eye level where shoppers look.",
 "Crews vacuum grooves with crevice tools and wipe faces, top to bottom.",
 ["Wall fixture area", "Slatwall inserts", "Accessories", "Stocking schedule"],
 ["Inserts can scratch.", "Accessories should not be removed."],
 [("How is slatwall cleaned?", "Vacuum the grooves and wipe the faces."),
  ("Why does slatwall get dusty?", "Its grooves trap dust."),
  ("Are wall fixtures cleaned before stocking?", "Yes."),
  ("What is grid wall?", "A metal grid display used in stores.")]),
"Display fixture and mannequin cleaning": T(
 "Display fixture and mannequin cleaning cleans tables, racks, mannequins, displays and decorative fixtures on the sales floor.",
 "Display fixtures are where shoppers look first. Dust and fingerprints on them look careless.",
 "Crews clean each fixture by material, using gentle cleaners on mannequins and finishes.",
 ["Fixture types", "Materials", "Mannequin finishes", "Timing"],
 ["Mannequin finishes can be damaged by solvents.", "Fixtures may be fragile."],
 [("How are mannequins cleaned?", "Gently, with mild cleaners."),
  ("Are display tables cleaned before stocking?", "Yes."),
  ("Who places mannequins?", "Visual merchandising teams."),
  ("Are acrylic displays easy to scratch?", "Yes.")]),
"Fitting room cleaning": T(
 "Fitting room cleaning cleans fitting room doors, mirrors, benches, hooks, walls and floors before a store opens.",
 "Fitting rooms are small spaces with mirrors and are inspected closely by shoppers.",
 "Crews detail mirrors, hardware and surfaces and clean floors.",
 ["Room count", "Mirrors", "Hardware", "Floors"],
 ["Mirror edges are sensitive to moisture.", "Doors may have locks."],
 [("Are fitting rooms cleaned before opening?", "Yes."),
  ("How are fitting room mirrors cleaned?", "Spray onto cloths."),
  ("Are hooks cleaned?", "Yes."),
  ("Why focus on fitting rooms?", "Shoppers notice them.")]),
"Point-of-sale counter detailing": T(
 "Point-of-sale counter detailing cleans checkout counters, cash wraps, display cases and accessories at the point of sale.",
 "The cash wrap is where every shopper ends their visit.",
 "Crews clean surfaces, glass and accessories without spraying electronics.",
 ["Counter materials", "Electronics", "Glass", "Accessories"],
 ["Do not spray electronics.", "Stone counters need stone-safe cleaners."],
 [("What is a cash wrap?", "The checkout counter in a store."),
  ("How are POS counters cleaned?", "Surfaces and glass, avoiding electronics."),
  ("Are POS terminals cleaned?", "Exteriors gently."),
  ("Is the cash wrap cleaned before opening?", "Yes.")]),
"Merchandise set support cleaning": T(
 "Merchandise set support cleaning keeps the store clean while merchandise is unpacked and set, removing packaging and debris as teams work.",
 "Stocking produces large volumes of cardboard and plastic. Without cleanup, the store fills with debris right before opening.",
 "Crews remove packaging continuously and clean as areas are completed.",
 ["Stocking schedule", "Packaging volume", "Recycling", "Areas"],
 ["Do not remove merchandise.", "Cardboard volume can be large."],
 [("What is merchandise set?", "Stocking a store before opening."),
  ("Why clean during merchandise set?", "Packaging piles up."),
  ("Is cardboard recycled?", "Often."),
  ("Who stocks the store?", "The retailer's team.")]),
"Stockroom and backroom cleaning": T(
 "Stockroom and backroom cleaning cleans storage rooms, receiving areas, break rooms and offices behind the sales floor.",
 "Back rooms are used for storage during construction and are often the dirtiest areas at opening.",
 "Crews clear debris, clean shelving and floors and clean break areas.",
 ["Rooms", "Shelving", "Debris", "Break areas"],
 ["Do not discard stored merchandise.", "Back rooms often hold trade materials."],
 [("Are stockrooms cleaned before opening?", "Yes."),
  ("Why are back rooms dirty?", "They are used for storage."),
  ("Are break rooms cleaned?", "Yes."),
  ("Is shelving cleaned?", "Yes.")]),
"Retail remodel overnight cleaning": T(
 "Retail remodel overnight cleaning cleans an operating store after each night of remodel work so it can open the next morning.",
 "Stores in remodel cannot close. Cleaning each night keeps them safe and presentable.",
 "Crews clean work areas, floors and fixtures after construction crews finish each night.",
 ["Remodel schedule", "Work areas", "Opening time", "Protection"],
 ["Crews must finish before opening.", "Merchandise must be protected."],
 [("How does overnight remodel cleaning work?", "Crews clean after each night's construction."),
  ("Do stores stay open during remodels?", "Often."),
  ("Is merchandise covered?", "Yes."),
  ("Who coordinates overnight cleaning?", "The GC and store manager.")]),
"Phased store remodel cleaning": T(
 "Phased store remodel cleaning cleans each phase of a store remodel as it is completed, so finished areas can reopen to shoppers.",
 "Remodels move through a store in phases; each completed phase must be cleaned and turned back over.",
 "Crews clean each phase completely and protect it from adjacent work.",
 ["Phase schedule", "Areas", "Protection", "Turnover"],
 ["Adjacent work can re-soil cleaned areas.", "Phases may shift."],
 [("What is a phased remodel?", "A remodel done in sections."),
  ("How is each phase cleaned?", "Completely, then protected."),
  ("Does phased cleaning cost more?", "It can."),
  ("Who decides phases?", "The GC and retailer.")]),
"Multi-site retail rollout cleaning": T(
 "Multi-site retail rollout cleaning delivers the same cleaning scope and checklist across many store openings or remodels in different locations.",
 "National retailers need consistent results across locations, with one standard and one point of coordination.",
 "Beyond Klean standardizes the scope and matches verified local contractors where coverage exists.",
 ["Store list and schedule", "Standard scope", "Local coverage", "Reporting"],
 ["Coverage varies by market.", "Consistent checklists are essential."],
 [("What is a retail rollout?", "A program of openings or remodels across many locations."),
  ("How is consistency maintained?", "With one scope and checklist."),
  ("Does Beyond Klean cover every market?", "Coverage is being built market by market."),
  ("Who manages rollout cleaning?", "The retailer or GC with Beyond Klean.")]),
"Restaurant chain opening clean": T(
 "A restaurant chain opening clean is the standardized pre-opening clean for chain restaurants, covering dining, kitchen, restrooms and exterior.",
 "Chains need consistent openings and health inspection readiness.",
 "Crews follow the chain's checklist plus food-safe kitchen procedures.",
 ["Chain checklist", "Kitchen", "Dining room", "Inspection date"],
 ["Kitchen needs food-safe products.", "Specialty equipment by vendors."],
 [("Do restaurant chains have cleaning checklists?", "Many do."),
  ("Is the kitchen cleaned to health standards?", "Yes."),
  ("Is the exterior cleaned?", "Yes."),
  ("Who provides the checklist?", "The chain.")]),
"Bank branch opening clean": T(
 "A bank branch opening clean prepares new or remodeled branches, including lobbies, teller lines, offices, ATMs exteriors and vault areas.",
 "Branches have security areas and customer-facing spaces that must be presentable.",
 "Crews clean under security escort where required.",
 ["Areas", "Security requirements", "ATMs", "Vault areas"],
 ["Security rules apply.", "Do not open security equipment."],
 [("Are bank vaults cleaned?", "Areas around them, under escort."),
  ("Are ATMs cleaned?", "Exteriors."),
  ("Is security escort required?", "Often."),
  ("Is the lobby cleaned?", "Yes.")]),
"Pharmacy and clinic retail opening clean": T(
 "A pharmacy and clinic retail opening clean prepares retail pharmacies and clinics, including dispensing areas, exam rooms and storage.",
 "Pharmacies and clinics have health requirements and sensitive areas.",
 "Crews follow facility requirements and use appropriate products.",
 ["Areas", "Requirements", "Storage", "Exam rooms"],
 ["Compounding areas have special requirements.", "Medication storage must be clean."],
 [("Are pharmacies cleaned differently?", "Yes, with health requirements."),
  ("Are exam rooms cleaned?", "Yes."),
  ("Is compounding cleaning special?", "Yes."),
  ("Who sets requirements?", "The pharmacy or clinic.")]),
}
