def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Healthcare post-construction terminal-style clean": T(
 "A healthcare post-construction terminal-style clean is a protocol-driven, top-to-bottom final clean of hospital or clinical space after construction, done before patients return and coordinated with the facility's infection prevention team.",
 "Construction dust in a hospital can carry fungal spores and other contaminants that are dangerous to immunocompromised patients. Healthcare construction is governed by an infection control risk assessment, and the final clean is part of it.",
 "Only trained healthcare cleaning crews are routed, after review. They work inside containment, HEPA vacuum and damp-wipe every surface top down with hospital-approved products, and coordinate the release of the space with environmental services.",
 ["Infection control risk assessment class and requirements", "Hospital-approved products and procedures", "Coordination with environmental services and infection prevention", "Containment removal sequence"],
 ["Products must be approved by the facility; outside chemicals are typically not allowed.", "Containment comes down only after cleaning and facility sign-off."],
 [("What is an infection control risk assessment?", "A healthcare planning tool that classifies construction work by risk and sets the dust control and cleaning measures required, often called an ICRA."),
  ("Who cleans a hospital after construction?", "Trained post-construction crews working with the hospital's environmental services department, which usually does or verifies the final terminal clean."),
  ("Why is hospital construction cleaning different from office cleaning?", "Patients may be highly vulnerable to airborne contaminants, so methods, products and sign-off follow infection control protocols."),
  ("Can any cleaning company clean a hospital construction area?", "No. Healthcare work is routed only to crews trained in healthcare construction protocols, and only after review.")]),
"Medical office post-construction clean": T(
 "A medical office post-construction clean prepares a new or renovated outpatient office, such as a primary care, specialty or imaging suite, for patient use, covering exam rooms, waiting areas, labs and restrooms.",
 "Medical offices see patients immediately after opening. Dust on exam room surfaces, cabinetry and equipment is unacceptable, and practices often move in quickly after turnover.",
 "Crews clean top down with HEPA vacuums and damp wiping, detail casework, exam room surfaces and sinks, and leave disinfection to the practice's protocols or registered-product services.",
 ["Exam room and procedure room count", "Medical equipment installed", "Practice move-in date", "Disinfection responsibility"],
 ["Do not clean inside medical equipment.", "Disinfection claims require registered products used per label."],
 [("Is a medical office cleaned differently from a regular office?", "Yes. Exam rooms, sinks, casework and waiting areas need detailed cleaning, and the practice usually follows with its own disinfection protocol."),
  ("Who disinfects a new medical office?", "The practice's cleaning provider or staff, using registered disinfectants according to the label."),
  ("When should a medical office be cleaned?", "After all trades and furniture installation, close to move-in."),
  ("Are exam room cabinets cleaned inside?", "Yes, cabinets and drawers are vacuumed and wiped.")]),
"Dental office post-construction clean": T(
 "A dental office post-construction clean prepares operatories, sterilization rooms, labs and reception areas after build-out, working around delivery units, chairs and cabinetry installed by dental equipment vendors.",
 "Dental offices have dense equipment, plumbing and cabinetry in every operatory. Construction dust in operatory cabinetry and equipment is unacceptable for patient care.",
 "Crews coordinate with the dental equipment installer, clean surfaces and cabinetry with HEPA and damp methods, and leave equipment internals and lines to the vendor.",
 ["Operatory count", "Dental equipment installer schedule", "Sterilization room", "Move-in date"],
 ["Do not clean inside dental equipment or waterlines.", "Chairs and delivery units have manufacturer care requirements."],
 [("Who cleans dental equipment after installation?", "The dental equipment vendor handles internals and waterlines; cleaning crews handle external surfaces and the room."),
  ("What is a dental operatory?", "A treatment room with a dental chair and equipment."),
  ("Are sterilization rooms cleaned?", "Yes, surfaces and cabinetry, before the practice sets up its sterilization process."),
  ("Do dental offices need special cleaning products?", "Practices often specify products compatible with their equipment.")]),
"Operating room post-construction clean": T(
 "An operating room post-construction clean is a specialized, protocol-driven clean of new or renovated operating rooms before air balancing verification, testing and clinical use.",
 "Operating rooms have the strictest environmental requirements in a hospital, and contamination can lead to surgical site infections.",
 "Only specialized healthcare crews are routed after review, working with the hospital's infection prevention and facilities teams.",
 ["Hospital protocols", "Air testing requirements", "Approved products", "Sign-off process"],
 ["Air and surface testing may be required before use.", "Only facility-approved products."],
 [("Who cleans operating rooms after construction?", "Specialized healthcare crews working with hospital teams."),
  ("Are operating rooms tested after cleaning?", "Often, through air and surface testing."),
  ("Why is OR cleaning so strict?", "To prevent surgical site infections."),
  ("Can a general cleaning crew clean an OR?", "No, it requires specialized training.")]),
"Laboratory post-construction clean": T(
 "A laboratory post-construction clean cleans new research or clinical labs, including casework, benches, fume hood exteriors and floors, following the lab's safety requirements.",
 "Labs may have chemical, biological or sensitive instrument requirements. Dust can affect experiments and equipment.",
 "Only reviewed crews clean labs under the safety officer's direction.",
 ["Lab type and safety requirements", "Surfaces and equipment", "Approved products", "Safety officer contact"],
 ["Do not touch lab equipment or chemicals.", "Follow lab safety rules."],
 [("Who approves lab cleaning?", "The lab's safety officer."),
  ("Are lab benches cleaned?", "Yes, with approved products."),
  ("Why is lab cleaning conditional?", "Because of chemical and biological hazards."),
  ("Are fume hoods cleaned inside?", "Interiors are cleaned only per lab procedures.")]),
"Fume hood exterior cleaning": T(
 "Fume hood exterior cleaning cleans the outside surfaces, sashes and work surface edges of laboratory fume hoods without disturbing airflow monitors or certification labels.",
 "Fume hoods are certified for airflow. Cleaning must not affect them.",
 "Crews clean exteriors and sashes carefully, leaving interiors and monitors alone unless the lab approves.",
 ["Hood count", "Sash material", "Monitors", "Certification labels"],
 ["Do not adjust sashes or monitors.", "Certification labels must stay."],
 [("What is a fume hood?", "A ventilated enclosure for working with hazardous chemicals."),
  ("Can cleaners clean inside fume hoods?", "Only per lab procedures."),
  ("Are fume hood sashes cleaned?", "Yes, carefully."),
  ("Why keep certification labels?", "They show the hood passed airflow testing.")]),
"Cleanroom protocol cleaning": T(
 "Cleanroom protocol cleaning cleans controlled environments to defined particle standards using specific garments, wipes, agents and sequences before certification.",
 "Cleanrooms must meet particle counts for certification. Improper cleaning causes failure.",
 "Only certified cleanroom cleaning specialists are routed after review.",
 ["Cleanroom class", "Protocol", "Garments and materials", "Certification"],
 ["Wrong materials add particles.", "Sequence matters."],
 [("What is a cleanroom?", "A room with controlled particle levels."),
  ("How are cleanrooms cleaned?", "With specific protocols and materials."),
  ("Who certifies cleanrooms?", "Independent certifiers."),
  ("Why is cleanroom cleaning specialized?", "Particle limits are strict.")]),
"Pharmacy compounding room cleaning": T(
 "Pharmacy compounding room cleaning cleans sterile and non-sterile compounding rooms to pharmacy standards before certification and use.",
 "Compounding rooms must meet strict standards for patient safety.",
 "Only qualified specialists are routed after review, following pharmacy procedures.",
 ["Room classification", "Procedures", "Agents", "Certification"],
 ["Only approved agents.", "Certification required."],
 [("What is a compounding room?", "A room where pharmacists prepare medications."),
  ("Are compounding rooms certified?", "Yes."),
  ("Who cleans compounding rooms?", "Qualified specialists."),
  ("Why is it conditional?", "Strict standards.")]),
"Data center post-construction cleaning": T(
 "Data center post-construction cleaning removes construction contamination from white space, subfloors, cabinets and support rooms before equipment is energized.",
 "Data center equipment is sensitive to dust and static. Contamination can cause failures.",
 "Only trained critical environment crews are routed after review.",
 ["White space", "Subfloors", "Cabinets", "Antistatic requirements"],
 ["Static discharge can damage equipment.", "Do not disturb cabling."],
 [("Why clean a data center after construction?", "Dust can damage equipment."),
  ("What is white space?", "The area where IT equipment sits."),
  ("Who cleans data centers?", "Trained critical environment crews."),
  ("Are subfloors cleaned?", "Yes.")]),
"Sub-floor plenum cleaning in data centers": T(
 "Sub-floor plenum cleaning in data centers cleans the space under raised floors, where cooling air flows to equipment.",
 "Dust under the floor is blown into equipment.",
 "Only trained crews clean subfloors with HEPA equipment.",
 ["Plenum area", "Panel lifting", "Cabling", "HEPA"],
 ["Do not lift too many panels.", "Avoid cabling."],
 [("Why clean under data center floors?", "Dust blows into equipment."),
  ("How are subfloors cleaned?", "With HEPA vacuums."),
  ("Who cleans subfloors?", "Trained crews."),
  ("Is it done before equipment?", "Ideally.")]),
"Server rack exterior cleaning": T(
 "Server rack exterior cleaning cleans the outside of server cabinets and racks with antistatic methods.",
 "Rack exteriors collect dust that can be drawn into equipment.",
 "Only trained crews clean racks with approval.",
 ["Rack count", "Approval", "Antistatic", "Equipment status"],
 ["Do not open racks.", "Avoid static."],
 [("Can cleaners clean server racks?", "Exteriors, with approval."),
  ("Why antistatic cleaning?", "Static can damage equipment."),
  ("Are racks opened?", "No."),
  ("Who approves rack cleaning?", "IT.")]),
"Controlled contamination cleaning": T(
 "Controlled contamination cleaning cleans environments with contamination limits, such as electronics manufacturing or aerospace assembly, following site protocols.",
 "These environments have strict contamination controls.",
 "Only specialists are routed after review.",
 ["Protocol", "Materials", "Training", "Verification"],
 ["Wrong materials cause contamination.", "Protocols must be followed."],
 [("What is controlled contamination cleaning?", "Cleaning to defined contamination limits."),
  ("Where is it used?", "Manufacturing and aerospace."),
  ("Who does it?", "Specialists."),
  ("Is verification required?", "Often.")]),
"Vivarium and animal facility cleaning": T(
 "Vivarium and animal facility cleaning cleans research animal facilities after construction, following facility and regulatory requirements.",
 "Animal facilities have strict health and regulatory requirements.",
 "Only specialists are routed after review.",
 ["Facility requirements", "Products", "Areas", "Approval"],
 ["Products must be approved.", "Regulatory requirements apply."],
 [("What is a vivarium?", "A facility for research animals."),
  ("Who cleans vivariums?", "Specialists."),
  ("Why is it conditional?", "Regulatory requirements."),
  ("Are products restricted?", "Yes.")]),
}
