def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"School post-construction cleaning": T(
 "School post-construction cleaning prepares new or renovated K-12 and campus buildings for students, covering classrooms, corridors, gyms, cafeterias, restrooms and offices before the first day of school.",
 "Schools open on fixed dates set by the academic calendar. Many identical rooms must reach the same standard, and students and staff arrive days after construction ends.",
 "Crews work room by room with consistent checklists, use low-odor products, and schedule gym and cafeteria cleaning around floor finishing and kitchen inspection.",
 ["Building size and room count", "First day of school and move-in dates", "Gym floor and kitchen schedules", "Background check requirements for crews"],
 ["Background checks may be required for anyone working on school grounds.", "Summer schedules are tight; book early."],
 [("When should a new school be cleaned?", "After trades finish and before furniture and staff move in, with a touch-up before students arrive."),
  ("Do school cleaning crews need background checks?", "Many districts require them for anyone working on school property."),
  ("Why use low-odor products in schools?", "Students and staff arrive soon after cleaning, and strong odors cause complaints."),
  ("Are school kitchens cleaned for inspection?", "Yes, cafeteria kitchens are cleaned to food service standards before health inspection.")]),
"Classroom turnover cleaning": T(
 "Classroom turnover cleaning cleans individual classrooms after construction or renovation, including boards, casework, windows, floors, desks and technology mounts, so teachers can set up.",
 "Teachers often have only a few days to set up rooms. A dusty classroom delays setup and starts the year poorly.",
 "Crews follow a classroom checklist, cleaning top down and detailing boards, casework and sinks before floors.",
 ["Classroom count", "Furniture status", "Technology installation", "Teacher move-in date"],
 ["Do not move technology equipment without permission.", "Whiteboards need manufacturer-approved cleaners."],
 [("What does classroom turnover cleaning include?", "Boards, casework, windows, floors, furniture and fixtures, cleaned top down."),
  ("How long does it take to clean a classroom after construction?", "Usually a few crew-hours per room, depending on dust and furniture."),
  ("Are interactive boards cleaned?", "Gently, with approved cleaners and never sprayed directly."),
  ("When can teachers move in?", "After turnover cleaning is complete and signed off.")]),
"Dormitory and student housing turnover": T(
 "Dormitory and student housing turnover cleans residence hall rooms, bathrooms, lounges and corridors after construction or summer renovations before students move in.",
 "Move-in day is fixed and students arrive by the hundreds. Rooms must be clean and consistent.",
 "Crews clean room by room with checklists and focus on bathrooms, closets and windows.",
 ["Room count", "Bathrooms", "Move-in date", "Furniture"],
 ["Schedules are compressed.", "Shared bathrooms need extra attention."],
 [("When are dorms cleaned?", "Before move-in, often during summer."),
  ("Are dorm bathrooms cleaned?", "Yes, they are a focus."),
  ("How long does dorm turnover take?", "It depends on the number of rooms."),
  ("Who sets the dorm cleaning standard?", "The housing department.")]),
"Hotel room post-construction cleaning": T(
 "Hotel room post-construction cleaning cleans guest rooms after new construction or property improvement plan renovations so they can return to inventory.",
 "Hotels lose revenue every night a room is out of service. Rooms must reach brand standards before returning to inventory.",
 "Crews clean floor by floor with brand checklists, detailing bathrooms, furniture, windows and HVAC units.",
 ["Room count and floors", "Brand standards", "Return-to-inventory schedule", "Furniture and fixtures"],
 ["Brand inspections can be strict.", "Housekeeping takes over after turnover."],
 [("What is a hotel PIP?", "A brand-required property improvement plan."),
  ("How are hotel rooms cleaned after renovation?", "Floor by floor with brand checklists."),
  ("Why is speed important?", "Rooms out of service lose revenue."),
  ("Who inspects hotel rooms?", "Hotel management and sometimes brand inspectors.")]),
"Hotel public area post-construction cleaning": T(
 "Hotel public area post-construction cleaning cleans lobbies, corridors, ballrooms, restaurants, fitness areas and pools after construction.",
 "Public areas set guests' first impression.",
 "Crews clean high-visibility areas with attention to finishes and lighting.",
 ["Areas", "Finishes", "Feature lighting", "Opening date"],
 ["Stone floors need special care.", "Chandeliers need specialists."],
 [("What are hotel public areas?", "Lobbies, corridors, ballrooms and amenities."),
  ("Are ballrooms cleaned?", "Yes."),
  ("Are hotel lobbies cleaned overnight?", "Often."),
  ("Who cleans chandeliers?", "Specialists.")]),
"Fitness center post-construction cleaning": T(
 "Fitness center post-construction cleaning cleans gyms and fitness rooms, including rubber floors, mirrors, equipment exteriors and locker rooms.",
 "Fitness centers have many mirrors, equipment and floors that show dust.",
 "Crews clean equipment exteriors, mirrors, floors and locker rooms.",
 ["Equipment", "Floors", "Mirrors", "Locker rooms"],
 ["Do not move heavy equipment.", "Rubber floors need approved cleaners."],
 [("Are gym mirrors cleaned?", "Yes."),
  ("Is gym equipment cleaned?", "Exteriors."),
  ("How are rubber gym floors cleaned?", "With approved cleaners."),
  ("Are locker rooms cleaned?", "Yes.")]),
"Pool deck and natatorium cleaning": T(
 "Pool deck and natatorium cleaning cleans pool decks, natatorium surfaces and equipment areas after construction, before the pool is filled or opened.",
 "Construction debris in pools and drains causes problems. Decks must be slip-resistant.",
 "Crews clean decks and surfaces and coordinate with pool contractors.",
 ["Deck area", "Pool status", "Drains", "Pool contractor"],
 ["Do not let debris enter pool.", "Slippery surfaces."],
 [("Is the pool itself cleaned by cleaners?", "Pool contractors handle the pool."),
  ("Are pool decks cleaned?", "Yes."),
  ("What is a natatorium?", "An indoor pool building."),
  ("Why clean pool drains?", "Debris causes problems.")]),
"Church and worship space post-construction cleaning": T(
 "Church and worship space post-construction cleaning cleans sanctuaries, pews, altars, fellowship halls and classrooms after construction.",
 "Worship spaces have high ceilings, wood pews and feature elements that need care.",
 "Crews clean high areas, pews and finishes with appropriate methods.",
 ["Sanctuary", "Pews", "High ceilings", "Fellowship hall"],
 ["Wood finishes need care.", "Stained glass needs specialists."],
 [("How are church pews cleaned?", "With wood-safe cleaners."),
  ("Are sanctuary ceilings cleaned?", "Yes, with lifts."),
  ("Who cleans stained glass?", "Specialists."),
  ("Is the fellowship hall cleaned?", "Yes.")]),
"Theater and auditorium post-construction cleaning": T(
 "Theater and auditorium post-construction cleaning cleans seating, stages, aisles and lobbies after construction.",
 "Theaters have many seats, high ceilings and stage equipment.",
 "Crews clean seating row by row and coordinate with stage contractors.",
 ["Seating", "Stage", "Lobby", "Ceiling"],
 ["Stage rigging is not touched.", "Seats have mechanisms."],
 [("Are theater stages cleaned?", "Floors, with care."),
  ("Who handles stage rigging?", "Stage contractors."),
  ("Are theater seats cleaned?", "Yes."),
  ("Is the lobby cleaned?", "Yes.")]),
"Arena and stadium post-construction cleaning": T(
 "Arena and stadium post-construction cleaning cleans seating bowls, concourses, suites, locker rooms and concessions in large venues.",
 "Venues are huge and open on fixed event dates.",
 "Specialist crews with large teams and equipment are routed.",
 ["Venue size", "Event date", "Seating", "Concessions"],
 ["Scale requires large teams.", "Concessions need food-safe cleaning."],
 [("How are stadiums cleaned after construction?", "With large crews."),
  ("Are suites cleaned?", "Yes."),
  ("Is seating cleaned?", "Yes."),
  ("Are concessions cleaned?", "Yes.")]),
"Library stack and shelving cleaning": T(
 "Library stack and shelving cleaning cleans library shelving and stacks before books are shelved.",
 "Dust on shelves damages books.",
 "Crews vacuum and wipe shelving before collections move in.",
 ["Shelving", "Collection move date", "Areas", "Furniture"],
 ["Do not clean after books are shelved without approval.", "Shelving can be tall."],
 [("Why clean library shelves?", "Dust damages books."),
  ("When are shelves cleaned?", "Before books move in."),
  ("Are reading rooms cleaned?", "Yes."),
  ("Who moves library collections?", "Library movers.")]),
}
