def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Warehouse post-construction cleaning": T(
 "Warehouse post-construction cleaning prepares new distribution centers and warehouses for tenants: overhead dusting, slab scrubbing, dock areas, offices, restrooms and exterior truck courts.",
 "Warehouse tenants move in fast, and racking installers and operations need a clean slab. Overhead dust and slab debris become product contamination and safety issues later.",
 "Crews clean top down: overhead first from lifts, then sweep and ride-on scrub the slab in lanes, then detail docks, offices and restrooms.",
 ["Building square footage and clear height", "Racking installation schedule", "Office and restroom areas", "Dock count and truck court"],
 ["Clean overhead before racking goes in.", "Wet slabs are slippery for lifts."],
 [("What is included in warehouse post-construction cleaning?", "Overhead dusting, slab sweeping and scrubbing, dock cleaning, office and restroom detailing and exterior sweeping."),
  ("How long does it take to clean a new warehouse?", "It depends on size; large distribution centers can take several days with multiple machines."),
  ("Should the warehouse be cleaned before racking?", "Yes. Empty buildings are far faster and easier to clean."),
  ("Who cleans warehouse truck courts?", "The cleaning contractor with power sweepers.")]),
"Pallet rack cleaning": T(
 "Pallet rack cleaning removes dust and debris from racking uprights, beams, decking and tops in warehouses and stores.",
 "Rack tops collect dust that falls onto stored product. Food and pharmaceutical warehouses are audited for it.",
 "Crews clean from lifts top down, vacuuming rack tops and wiping beams, with product covered.",
 ["Rack length and height", "Loaded or empty", "Product protection", "Lift access"],
 ["Never climb racking.", "Loaded racks need product protection."],
 [("How is pallet racking cleaned?", "From lifts, vacuuming tops and wiping beams."),
  ("Can workers climb racking to clean?", "No, use lifts."),
  ("Why clean rack tops?", "Dust falls onto product."),
  ("Is rack cleaning part of high dusting?", "Often.")]),
"Industrial equipment exterior cleaning": T(
 "Industrial equipment exterior cleaning cleans the outside of production machines and equipment after installation, with the owner's approval.",
 "New equipment is dusty after construction and must be clean for startup.",
 "Crews clean exteriors under lockout and owner direction.",
 ["Equipment list", "Lockout", "Approval", "Methods"],
 ["Lockout is required.", "Do not touch controls."],
 [("Is lockout required to clean equipment?", "Yes."),
  ("Who approves equipment cleaning?", "The owner."),
  ("Are controls cleaned?", "Exteriors only."),
  ("Why clean equipment before startup?", "Dust affects operation.")]),
"Conveyor system exterior cleaning": T(
 "Conveyor system exterior cleaning cleans conveyor frames, guards and supports after installation.",
 "Conveyors collect dust and debris that can enter products.",
 "Crews clean under lockout.",
 ["Conveyor length", "Lockout", "Guards", "Debris"],
 ["Lockout required.", "Do not remove guards."],
 [("Are conveyors cleaned after installation?", "Yes."),
  ("Is lockout required?", "Yes."),
  ("Are guards removed?", "No."),
  ("Who services conveyors?", "Vendors.")]),
"Manufacturing plant post-construction cleaning": T(
 "Manufacturing plant post-construction cleaning prepares production areas for startup.",
 "Plants must be clean for safety and product quality.",
 "Specialist crews clean under plant procedures.",
 ["Areas", "Procedures", "Equipment", "Startup"],
 ["Plant procedures apply.", "Lockout required."],
 [("Who cleans manufacturing plants?", "Specialist crews."),
  ("Are plant procedures followed?", "Yes."),
  ("Is overhead cleaning included?", "Often."),
  ("When is cleaning done?", "Before startup.")]),
"Cold storage facility cleaning": T(
 "Cold storage facility cleaning cleans cold warehouses before they are cooled.",
 "Once cold, cleaning is hard and moisture freezes.",
 "Crews clean before pull-down with minimal water.",
 ["Facility size", "Pull-down date", "Floors", "Racking"],
 ["Water freezes.", "Cold work requires PPE."],
 [("Why clean before cooling?", "Moisture freezes."),
  ("Is water used?", "Minimally."),
  ("Are racks cleaned?", "Yes."),
  ("What is pull-down?", "Cooling the facility.")]),
"Truck court and dock apron sweeping": T(
 "Truck court and dock apron sweeping clears debris from truck courts and dock aprons with power sweepers.",
 "Debris damages tires and blows into docks.",
 "Crews power sweep and pick up debris.",
 ["Area", "Debris", "Equipment", "Timing"],
 ["Traffic must be controlled.", "Drains protected."],
 [("What is a truck court?", "The paved area for trucks."),
  ("How is it cleaned?", "Power sweeping."),
  ("Why sweep truck courts?", "Debris damages tires."),
  ("When is it done?", "Before turnover.")]),
}
