def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Sidewalk pressure washing": T(
 "Sidewalk pressure washing removes construction mud, concrete slurry, paint, rust and grime from new sidewalks and walkways before turnover, with wash water collected rather than sent to storm drains.",
 "Sidewalks are the first surface every visitor walks on. Mud and slurry stains also track straight into the new building.",
 "Crews sweep first, pre-treat stains, use surface cleaners at pressures safe for new concrete, and recover or contain wash water.",
 ["Square footage of walks", "Concrete age and finish", "Stains present", "Storm drain protection"],
 ["High pressure on young concrete can etch the surface.", "Wash water must not enter storm drains."],
 [("When can new concrete be pressure washed?", "After it has cured enough; very young concrete can be etched by high pressure, so follow the concrete contractor's guidance."),
  ("Can pressure washing water go into storm drains?", "Generally no. Wash water should be recovered or contained."),
  ("What is a surface cleaner?", "A rotating pressure washing attachment that cleans flat concrete evenly without stripes."),
  ("Is sidewalk cleaning part of final clean?", "Yes, exterior walks are usually cleaned before the owner walk.")]),
"Parking lot sweeping": T(
 "Parking lot sweeping removes construction dirt, gravel, debris and litter from new parking lots and drives with power sweepers.",
 "Lots collect construction debris that damages tires, clogs drains and makes a new property look unfinished. It is also required before striping.",
 "Crews power sweep the lot in passes, hand-sweep corners and islands and clear debris from drain inlets.",
 ["Lot size", "Striping schedule", "Drain inlets", "Night or day work"],
 ["Sweepers must not enter active traffic without control.", "Fresh asphalt seal coat needs cure time."],
 [("Why sweep a parking lot before striping?", "Paint does not stick to dirt and debris."),
  ("How often should parking lots be swept during construction?", "As needed, often weekly near completion."),
  ("Who sweeps parking lots?", "Power sweeping contractors."),
  ("Are drain inlets cleaned?", "Debris is cleared from grates.")]),
"Parking lot washing": T(
 "Parking lot washing cleans paved lots of stains, oil and grime using water recovery equipment, usually as a finishing step after sweeping.",
 "Oil and concrete stains on new pavement look neglected.",
 "Crews use recovery equipment to keep water out of storm drains.",
 ["Lot area", "Stains", "Water recovery", "Drains"],
 ["Wash water must be recovered.", "Pavement coatings can be damaged."],
 [("Is parking lot washing different from sweeping?", "Yes, it uses water to remove stains."),
  ("Is wash water recovered?", "It should be."),
  ("Can oil stains be removed?", "Often."),
  ("When is lot washing done?", "Before turnover.")]),
"Loading dock washing": T(
 "Loading dock washing cleans dock aprons, bumpers, levelers' exteriors and walls with pressure washing and water recovery.",
 "Docks collect oil, debris and grime.",
 "Crews wash with recovery and protect drains.",
 ["Dock count", "Levelers", "Drains", "Water recovery"],
 ["Dock edges are fall hazards.", "Drains protected."],
 [("How are loading docks washed?", "Pressure washing with recovery."),
  ("Are dock levelers cleaned?", "Exteriors."),
  ("Are dock drains protected?", "Yes."),
  ("Why wash docks?", "Grime and oil.")]),
"Dumpster pad degreasing": T(
 "Dumpster pad degreasing cleans grease, food waste and stains from dumpster and compactor pads.",
 "Dumpster pads smell and attract pests.",
 "Crews degrease and wash with recovery.",
 ["Pad size", "Grease", "Drains", "Recovery"],
 ["Grease wash water must be recovered.", "Pests."],
 [("Why degrease dumpster pads?", "Odor and pests."),
  ("Is wash water recovered?", "Yes."),
  ("How often?", "At turnover and periodically."),
  ("Are enclosures cleaned?", "Yes.")]),
"Building facade washing": T(
 "Building facade washing cleans exterior walls of construction dust, overspray and grime, using methods matched to each cladding material.",
 "The facade is the building's face; construction leaves it streaked and dusty.",
 "Crews choose soft wash or low pressure for each material.",
 ["Facade materials", "Height", "Access", "Water recovery"],
 ["High pressure damages some claddings.", "Fall protection required."],
 [("How is a building facade cleaned?", "With methods matched to the material."),
  ("Can high pressure damage facades?", "Yes."),
  ("Who cleans facades?", "Specialists."),
  ("Is water recovered?", "Often.")]),
"Exterior soft washing": T(
 "Exterior soft washing cleans building exteriors with low pressure and cleaning solutions.",
 "High pressure damages stucco, EIFS and paint.",
 "Crews apply solutions and rinse at low pressure.",
 ["Surfaces", "Solutions", "Plants", "Runoff"],
 ["Solutions can harm plants.", "Runoff control."],
 [("What is soft washing?", "Low-pressure washing with solutions."),
  ("Why soft wash?", "To avoid damage."),
  ("Are plants protected?", "Yes."),
  ("Which surfaces need soft washing?", "Stucco, EIFS, paint.")]),
"Brick and masonry cleaning": T(
 "Brick and masonry cleaning removes mortar smears, stains and residue from new brick and block.",
 "Mortar stains look unfinished.",
 "Crews use masonry cleaners suited to the brick.",
 ["Brick type", "Cleaner", "Testing", "Rinse"],
 ["Wrong acids stain brick.", "Pre-wetting is required."],
 [("How is mortar removed from brick?", "With masonry cleaners."),
  ("Can acid stain brick?", "Yes."),
  ("Is testing needed?", "Yes."),
  ("Who cleans new brick?", "Masonry cleaning specialists.")]),
"Masonry efflorescence removal": T(
 "Masonry efflorescence removal cleans white salt deposits from brick and block walls.",
 "Efflorescence looks bad and signals moisture.",
 "Crews dry-brush then use cleaners.",
 ["Area", "Moisture", "Cleaner", "Testing"],
 ["It can return.", "Acids stain."],
 [("What causes efflorescence on brick?", "Salts carried by water."),
  ("Can it be removed?", "Yes."),
  ("Will it return?", "Possibly."),
  ("Is it harmful?", "Mostly cosmetic.")]),
"Stucco and EIFS cleaning": T(
 "Stucco and EIFS cleaning cleans synthetic and traditional stucco with low pressure and gentle solutions.",
 "High pressure damages EIFS.",
 "Crews soft wash.",
 ["Area", "Material", "Height", "Solutions"],
 ["High pressure damages EIFS.", "Water intrusion."],
 [("Can EIFS be pressure washed?", "Low pressure only."),
  ("What is EIFS?", "Synthetic stucco system."),
  ("How is stucco cleaned?", "Soft wash."),
  ("Who cleans EIFS?", "Specialists.")]),
"Metal panel and canopy cleaning": T(
 "Metal panel and canopy cleaning cleans exterior metal panels and canopies, removing film, dust and residue.",
 "Metal panels show streaks and residue.",
 "Crews remove film and wash.",
 ["Area", "Film", "Height", "Finish"],
 ["Abrasives scratch.", "Film bakes on."],
 [("How are metal canopies cleaned?", "Washing with mild cleaners."),
  ("Is film removed?", "Yes."),
  ("Can abrasives be used?", "No."),
  ("Who cleans canopies?", "Cleaning crews.")]),
"Paver and hardscape cleaning": T(
 "Paver and hardscape cleaning removes construction stains, mud and residue from pavers and hardscape.",
 "Hardscape is highly visible.",
 "Crews wash and treat stains.",
 ["Area", "Stains", "Joint sand", "Sealer"],
 ["Pressure displaces joint sand.", "Sealer damage."],
 [("How are pavers cleaned?", "Washing and stain treatment."),
  ("Does washing remove joint sand?", "It can."),
  ("Are pavers sealed?", "Sometimes."),
  ("Who cleans hardscape?", "Cleaning crews.")]),
"Paver joint sand cleanup": T(
 "Paver joint sand cleanup sweeps excess joint sand from paver surfaces after installation.",
 "Loose sand is tracked inside.",
 "Crews sweep and blow sand into joints or remove it.",
 ["Area", "Sand", "Sweeping", "Timing"],
 ["Sand scratches floors inside.", "Polymeric sand needs care."],
 [("Why clean paver sand?", "It is tracked inside."),
  ("What is polymeric sand?", "Sand that hardens."),
  ("Is sand swept into joints?", "Often."),
  ("When?", "After installation.")]),
"Entryway and vestibule cleaning": T(
 "Entryway and vestibule cleaning cleans building entrances, vestibules, doors and mats.",
 "Entrances are the first impression.",
 "Crews clean glass, floors and mats.",
 ["Entrances", "Glass", "Floors", "Mats"],
 ["High traffic.", "Mats need cleaning."],
 [("Why focus on entrances?", "First impression."),
  ("Are vestibules cleaned?", "Yes."),
  ("Are mats cleaned?", "Yes."),
  ("Is glass cleaned?", "Yes.")]),
"Exterior signage and monument sign cleaning": T(
 "Exterior signage and monument sign cleaning cleans building signs and monument signs.",
 "Signs identify the property.",
 "Crews clean with appropriate methods.",
 ["Signs", "Materials", "Lighting", "Height"],
 ["Electrical components.", "Finish damage."],
 [("Are monument signs cleaned?", "Yes."),
  ("Are illuminated signs cleaned?", "Exteriors."),
  ("Who cleans signs?", "Cleaning crews."),
  ("Why clean signs?", "Visibility.")]),
"Exterior light fixture and pole base cleaning": T(
 "Exterior light fixture and pole base cleaning cleans site lights and pole bases.",
 "Pole bases collect concrete and dirt.",
 "Crews clean bases and fixtures.",
 ["Pole count", "Bases", "Fixtures", "Height"],
 ["Electrical.", "Height."],
 [("Are light pole bases cleaned?", "Yes."),
  ("Are fixtures cleaned?", "Yes."),
  ("Why?", "Appearance."),
  ("Who?", "Cleaning crews.")]),
"Site furniture and bike rack cleaning": T(
 "Site furniture and bike rack cleaning cleans benches, tables, bike racks and receptacles.",
 "Site furniture is used immediately.",
 "Crews clean and remove labels.",
 ["Furniture", "Labels", "Materials", "Count"],
 ["Finish damage.", "Labels."],
 [("Is site furniture cleaned?", "Yes."),
  ("Are labels removed?", "Yes."),
  ("Who cleans?", "Crews."),
  ("When?", "Before turnover.")]),
"Landscape bed debris removal": T(
 "Landscape bed debris removal picks construction debris out of landscape beds and planters.",
 "Debris in beds looks bad.",
 "Crews pick debris by hand.",
 ["Beds", "Debris", "Plants", "Mulch"],
 ["Do not damage plants.", "Sharp debris."],
 [("Why clean landscape beds?", "Debris looks bad."),
  ("Is mulch disturbed?", "Minimally."),
  ("Who?", "Crews."),
  ("When?", "Before turnover.")]),
"Storm drain inlet protection cleanup": T(
 "Storm drain inlet protection cleanup cleans and removes inlet protection at project end.",
 "Inlet protection collects sediment.",
 "Crews remove sediment and protection when approved.",
 ["Inlets", "Approval", "Sediment", "Disposal"],
 ["Remove only when approved.", "Sediment disposal."],
 [("What is inlet protection?", "Barriers keeping sediment out of drains."),
  ("When is it removed?", "When approved."),
  ("Who approves?", "GC and permit."),
  ("Is sediment removed?", "Yes.")]),
"Silt fence and erosion control debris cleanup": T(
 "Silt fence and erosion control debris cleanup removes silt fence and debris when the site is stabilized.",
 "Erosion controls must be removed at closeout.",
 "Crews remove fence and sediment when approved.",
 ["Fence length", "Approval", "Sediment", "Disposal"],
 ["Remove only when approved.", "Sediment."],
 [("When is silt fence removed?", "When the site is stabilized."),
  ("Who approves?", "Permit authority."),
  ("Is sediment removed?", "Yes."),
  ("Who removes it?", "Crews.")]),
"Curb and gutter cleaning": T(
 "Curb and gutter cleaning removes mud, debris and concrete from curbs and street gutters.",
 "Curbs show mud and debris.",
 "Crews sweep and wash with recovery.",
 ["Length", "Debris", "Drains", "Recovery"],
 ["Drains.", "Traffic."],
 [("Why clean curbs?", "Appearance."),
  ("Is water recovered?", "Yes."),
  ("Who?", "Crews."),
  ("When?", "Before turnover.")]),
"Wastewater recovery during washing": T(
 "Wastewater recovery during washing collects water from exterior washing with vacuums and berms.",
 "Storm water rules prohibit discharging wash water.",
 "Crews use recovery systems.",
 ["Equipment", "Disposal", "Drains", "Permit"],
 ["Discharge violations.", "Disposal rules."],
 [("Why recover wash water?", "Storm water rules."),
  ("How?", "Vacuums and berms."),
  ("Where does it go?", "Approved disposal."),
  ("Is it required?", "Often.")]),
"Graffiti removal": T(
 "Graffiti removal removes paint and markers from surfaces.",
 "Graffiti damages appearance.",
 "Crews use removers matched to surfaces.",
 ["Surfaces", "Paint type", "Removers", "Coatings"],
 ["Removers damage surfaces.", "Ghosting."],
 [("Can graffiti be removed?", "Usually."),
  ("Are anti-graffiti coatings available?", "Yes."),
  ("Who removes?", "Specialists."),
  ("Is fresh graffiti easier?", "Yes.")]),
"Roof debris removal": T(
 "Roof debris removal clears construction debris from roofs.",
 "Debris damages membranes and clogs drains.",
 "Crews remove debris with fall protection.",
 ["Roof area", "Fall protection", "Drains", "Membrane"],
 ["Falls.", "Punctures."],
 [("Why clean roofs?", "Debris damages them."),
  ("Is fall protection needed?", "Yes."),
  ("Are drains cleared?", "Yes."),
  ("Who?", "Crews.")]),
"Gutter and downspout debris removal": T(
 "Gutter and downspout debris removal clears debris from gutters and downspouts.",
 "Clogged gutters overflow.",
 "Crews clear by hand.",
 ["Length", "Access", "Debris", "Downspouts"],
 ["Ladders.", "Falls."],
 [("Why clean gutters?", "Overflow."),
  ("Who?", "Crews."),
  ("When?", "At turnover."),
  ("Are downspouts checked?", "Yes.")]),
"Balcony and terrace cleaning": T(
 "Balcony and terrace cleaning cleans outdoor balconies, terraces and railings.",
 "Balconies show debris and stains.",
 "Crews clean floors, rails and glass.",
 ["Count", "Rails", "Glass", "Drains"],
 ["Falls.", "Drains."],
 [("Are balconies cleaned?", "Yes."),
  ("Are rails cleaned?", "Yes."),
  ("Are drains cleared?", "Yes."),
  ("Who?", "Crews.")]),
"Solar array cleaning": T(
 "Solar array cleaning cleans solar panels following the manufacturer's guidance and electrical safety rules.",
 "Dust reduces output.",
 "Only qualified crews are routed after review.",
 ["Array size", "Access", "Manufacturer", "Electrical"],
 ["Electrical hazards.", "Panel damage."],
 [("Can solar panels be cleaned?", "Yes, per manufacturer."),
  ("Why conditional?", "Electrical hazards."),
  ("Does dust reduce output?", "Yes."),
  ("Who cleans?", "Qualified crews.")]),
}
