def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Paint overspray removal": T(
 "Paint overspray removal takes fine mist of paint, primer or coating off surfaces it was never meant to land on, such as glass, floors, fixtures, hardware and trim, at final clean.",
 "Overspray is on nearly every punch list. It is often invisible until light hits it, and aggressive removal can damage the surface underneath more than the paint itself.",
 "Crews identify the paint and the surface, then work least-aggressive first: plastic blades and mild removers on hard surfaces, lubricated razor work on suitable glass, and specialty products only after testing.",
 ["Surfaces affected and their materials", "Paint type: latex, oil, epoxy or texture", "Remover testing location", "Who is responsible: painter or cleaner"],
 ["Solvents can soften plastics, powder coat and fresh paint nearby.", "Overspray on textured surfaces may need the painter to correct it."],
 [("How do you remove paint overspray from windows?", "On suitable glass, with a sharp, lubricated blade held flat and fresh water, after confirming the glass type allows scraping."),
  ("How do you know if a surface has overspray?", "Run a clean hand or a plastic bag over it or look in raking light. Overspray feels gritty and shows as a dull haze."),
  ("Who is responsible for paint overspray?", "Usually the painting contractor under their protection obligations, though GCs often have the cleaning crew remove it and back-charge."),
  ("Can overspray be removed from car finishes in a parking area?", "Vehicle overspray is a specialty auto detailing job and should not be attempted with construction cleaning methods.")]),
"Paint drip and splatter removal": T(
 "Paint drip and splatter removal takes larger dried drops and splatters of paint off floors, counters, fixtures, glass and hardware.",
 "Drips are thicker than overspray and bond firmly once dry. They show on every type of finish and are among the most common punch list items.",
 "Crews soften drips where safe, lift them with plastic scrapers, and use paint removers suited to both the paint and the surface, rinsing any residue.",
 ["Drip locations and surfaces", "Paint type", "Remover compatibility", "Touch-up needs"],
 ["Metal scrapers gouge soft finishes.", "Removers can dull glossy surfaces."],
 [("How do you remove dried latex paint drips from a hard floor?", "Soften with warm water or a latex remover, lift with a plastic scraper and clean the residue."),
  ("Can paint drips be removed from carpet?", "Often, especially latex, if treated with the right spotter before fully cured."),
  ("Are paint drips on countertops a problem?", "They can be removed with care, but stone and quartz need compatible products."),
  ("How do you prevent paint drips?", "With drop cloths, floor protection and careful painting.")]),
"Adhesive residue removal": T(
 "Adhesive residue removal takes sticky residue from tape, labels, protection films, mastic and glues off finished surfaces without damaging them.",
 "Adhesive residue attracts dirt and becomes a dark, sticky spot. It shows up on glass, counters, floors, appliances and walls throughout a building.",
 "Crews start with gentle citrus or plant-based removers and plastic tools, test on hidden areas and clean off remover residue completely.",
 ["Adhesive type", "Surfaces", "Remover testing", "Residue cleanup"],
 ["Solvents can damage plastics and coatings.", "Remover residue left behind attracts dirt."],
 [("What removes sticky residue without damaging surfaces?", "Mild citrus or plant-based removers and plastic tools, tested first."),
  ("Why does adhesive residue turn black?", "It traps dirt and dust."),
  ("Can heat help remove adhesive?", "Gentle warming softens many adhesives."),
  ("Is adhesive removal part of final clean?", "Yes, it is a common final clean task.")]),
"Tape residue removal": T(
 "Tape residue removal cleans the adhesive left by painter's tape, duct tape, carpet tape and masking tape used during construction.",
 "Tape left on too long, especially in heat or sunlight, leaves residue that is hard to remove and can pull paint when peeled.",
 "Crews peel tape slowly at a low angle, then remove residue with gentle removers safe for the surface.",
 ["Tape locations", "Duration tape was in place", "Surfaces", "Removers"],
 ["Fast peeling can pull paint.", "Duct tape residue is especially stubborn."],
 [("Why does painter's tape leave residue?", "Left too long or in sun, its adhesive bonds to the surface."),
  ("How should tape be removed?", "Slowly at a low angle."),
  ("Can tape pull paint off walls?", "Yes, especially if paint is fresh or tape is old."),
  ("How is duct tape residue removed?", "With adhesive removers tested on the surface.")]),
"Stucco and plaster splatter removal": T(
 "Stucco and plaster splatter removal takes hardened stucco, plaster and texture splatter off windows, frames, floors and exterior surfaces.",
 "Stucco and plaster bond to glass and metal and can scratch surfaces if scraped dry.",
 "Crews soak splatter to soften it, remove it carefully with plastic or lubricated tools, and rinse thoroughly.",
 ["Surfaces affected", "Extent", "Glass type", "Rinse plan"],
 ["Dry scraping scratches glass.", "Acidic removers etch glass and metal."],
 [("How do you remove stucco from windows?", "Soak to soften and remove carefully with lubricated tools."),
  ("Can stucco scratch glass?", "Yes, if dragged across it."),
  ("Who removes stucco splatter?", "The stucco contractor or cleaning crew."),
  ("Is plaster easier to remove than stucco?", "Often, because it softens with water.")]),
"Concrete and mortar splatter removal": T(
 "Concrete and mortar splatter removal takes hardened cement-based splatter off floors, walls, frames, fixtures and hardscape throughout a project.",
 "Cement splatter bonds tightly and is alkaline. Acidic removers that dissolve it can also damage stone, metal and glass.",
 "Crews remove by soaking and mechanical methods first, using cement removers only after testing and protecting nearby surfaces.",
 ["Surfaces and extent", "Remover testing", "Protection", "Rinse"],
 ["Acids damage many finishes.", "Thorough rinsing is essential."],
 [("How do you remove cement splatter?", "Soak, scrape carefully and use tested removers."),
  ("Can concrete removers damage surfaces?", "Yes, many are acidic."),
  ("Is mortar the same as concrete?", "Both are cement-based."),
  ("Who removes mortar splatter?", "The mason or cleaning crew.")]),
}
