def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Spray foam overspray removal": T(
 "Spray foam overspray removal takes cured or partly cured polyurethane spray foam off framing, windows, floors and fixtures near insulated areas.",
 "Spray foam bonds aggressively and is hard to remove once cured. Overspray on windows, equipment or finishes is a common problem near foam installations.",
 "Crews remove cured foam mechanically with plastic tools, use foam-specific removers on uncured residue, and test any product on the finish first.",
 ["Surfaces affected", "Foam cure state", "Removers", "Ventilation"],
 ["Solvents for foam can damage finishes and plastics.", "Uncured foam requires PPE and ventilation."],
 [("Can cured spray foam be removed from windows?", "Usually by careful mechanical removal; cured foam does not dissolve easily."),
  ("Why is spray foam hard to remove?", "It bonds strongly and cures quickly."),
  ("Who is responsible for foam overspray?", "Typically the insulation contractor."),
  ("Is PPE needed?", "Yes, especially around uncured foam.")]),
"Fireproofing overspray removal": T(
 "Fireproofing overspray removal takes spray-applied fire-resistive material off surfaces where it was not intended, such as ducts, conduit, glass or adjacent finishes, without damaging the fireproofing that is required.",
 "Fireproofing is a life-safety material, and removing it from the wrong place can damage it where it is needed. Older material may contain asbestos.",
 "Requests are reviewed and routed only to qualified providers with the GC and fireproofing contractor's approval.",
 ["Material type and testing", "Surfaces affected", "GC and fireproofing contractor approval", "Repair procedure"],
 ["Do not damage required fireproofing.", "Suspect older material must be tested before disturbance."],
 [("Can fireproofing overspray be removed?", "Yes, from surfaces where it does not belong, by qualified crews with approval."),
  ("Why is fireproofing removal conditional?", "It is a life-safety material and older material may contain asbestos."),
  ("Who repairs damaged fireproofing?", "The fireproofing contractor."),
  ("Is fireproofing dust hazardous?", "It should be handled with dust controls.")]),
"Joint compound film removal": T(
 "Joint compound film removal takes the thin white film of drywall mud off floors, frames, glass and finishes where it was smeared or splashed.",
 "Mud film looks chalky and spreads into a haze if wiped wet.",
 "Crews dry-remove and vacuum first, then use clean water and microfiber in small passes.",
 ["Surfaces", "Extent", "Method", "Rinse"],
 ["Wet wiping spreads the film.", "Changing water often is critical."],
 [("How do you remove drywall mud film?", "Dry-remove and vacuum, then wipe with clean water and microfiber."),
  ("Why does mud film come back after cleaning?", "Dirty water redeposits it."),
  ("Is joint compound film a punch item?", "Yes."),
  ("Who removes mud film?", "The drywall contractor or cleaning crew.")]),
"Pencil, marker and layout line removal": T(
 "Pencil, marker and layout line removal cleans layout marks, chalk lines, pencil notes and marker from finishes that will remain exposed.",
 "Trades mark measurements and notes on walls, floors and ceilings. On exposed concrete, paint and stone they remain visible.",
 "Crews use erasers, mild cleaners and marker removers suited to the surface, testing first.",
 ["Surfaces", "Mark types", "Removers", "Exposed concrete"],
 ["Permanent marker can bleed through paint.", "Solvents damage some finishes."],
 [("How do you remove permanent marker from concrete?", "With marker removers suited to concrete, tested first."),
  ("Can chalk lines be removed?", "Usually with dry brushing and mild cleaners."),
  ("Do layout marks bleed through paint?", "Permanent marker can."),
  ("Who removes layout marks?", "The cleaning crew or responsible trade.")]),
"Label, sticker and UPC removal": T(
 "Label, sticker and UPC removal takes manufacturer labels, barcodes and shipping stickers off fixtures, doors, equipment, glass and appliances throughout a building.",
 "Labels are on almost everything delivered to a jobsite. Every one left behind looks unfinished and is likely to appear on the punch list.",
 "Crews peel labels and remove adhesive with surface-safe products, leaving required ratings, nameplates and warning labels in place.",
 ["Locations", "Labels to keep", "Adhesive types", "Surfaces"],
 ["Do not remove required safety, fire rating or equipment labels.", "Blades scratch soft surfaces."],
 [("Which labels should not be removed?", "Fire ratings, nameplates, warning labels and inspection tags."),
  ("How is sticker residue removed?", "With surface-safe adhesive removers."),
  ("Are labels a common punch item?", "Yes, very common."),
  ("Who removes labels?", "The cleaning crew at final clean.")]),
"Protective film removal from appliances and fixtures": T(
 "Protective film removal from appliances and fixtures peels the plastic film off stainless, glass, plastic and painted surfaces of appliances, fixtures and equipment.",
 "Film protects finishes during construction but bakes on in heat and sun and leaves residue.",
 "Crews peel film slowly and remove residue with surface-safe products.",
 ["Items with film", "Age and exposure", "Residue", "Surfaces"],
 ["Old film leaves residue.", "Blades scratch."],
 [("When should film be removed from appliances?", "At final clean, before heat bakes it on."),
  ("Does film leave residue?", "Often, if left too long."),
  ("How is film residue removed?", "With surface-safe removers."),
  ("Who removes appliance film?", "The cleaning crew.")]),
}
