def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Rust stain removal from finishes": T(
 "Rust stain removal from finishes takes orange rust marks off tile, stone, fixtures, counters and painted surfaces, often left by steel tools, cans or fasteners set down during construction.",
 "Rust stains are common near metal tools and materials and look like damage to new finishes. Many rust removers are acidic and can etch stone or dull finishes.",
 "Crews identify the surface, test rust removers made for that material, use poultices on porous stone, and rinse thoroughly.",
 ["Stain locations and surfaces", "Remover compatibility", "Testing", "Stone or porous surfaces"],
 ["Acids etch marble and limestone.", "Some deep stains in stone may be permanent."],
 [("What causes rust stains on new finishes?", "Steel tools, cans, fasteners or metal debris left on wet surfaces."),
  ("Can rust be removed from marble?", "Sometimes, with stone-safe poultices; acids will etch it."),
  ("What is a rust poultice?", "A paste that draws rust out of porous materials."),
  ("Who removes rust stains?", "Cleaning crews or stone specialists for delicate stone.")]),
"Water spot and mineral deposit removal": T(
 "Water spot and mineral deposit removal cleans hard water spots, mineral rings and scale from fixtures, glass, stainless and counters.",
 "Water spots appear as soon as fixtures are tested and look dirty.",
 "Crews use non-acidic or mild descalers suited to each surface and dry thoroughly.",
 ["Surfaces", "Severity", "Descaler compatibility", "Drying"],
 ["Acids damage stone and some metals.", "Spots return if surfaces are left wet."],
 [("How do you remove water spots from fixtures?", "With mild descalers suited to the finish, then dry."),
  ("Why do water spots appear?", "Minerals left after water evaporates."),
  ("Can vinegar remove water spots?", "Sometimes, but it can damage stone and some finishes."),
  ("How are water spots prevented?", "Dry surfaces after cleaning.")]),
"Tar and roofing material removal": T(
 "Tar and roofing material removal cleans asphalt, roofing cement, sealants and tar from walls, walkways, windows and fixtures near roofing work.",
 "Tar tracks onto walkways and stains surfaces. Removers can damage finishes if used incorrectly.",
 "Crews remove bulk material mechanically and use tar removers tested on the surface.",
 ["Surfaces", "Material type", "Removers", "Protection"],
 ["Solvents damage some finishes.", "Tar can be tracked inside."],
 [("How is roofing tar removed from concrete?", "Mechanical removal, then tar removers."),
  ("Can tar be removed from windows?", "Usually, carefully."),
  ("Is tar tracked inside?", "Often, on shoes."),
  ("Who removes tar?", "The roofer or cleaning crew.")]),
"Floor protection installation": T(
 "Floor protection installation lays temporary board, film or sheeting over finished floors to protect them during the rest of construction.",
 "Finished floors are damaged by tools, lifts, debris and traffic. Protection prevents costly repairs.",
 "Crews clean the floor first, then install protection with tape at seams and edges, avoiding tape on finishes that it could damage.",
 ["Floor types and areas", "Protection material", "Tape type", "Traffic expected"],
 ["Debris under protection scratches floors.", "Some tapes damage finishes."],
 [("Why clean floors before installing protection?", "Debris under protection scratches floors."),
  ("What floor protection is used?", "Board, film or sheeting."),
  ("Does floor protection damage floors?", "Wrong tape or trapped moisture can."),
  ("Who installs floor protection?", "The GC, flooring contractor or cleaning crew.")]),
"Floor protection removal and disposal": T(
 "Floor protection removal and disposal takes up temporary floor protection at the end of the project and captures the dust trapped beneath it.",
 "Protection holds dust and debris. Removing it carelessly releases dust into clean areas.",
 "Crews vacuum protection surfaces, roll or fold them inward, dispose of them and then clean the floor.",
 ["Protection type and area", "Disposal", "Floor cleaning after", "Timing"],
 ["Dust trapped under protection spreads.", "Tape residue needs removal."],
 [("When is floor protection removed?", "Near final clean."),
  ("What happens to dust under protection?", "It must be captured."),
  ("Is floor protection recycled?", "Sometimes."),
  ("Who removes floor protection?", "The cleaning crew or GC.")]),
"Adhesive under floor protection cleanup": T(
 "Adhesive under floor protection cleanup removes tape and adhesive residue left on floors after protection is removed.",
 "Tape residue on floors attracts dirt.",
 "Crews remove residue with floor-safe removers.",
 ["Floor types", "Tape", "Removers", "Area"],
 ["Solvents damage floors.", "Residue attracts dirt."],
 [("Does floor protection tape leave residue?", "Often."),
  ("How is it removed?", "With floor-safe removers."),
  ("Can removers damage floors?", "Some can."),
  ("Who cleans tape residue?", "The cleaning crew.")]),
}
