def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Elevator cab interior detailing": T(
 "Elevator cab interior detailing cleans the walls, ceiling, lights, handrails, control panel, door faces and floor of passenger and service elevator cabs after protection pads come down.",
 "The elevator is used by every visitor, and its finishes are close to the eye. Fingerprints on stainless, scratches hidden under pads and dust on ceiling lights all show up immediately.",
 "Crews work with the cab placed on independent service by the elevator contractor, clean ceiling to floor with finish-specific products, and wipe stainless with the grain.",
 ["Number of cabs", "Wall and floor finishes", "Elevator contractor coordination for independent service", "Pad removal timing"],
 ["Do not spray liquids into control panels or door sensors.", "Report scratches found under pads rather than trying to polish them out."],
 [("How are elevator cabs cleaned after construction?", "With the cab on independent service, crews clean ceiling, lights, walls, rails, control panel and floor using products matched to each finish."),
  ("Can cleaning crews operate elevators?", "No. The elevator contractor or building staff places the cab on independent service for cleaning."),
  ("How is stainless in an elevator cleaned without streaks?", "With a neutral cleaner, then a clean dry cloth wiped in the direction of the grain."),
  ("What if the cab is scratched under the pads?", "The damage is documented and reported to the GC; scratches are repaired by finish specialists, not cleaners.")]),
"Elevator door and sill track cleaning": T(
 "Elevator door and sill track cleaning vacuums the grooved sills at every landing and in the cab and cleans hoistway and cab door faces.",
 "Grit, screws and debris in elevator sills keep doors from closing properly and cause service calls and failed inspections.",
 "Crews vacuum each sill groove with crevice tools and pick out debris by hand, working floor by floor with the elevator contractor's coordination.",
 ["Number of landings and cabs", "Debris in sills", "Coordination with elevator contractor", "Door finishes"],
 ["Never reach into the hoistway.", "Do not wash debris into sill grooves."],
 [("Why are elevator sills cleaned?", "Debris in the sill grooves can stop doors from closing and cause service calls."),
  ("How often should elevator sills be cleaned during construction?", "Regularly, because construction traffic fills them quickly, and thoroughly before inspection."),
  ("Can elevator sills be cleaned with water?", "They should be vacuumed; water washes debris deeper into the track."),
  ("Who handles elevator door adjustments?", "The elevator contractor.")]),
"Elevator pit debris removal": T(
 "Elevator pit debris removal clears construction debris from the bottom of elevator hoistways, only under the elevator contractor's lockout and supervision.",
 "Elevator inspectors require clean pits. Debris in a pit is a fire hazard and can interfere with equipment.",
 "Crews enter only with the elevator contractor's lockout, fall protection and supervision, remove debris and vacuum dust.",
 ["Pit count", "Lockout and supervision", "Debris type", "Water in pit"],
 ["Pit entry requires lockout and trained supervision.", "Water in pits must be addressed by the GC."],
 [("Who can enter an elevator pit?", "Only authorized people with the elevator contractor's lockout."),
  ("Why must elevator pits be clean?", "Inspectors require it and debris is a hazard."),
  ("What is found in elevator pits?", "Construction debris, trash and dust."),
  ("Is water in an elevator pit a problem?", "Yes, and it must be addressed before inspection.")]),
"Escalator and moving walk cleaning": T(
 "Escalator and moving walk cleaning cleans the balustrades, handrails, skirts and exterior panels of escalators and moving walks under the escalator contractor's control.",
 "Escalators are complex, moving equipment. Debris in steps and comb plates causes damage and safety problems.",
 "Requests are reviewed and routed only with the escalator contractor's lockout and approval.",
 ["Units", "Lockout", "Exterior surfaces", "Contractor approval"],
 ["Never clean a running escalator.", "Comb plates and steps are serviced by the contractor."],
 [("Who cleans escalators?", "Exteriors can be cleaned with approval; mechanical parts are serviced by the escalator contractor."),
  ("Why is escalator cleaning conditional?", "It is moving equipment with serious hazards."),
  ("Are escalator handrails cleaned?", "Yes, with approved cleaners."),
  ("Can debris damage escalators?", "Yes, in steps and comb plates.")]),
"Stairwell cleaning top to bottom": T(
 "Stairwell cleaning top to bottom details stair towers from the roof landing to the ground floor, including rails, treads, risers, landings, walls and doors.",
 "Every trade uses the stairs, so stairwells are the dirtiest spaces at turnover. They are also exit routes that fire inspectors check.",
 "Crews start at the top floor, dust rails and ledges, clean walls and doors, then treads and landings, working down so nothing falls on cleaned areas.",
 ["Number of stair towers and floors", "Tread finish", "Doors and hardware", "Inspection date"],
 ["Wet stairs are slippery; post signs and work in sections.", "Keep the exit route usable during cleaning."],
 [("Why are stairwells cleaned from the top down?", "So dust and debris fall onto areas not yet cleaned."),
  ("Do fire inspectors check stairwells?", "Yes, they are exit routes."),
  ("What is included in stairwell cleaning?", "Rails, treads, risers, landings, walls and doors."),
  ("How long does it take to clean a stair tower?", "It depends on height and dirt; tall towers can take a full shift.")]),
"Corridor and hallway detailing": T(
 "Corridor and hallway detailing cleans corridors from ceiling to floor, including walls, doors, signage, lights, wall protection and floors.",
 "Corridors connect every space and are walked by every visitor.",
 "Crews clean top down and finish floors last.",
 ["Corridor length", "Finishes", "Doors", "Floors"],
 ["Traffic during cleaning.", "Corner guards and rails."],
 [("What is included in corridor cleaning?", "Walls, doors, signage, lights and floors."),
  ("Are corridors cleaned last?", "Often, because trades use them to reach rooms."),
  ("Are corner guards cleaned?", "Yes."),
  ("Is corridor cleaning part of final clean?", "Yes.")]),
"Lobby final detailing": T(
 "Lobby final detailing is the most detailed clean in the building, covering entry glass, floors, walls, feature elements, reception, elevators lobbies and furniture.",
 "The lobby is the first impression for owners, tenants and guests.",
 "Crews detail every surface with finish-specific methods and touch up before the owner walk.",
 ["Lobby finishes", "Feature elements", "Glass", "Furniture"],
 ["Stone floors need care.", "High areas need lifts."],
 [("Why is the lobby cleaned last?", "It gets the most traffic."),
  ("Are lobby feature walls cleaned?", "Yes."),
  ("Is lobby glass cleaned?", "Yes."),
  ("Is the lobby touched up before the owner walk?", "Yes.")]),
}
