def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Final clean of entire building": T(
 "A final clean of the entire building is the complete, detailed cleaning of every space, inside and out, after construction is finished and before the Substantial Completion inspection and owner turnover.",
 "Most specifications require final cleaning to be complete before the GC requests the Substantial Completion inspection. A building that is not inspection-clean can fail the walk and delay the certificate, occupancy and payment.",
 "Crews work top down and inside out, room by room against a checklist: overhead, fixtures, walls, glass, casework, restrooms and finally floors, using HEPA capture and finish-safe products.",
 ["Building size and room count", "Spec section requirements for final cleaning", "Inspection and owner walk dates", "Items by others: duct, hood, high-rise glass"],
 ["Trades returning for punch work will re-soil clean areas.", "Overhead and exterior work are often missed unless written into the scope."],
 [("What is included in a final construction clean?", "Every surface in every room: overhead, lights, walls, doors, glass, casework, fixtures, restrooms, floors, plus exterior entries and walks."),
  ("When should the final clean happen?", "After all trades finish, before the Substantial Completion inspection and owner walk."),
  ("How much does a final clean cost?", "It is usually priced per square foot or by crew-day, based on size, finishes, heights and schedule."),
  ("What is the difference between final clean and touch-up?", "The final clean is complete and detailed; touch-up is a quick pass to fix areas that got dirty again.")]),
"Final clean by phase or floor": T(
 "A final clean by phase or floor completes the final clean in one area at a time as each is finished, so it can be inspected, handed over or protected while other areas continue.",
 "Large projects and phased occupancies turn over in parts. Each part needs to be final-cleaned and kept clean until handover.",
 "Crews clean each released area completely, document it and coordinate protection or access control so it stays clean.",
 ["Phase plan", "Handover dates", "Protection", "Documentation"],
 ["Adjacent work can re-soil finished areas.", "Multiple mobilizations affect pricing."],
 [("Why do a final clean in phases?", "So each area can be inspected or occupied as it is finished."),
  ("How is a finished phase kept clean?", "With protection, access control and touch-ups."),
  ("Does phased cleaning cost more?", "It can, due to multiple mobilizations."),
  ("Who decides the phases?", "The GC and owner.")]),
"Light clean (phase 2)": T(
 "A light clean, also called a phase 2 or detail clean, cleans surfaces, fixtures and glass after most finishes are installed, between the rough clean and the final clean.",
 "The light clean removes the dust from finish trades so the final clean is faster and higher quality.",
 "Crews clean surfaces, fixtures and glass, leaving final detailing and floors for the final clean.",
 ["Areas", "Finishes installed", "Timing", "Scope"],
 ["Too early means repeating it.", "Floors are often protected still."],
 [("What is a light clean?", "The middle phase of construction cleaning."),
  ("Is the light clean always needed?", "Not always; it depends on project size."),
  ("What is cleaned in the light clean?", "Surfaces, fixtures and glass."),
  ("When is the light clean?", "After most finishes are installed.")]),
"Touch-up clean before owner walk": T(
 "A touch-up clean before the owner walk is a fast, focused pass right before the owner or architect inspection, re-cleaning anything that got dirty since the final clean.",
 "The owner walk decides how many items land on the punch list. Fresh footprints, fingerprints and dust from last-minute work can turn a clean building into a long list.",
 "Crews walk the inspection route, re-clean glass, fixtures, floors and entries, and check the areas inspectors look at most.",
 ["Owner walk date and route", "Recent trade activity", "Focus areas", "Crew availability"],
 ["Trades working after touch-up will re-soil areas.", "Touch-up is not a substitute for a full final clean."],
 [("What is a touch-up clean?", "A quick re-clean right before an inspection or owner walk."),
  ("When should the touch-up happen?", "The day before or morning of the owner walk."),
  ("What is cleaned in a touch-up?", "Glass, fixtures, floors, entries and anything re-soiled."),
  ("Is touch-up cleaning priced separately?", "Usually, yes.")]),
"Punch-list cleaning": T(
 "Punch-list cleaning addresses the cleaning items recorded on the architect's or owner's punch list, such as smudges, labels, residue and missed areas.",
 "Cleaning items on the punch list must be closed for the project to reach final completion and payment.",
 "Crews work item by item from the list and document completion.",
 ["Punch list", "Locations", "Documentation", "Deadline"],
 ["Items must be documented as closed.", "Some items belong to other trades."],
 [("What is a punch list?", "A list of items to finish or fix."),
  ("What cleaning items are on punch lists?", "Smudges, labels, residue and missed areas."),
  ("How are punch items closed?", "By completing and documenting them."),
  ("Who assigns punch items?", "The GC.")]),
"Pre-certificate of occupancy clean": T(
 "A pre-certificate of occupancy clean prepares the building for the building official's final inspection before a certificate of occupancy is issued.",
 "The CO inspection checks life-safety systems and finished conditions. Debris, blocked exits and dirty equipment rooms are common issues.",
 "Crews clear exits, equipment rooms and inspection areas and complete a building-wide clean.",
 ["Inspection date", "Exit routes", "Equipment rooms", "Areas"],
 ["Blocked exits fail inspection.", "Labels may need to stay."],
 [("What is a certificate of occupancy?", "Permission from the building authority to occupy the building."),
  ("Does cleaning affect the CO inspection?", "Debris and blocked exits can cause problems."),
  ("What is cleaned before CO?", "Exits, equipment rooms and inspection areas."),
  ("Who schedules the CO inspection?", "The GC.")]),
}
