def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Pre-health inspection clean": T(
 "A pre-health inspection clean prepares restaurants, food stores, schools kitchens and other food facilities for the health department's opening inspection.",
 "Food facilities cannot open without passing health inspection, and construction dust, debris in drains and dirty equipment are common reasons for failure.",
 "Crews clean top down with food-safe products, focus on overhead areas, equipment, handwash sinks and drains, and leave sanitizing to the operator or label-directed service.",
 ["Inspection date", "Food areas and equipment", "Handwash stations", "Drains and floor sinks"],
 ["Non-food-safe chemicals must not be used in food areas.", "Inspectors look overhead and under equipment."],
 [("What does a health inspector look for at an opening?", "Clean, cleanable surfaces, working handwash sinks, clean equipment, no debris and no dust over food areas."),
  ("When should the pre-inspection clean happen?", "A day or two before the inspection, after all trades are out of the kitchen."),
  ("Does the cleaning crew sanitize surfaces?", "Cleaning is done first; sanitizing is done with registered products by trained staff."),
  ("Why do new restaurants fail health inspection?", "Common reasons include dust overhead, debris in drains and missing sanitation steps.")]),
"Pre-fire marshal inspection clean": T(
 "A pre-fire marshal inspection clean prepares the building for fire inspection by clearing exits, fire equipment and equipment rooms.",
 "Fire inspectors check exits, fire equipment and storage. Blocked or dirty areas cause findings.",
 "Crews clear exits, clean fire equipment exteriors and remove combustible debris.",
 ["Inspection date", "Exits", "Fire equipment", "Storage"],
 ["Blocked exits are violations.", "Fire equipment must not be moved."],
 [("What does a fire marshal check?", "Exits, fire equipment and storage."),
  ("Are fire extinguishers cleaned?", "Their cabinets are."),
  ("Why remove combustible debris?", "It is a fire hazard."),
  ("Who schedules fire inspection?", "The GC.")]),
"Owner move-in clean": T(
 "An owner move-in clean prepares a finished building for the owner or tenant to move in, cleaning after furniture, equipment and IT installation.",
 "Move-in brings new dust and packaging after the final clean.",
 "Crews clean after installers and before occupants arrive.",
 ["Move-in date", "Installers", "Areas", "Packaging"],
 ["Installers re-soil spaces.", "Timing is tight."],
 [("What is a move-in clean?", "A clean right before occupants move in."),
  ("Why clean again before move-in?", "Installers create dust."),
  ("Is packaging removed?", "Yes."),
  ("Who arranges move-in cleaning?", "The owner or GC.")]),
"Tenant improvement final clean": T(
 "A tenant improvement final clean is the final clean of an interior build-out for a specific tenant before move-in.",
 "TI spaces often share buildings with occupied tenants and must be cleaned without disturbing them.",
 "Crews clean the suite completely and coordinate building access.",
 ["Suite size", "Building rules", "Access", "Move-in date"],
 ["Building rules limit hours.", "Common areas must stay clean."],
 [("What is a TI final clean?", "The final clean of a tenant build-out."),
  ("Are common areas cleaned?", "Areas affected by work are."),
  ("Do buildings limit cleaning hours?", "Often."),
  ("Who arranges TI cleaning?", "The GC.")]),
"Phased occupancy cleaning": T(
 "Phased occupancy cleaning cleans and hands over areas as they are occupied in stages.",
 "Occupied areas must stay clean while work continues nearby.",
 "Crews clean each area and protect it from adjacent work.",
 ["Phases", "Protection", "Occupied areas", "Schedule"],
 ["Dust migration.", "Coordination."],
 [("What is phased occupancy?", "Occupying a building in stages."),
  ("How are occupied areas protected?", "With barriers and cleaning."),
  ("Who plans phases?", "The GC and owner."),
  ("Is cleaning repeated?", "Often.")]),
"Post-furniture install clean": T(
 "A post-furniture install clean removes packaging, dust and debris left after furniture installation.",
 "Furniture installers leave packaging and dust.",
 "Crews remove packaging and clean furniture and floors.",
 ["Furniture", "Packaging", "Floors", "Timing"],
 ["Packaging volume.", "Floor damage."],
 [("Why clean after furniture installation?", "Packaging and dust."),
  ("Is furniture cleaned?", "Yes."),
  ("Who removes packaging?", "Installers or crews."),
  ("When?", "After installation.")]),
}
