def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Post-IT and AV install clean": T(
 "A post-IT and AV install clean removes the ceiling tile dust, cable scraps, packaging and fingerprints left after technology, audio-visual and security installers finish.",
 "Low-voltage installers often work after the final clean, lifting ceiling tiles, pulling cable and mounting displays, and leave dust and debris in finished rooms.",
 "Crews follow the installers' completion schedule, collect cable scraps and packaging, wipe displays and devices dry and re-clean floors and surfaces.",
 ["Installer schedule", "Rooms with new equipment", "Ceiling tiles disturbed", "Display and device cleaning rules"],
 ["Never spray liquid on screens or devices.", "Do not move or unplug installed equipment."],
 [("Why does a building need cleaning after IT installation?", "Installers lift ceiling tiles and pull cable, which drops dust and debris into finished rooms."),
  ("How are new TV screens and displays cleaned?", "With a dry or barely damp microfiber cloth, never spraying liquid on the screen."),
  ("What debris do AV installers leave?", "Cable scraps, ties, packaging, ceiling tile dust and screws."),
  ("When is the post-IT clean scheduled?", "After the technology installers finish and before occupants move in.")]),
"Model unit and show suite cleaning": T(
 "Model unit and show suite cleaning keeps models and sales suites spotless for tours during construction and lease-up.",
 "Models sell the project; dust and fingerprints undermine it.",
 "Crews clean models on a schedule and before tours.",
 ["Units", "Schedule", "Tours", "Furnishings"],
 ["Construction dust migrates.", "Furniture care."],
 [("Why clean model units often?", "They are toured constantly."),
  ("Are model furnishings cleaned?", "Yes."),
  ("How often?", "Weekly or before tours."),
  ("Who arranges?", "The developer.")]),
"Vacant space turnover cleaning": T(
 "Vacant space turnover cleaning cleans empty suites or units between tenants or after renovation so they can be shown or leased.",
 "Vacant spaces collect dust and must look ready for prospects.",
 "Crews clean the full space and touch up before showings.",
 ["Space size", "Condition", "Showings", "Schedule"],
 ["Spaces re-soil while vacant.", "Utilities may be off."],
 [("What is vacant space turnover?", "Cleaning empty spaces for leasing."),
  ("How often?", "Before showings."),
  ("Who arranges?", "Property managers."),
  ("Are utilities needed?", "Water and power help.")]),
"Property management turnover cleaning": T(
 "Property management turnover cleaning cleans spaces for property managers between tenants or after work orders.",
 "Property managers need fast, consistent turnovers.",
 "Crews follow property manager checklists.",
 ["Checklist", "Schedule", "Space", "Access"],
 ["Short turnaround.", "Consistency."],
 [("What is PM turnover?", "Cleaning between tenants."),
  ("Who sets the checklist?", "The property manager."),
  ("How fast?", "Often a few days."),
  ("Are photos provided?", "Often.")]),
"Post-renovation reset clean": T(
 "A post-renovation reset clean returns an occupied space to normal after a renovation, removing dust from surrounding areas.",
 "Renovations spread dust beyond the work area.",
 "Crews clean the renovated and surrounding areas.",
 ["Areas", "Dust spread", "Occupants", "Schedule"],
 ["Dust migration.", "Occupant schedules."],
 [("What is a reset clean?", "Cleaning after renovation."),
  ("Are surrounding areas cleaned?", "Yes."),
  ("Who arranges?", "Owners or managers."),
  ("When?", "After renovation.")]),
"Post-equipment installation cleaning": T(
 "Post-equipment installation cleaning cleans areas after equipment is installed, removing packaging and dust.",
 "Equipment installation creates debris.",
 "Crews clean around new equipment without touching controls.",
 ["Equipment", "Areas", "Packaging", "Controls"],
 ["Do not touch controls.", "Packaging volume."],
 [("Why clean after equipment installation?", "Debris and dust."),
  ("Is equipment cleaned?", "Exteriors."),
  ("Who removes packaging?", "Installers or crews."),
  ("When?", "After installation.")]),
}
