def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Emergency or overnight turnaround clean": T(
 "An emergency or overnight turnaround clean mobilizes a crew on short notice to get a space inspection-ready or open by the next morning, after a schedule slip, failed inspection or surprise walk.",
 "Inspections, openings and owner walks sometimes move up, or a space fails a walk. A fast, organized crew can save a date that cannot move.",
 "Beyond Klean confirms contractor capacity before promising a time, then the crew focuses on the inspection route and highest-visibility items first.",
 ["Deadline and inspection route", "Space size and condition", "Access hours", "Night labor pricing"],
 ["Rush work usually carries premium pricing.", "A rush clean cannot fix work trades have not finished."],
 [("Can a building be cleaned overnight before an inspection?", "Often yes, if a crew with enough people is available and trades are finished."),
  ("How fast can Beyond Klean get a crew?", "We confirm a contractor's capacity before promising a time, and say plainly if we cannot cover it."),
  ("Does rush cleaning cost more?", "Usually, because of night and overtime labor."),
  ("What is cleaned first in a rush clean?", "The inspection route and the most visible areas.")]),
"Before-and-after photo documentation": T(
 "Before-and-after photo documentation photographs areas before and after cleaning to prove the work and protect against disputes.",
 "Photos resolve disputes about damage and completeness and support closeout.",
 "Crews photograph areas consistently and organize photos by location.",
 ["Areas", "Format", "Organization", "Delivery"],
 ["Inconsistent photos lose value.", "Photos must be dated."],
 [("Why take before-and-after photos?", "To prove work and resolve disputes."),
  ("Are photos dated?", "Yes."),
  ("Who receives photos?", "The GC."),
  ("Are photos required?", "Often.")]),
"Room-by-room cleaning checklist sign-off": T(
 "Room-by-room cleaning checklist sign-off records each room's cleaning against a checklist and gets sign-off from the GC.",
 "Checklists ensure nothing is missed and provide proof.",
 "Crews complete checklists and walk rooms with the GC.",
 ["Checklist", "Rooms", "Sign-off", "Records"],
 ["Missed items.", "Sign-off delays."],
 [("Why use room checklists?", "To ensure completeness."),
  ("Who signs off?", "The GC."),
  ("Are checklists kept?", "Yes."),
  ("Are checklists project-specific?", "Often.")]),
"Cleaning product SDS and data sheet package": T(
 "A cleaning product SDS and data sheet package compiles safety and technical data for products used, for closeout and green building records.",
 "Owners and green building projects require documentation of products.",
 "Crews compile SDS and data sheets.",
 ["Products", "SDS", "Technical data", "Delivery"],
 ["Outdated sheets.", "Missing products."],
 [("What is an SDS?", "A safety data sheet."),
  ("Why provide data sheets?", "For records and safety."),
  ("Who compiles them?", "The cleaning contractor."),
  ("Are they required?", "Often.")]),
"Attic stock and spare material staging": T(
 "Attic stock and spare material staging cleans, labels and stages spare materials for the owner.",
 "Owners need organized spare materials for future repairs.",
 "Crews clean, label and stage materials.",
 ["Materials", "Labels", "Location", "Inventory"],
 ["Do not discard attic stock.", "Labeling."],
 [("What is attic stock?", "Spare materials for repairs."),
  ("Where is it stored?", "Where the owner directs."),
  ("Is it labeled?", "Yes."),
  ("Who stages it?", "The GC or crew.")]),
"Owner training area preparation": T(
 "Owner training area preparation cleans and sets up rooms where the owner's staff are trained on building systems.",
 "Training sessions happen near turnover and need clean rooms.",
 "Crews clean the training room.",
 ["Room", "Schedule", "Setup", "Equipment"],
 ["Timing.", "Equipment."],
 [("What is owner training?", "Training on building systems."),
  ("Is the room cleaned?", "Yes."),
  ("When?", "Before sessions."),
  ("Who arranges?", "The GC.")]),
}
