def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Apartment unit post-construction clean": T(
 "An apartment unit post-construction clean is the final clean of a new or renovated apartment before inspection and lease-up: kitchen, appliances, bathrooms, closets, windows, fixtures and floors.",
 "Apartment communities turn over units on a rolling schedule, and every unit must look the same to residents and leasing agents. Missed appliance interiors and closets are common complaints.",
 "Crews use a repeatable unit checklist, cleaning top down and finishing with floors, and inspect each unit before handing it to the property's leasing team.",
 ["Unit count and types", "Rolling release schedule", "Appliance package", "Inspection and sign-off process"],
 ["Units sitting empty after cleaning may need a re-dust before move-in.", "Paint touch-ups after cleaning re-soil units."],
 [("What is included in an apartment final clean?", "Kitchen, appliances inside and out, bathrooms, closets, windows, blinds, fixtures, outlets, baseboards and floors."),
  ("How long does it take to clean a new apartment?", "A typical unit takes a few crew-hours, depending on size and finishes."),
  ("Are appliance interiors cleaned?", "Yes, packaging, film and dust are removed inside and out."),
  ("Do units need cleaning again before move-in?", "Often a light re-dust if units sat empty.")]),
"Condo unit final clean": T(
 "A condo unit final clean prepares a new condominium for owner closing and walkthrough, to a higher detail standard than a rental turnover.",
 "Condo buyers walk their unit with a punch list and expect it to be flawless.",
 "Crews detail every surface and fixture, with a touch-up before the buyer walk.",
 ["Unit finishes", "Buyer walk date", "Appliances", "Touch-up"],
 ["Buyers inspect closely.", "High-end finishes need care."],
 [("Is a condo clean different from an apartment clean?", "Buyers expect higher detail."),
  ("When is the condo cleaned?", "Before the buyer walkthrough."),
  ("Are appliances cleaned?", "Yes."),
  ("Is touch-up needed?", "Usually.")]),
"Townhome final clean": T(
 "A townhome final clean cleans multi-level townhomes, including stairs, garages and outdoor spaces.",
 "Townhomes have multiple floors and garages.",
 "Crews clean top floor down.",
 ["Units", "Floors", "Garage", "Outdoor"],
 ["Stairs.", "Garages."],
 [("Are townhome garages cleaned?", "Yes."),
  ("Are stairs cleaned?", "Yes."),
  ("Is the patio cleaned?", "Yes."),
  ("Top down?", "Yes.")]),
"Amenity space final clean": T(
 "An amenity space final clean prepares clubhouses, fitness rooms, pools, lounges and coworking spaces.",
 "Amenities sell the property.",
 "Crews clean amenities before tours.",
 ["Spaces", "Furnishings", "Equipment", "Tour dates"],
 ["Pools.", "Equipment."],
 [("Why clean amenities first?", "They sell the property."),
  ("Is the clubhouse cleaned?", "Yes."),
  ("Is the pool deck cleaned?", "Yes."),
  ("Is the fitness room cleaned?", "Yes.")]),
"Leasing office final clean": T(
 "A leasing office final clean prepares the leasing center for opening.",
 "The leasing office is the first stop for prospects.",
 "Crews detail the office.",
 ["Office", "Furniture", "Glass", "Restrooms"],
 ["Timing.", "Furniture."],
 [("Why clean the leasing office first?", "Prospects visit."),
  ("Is furniture cleaned?", "Yes."),
  ("Are restrooms cleaned?", "Yes."),
  ("When?", "Before opening.")]),
"Appliance interior and exterior cleaning": T(
 "Appliance interior and exterior cleaning removes packaging, film, labels and dust from refrigerators, ranges, dishwashers, microwaves and washers.",
 "Residents open appliances first.",
 "Crews clean inside and out.",
 ["Appliances", "Film", "Packaging", "Labels"],
 ["Do not remove required labels.", "Film."],
 [("Are appliance interiors cleaned?", "Yes."),
  ("Is film removed?", "Yes."),
  ("Are manuals left?", "Yes."),
  ("Which labels stay?", "Required labels.")]),
"Range hood and microwave detailing": T(
 "Range hood and microwave detailing cleans hoods, filters and over-range microwaves.",
 "Hoods collect dust and film.",
 "Crews clean hoods and microwaves.",
 ["Hoods", "Filters", "Microwaves", "Film"],
 ["Film.", "Filters."],
 [("Are hood filters cleaned?", "Yes."),
  ("Is the microwave cleaned?", "Yes."),
  ("Is film removed?", "Yes."),
  ("Why?", "Residents use them.")]),
"Washer and dryer area cleaning": T(
 "Washer and dryer area cleaning cleans laundry closets and rooms.",
 "Laundry areas collect dust.",
 "Crews clean appliances and closets.",
 ["Area", "Appliances", "Vents", "Floors"],
 ["Vents.", "Appliances."],
 [("Are laundry closets cleaned?", "Yes."),
  ("Are washers cleaned?", "Yes."),
  ("Are vents checked?", "Yes."),
  ("Why?", "Dust.")]),
"Dryer vent debris check": T(
 "A dryer vent debris check looks for construction debris in dryer vent lines before turnover.",
 "Debris in vents is a fire hazard.",
 "Crews check and clear accessible debris and report blockages.",
 ["Vents", "Access", "Reporting", "Units"],
 ["Fire hazard.", "Access."],
 [("Why check dryer vents?", "Fire hazard."),
  ("Who clears blockages?", "Specialists."),
  ("Is debris common?", "Yes."),
  ("When?", "Before turnover.")]),
"Garage and storage unit cleaning": T(
 "Garage and storage unit cleaning cleans garages and storage units.",
 "These areas collect debris.",
 "Crews sweep and clean.",
 ["Units", "Debris", "Floors", "Doors"],
 ["Debris.", "Doors."],
 [("Are garages cleaned?", "Yes."),
  ("Are storage units cleaned?", "Yes."),
  ("Who?", "Crews."),
  ("When?", "Before turnover.")]),
"Mailroom and package room cleaning": T(
 "Mailroom and package room cleaning cleans mailrooms and package rooms.",
 "Residents use them daily.",
 "Crews clean lockers and floors.",
 ["Room", "Lockers", "Floors", "Labels"],
 ["Lockers.", "Labels."],
 [("Are mailrooms cleaned?", "Yes."),
  ("Are package lockers cleaned?", "Yes."),
  ("Who?", "Crews."),
  ("When?", "Before turnover.")]),
"Trash room and chute room cleaning": T(
 "Trash room and chute room cleaning cleans trash rooms, chute doors and compactor areas.",
 "Trash rooms smell and collect debris.",
 "Crews clean and degrease.",
 ["Rooms", "Chutes", "Compactors", "Floors"],
 ["Odors.", "Compactors."],
 [("Are trash chutes cleaned?", "Doors and rooms."),
  ("Who cleans chute interiors?", "Specialists."),
  ("Why?", "Odors."),
  ("When?", "Before turnover.")]),
}
