def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

C = {
"Water damage cleanup": T(
 "Water damage cleanup removes water, dries structures and contents, and removes damaged materials after leaks, floods or storms. It is restoration work routed only to qualified restoration contractors.",
 "Wet building materials can grow mold within days. Water damage on a jobsite or in a new building needs fast, documented drying to protect the structure and the warranty.",
 "Requests are reviewed and routed only to restoration contractors with appropriate training and insurance, who extract water, dry with monitored equipment and document moisture readings.",
 ["Source and extent of water", "Category of water: clean, gray or black", "Materials affected", "Insurance and documentation needs"],
 ["Contaminated water requires specialized handling.", "Wet drywall and insulation often must be removed, not dried."],
 [("What should be done first after water damage on a jobsite?", "Stop the source, protect people and power, document the damage, and get a qualified restoration contractor started on drying quickly."),
  ("How quickly can mold grow after water damage?", "Mold can begin growing within a few days on wet materials, which is why fast drying matters."),
  ("Who handles water damage restoration?", "Restoration contractors with training in water damage drying and documentation."),
  ("Does water damage need insurance documentation?", "Usually, including photos, moisture readings and drying records.")]),
"Mold remediation": T(
 "Mold remediation removes mold growth and contaminated materials under containment, followed by cleaning and, often, clearance testing. Rules vary by state, and it is routed only to licensed or qualified remediation contractors.",
 "Mold in a new building is a health, warranty and liability concern. Improper removal spreads spores through the building.",
 "Requests are reviewed and routed only to qualified remediation contractors, with independent assessment where required.",
 ["Extent and location", "Moisture source", "State licensing rules", "Clearance testing"],
 ["The moisture source must be fixed or mold returns.", "Disturbing mold without containment spreads it."],
 [("Can a cleaning company remove mold?", "Small surface areas may be cleaned in some places, but larger remediation should be done by qualified or licensed professionals."),
  ("Do some states license mold remediation?", "Yes. Florida, for example, has licensing requirements for mold assessors and remediators."),
  ("What is clearance testing?", "Testing after remediation to confirm the area is acceptable."),
  ("Why fix moisture first?", "Mold returns if moisture continues.")]),
"Fire and smoke residue cleaning": T(
 "Fire and smoke residue cleaning removes soot, smoke residue and odor after fires. It is restoration specialty work.",
 "Smoke residue is acidic and damages surfaces; odor lingers without proper treatment.",
 "Routed only to qualified restoration contractors.",
 ["Extent", "Surfaces", "Odor", "Insurance"],
 ["Wrong methods smear soot.", "Odor treatment is specialized."],
 [("Who cleans after a fire?", "Restoration contractors."),
  ("Is soot harmful?", "It can be."),
  ("Can smoke odor be removed?", "Usually, by specialists."),
  ("Is it covered by insurance?", "Often.")]),
"Asbestos abatement": T(
 "Asbestos abatement removes asbestos-containing materials under federal, state and local rules by licensed abatement contractors.",
 "Asbestos fibers cause serious disease. Disturbing it without controls is illegal and dangerous.",
 "Never routed to cleaning crews; only licensed abatement contractors after review.",
 ["Survey results", "Licensing", "Notifications", "Clearance"],
 ["Stop work if suspect material is found.", "Notifications may be required."],
 [("What if asbestos is found during construction?", "Stop work and call a licensed abatement contractor."),
  ("Can cleaners remove asbestos?", "No."),
  ("Is asbestos still found in buildings?", "Yes, in older buildings."),
  ("Is clearance testing required?", "Often.")]),
"Lead paint abatement": T(
 "Lead paint abatement removes or controls lead-based paint hazards under EPA and OSHA rules by certified contractors.",
 "Lead dust harms health, especially children's.",
 "Routed only to certified contractors after review.",
 ["Testing", "Certification", "Work practices", "Clearance"],
 ["Lead dust spreads easily.", "Rules apply."],
 [("Who handles lead paint?", "Certified contractors."),
  ("Is lead paint dangerous?", "Yes."),
  ("Are there rules?", "Yes, EPA and OSHA."),
  ("Is clearance required?", "Often.")]),
"Biohazard and sharps cleanup on jobsites": T(
 "Biohazard and sharps cleanup removes blood, bodily fluids, needles and similar hazards from jobsites.",
 "Biohazards carry infection risk.",
 "Routed only to trained biohazard contractors.",
 ["Hazard type", "PPE", "Disposal", "Training"],
 ["Infection risk.", "Proper disposal."],
 [("Who cleans biohazards?", "Trained contractors."),
  ("Are needles common on sites?", "Sometimes."),
  ("Is disposal regulated?", "Yes."),
  ("Is PPE required?", "Yes.")]),
"Bird and pest dropping removal": T(
 "Bird and pest dropping removal cleans droppings and nesting material with protective measures.",
 "Droppings can carry disease.",
 "Routed only to trained crews.",
 ["Extent", "PPE", "Disposal", "Prevention"],
 ["Disease risk.", "PPE needed."],
 [("Are bird droppings hazardous?", "They can be."),
  ("Who removes them?", "Trained crews."),
  ("Is PPE needed?", "Yes."),
  ("How to prevent?", "Exclusion.")]),
"Hazardous material spill cleanup": T(
 "Hazardous material spill cleanup responds to spills of fuels, chemicals and hazardous substances.",
 "Hazardous spills require trained responders and reporting.",
 "Routed only to hazmat responders.",
 ["Material", "Reporting", "Training", "Disposal"],
 ["Reporting may be required.", "Training required."],
 [("Who cleans hazmat spills?", "Trained responders."),
  ("Must spills be reported?", "Some must."),
  ("Can cleaners help?", "No."),
  ("Is disposal regulated?", "Yes.")]),
"Disinfection service with registered products": T(
 "Disinfection service with registered products applies EPA-registered disinfectants according to label directions.",
 "Disinfection claims must match label use.",
 "Routed only to trained providers.",
 ["Product", "Label", "Surfaces", "Documentation"],
 ["Label must be followed.", "Claims must be accurate."],
 [("What is disinfection?", "Killing germs with registered products."),
  ("Must labels be followed?", "Yes."),
  ("Is cleaning required first?", "Usually."),
  ("Who provides it?", "Trained providers.")]),
"Post-event facility restoration": T(
 "Post-event facility restoration cleans and restores buildings after storms, hurricanes and similar events.",
 "Storm damage requires fast, coordinated restoration.",
 "Routed only to qualified restoration contractors.",
 ["Damage", "Insurance", "Safety", "Schedule"],
 ["Safety hazards.", "Insurance documentation."],
 [("What is post-event restoration?", "Cleanup after storms."),
  ("Who does it?", "Restoration contractors."),
  ("Is insurance involved?", "Often."),
  ("Is Florida prone to storms?", "Yes.")]),
}
