F = {
"Site, Debris & Waste Management": dict(slug="site-debris-waste", short="Site & Debris",
 intro="Debris control is the first cleaning scope on every jobsite and the one that sets the pace for every trade after it. This family covers hauling, sorting, recycling and the daily housekeeping that keeps walking paths open, combustible waste down and inspectors satisfied.",
 faq=[
  ("Who is responsible for jobsite debris on a commercial project?", "The general contractor is responsible overall, and most subcontracts make each trade clean up its own waste. In practice trades leave scraps behind, so GCs often hire a dedicated cleanup crew to sweep, haul and sort daily or weekly."),
  ("How often should a construction site be cleaned?", "Busy interiors usually need a daily sweep of walking paths and a deeper weekly clean. Fast-track jobs with many trades on site sometimes need two passes a day near egress routes and stairwells."),
  ("What is the difference between debris removal and a rough clean?", "Debris removal is ongoing: it clears waste as it is created. A rough clean is a defined phase after framing, drywall and rough-in that removes bulk debris and dust so finish trades can start."),
  ("Can construction waste be recycled?", "Yes. Metal, clean wood, cardboard and gypsum drywall are commonly recycled where local haulers accept them. Separating streams at the source usually lowers haul costs and supports LEED waste-diversion credits."),
  ("Does Beyond Klean provide dumpsters?", "No. The roll-off is usually arranged by the GC or the hauler. The cleanup contractors we match load, sort and manage the debris that goes into them."),
  ("What does OSHA require for jobsite housekeeping?", "OSHA's construction rules require walking and working surfaces to be kept free of scrap, debris and protruding nails, and combustible waste to be removed regularly. Where silica dust is present, dry sweeping is restricted in favor of wet or HEPA methods."),
  ("Can a cleanup crew work while other trades are on site?", "Yes, and most progress cleaning happens exactly that way. Crews coordinate with the superintendent's look-ahead schedule so they clear areas between trades without blocking work."),
  ("How is jobsite cleanup priced?", "It is usually priced per visit, per crew-day or as a monthly allowance, based on square footage, number of floors, debris volume and whether hauling is included. Contractors confirm pricing after reviewing the site and schedule."),
 ]),
"Rough Clean": dict(slug="rough-clean", short="Rough Clean",
 intro="The rough clean is phase one of construction cleaning. It happens after framing, drywall and mechanical rough-in, before finish trades arrive, and removes the bulk debris and heavy dust that would otherwise end up sealed into walls, ceilings and ductwork.",
 faq=[
  ("When does the rough clean happen?", "After framing, drywall hanging and taping, and mechanical, electrical and plumbing rough-in are complete, and before flooring, ceilings and finish carpentry start. On large buildings it moves floor by floor."),
  ("What is included in a rough clean?", "Removing bulk debris, scraping drywall mud and overspray off slabs, vacuuming stud bays and openings, and clearing mechanical rooms and shafts. Fine detailing waits for the final clean."),
  ("Why not skip the rough clean and do one big final clean?", "Dust and debris left at rough stage get trapped behind ceilings, inside ductwork and under new flooring. A rough clean protects finishes and makes the final clean faster and cheaper."),
  ("Is a rough clean the same as a construction clean?", "It is one phase of it. Construction cleaning usually runs in three phases: rough clean, light or detail clean, and final clean, with touch-up before the owner walk."),
  ("How long does a rough clean take?", "It depends on square footage, debris volume and access. A small tenant space may take a day; a multistory building is usually phased over several days as floors become ready."),
  ("Should the slab be scraped before flooring is installed?", "Yes. Hardened joint compound, paint drips and overspray under resilient flooring or carpet create bumps and adhesion problems. Flooring installers expect a clean, scraped slab."),
  ("Who sets the rough clean schedule?", "The general contractor's superintendent, based on when each area is released by the drywall and MEP trades. Good cleanup contractors work from the GC's three-week look-ahead."),
  ("Does a rough clean require HEPA equipment?", "On most commercial jobs it should. Drywall and concrete dust are fine enough to pass through ordinary vacuums, and silica rules restrict dry sweeping where concrete dust is present."),
 ]),
"Fine Dust, Drywall Dust & Controlled-Dust Cleaning": dict(slug="fine-dust-control", short="Fine Dust Control",
 intro="Fine dust is the hardest construction residue to get rid of. Drywall and concrete dust settle on every surface, drift into HVAC systems and keep reappearing for weeks if they are pushed around instead of captured. This family covers capture-first dust removal, silica-aware housekeeping and dust control in occupied renovations.",
 faq=[
  ("Why does drywall dust keep coming back after cleaning?", "Because it was moved, not removed. Dry dusting and sweeping lift fine particles into the air, where they settle again hours later. HEPA vacuuming and damp microfiber capture it so it stays gone."),
  ("Is drywall dust harmful?", "Drywall dust can irritate eyes, skin and lungs, and some joint compounds contain crystalline silica. Concrete and masonry dust carry more silica. Capture methods and proper respiratory protection reduce exposure."),
  ("What is HEPA vacuuming?", "Vacuuming with a sealed machine whose high-efficiency particulate air filter captures at least 99.97 percent of particles at 0.3 microns. It keeps fine construction dust from passing straight through the vacuum back into the room."),
  ("Can you use a leaf blower or compressed air to clean construction dust?", "It is a poor practice indoors and restricted under OSHA's silica standard. Blowing dust spreads it into finished spaces and HVAC systems and increases worker exposure."),
  ("How is dust controlled during renovation of an occupied building?", "With containment barriers, negative air machines, sticky mats at exits, HEPA vacuuming and frequent damp cleaning outside the work zone. Healthcare projects follow stricter infection-control protocols."),
  ("When should fine dust removal happen?", "Last, after all dust-producing trades are finished in that area. Dusting before ceiling, electrical or millwork touch-ups finish usually means doing it twice."),
  ("Does fine dust removal include inside cabinets and drawers?", "It should. Owners and inspectors open drawers and cabinet doors, and dust collects inside them during construction. Confirm it is in the scope."),
  ("What is silica-aware housekeeping?", "Cleaning methods that keep crystalline silica dust out of the air: wet sweeping, HEPA vacuuming and approved sweeping compounds instead of dry sweeping, brushing or compressed air."),
 ]),
"Overhead & Elevated Surfaces (Above Eye Level)": dict(slug="overhead-high-dusting", short="Overhead & High Dusting",
 intro="Everything above eye level collects the heaviest construction dust: decks, beams, joists, ducts, pipes, cable trays and light fixtures. It falls onto finished floors, food areas and merchandise if it is left. This family covers overhead cleaning at turnover and the recurring high dusting that keeps it clean afterward through Above Eye Level Cleaning.",
 faq=[
  ("What is high dusting?", "Cleaning surfaces that are out of normal reach, usually above eight to ten feet: open ceiling decks, beams, joists, ductwork, pipes, cable trays, light fixtures and the tops of racking and walls."),
  ("Why do new buildings need overhead cleaning?", "Construction dust rises and settles on every horizontal surface overhead. In open-ceiling stores, warehouses and restaurants it is visible, falls onto finished surfaces and can fail food-safety and owner inspections."),
  ("How do crews clean ceilings 20 or 30 feet up?", "With scissor lifts or boom lifts, extension poles and HEPA vacuum attachments that capture dust at the surface. Dust should be captured, not knocked down onto the floor."),
  ("Is overhead cleaning included in a normal final clean?", "Often it is not. Many final-clean scopes stop at reachable surfaces. If the building has an open ceiling or exposed structure, overhead cleaning should be written into the bid as its own line item."),
  ("How often should high dusting be done after the building opens?", "Retail and warehouse spaces typically schedule it quarterly or semiannually. Food facilities often tie it to audit schedules. Heavy-dust environments may need it more often."),
  ("Can high dusting be done while a store is open?", "Yes, usually overnight or before opening, with merchandise covered or areas cordoned off. Lift work over shoppers is avoided."),
  ("Is high dusting safe for sprinkler heads?", "Sprinkler heads need careful, light dusting only. Crews should never hang anything from them, paint them or use pressure on them. Damaged or painted heads must be replaced by a fire protection contractor."),
  ("What is Above Eye Level Cleaning?", "Our partner program focused on overhead cleaning. Beyond Klean handles construction turnover; AboveEyeLevelCleaning.com handles the scheduled high dusting that keeps the space clean after it opens."),
 ]),
"Walls, Ceilings & Interior Finishes": dict(slug="walls-ceilings-finishes", short="Walls & Ceilings",
 intro="Wall and ceiling finishes are what owners see first and touch least, so every scuff, fingerprint and smear shows. This family covers painted walls, wallcoverings, specialty panels, acoustic ceilings, grid and diffusers, cleaned with methods that do not damage fresh paint or new tile.",
 faq=[
  ("Can you wash freshly painted walls?", "Not right away. Most latex paints need days to weeks to cure fully, depending on the product. Early cleaning should be light spot cleaning with neutral cleaners and soft microfiber, not scrubbing."),
  ("How do you clean acoustic ceiling tiles without staining them?", "With dry methods first: dry sponges, soft brushes and HEPA vacuuming. Liquid cleaners can leave water rings on mineral fiber tile. Badly soiled tiles are often cheaper to replace."),
  ("Who cleans the ceiling grid after construction?", "It should be in the cleaning contractor's final clean scope. Grid gets fingerprints from tile setters and dust from above-ceiling work, and it is a common punch item."),
  ("Should air diffusers be cleaned before turnover?", "Yes. Diffusers and return grilles catch construction dust and often show dark streaks soon after the HVAC starts. Face cleaning is part of final clean; duct interior cleaning is a separate specialty."),
  ("What is the best way to remove scuffs from walls?", "Start with the gentlest option: a damp microfiber cloth, then a neutral cleaner, then a melamine sponge used lightly. Aggressive rubbing burnishes flat paint and leaves a shiny patch."),
  ("Do wallcoverings need special cleaning?", "Yes. Vinyl wallcovering tolerates mild cleaners; fabric and natural-fiber wallcoverings need dry methods. Always follow the manufacturer's care instructions."),
  ("Are wall and ceiling smudges really punch-list items?", "Yes. Architects and owners routinely list fingerprints, overspray and smudges on walls and ceilings during the punch walk."),
  ("What about walls above 10 feet?", "Upper walls, ledges and soffits need lifts or poles and are usually part of the overhead scope. They collect dust the same way decks and ducts do."),
 ]),
"Doors, Hardware, Millwork & Casework": dict(slug="doors-millwork-casework", short="Doors & Millwork",
 intro="Doors, hardware, cabinets and counters are opened, touched and inspected more than any other finish. They also arrive from the factory with films, labels and dust. This family covers detailing them without damaging factory finishes, fire labels or new hardware coatings.",
 faq=[
  ("Should the labels on fire-rated doors be removed?", "No. The fire rating label on the door edge and frame must stay in place and readable. Cleaners should work around it and never paint over or remove it."),
  ("How do you clean new cabinets after construction?", "Vacuum dust from inside boxes and drawers, then wipe with a mild cleaner suitable for the finish. Avoid ammonia, abrasive pads and excess water, which can damage wood finishes and edge banding."),
  ("What cleaner is safe for quartz countertops?", "Mild, pH-neutral cleaners and soft cloths. Strong alkalis, solvents and abrasive pads can dull or discolor the resin in engineered quartz."),
  ("How should brass and stainless door hardware be cleaned?", "With a soft cloth and a cleaner made for that finish. Abrasives scratch, and some metal polishes strip protective lacquer from brass and bronze."),
  ("Do toilet partitions need special cleaning?", "Powder-coated, plastic laminate, solid plastic and stainless partitions each have recommended cleaners. Most need only a neutral cleaner; sticker and adhesive removal needs care on powder coat."),
  ("Is cleaning inside drawers part of a final clean?", "On a well-written scope, yes. Inspectors and owners open them, and they collect construction dust and packaging debris."),
  ("What is the most common millwork punch item?", "Dust, adhesive and pencil marks on cabinet faces and inside boxes, followed by fingerprints and protective film left on edges and hardware."),
  ("Who removes the blue protective film on new hardware and appliances?", "Usually the cleaning crew at final clean, unless the installer is required to. Film left too long in sun or heat becomes hard to remove."),
 ]),
"Glass, Windows & Glazing": dict(slug="glass-windows", short="Glass & Windows",
 intro="New glass arrives with labels, stucco, paint, concrete splatter and sealant, and the way it is cleaned decides whether it ends up clear or scratched. This family covers construction window cleaning, storefronts, interior glazing, mirrors and specialty glass, done with coating-safe methods and documented care.",
 faq=[
  ("Why does new glass get scratched during construction cleaning?", "Scratches come from dragging debris under a blade, from fabricating debris fused to tempered glass, and from using dull or dirty scrapers. Proper lubrication, fresh blades and the right technique on the right glass type reduce the risk."),
  ("Can razor blades be used on new windows?", "On uncoated glass, a clean blade used flat with lubrication is a standard method. Some coated, tempered and low-E surfaces should not be scraped at all. The glass manufacturer's guidance controls."),
  ("What is a glass scratch waiver?", "A contract clause, recommended by the window cleaning industry, that addresses liability for scratches that may result from removing construction debris from glass. Many construction window cleaners require one."),
  ("When should construction windows be cleaned?", "After exterior finishes like stucco, painting and sealants are complete and the scaffolding is down, then touched up after punch work. Cleaning earlier usually means cleaning twice."),
  ("How do you remove concrete splatter from glass?", "Carefully, starting with soaking and gentle mechanical removal. Acidic concrete removers can etch glass and damage metal frames, so they are a last resort and must be tested first."),
  ("Who cleans high-rise windows after construction?", "Specialty contractors using rope access, swing stages or building maintenance units. It requires trained, insured crews and fall-protection plans, so it is routed only to qualified providers."),
  ("What is pure-water window cleaning?", "Cleaning with deionized or reverse-osmosis water through a water-fed pole. With minerals removed, glass dries without spots, and little or no detergent is needed."),
  ("Should the stickers on new windows be removed?", "Yes, at final clean, unless the inspector needs to see energy labels first. Ask the GC whether the code inspection requires labels in place."),
 ]),
"Hard Floors": dict(slug="hard-floors", short="Hard Floors",
 intro="Floors are the largest finished surface in most buildings and the first thing an owner judges. Each floor type needs a different first cleaning: concrete, resilient vinyl, tile, stone, terrazzo, wood and epoxy. This family covers initial care that matches manufacturer requirements and protects the floor warranty.",
 faq=[
  ("Does new VCT need to be stripped before waxing?", "New VCT has a factory coating that must be removed or prepared before floor finish will bond. That is why new VCT gets an initial scrub or strip and multiple coats of finish, not just a mop and wax."),
  ("Can LVT be waxed?", "Most luxury vinyl tile is designed to be maintained without wax. Applying finish or using the wrong cleaner can void the manufacturer's warranty. Follow the manufacturer's maintenance guide."),
  ("How do you remove grout haze from new tile?", "With a grout haze remover suited to the tile and grout type, applied after the grout has cured enough. Acidic removers are not safe on marble, limestone, travertine or some grouts."),
  ("How is a new concrete floor cleaned?", "Usually with an auto-scrubber, a neutral or mildly alkaline cleaner and pads chosen for the finish. Polished and sealed concrete need gentler pads and cleaners than raw slabs."),
  ("What is efflorescence?", "A white, powdery salt deposit that appears when water moves through concrete, masonry or grout and evaporates. It needs a remover matched to the surface, and the moisture source should be found."),
  ("Is polishing concrete part of cleaning?", "No. Concrete grinding and polishing is a flooring specialty with heavy equipment and silica controls. Cleaning contractors maintain polished concrete; polishing contractors create it."),
  ("How long before new floors can be cleaned?", "Tile grout, floor finishes, epoxy and wood coatings each have cure times. Cleaning too early can damage them. The installer's cure schedule should be in the cleaning plan."),
  ("Who removes tire and forklift marks from new warehouse floors?", "The cleaning contractor at final clean, using scrubbers with appropriate pads and cleaners. Non-marking tires on lifts reduce the problem."),
 ]),
"Carpet & Soft Surfaces": dict(slug="carpet-soft-surfaces", short="Carpet & Soft Surfaces",
 intro="New carpet is the softest target on a jobsite. It traps drywall dust, catches paint and mud, and shows every stain at turnover. This family covers construction vacuuming, extraction, spotting and upholstery, using low-moisture methods that dry fast and do not leave residue that resoils.",
 faq=[
  ("Does new carpet need to be cleaned before move-in?", "Yes. Even when carpet is installed late, it collects drywall dust, footprints and debris during punch and furniture installation. A thorough HEPA vacuum is the minimum; extraction is common."),
  ("Can drywall mud be removed from carpet?", "Usually, if it is handled properly. Let it dry, break it up and vacuum it, then treat the remaining residue. Wiping wet mud spreads it into the fibers."),
  ("How long does carpet take to dry after extraction?", "Usually a few hours with low-moisture methods and good airflow. Over-wetting can cause odors, delamination and wicking stains."),
  ("What causes stains to reappear after carpet cleaning?", "Wicking. Soil or residue deep in the backing rises back to the fiber tips as the carpet dries. Proper extraction and rinsing reduce it."),
  ("Should carpet tile be cleaned differently than broadloom?", "Similar methods apply, but carpet tile can be lifted and replaced, so badly damaged tiles are often swapped rather than cleaned."),
  ("Do construction cleaners clean office furniture?", "Many do vacuuming and wipe-down after furniture installation. Upholstery extraction is usually a separate line item."),
  ("What vacuum should be used on new carpet?", "A commercial HEPA-filtered upright or backpack vacuum. Ordinary filters pass fine drywall dust back into the air."),
  ("Is carpet protection film safe to leave on?", "Only for a short time. Adhesive film left too long, especially in heat or sun, can leave residue and damage pile."),
 ]),
"Restrooms & Plumbing Fixtures": dict(slug="restrooms-fixtures", short="Restrooms & Fixtures",
 intro="Restrooms get the closest inspection on any project. Caulk smears, sticker residue, grout haze and fingerprints on new fixtures are classic punch items. This family covers detailing fixtures, accessories, tile and drains with cleaners that protect new chrome, vitreous china and solid surface.",
 faq=[
  ("How do you remove stickers from new toilets and sinks?", "Peel the label, then remove the adhesive with a product that is safe for vitreous china and chrome. Razor blades can scratch glazes and plated finishes."),
  ("Can acidic bowl cleaners be used on new restroom fixtures?", "They should be avoided at turnover. New chrome, grout and some stone are sensitive to acids. Neutral cleaners and non-acidic descalers are safer for initial cleaning."),
  ("What is caulk haze?", "A thin film of silicone or sealant left on surfaces around a joint after caulking. It attracts dirt and looks smeary. It needs a remover that will not damage the surrounding finish."),
  ("Should restroom cleaning include floor drains?", "Yes. Floor drains often collect grout, debris and mortar during construction and should be checked and cleaned so they drain freely at turnover."),
  ("Who cleans the restroom accessories?", "The cleaning contractor during final clean: soap and towel dispensers, grab bars, mirrors, hand dryers and partitions."),
  ("Is disinfecting part of a construction restroom clean?", "Cleaning is. Disinfecting is a separate step that requires EPA-registered products used according to the label, and it is only claimed when actually done that way."),
  ("How clean does a restroom need to be for the owner walk?", "Free of dust, labels, residue, smears and debris, with fixtures polished and drains clear. Inspectors look under sinks, behind toilets and inside stalls."),
  ("Do eyewash stations need cleaning before turnover?", "The exterior should be cleaned. Flushing and testing is the facility's responsibility under its safety program."),
 ]),
"Kitchens, Food Facilities & FRP": dict(slug="kitchens-food-frp", short="Kitchens & Food Facilities",
 intro="A food facility cannot open until it passes health inspection, and construction dust in a kitchen is a food-safety problem, not a cosmetic one. This family covers restaurant and grocery turnover, stainless and refrigeration, FRP wall systems and kitchen ceilings, with residue-free cleaning and sanitizing done only with properly registered products.",
 faq=[
  ("What is FRP?", "Fiberglass reinforced plastic: the washable, textured wall panels used in commercial kitchens, restrooms and food areas. It is installed with adhesive and trim, and it needs non-abrasive cleaning."),
  ("Who cleans a new restaurant before opening?", "A post-construction cleaning contractor handles the building and equipment exteriors. Hood and duct cleaning, ice machine sanitizing and refrigeration startup are usually done by their own specialty contractors."),
  ("Is kitchen hood cleaning part of construction cleaning?", "The hood exterior is. Hood and grease duct interior cleaning is a regulated specialty under NFPA 96 and is done by certified hood cleaning contractors."),
  ("What is the difference between cleaning and sanitizing a food surface?", "Cleaning removes soil and residue. Sanitizing reduces microorganisms to safe levels and must be done with registered sanitizers at label concentrations. Food-contact surfaces need both, in that order."),
  ("How do you remove construction dust from a walk-in cooler?", "Vacuum and wipe panels, shelving and floors with food-safe cleaners before the box is started up and stocked. Dust in a running cooler can end up on product."),
  ("What do health inspectors look for at a new restaurant opening?", "Clean, intact, cleanable surfaces; no construction debris; working handwash sinks; clean equipment; and no dust over food areas. Overhead dust is a common finding."),
  ("Can grocery departments open in phases?", "Yes. Grocery openings often turn over by department, and cleaning must follow each department's handover date, especially deli, bakery and meat rooms."),
  ("Why is stainless steel streaky after cleaning?", "Streaks come from residue, hard water or wiping against the grain. Clean with a neutral cleaner, rinse, dry and finish with the grain."),
 ]),
"Mechanical, Electrical & Construction IAQ": dict(slug="mechanical-electrical-iaq", short="Mechanical & IAQ",
 intro="Mechanical and electrical rooms are where construction dust damages expensive new equipment, and HVAC systems are where it becomes an indoor air quality complaint. This family covers non-invasive cleaning around equipment and the construction IAQ steps green building standards expect before occupancy.",
 faq=[
  ("Can a cleaning crew clean an electrical room?", "Only non-invasive cleaning of floors, walls and enclosure exteriors, and only where the electrical contractor or facility allows it. Nothing inside energized equipment, and no liquids near live gear."),
  ("What is construction indoor air quality management?", "A plan, often required on LEED projects, to keep dust and contaminants out of the HVAC system and building during construction: protecting ducts, filtering returns, housekeeping and scheduling."),
  ("Should HVAC filters be changed before occupancy?", "Yes. Filters that ran during construction are loaded with dust. Green building standards call for new filtration media before occupancy."),
  ("What is a building flush-out?", "Running the HVAC system with outdoor air for a set period after construction, before or during early occupancy, to dilute contaminants from new finishes. A thorough final clean should come first."),
  ("Is duct cleaning part of a construction cleanup?", "Duct exteriors are. Duct interior cleaning is a specialty, often done to NADCA standards, and is only needed when ducts were contaminated during construction."),
  ("Why were the ducts capped during construction?", "To keep construction dust out of them. If caps were missed or torn, dust gets in, and duct cleaning may be needed before turnover."),
  ("Who cleans the rooftop units?", "The exterior of rooftop units and curbs can be cleaned by the cleaning contractor. Coils and internal components belong to the mechanical contractor."),
  ("Does Beyond Klean provide IAQ testing?", "No. Air quality testing is done by independent industrial hygiene or commissioning professionals. Our network handles the cleaning and documentation that supports it."),
 ]),
"Retail Fixtures & Store Opening": dict(slug="retail-store-opening", short="Retail & Store Openings",
 intro="Retail openings run on fixed dates set long before construction finishes. Merchandise cannot be set on dusty fixtures, and a grand opening cannot move. This family covers store opening cleans, fixture and gondola detailing, overnight remodels and multi-site rollouts.",
 faq=[
  ("When should the cleaning crew start on a new store?", "After fixtures are installed and before merchandise is set. Most store openings need a fixture clean, a merchandise-set support clean and a final pre-opening clean."),
  ("What is a store opening clean?", "The final clean of a new or remodeled store before it opens: floors, glass, fixtures, fitting rooms, stockrooms and restrooms, timed around merchandise delivery and the opening date."),
  ("Can remodels be cleaned overnight while the store stays open?", "Yes. Overnight crews clean after each night's construction so the store can trade the next morning. It takes coordination with the remodel schedule."),
  ("How do national retailers handle cleaning for many locations?", "Through rollout programs: one scope, one checklist and coordinated crews across many sites, so every store opens to the same standard."),
  ("Who cleans gondola shelving?", "The cleaning contractor, after the fixture installer is done and before stocking. Shelves, uprights, kick plates and price channels all collect dust."),
  ("Does store opening cleaning include the ceiling?", "It should for open-ceiling stores. Dust from the deck falls onto merchandise and fixtures after opening if it is not cleaned first."),
  ("How long does a store opening clean take?", "It depends on size and how many trades are still working. A small store may need a day; a big box store may need multiple shifts over several days."),
  ("Do restaurant chains use the same approach?", "Yes. Chains typically standardize their opening clean across locations and add kitchen-specific items for health inspection."),
 ]),
"Specialty & Controlled Environments": dict(slug="specialty-environments", short="Specialty Environments",
 intro="Healthcare, labs, cleanrooms, data centers, schools, hotels and industrial plants each have their own cleaning requirements before occupancy. Many are protocol-driven and need trained crews. This family covers them by facility type, with regulated work routed only to qualified providers.",
 faq=[
  ("Is post-construction cleaning in a hospital different?", "Yes. Healthcare construction follows infection-control risk assessments, and final cleaning before patients return is protocol-based, often coordinated with the hospital's environmental services department."),
  ("What is cleanroom cleaning?", "Cleaning to a defined particle standard using specific garments, low-lint wipes, approved cleaning agents and a set sequence. It is required before cleanroom certification."),
  ("Who cleans a data center after construction?", "Specialty contractors trained for critical environments. They clean subfloors, raised floor tiles, cabinets and surfaces with antistatic methods and HEPA equipment."),
  ("Do schools have special cleaning requirements after construction?", "Schools usually open on fixed dates, have many identical rooms and often require background-checked crews. Low-odor products matter because students arrive soon after."),
  ("What is a hotel PIP?", "A property improvement plan, a brand-required renovation. PIP cleaning turns renovated rooms back to inventory quickly, often floor by floor."),
  ("Can any cleaning company clean a lab?", "Not safely. Labs may have chemical, biological or equipment hazards. Cleaning is limited to what the lab's safety officer approves."),
  ("How are specialty cleaning contractors verified?", "By checking training, protocols, references for that facility type, and insurance that covers the work. Regulated scopes are approved case by case."),
  ("Are warehouses considered specialty environments?", "Not usually, but their size calls for ride-on scrubbers, lifts for racking and high dusting, and crews that work fast across very large slabs."),
 ]),
"Exterior, Hardscape & Building Envelope": dict(slug="exterior-hardscape", short="Exterior & Hardscape",
 intro="The exterior is the first thing an owner, tenant or inspector sees. Mud on sidewalks, mortar on brick and debris in landscape beds make a finished building look unfinished. This family covers flatwork, facades, masonry, parking areas and site cleanup, with wash water kept out of storm drains.",
 faq=[
  ("Can wash water from pressure washing go into the storm drain?", "Generally no. Wash water often carries soil, concrete fines, oils and detergents that storm water rules prohibit. Crews use recovery equipment or block and vacuum the drains."),
  ("How do you clean mortar off new brick?", "With a masonry cleaner suited to the brick type, pre-wetting the wall and rinsing thoroughly. The wrong acid can stain light-colored brick or burn mortar joints."),
  ("When is the exterior cleaned on a construction project?", "After landscaping, striping and exterior trades finish, and before the certificate of occupancy inspection and owner walk."),
  ("What is soft washing?", "Cleaning facades and roofs with low pressure and cleaning solutions instead of high pressure, which can damage stucco, EIFS, paint and sealants."),
  ("Is parking lot sweeping part of a construction cleanup?", "Often yes, especially before striping and before the final walk. Power sweepers handle large lots quickly."),
  ("Can graffiti be removed from new construction?", "Usually, with removers matched to the surface. Fresh graffiti is much easier to remove, and anti-graffiti coatings can protect high-risk walls."),
  ("Who cleans the gutters at the end of a project?", "The cleaning contractor or roofer. Gutters and roof drains collect construction debris that can cause backups in the first heavy rain."),
  ("Should solar panels be cleaned after construction?", "If construction dust coated them, yes, but only by crews following the panel manufacturer's guidance and electrical safety rules."),
 ]),
"Residue, Stain & Protective-Material Removal": dict(slug="residue-removal", short="Residue Removal",
 intro="Residues are the hardest items on any punch list: paint, adhesive, caulk, grout haze, plaster, foam, labels and protective film. The wrong removal method damages new finishes and creates rework. This family covers least-aggressive-first residue removal and the protection that keeps finishes safe in the first place.",
 faq=[
  ("What does least-aggressive-first mean?", "Start with the gentlest method that might work: dry removal, then water, then neutral cleaners, then targeted solvents, and test each one in a hidden spot. Stop at the first method that works."),
  ("How do you remove paint overspray from new surfaces?", "It depends on the surface and paint type. Plastic blades and mild removers work on many hard surfaces; glass may take a blade; textured and porous surfaces need specialty products and testing."),
  ("What removes adhesive residue safely?", "Citrus or soy-based removers and mineral oils work on many adhesives without harsh solvents. Some substrates, including certain plastics and finishes, react to solvents, so test first."),
  ("Why does protective film need to come off promptly?", "Heat and UV make film adhesive bond harder over time. Film left on for months can leave residue or pull finish when removed."),
  ("Who removes floor protection at the end of a job?", "Usually the cleaning contractor during final clean, unless the flooring contractor or GC handles it. The dust trapped under it must be captured, not swept around."),
  ("Is grout haze a cleaning or tile problem?", "Both. The tile setter is expected to clean grout as it is installed, but light haze is common and is removed at final clean. Heavy haze goes back to the installer."),
  ("Can paint drips on concrete be removed?", "Usually, by scraping and with removers suited to the paint and the floor finish. Polished concrete needs gentler methods than raw slab."),
  ("What is the most common residue on construction punch lists?", "Labels and stickers, paint overspray, tape residue and caulk smears appear on nearly every punch list."),
 ]),
"Vertical Transportation & Circulation": dict(slug="elevators-stairs-circulation", short="Elevators & Stairs",
 intro="Elevators, stairs, lobbies and corridors are used by every trade during construction and every visitor afterward. They collect the most traffic dirt and debris. This family covers cab and sill detailing, pits, stair towers and circulation spaces.",
 faq=[
  ("Who cleans the elevator pit?", "Pits collect debris during construction and must be clean for inspection. The cleaning contractor can remove debris only with the elevator contractor's lockout and permission."),
  ("Why do elevator sills need cleaning?", "Debris in sill tracks can keep doors from closing properly and cause service calls. Sills should be vacuumed clean before turnover."),
  ("When is the elevator cab protection removed?", "Near the end of the project, after heavy deliveries and furniture moves are complete. The cab is then detailed."),
  ("How are stairwells cleaned after construction?", "Top to bottom: dust rails and ledges, clean treads and nosings, then floors, so dust does not fall onto cleaned areas."),
  ("Are escalators cleaned by the cleaning contractor?", "Only exterior surfaces and only with the escalator contractor's permission and lockout. Comb plates and step cleaning are specialty work."),
  ("What does a lobby final clean include?", "Floors, entry glass, walls, signage, furniture, elevator lobbies and any feature walls or lighting. It is the most visible space in the building."),
  ("Should stair nosings be cleaned separately?", "They need attention because they collect grime and adhesive residue. Nosings are often a visible punch item."),
  ("Can corridors be cleaned while tenants move in?", "Yes, with phased cleaning that follows move-in schedules and focuses on high-traffic routes."),
 ]),
"Turnover, Punch & Closeout Support": dict(slug="turnover-punch-closeout", short="Turnover & Closeout",
 intro="Turnover is where cleaning decides whether a project closes on time. The final clean comes before the Substantial Completion inspection, touch-ups follow the punch walk, and the owner moves in after that. This family covers final, phased and touch-up cleaning plus the documentation GCs need for closeout.",
 faq=[
  ("What is the difference between a final clean and a touch-up clean?", "The final clean is a complete, detailed clean of the space before inspection. A touch-up clean is a quick pass right before the owner walk, or after punch work, to fix areas that got dirty again."),
  ("What does Substantial Completion have to do with cleaning?", "Most construction specs require final cleaning to be complete before the GC requests the Substantial Completion inspection. A dirty building can fail that walk and delay the certificate and payment."),
  ("What is a sparkle clean?", "An informal name for the last detailed touch-up before an owner walk or grand opening. It focuses on glass, fixtures, floors and anything visible."),
  ("How many phases does construction cleaning have?", "Usually three: rough clean, light or detail clean, and final clean, followed by touch-ups. Not every project needs every phase."),
  ("Who pays for re-cleaning after punch work?", "That depends on the contract. Many GCs carry a re-clean allowance, or back-charge the trade that made the mess. Cleaning contracts should define how re-cleans are priced."),
  ("What cleaning documentation do GCs need for closeout?", "Often photo documentation, signed room checklists, product data sheets for cleaning chemicals and records supporting LEED or IAQ requirements."),
  ("What is attic stock?", "Spare materials left for the owner, such as extra tiles, ceiling panels and paint. It should be cleaned, labeled and staged where the owner wants it."),
  ("Can a building be cleaned and turned over in phases?", "Yes. Phased occupancy is common in large projects; each area is final-cleaned and protected when it is handed over."),
 ]),
"Multifamily & Residential-Scale Turnover": dict(slug="multifamily-turnover", short="Multifamily Turnover",
 intro="Multifamily projects turn over dozens or hundreds of nearly identical units on rolling schedules. Speed and consistency set the pace of lease-up. This family covers unit final cleans, appliances, amenity spaces and back-of-house rooms in apartments, condos and townhomes.",
 faq=[
  ("How long does it take to clean a new apartment unit?", "A typical unit final clean takes a few crew-hours, depending on size, finishes and how much construction dust is left. Consistent checklists keep units uniform."),
  ("Are appliances cleaned inside and out?", "They should be: remove packaging, film and labels, then clean interiors and exteriors so the unit is ready to show."),
  ("Who cleans amenity spaces in a new apartment community?", "The same cleaning contractor, usually before leasing tours start. Clubhouses, fitness rooms and pool areas are prioritized because they sell the property."),
  ("What is a model unit clean?", "A detailed clean of the units used for tours, often repeated as they get foot traffic during lease-up."),
  ("Do units need re-cleaning before move-in?", "Often yes, if units sat empty after final clean. A light dust and floor clean before move-in keeps the first impression right."),
  ("Can dryer vents be clogged from construction?", "Yes. Drywall dust and debris can enter vent lines during construction, and a quick check before turnover can prevent fire risk and complaints."),
  ("Do trash rooms and chutes need cleaning at turnover?", "Yes. They collect construction debris and odors, and chute doors and rooms should be clean before residents move in."),
  ("What is the biggest multifamily cleaning challenge?", "Schedule. Units are released on a rolling basis, and cleaning has to match the pace of inspections and lease-up."),
 ]),
"Restoration & Regulated Work (Conditional)": dict(slug="restoration-regulated", short="Restoration & Regulated",
 intro="Some cleaning work is regulated: mold remediation, asbestos and lead abatement, biohazard and hazardous material cleanup, fire and water damage restoration. These scopes carry licensing, testing and liability requirements. They are listed so buyers can find the right path, and they are routed only to properly licensed providers after case-by-case review.",
 faq=[
  ("Can a regular cleaning company remove mold?", "Small, surface-level mold cleanup may be allowed in some places, but remediation of larger areas typically involves licensed or certified professionals, containment and clearance testing, depending on state rules."),
  ("Who handles asbestos found during construction?", "Work must stop in the area, and a licensed asbestos abatement contractor handles removal under federal and state rules. Cleaning crews must not disturb suspect materials."),
  ("What happens if lead paint is disturbed during renovation?", "Lead-safe work practices and cleanup are required under EPA and OSHA rules, and clearance testing may be needed. Certified renovators and abatement contractors handle this."),
  ("What is post-storm cleanup?", "Removing debris, water, mud and damaged materials after hurricanes, floods or wind events, often followed by drying and mold prevention. Florida projects plan for it."),
  ("Can construction cleaners disinfect?", "Only with EPA-registered disinfectants used according to the label, and only when the claim is accurate. Cleaning and disinfecting are different services."),
  ("How does Beyond Klean handle regulated scopes?", "They are never routed automatically. Each request is reviewed, and only providers with the required licenses, training and insurance are introduced."),
  ("What is a biohazard on a jobsite?", "Blood, bodily fluids, sharps or animal waste. Cleanup requires trained personnel, protective equipment and proper disposal."),
  ("Is fire and smoke damage cleaning a restoration job?", "Yes. Smoke residue cleaning, odor control and contents cleaning are restoration specialties, often handled through insurance claims."),
 ]),
}
