def T(a, y, m, s, w, q):
    return dict(a=a, y=y, m=m, s=s, w=w, q=q)

P = {
"Post-equipment installation cleaning": T(
 "Post-equipment installation cleaning cleans the area around newly installed equipment, such as kitchen lines, laundry machines, fitness equipment, medical equipment or production machinery, removing packaging, dust and debris.",
 "Equipment is often delivered and set after the final clean. Crating, foam, plastic and dust left behind make the space look unfinished and can block access.",
 "Crews remove packaging, vacuum and wipe the equipment exteriors where allowed, clean floors and walls around it and leave controls and connections untouched.",
 ["Equipment list and installers", "Packaging and crating", "Allowed exterior cleaning", "Floor and wall touch-ups"],
 ["Do not touch controls, panels or connections.", "Some equipment has manufacturer-specific cleaning rules."],
 [("Why clean after equipment installation?", "Installers leave packaging, dust and debris, often after the final clean is finished."),
  ("Is new equipment cleaned by the cleaning crew?", "Exterior surfaces are wiped where allowed; internals are left to the vendor."),
  ("Who removes equipment crating?", "Installers sometimes remove it; otherwise the cleaning crew handles it."),
  ("When is post-equipment cleaning done?", "Right after installation, before inspection or move-in.")]),
"Emergency or overnight turnaround clean": dict(q=[
  ("Can a building be cleaned overnight before an inspection?", "Often yes, if a crew with enough people is available and the trades are finished. The crew focuses on the inspection route and the most visible areas first."),
  ("How fast can Beyond Klean get an emergency cleaning crew?", "We confirm a contractor's capacity before promising a time, and we say plainly when we cannot cover a deadline instead of overpromising."),
  ("Does rush or overnight cleaning cost more?", "Usually, because of night and overtime labor and short-notice scheduling. The premium is often small compared to a missed inspection or opening."),
  ("What gets cleaned first in an emergency clean?", "The inspection route, entrances, restrooms, glass and floors, because those are what inspectors and owners see first.")]),
"Before-and-after photo documentation": T(
 "Before-and-after photo documentation photographs areas before cleaning and after completion, organized by room or location, to prove completion, protect against damage claims and support closeout and LEED records.",
 "Disputes about what was dirty, what was damaged and what was finished are common at closeout. Dated, organized photos settle them quickly.",
 "Crews photograph each area from consistent angles before and after work, note existing damage, and deliver photos organized by floor and room.",
 ["Areas to document", "Photo format and naming", "Existing damage notes", "Delivery method"],
 ["Photos without dates or locations lose value.", "Existing damage must be photographed before cleaning starts."],
 [("Why take before-and-after photos of construction cleaning?", "They prove the work was done and show existing damage, which prevents disputes at closeout."),
  ("How should cleaning photos be organized?", "By floor and room, with dates and consistent angles, so anyone can find a specific space."),
  ("Who receives cleaning photo documentation?", "The GC, and through them the owner, for closeout records."),
  ("Do LEED projects need cleaning photos?", "Construction IAQ credits often require dated photos of protection and housekeeping measures.")]),
"Room-by-room cleaning checklist sign-off": T(
 "Room-by-room cleaning checklist sign-off records each room's cleaning against a written checklist and gets the GC's signature before the owner walk, so nothing is missed and completion is documented.",
 "Large buildings have hundreds of rooms. Without checklists, rooms get skipped and items like cabinet interiors and door tops are forgotten.",
 "Crews complete a checklist per room, the crew lead inspects, and the GC walks and signs off rooms or floors before the owner walk.",
 ["Checklist items per room type", "Inspection process", "Sign-off authority", "Record keeping"],
 ["Checklists that are too generic miss room-specific items.", "Sign-off should happen before trades return for punch work."],
 [("Why use room-by-room cleaning checklists?", "They make sure every item in every room is cleaned and give a clear record of completion."),
  ("Who signs off on cleaning checklists?", "The cleaning crew lead first, then the GC's superintendent or project manager."),
  ("Are checklists different for each room type?", "Yes, restrooms, kitchens, offices and mechanical rooms each need their own items."),
  ("What happens to signed checklists?", "They are kept for closeout records and help resolve later disputes.")]),
"Cleaning product SDS and data sheet package": T(
 "A cleaning product SDS and data sheet package compiles the Safety Data Sheets and technical data sheets for every cleaning product used on the project, for the GC's safety program, closeout binder and green building documentation.",
 "OSHA's hazard communication rules require SDS access on site, and owners and green building projects often ask what products were used in their building.",
 "The cleaning contractor lists every product used, collects current SDS and technical sheets, and delivers them organized for the closeout binder.",
 ["Product list", "Current SDS versions", "Technical data sheets", "Delivery format"],
 ["Outdated SDS versions do not meet requirements.", "Substituted products must be added to the package."],
 [("What is a Safety Data Sheet?", "A standardized document from the manufacturer describing a chemical's hazards, handling, protective equipment and first aid."),
  ("Why does the owner want cleaning product data sheets?", "To know what was used in their building, for safety and green building records."),
  ("Who compiles the SDS package?", "The cleaning contractor, as part of closeout."),
  ("Are SDS required on construction sites?", "Yes, workers must have access to SDS for chemicals they use under OSHA's hazard communication standard.")]),
"Attic stock and spare material staging": T(
 "Attic stock and spare material staging cleans, labels, inventories and stages spare finish materials, such as tile, ceiling panels, carpet tiles and paint, in the location the owner designates.",
 "Specs often require attic stock for future repairs. If it is lost, damaged or thrown out during cleanup, the owner cannot match finishes later.",
 "Crews gather spare materials, label them by type and location used, list them on an inventory and stage them in the owner's designated storage room.",
 ["Attic stock list from specs", "Storage location", "Labeling", "Inventory sign-off"],
 ["Attic stock is easily thrown out during final haul-off.", "Materials must be kept dry and protected."],
 [("What is attic stock?", "Spare finish materials, such as tile, carpet, ceiling panels and paint, left for the owner's future repairs."),
  ("Why is attic stock labeled?", "So the owner knows what each material is and where it was used."),
  ("Where is attic stock stored?", "In a storage room or location the owner designates."),
  ("Who is responsible for attic stock?", "The GC, with the cleaning crew often handling staging and labeling.")]),
"Owner training area preparation": T(
 "Owner training area preparation cleans and sets up the rooms where the owner's facility staff are trained on building systems, such as HVAC, controls, fire systems and equipment, near turnover.",
 "Training sessions happen during the busiest week of closeout. A clean, ready room keeps sessions on time and reflects well on the project team.",
 "Crews clean the training room, set tables and chairs if requested and touch up the equipment rooms that will be toured during training.",
 ["Training dates", "Room location", "Setup needs", "Equipment rooms toured"],
 ["Training dates move; confirm the day before.", "Equipment rooms toured should be clean too."],
 [("What is owner training in construction?", "Sessions where installers teach the owner's staff to operate and maintain building systems."),
  ("Why clean the training room?", "It is where the owner's team spends hours during closeout."),
  ("Are equipment rooms cleaned before training tours?", "Yes, rooms shown during training should be clean and clear."),
  ("Who schedules owner training?", "The GC coordinates it with installers and the owner.")]),
}
