"""Beyond Klean construction-cleaning task taxonomy.

Each task line is:  "Task name | phase | tier | alias; alias; ..."
  phase: R=rough  P=progress  F=final  T=touch-up/punch  O=occupancy/turnover
         A=any stage / specialty  M=recurring maintenance after turnover
  tier:  C=core (route to verified generalist)  A=adjacent (verified specialist)
         X=conditional (licensed / regulated; manual approval only)
Aliases are other names the same task is sold or searched under. They are
counted as overlap, not as separate tasks.

Run:  python3 build_taxonomy.py   -> writes tasks.csv, tasks.json, stats.json
"""
import csv, json, re
from collections import Counter, defaultdict
from pathlib import Path

OUT = Path(__file__).parent
DATA = []

def fam(name, groups):
    DATA.append((name, groups))

def g(name, why, green, tasks):
    return (name, why, green, tasks)

# ---------------------------------------------------------------------------
fam("Site, Debris & Waste Management", [
  g("Construction debris removal",
    "Loose debris is the #1 jobsite trip, puncture and fire hazard and blocks every trade that follows.",
    "Source-separated debris streams (metal, cardboard, wood, drywall) divert material from landfill and lower haul cost.",
    ["Bulk debris pickup by floor | R | C | trash out; debris haul-out",
     "Drywall scrap collection | R | C | gypsum scrap removal",
     "Lumber and wood scrap collection | R | C | wood waste pickup",
     "Metal scrap and stud offcut collection | R | C | metal recycling pickup",
     "Cardboard and packaging breakdown | R | C | packaging removal; box breakdown",
     "Pallet and crate removal | R | C | pallet haul-off",
     "Insulation scrap removal | R | C | batt insulation cleanup",
     "Ceiling tile scrap and carton removal | R | C | ACT scrap removal",
     "Flooring offcut and carton removal | R | C | flooring scrap pickup",
     "Wire, conduit and cable offcut pickup | R | C | electrical scrap pickup",
     "Fastener and screw sweep with magnetic sweeper | R | C | nail sweep; magnet sweep",
     "Tile and stone offcut removal | R | C | masonry scrap pickup",
     "Glass shard and broken glazing cleanup | R | C | broken glass cleanup",
     "Construction dumpster loading | R | C | roll-off loading",
     "Debris chute operation support | R | C | trash chute loading",
     "Dumpster area housekeeping | P | C | roll-off area cleanup",
     "Recycling stream separation | P | C | waste diversion sorting; construction recycling",
     "Waste diversion tracking for LEED | P | A | LEED waste log; diversion report",
     "Final haul-off of remaining debris | F | C | final trash out",
     "Surplus material staging for return | F | C | leftover material staging",
    ]),
  g("Jobsite housekeeping and safety",
    "OSHA housekeeping rules require clear walking surfaces and controlled combustible waste; a clean site is a safer and faster site.",
    "Wet methods and HEPA capture keep dust on the floor and out of lungs instead of re-suspending it with brooms or blowers.",
    ["Daily jobsite sweep | P | C | daily cleanup; progress sweep",
     "Weekly jobsite clean | P | C | weekly site cleaning",
     "Stairwell and egress path clearing | P | C | egress cleanup; exit path clearing",
     "Trade-area cleanup between trades | P | C | trade turnover clean; after-trade clean",
     "Jobsite trailer cleaning | P | C | site office cleaning; construction trailer cleaning",
     "Portable toilet area upkeep | P | A | porta-john area cleanup",
     "Break and lunch area cleaning | P | C | jobsite break area cleanup",
     "Tool and material laydown area cleanup | P | C | laydown yard cleanup",
     "Mud and track-out removal at entrances | P | C | track-out cleanup",
     "Silica-aware wet sweeping | P | C | wet sweep; dust suppression sweeping",
     "HEPA vacuuming of work areas | P | C | HEPA vac cleanup",
     "Sweeping compound application | P | C | dust control compound sweep",
     "Combustible waste removal | P | C | fire load reduction cleanup",
     "Spill response for paint and non-hazardous liquids | A | A | small spill cleanup",
     "Concrete washout area maintenance | P | A | washout pit cleanup",
     "Pre-inspection jobsite clean | A | C | inspection-ready cleanup; OSHA walk prep",
     "Owner walkthrough and VIP tour prep clean | A | C | tour-ready clean",
    ]),
])

fam("Rough Clean", [
  g("Rough clean (phase 1)",
    "Rough clean removes bulk debris and dust after framing, drywall and MEP rough-in so finish trades can start on clean substrate.",
    "Top-down HEPA vacuuming and microfiber capture keep fine dust from settling into ducts and finishes installed next.",
    ["Rough clean of entire building | R | C | phase 1 clean; rough cleaning",
     "Rough clean by floor or phase | R | C | partial rough clean",
     "Interior wall stud bay vacuuming before close-in | R | C | stud cavity cleanout",
     "Slab scraping of drywall mud and joint compound | R | C | mud scrape; slab scrape",
     "Slab scraping of overspray and drips | R | C | floor scrape",
     "Window sill and opening rough wipe | R | C | rough window clean",
     "Rough clean of mechanical and electrical rooms | R | C | MEP room rough clean",
     "Rough clean of shafts and chases | R | A | shaft cleanout",
     "Rough clean of plenum above ceiling before grid close | R | A | above-ceiling cleanout; plenum clean",
     "Removal of sticker and label backing debris | R | C | label debris cleanup",
     "Rough clean of exterior perimeter | R | C | perimeter debris pickup",
    ]),
])

fam("Fine Dust, Drywall Dust & Controlled-Dust Cleaning", [
  g("Fine dust removal",
    "Drywall and concrete dust is abrasive, migrates into HVAC and electronics, and re-deposits for weeks if it is pushed around instead of captured.",
    "HEPA-filtered vacuums, damp microfiber and pH-neutral solutions capture dust rather than redistributing it — the safer, cleaner method.",
    ["Fine drywall dust removal from all horizontal surfaces | F | C | drywall dust cleaning; sheetrock dust removal",
     "Fine dust removal from vertical wall surfaces | F | C | wall dusting",
     "Fine dust removal from window frames and mullions | F | C | mullion dusting",
     "Fine dust removal from door tops and frame heads | F | C | door top dusting",
     "Fine dust removal from light switch and outlet plates | F | C | device plate cleaning",
     "Fine dust removal from baseboards | F | C | baseboard dusting",
     "Fine dust removal from cabinets and casework interiors | F | C | cabinet interior dusting",
     "Fine dust removal from fire extinguisher cabinets | F | C | FEC cleaning",
     "Fine dust removal from signage and wayfinding | F | C | sign dusting",
     "Fine dust removal from electronics and low-voltage devices | F | A | device dusting",
     "Fine dust removal from server and IT rooms | F | A | IT room dust removal",
     "Concrete dust removal after grinding or saw cutting | A | C | concrete dust cleanup; slurry dust cleanup",
     "Silica-aware housekeeping cleanup | A | C | silica dust cleanup; crystalline silica housekeeping",
     "Dust re-clean after late-trade work | T | C | re-dust; after-trade re-clean",
     "Dust containment barrier cleanup and removal | A | C | zip wall removal; poly barrier removal",
     "Negative air zone final cleaning | A | A | containment zone clean",
     "Occupied-building renovation dust control cleaning | A | A | occupied renovation cleaning; ICRA-style cleaning",
     "Air scrubber filter change and unit wipe-down | A | A | air scrubber maintenance",
    ]),
])

fam("Overhead & Elevated Surfaces (Above Eye Level)", [
  g("Ceilings, decks and structure",
    "Overhead dust falls onto finished floors, food areas and merchandise; inspectors and owners look up, and dirty structure reads as unfinished work.",
    "HEPA vacuum capture at height with dry microfiber and low-moisture methods — no blowing dust down onto finished space.",
    ["Open ceiling deck cleaning | F | C | exposed deck cleaning; metal deck dusting",
     "Exposed structural steel beam cleaning | F | C | beam cleaning; I-beam dusting",
     "Bar joist cleaning | F | C | joist dusting; open web joist cleaning",
     "Wood truss and glulam cleaning | F | A | truss dusting",
     "Gymnasium rafter cleaning | F | A | gym ceiling cleaning",
     "Warehouse ceiling dust removal | F | C | warehouse high dusting",
     "Retail store ceiling dust capture | F | C | retail high dusting",
     "Exposed concrete ceiling cleaning | F | C | concrete soffit cleaning",
     "Acoustic deck and sound panel dusting | F | A | acoustic panel cleaning",
     "Spray-applied fireproofing area light dusting | F | X | SFRM area dusting",
     "Mezzanine underside cleaning | F | C | mezzanine soffit cleaning",
     "Atrium and lobby high ceiling cleaning | F | A | atrium cleaning",
     "Skylight well and light shaft cleaning | F | A | skylight well cleaning",
    ]),
  g("Overhead MEP exterior surfaces",
    "Pipes, ducts and trays collect the heaviest construction dust and later shed it into occupied space and food zones.",
    "HEPA capture and damp wipe with pH-neutral cleaners preserve paint and labeling on new MEP finishes.",
    ["Duct exterior cleaning | F | C | ductwork exterior dusting; spiral duct cleaning",
     "Fabric duct sock cleaning | F | A | textile duct cleaning",
     "Overhead piping exterior cleaning | F | C | pipe dusting",
     "Sprinkler pipe exterior dusting | F | C | fire sprinkler pipe dusting",
     "Sprinkler head careful dusting | F | A | sprinkler head cleaning",
     "Cable tray exterior dusting | F | C | cable tray cleaning",
     "Conduit run dusting | F | C | conduit dusting",
     "Unit heater exterior cleaning | F | C | unit heater dusting",
     "Overhead exhaust fan exterior cleaning | F | C | exhaust fan dusting",
     "HVLS ceiling fan cleaning | F | A | big fan cleaning; industrial ceiling fan cleaning",
     "Ceiling fan cleaning | F | C | fan blade dusting",
    ]),
  g("Lighting and fixtures at height",
    "Dust on new fixtures cuts light output and shows immediately under commissioning; it is a common punch item.",
    "Dry microfiber and manufacturer-safe cleaners protect lenses and powder-coated finishes.",
    ["High-bay light fixture cleaning | F | C | high bay cleaning",
     "Pendant and suspended light cleaning | F | C | pendant cleaning",
     "Linear light fixture and lens cleaning | F | C | troffer lens cleaning",
     "Chandelier and decorative fixture cleaning | F | A | chandelier cleaning",
     "Track lighting cleaning | F | C | track light dusting",
     "Exit sign and emergency light cleaning | F | C | exit light cleaning",
     "Clerestory and upper window cleaning | F | A | high window cleaning",
     "Elevated signage and banner cleaning | F | C | high sign cleaning",
     "Upper wall ledge and soffit cleaning | F | C | ledge dusting",
     "Top of shelving and racking dusting | F | C | rack top dusting",
     "Top of walk-in cooler box dusting | F | C | cooler top cleaning",
     "Top of millwork and display dusting | F | C | top-of-fixture dusting",
    ]),
  g("Recurring overhead maintenance",
    "Overhead dust returns after turnover; scheduled high dusting protects food safety audits, merchandise and indoor air.",
    "Planned low-moisture HEPA cycles prevent heavy buildup that later needs aggressive chemistry.",
    ["Quarterly high dusting program | M | C | scheduled high dusting",
     "Semiannual overhead cleaning program | M | C | twice-yearly ceiling cleaning",
     "Annual deep overhead cleaning | M | C | annual high dusting",
     "Pre-audit overhead cleaning for food facilities | M | C | audit prep high dusting; SQF prep",
     "Overnight high dusting in operating stores | M | C | after-hours high dusting",
    ]),
])

fam("Walls, Ceilings & Interior Finishes", [
  g("Wall surfaces",
    "Fingerprints, overspray and tape residue on new paint are the most-noticed punch items on owner walks.",
    "Gentle pH-neutral cleaning protects fresh paint films that harsh degreasers would burnish or etch.",
    ["Spot cleaning of painted walls | F | C | wall spot clean; scuff removal",
     "Full wall washing | F | C | wall wash",
     "Wallcovering and vinyl wall cleaning | F | C | wallpaper cleaning",
     "Wall protection and corner guard cleaning | F | C | crash rail cleaning",
     "Acoustic wall panel vacuuming | F | A | fabric wall panel cleaning",
     "Wood wall panel and slat cleaning | F | A | wood veneer wall cleaning",
     "Stone and tile wall cleaning | F | C | tile wall cleaning",
     "Marker board and whiteboard wall cleaning | F | C | dry erase wall cleaning",
     "Stainless and metal wall panel cleaning | F | C | metal panel cleaning",
     "Glass wall and back-painted glass cleaning | F | C | glass wall cleaning",
    ]),
  g("Ceiling surfaces",
    "Smudged tiles and grid are visible from every angle and frequently rejected at punch.",
    "Dry sponge and low-moisture methods avoid water-staining new acoustic tile.",
    ["Acoustic ceiling tile spot cleaning | F | C | ceiling tile cleaning; ACT cleaning",
     "Ceiling grid cleaning | F | C | T-bar cleaning",
     "Drywall ceiling and soffit cleaning | F | C | gyp ceiling cleaning",
     "Wood and specialty ceiling cleaning | F | A | linear wood ceiling cleaning",
     "Metal ceiling panel cleaning | F | C | metal ceiling cleaning",
     "Ceiling diffuser and grille face cleaning | F | C | diffuser cleaning; register cleaning; return grille cleaning",
     "Access panel cleaning | F | C | ceiling hatch cleaning",
    ]),
])

fam("Doors, Hardware, Millwork & Casework", [
  g("Doors and frames",
    "Doors are touched by every inspector; labels, overspray and fingerprints are classic punch items.",
    "Manufacturer-compatible cleaners protect factory finishes, fire labels and hardware coatings.",
    ["Door face cleaning | F | C | door cleaning",
     "Door frame and jamb cleaning | F | C | frame wipe",
     "Door hardware polishing | F | C | hardware cleaning; lever polish",
     "Door kick and push plate polishing | F | C | kick plate cleaning",
     "Door vision lite cleaning | F | C | door glass cleaning",
     "Overhead coil and roll-up door cleaning | F | C | roll-up door cleaning",
     "Sectional and dock door cleaning | F | C | dock door cleaning",
     "Revolving door cleaning | F | A | revolving door detailing",
     "Automatic sliding door track cleaning | F | C | auto door track cleaning",
     "Fire door label-safe cleaning | F | C | fire door cleaning",
     "Door threshold and sweep cleaning | F | C | threshold cleaning",
    ]),
  g("Millwork, casework and counters",
    "New cabinetry ships with dust, film and adhesive; drawers and shelves are opened at every owner walk.",
    "Wood-safe and laminate-safe cleaners preserve finishes; no ammonia or abrasive pads on new surfaces.",
    ["Cabinet interior and exterior detailing | F | C | cabinet cleaning; casework cleaning",
     "Drawer interior vacuum and wipe | F | C | drawer cleaning",
     "Countertop cleaning by material | F | C | counter cleaning",
     "Quartz and solid surface countertop cleaning | F | C | quartz counter cleaning",
     "Natural stone countertop cleaning | F | A | granite counter cleaning",
     "Laminate countertop cleaning | F | C | plastic laminate cleaning",
     "Reception and service desk detailing | F | C | front desk cleaning",
     "Shelving and adjustable shelf cleaning | F | C | shelf cleaning",
     "Closet rod and shelf cleaning | F | C | closet cleaning",
     "Trim, casing and crown molding cleaning | F | C | trim cleaning",
     "Baseboard and wall base cleaning | F | C | baseboard cleaning; cove base cleaning",
     "Wood paneling and wainscot cleaning | F | C | wainscot cleaning",
     "Handrail and guardrail cleaning | F | C | railing cleaning",
     "Built-in bench and banquette cleaning | F | C | banquette cleaning",
     "Locker interior and exterior cleaning | F | C | locker cleaning",
     "Toilet partition and urinal screen cleaning | F | C | partition cleaning",
     "Window treatment and blind dusting | F | C | blind cleaning",
     "Window sill and stool cleaning | F | C | sill cleaning",
    ]),
])

fam("Glass, Windows & Glazing", [
  g("Construction window cleaning",
    "New glass arrives with labels, paint, stucco and concrete splatter; improper scraping scratches tempered and coated glass and becomes a warranty fight.",
    "Lubricated scraping only where appropriate, coating-safe cleaners, and pure-water rinsing reduce chemical use and protect low-E coatings.",
    ["Interior window cleaning | F | C | inside window washing",
     "Exterior window cleaning | F | C | outside window washing",
     "Storefront glass cleaning | F | C | storefront window cleaning",
     "Window label and sticker removal | F | C | glass sticker removal; NFRC label removal",
     "Construction debris removal from glass | F | C | paint and stucco removal from glass",
     "Concrete and mortar splatter removal from glass | F | A | concrete on glass removal",
     "Window track and frame cleaning | F | C | window track cleaning",
     "Window screen cleaning and installation | F | C | screen cleaning",
     "Glass partition and interior glazing cleaning | F | C | glass partition cleaning",
     "Glass railing and balustrade cleaning | F | C | glass rail cleaning",
     "Shower glass and enclosure cleaning | F | C | shower door cleaning",
     "Mirror cleaning and edge detailing | F | C | mirror cleaning",
     "Display case and showcase glass cleaning | F | C | showcase cleaning",
     "Skylight cleaning | F | A | skylight washing",
     "Curtain wall cleaning | F | X | curtain wall washing",
     "High-rise exterior glass cleaning | F | X | rope access window cleaning; swing stage window cleaning",
     "Hard water stain removal from glass | A | A | mineral deposit removal; glass restoration",
     "Glass scratch assessment and documentation | A | A | scratch survey",
     "Glass protective film removal | F | C | glass film removal",
     "Pure-water fed-pole window cleaning | A | C | water fed pole cleaning",
    ]),
])

fam("Hard Floors", [
  g("Concrete floors",
    "New slabs carry mud, sealer haze, tire marks and curing residue; floor appearance drives the owner's first impression.",
    "Auto-scrubbing with neutral or low-alkaline solutions and controlled water recovery avoids acid etching and runoff.",
    ["Concrete floor auto-scrubbing | F | C | slab scrubbing; machine scrub",
     "Warehouse floor scrubbing | F | C | warehouse floor cleaning",
     "Sealed concrete floor cleaning | F | C | sealed slab cleaning",
     "Polished concrete maintenance clean | F | C | polished concrete cleaning",
     "Concrete polishing | A | X | concrete grinding and polishing",
     "Concrete grinding preparation | A | X | slab grinding",
     "Curing compound residue removal | F | A | cure and seal residue removal",
     "Tire mark and forklift mark removal | F | C | tire mark removal",
     "Concrete stain and oil spot treatment | F | C | oil stain removal",
     "Concrete efflorescence removal | A | A | efflorescence cleaning; white haze removal",
     "Rust stain removal from concrete | A | A | rust spot removal",
     "Paint and coating drip removal from concrete | F | C | paint drip removal",
     "Joint and crack debris vacuuming | F | C | control joint cleanout",
     "Densifier and guard application support | A | A | densifier application",
     "Epoxy floor preparation cleaning | A | A | epoxy prep clean",
     "Epoxy and resinous floor cleaning | F | C | epoxy floor cleaning",
     "Parking garage floor scrubbing | F | C | garage floor cleaning",
    ]),
  g("Resilient floors (VCT, LVT, sheet vinyl, rubber)",
    "Resilient floors need correct initial care; the wrong chemical voids manufacturer warranties.",
    "Manufacturer-approved, low-VOC finishes and neutral cleaners match the warranty and reduce off-gassing.",
    ["VCT initial floor finish | F | C | VCT initial wax; new VCT finishing",
     "VCT strip and refinish | A | C | VCT stripping and waxing",
     "VCT scrub and recoat | M | C | scrub and recoat",
     "LVT and LVP manufacturer-approved cleaning | F | C | luxury vinyl cleaning",
     "Sheet vinyl initial clean | F | C | sheet vinyl cleaning",
     "Rubber floor initial cleaning | F | C | rubber flooring cleaning",
     "Sports and gym floor rubber cleaning | F | A | athletic rubber floor cleaning",
     "Linoleum and marmoleum initial care | F | A | linoleum cleaning",
     "Static-dissipative floor cleaning | F | A | ESD floor cleaning",
     "Adhesive residue removal from resilient floors | F | C | floor adhesive removal",
     "Scuff and heel mark removal | F | C | scuff removal",
     "Burnishing | M | C | floor burnishing; high speed buffing",
    ]),
  g("Tile, stone and terrazzo",
    "Grout haze and setting-material film dull new tile and stone and are hard to remove once cured.",
    "Grout-haze removers matched to the stone type — non-acidic on calcareous stone — avoid etching and re-work.",
    ["Ceramic and porcelain tile initial clean | F | C | tile floor cleaning",
     "Grout haze removal | F | C | grout film removal; tile haze removal",
     "Grout line deep cleaning | A | C | grout cleaning",
     "Grout sealing | A | A | grout sealer application",
     "Quarry tile cleaning | F | C | quarry tile degreasing",
     "Natural stone floor initial clean | F | A | marble floor cleaning; stone floor cleaning",
     "Stone polishing and honing | A | X | marble polishing; stone restoration",
     "Terrazzo initial clean | F | A | terrazzo cleaning",
     "Terrazzo polishing | A | X | terrazzo restoration",
     "Mosaic and specialty tile detailing | F | A | mosaic cleaning",
     "Thinset and mortar splatter removal | F | C | mortar removal from tile",
    ]),
  g("Wood and specialty floors",
    "Wood floors are finish-sensitive; water and wrong chemistry cause cupping, hazing and warranty claims.",
    "Low-moisture, wood-safe cleaners and microfiber methods protect new finishes.",
    ["Hardwood floor initial clean | F | C | wood floor cleaning",
     "Engineered wood floor cleaning | F | C | engineered floor cleaning",
     "Gym and athletic hardwood floor cleaning | F | A | gym floor cleaning",
     "Bamboo and cork floor cleaning | F | A | cork floor cleaning",
     "Raised access floor cleaning | F | A | raised floor cleaning; data center floor tile cleaning",
     "Entrance mat and grate cleaning | F | C | walk-off grate cleaning",
     "Stair tread and nosing cleaning | F | C | stair cleaning",
    ]),
])

fam("Carpet & Soft Surfaces", [
  g("Carpet and textiles",
    "New carpet traps drywall dust and adhesive; poor extraction leaves wicking stains that reappear after turnover.",
    "Low-moisture extraction and neutral-pH rinse agents reduce drying time, residue and resoiling.",
    ["Construction carpet vacuuming | F | C | carpet vacuum",
     "Carpet extraction | F | C | hot water extraction; carpet shampoo",
     "Carpet tile cleaning | F | C | carpet tile vacuum and spot",
     "Carpet spot and stain treatment | F | C | carpet spotting",
     "Drywall mud and paint removal from carpet | F | C | paint on carpet removal",
     "Carpet seam and edge detailing | F | C | carpet edge vacuum",
     "Upholstery and furniture vacuuming | O | C | upholstery cleaning",
     "Upholstery extraction | O | A | furniture shampoo",
     "Fabric panel and cubicle cleaning | O | C | cubicle panel cleaning",
     "Entrance carpet and walk-off mat cleaning | F | C | walk-off mat cleaning",
     "Auditorium and theater seating cleaning | O | A | theater seat cleaning",
    ]),
])

fam("Restrooms & Plumbing Fixtures", [
  g("Restroom detailing",
    "Restrooms are inspected closely; caulk smears, sticker residue and grout haze are routine punch items.",
    "Non-acidic descalers and neutral cleaners protect new chrome, solid surface and grout.",
    ["Toilet and urinal detailing | F | C | toilet cleaning; urinal cleaning",
     "Sink and faucet detailing | F | C | lavatory cleaning",
     "Restroom fixture sticker and label removal | F | C | fixture label removal",
     "Caulk smear and silicone haze removal | F | C | caulk residue removal",
     "Shower and tub detailing | F | C | shower cleaning",
     "Restroom accessory cleaning | F | C | dispenser cleaning; grab bar cleaning",
     "Hand dryer cleaning | F | C | hand dryer detailing",
     "Floor drain and trap primer area cleaning | F | C | floor drain cleaning",
     "Restroom tile and grout detailing | F | C | restroom grout cleaning",
     "Drinking fountain and bottle filler cleaning | F | C | water fountain cleaning",
     "Mop sink and janitor closet cleaning | F | C | janitor closet cleaning",
     "Eyewash and emergency shower station cleaning | F | A | eyewash cleaning",
     "Plumbing fixture first-flush and aerator debris check | F | A | aerator cleaning",
    ]),
])

fam("Kitchens, Food Facilities & FRP", [
  g("Commercial kitchen turnover",
    "Food facilities cannot open until surfaces pass health inspection; construction dust in a kitchen is a food-safety finding.",
    "Food-safe, residue-free cleaners and a separate sanitizing step done only with registered products used per label.",
    ["Commercial kitchen post-construction clean | F | C | restaurant construction cleanup; kitchen turnover clean",
     "Stainless steel equipment exterior cleaning | F | C | stainless cleaning; stainless polishing",
     "Stainless steel protective film removal | F | C | PVC film removal from stainless",
     "Kitchen hood exterior cleaning | F | C | hood exterior cleaning",
     "Kitchen exhaust hood and duct cleaning | A | X | hood cleaning; NFPA 96 hood cleaning; grease duct cleaning",
     "Walk-in cooler interior cleaning | F | C | walk-in cleaning",
     "Walk-in freezer interior cleaning | F | C | freezer box cleaning",
     "Reach-in refrigeration cleaning | F | C | reach-in cleaning",
     "Kitchen ceiling cleaning | F | C | kitchen ceiling degreasing",
     "Food-contact surface pre-opening cleaning | F | C | food contact surface cleaning",
     "Food-contact surface sanitizing per label | F | A | sanitizing food surfaces",
     "Prep table and shelving cleaning | F | C | prep table cleaning",
     "Dish area and dish machine exterior cleaning | F | C | dishroom cleaning",
     "Grease trap area cleaning | A | A | grease interceptor area cleaning",
     "Bar and beverage station cleaning | F | C | bar cleaning",
     "Ice machine exterior cleaning | F | C | ice machine cleaning",
     "Ice machine interior cleaning and sanitizing | F | X | ice machine sanitizing",
     "Dry storage room cleaning | F | C | pantry cleaning",
     "Quarry tile kitchen floor degreasing | F | C | kitchen floor degreasing",
     "Kitchen floor drain and trench drain cleaning | F | C | trench drain cleaning",
    ]),
  g("FRP and washable wall systems",
    "FRP collects dust and adhesive squeeze-out at seams; health inspectors look for cleanable, intact wall surfaces.",
    "Non-abrasive, neutral cleaners prevent FRP surface fiber bloom that later traps soil.",
    ["FRP wall cleaning | F | C | FRP panel cleaning",
     "FRP wall degreasing | A | C | FRP degreasing",
     "FRP adhesive squeeze-out removal | F | C | FRP glue removal",
     "FRP trim and seam detailing | F | C | FRP joint cleaning",
     "Insulated metal panel wall cleaning | F | C | cooler wall panel cleaning",
    ]),
  g("Grocery and food retail",
    "Grocery openings stack many trades into a short window; departments open on fixed dates with zero tolerance for dust.",
    "Food-zone cleaning with residue-free products and HEPA capture overhead before merchandise is set.",
    ["Grocery store post-construction cleaning | F | C | supermarket construction cleaning",
     "Refrigerated case detailing | F | C | reach-in case cleaning; refrigerated display cleaning",
     "Deli department finish cleaning | F | C | deli cleaning",
     "Bakery department finish cleaning | F | C | bakery cleaning",
     "Meat and seafood department finish cleaning | F | C | meat room cleaning",
     "Produce department finish cleaning | F | C | produce area cleaning",
     "Checkstand and conveyor cleaning | F | C | checkout cleaning",
     "Receiving and loading bay cleaning | F | C | back dock cleaning",
     "Convenience store remodel cleanup | F | C | c-store cleaning",
     "Food plant post-construction cleaning | F | A | food processing plant cleaning",
    ]),
])

fam("Mechanical, Electrical & Construction IAQ", [
  g("Mechanical and electrical rooms",
    "Mechanical and electrical rooms are where dust damages new equipment; inspectors and commissioning agents flag dirty rooms.",
    "Non-invasive HEPA and dry methods only on energized-area surfaces; no liquids near live gear.",
    ["Mechanical room cleaning | F | C | boiler room cleaning; MER cleaning",
     "Electrical room non-invasive cleaning | F | A | electrical room cleaning",
     "Equipment exterior wipe-down | F | C | equipment cleaning",
     "Air handler exterior cleaning | F | C | AHU exterior cleaning",
     "Air handler interior cleaning | A | X | AHU coil and plenum cleaning",
     "HVAC duct interior cleaning | A | X | duct cleaning; NADCA duct cleaning",
     "Rooftop unit exterior and curb cleaning | F | A | RTU cleaning",
     "Generator and switchgear exterior cleaning | F | X | switchgear dusting",
     "Fire pump and riser room cleaning | F | C | riser room cleaning",
     "Telecom and IDF/MDF room cleaning | F | A | IDF cleaning; telecom room cleaning",
     "Elevator machine room cleaning | F | A | elevator machine room cleaning",
     "Chiller and boiler exterior cleaning | F | A | chiller cleaning",
    ]),
  g("Construction indoor air quality support",
    "Green-building and owner specs require HVAC protection and clean ductwork before occupancy; dust in ducts becomes an IAQ complaint.",
    "This is the core of a green construction cleanup: keep dust out of the air system and document it.",
    ["Duct opening seal inspection and re-seal cleanup | P | A | duct capping",
     "Return grille temporary filter media change | P | A | temporary filter change",
     "Final HVAC filter replacement coordination | F | A | filter change before occupancy",
     "Pre-flush-out final cleaning | F | A | flush-out prep clean",
     "Construction IAQ photo documentation | A | A | IAQ plan photos",
     "Low-VOC product log for cleaning materials | A | A | cleaning product VOC log",
    ]),
])

fam("Retail Fixtures & Store Opening", [
  g("Store opening and fixture cleaning",
    "Retail openings run on a fixed grand-opening date; merchandise cannot be set on dusty fixtures.",
    "Fixture-safe cleaners and HEPA dusting before merchandise is set reduce re-cleaning.",
    ["Store opening clean | F | C | grand opening cleaning; new store cleaning",
     "Gondola shelving detailing | F | C | gondola cleaning",
     "Wall fixture and slatwall cleaning | F | C | slatwall cleaning",
     "Display fixture and mannequin cleaning | F | C | fixture cleaning",
     "Fitting room cleaning | F | C | dressing room cleaning",
     "Point-of-sale counter detailing | F | C | POS cleaning",
     "Merchandise set support cleaning | O | C | merchandising support clean",
     "Stockroom and backroom cleaning | F | C | stockroom cleaning",
     "Retail remodel overnight cleaning | A | C | night remodel cleaning",
     "Phased store remodel cleaning | A | C | remodel phase cleaning",
     "Multi-site retail rollout cleaning | A | C | national rollout cleaning; program cleaning",
     "Restaurant chain opening clean | F | C | QSR opening cleaning",
     "Bank branch opening clean | F | C | branch opening cleaning",
     "Pharmacy and clinic retail opening clean | F | A | pharmacy opening clean",
    ]),
])

fam("Specialty & Controlled Environments", [
  g("Healthcare, lab and controlled spaces",
    "Healthcare and controlled environments have protocol-driven cleaning before occupancy; generic cleaning fails these specs.",
    "Protocol-matched products, HEPA, and documented methods — routed only to providers with the right training.",
    ["Healthcare post-construction terminal-style clean | F | X | hospital construction cleaning",
     "Medical office post-construction clean | F | A | medical office cleaning",
     "Dental office post-construction clean | F | A | dental office cleaning",
     "Operating room post-construction clean | F | X | OR construction cleaning",
     "Laboratory post-construction clean | F | X | lab cleaning",
     "Fume hood exterior cleaning | F | A | fume hood cleaning",
     "Cleanroom protocol cleaning | F | X | cleanroom certification cleaning",
     "Pharmacy compounding room cleaning | F | X | USP 797 room cleaning",
     "Data center post-construction cleaning | F | X | data center cleaning",
     "Sub-floor plenum cleaning in data centers | F | X | underfloor cleaning",
     "Server rack exterior cleaning | F | X | rack cleaning",
     "Controlled contamination cleaning | A | X | contamination control cleaning",
     "Vivarium and animal facility cleaning | F | X | vivarium cleaning",
    ]),
  g("Education, hospitality and assembly",
    "Schools, hotels and venues open on hard deadlines with many identical rooms; consistency at scale matters.",
    "Room-by-room checklists and low-odor methods support fast occupancy.",
    ["School post-construction cleaning | F | C | school construction cleaning",
     "Classroom turnover cleaning | O | C | classroom cleaning",
     "Dormitory and student housing turnover | O | C | dorm cleaning",
     "Hotel room post-construction cleaning | F | C | hotel PIP cleaning; hotel renovation cleaning",
     "Hotel public area post-construction cleaning | F | C | hotel lobby cleaning",
     "Fitness center post-construction cleaning | F | C | gym construction cleaning",
     "Pool deck and natatorium cleaning | F | A | pool area cleaning",
     "Church and worship space post-construction cleaning | F | C | church cleaning",
     "Theater and auditorium post-construction cleaning | F | C | auditorium cleaning",
     "Arena and stadium post-construction cleaning | F | A | stadium cleaning",
     "Library stack and shelving cleaning | F | C | library cleaning",
    ]),
  g("Industrial and warehouse",
    "Distribution and industrial buildings are huge, fast-track and measured by the square foot.",
    "Ride-on scrubbers with water recovery and HEPA sweepers cut water use on large slabs.",
    ["Warehouse post-construction cleaning | F | C | distribution center cleaning",
     "Pallet rack cleaning | F | C | warehouse rack cleaning",
     "Industrial equipment exterior cleaning | F | A | machine exterior cleaning",
     "Conveyor system exterior cleaning | F | A | conveyor cleaning",
     "Manufacturing plant post-construction cleaning | F | A | factory cleaning",
     "Cold storage facility cleaning | F | A | cold storage cleaning",
     "Truck court and dock apron sweeping | F | C | truck court sweeping",
    ]),
])

fam("Exterior, Hardscape & Building Envelope", [
  g("Exterior surfaces",
    "Curb appeal, accessibility routes and storm-water rules all apply at closeout; exterior mud and debris are the first things an owner sees.",
    "Water reclamation, biodegradable detergents where verified, and storm-drain protection keep wash water out of drains.",
    ["Sidewalk pressure washing | F | C | sidewalk cleaning",
     "Parking lot sweeping | F | C | lot sweeping; power sweeping",
     "Parking lot washing | F | A | lot washing",
     "Parking garage washing | F | C | garage power washing",
     "Loading dock washing | F | C | dock washing",
     "Dumpster pad degreasing | F | C | dumpster pad cleaning",
     "Building facade washing | F | A | facade cleaning; exterior wall washing",
     "Exterior soft washing | F | A | soft wash",
     "Brick and masonry cleaning | F | A | brick cleaning; mortar smear removal",
     "Masonry efflorescence removal | A | A | brick efflorescence removal",
     "Stucco and EIFS cleaning | F | A | EIFS cleaning",
     "Metal panel and canopy cleaning | F | C | canopy cleaning",
     "Paver and hardscape cleaning | F | C | paver cleaning",
     "Paver joint sand cleanup | F | C | paver sand cleanup",
     "Entryway and vestibule cleaning | F | C | entry cleaning",
     "Exterior signage and monument sign cleaning | F | C | sign cleaning",
     "Exterior light fixture and pole base cleaning | F | C | site light cleaning",
     "Site furniture and bike rack cleaning | F | C | site furnishing cleaning",
     "Landscape bed debris removal | F | C | planter debris cleanup",
     "Storm drain inlet protection cleanup | F | A | inlet protection removal",
     "Silt fence and erosion control debris cleanup | F | A | erosion control cleanup",
     "Curb and gutter cleaning | F | C | curb cleaning",
     "Wastewater recovery during washing | A | A | wash water reclamation",
     "Graffiti removal | A | A | graffiti cleaning",
     "Rust and irrigation stain removal from hardscape | A | A | rust removal from concrete",
     "Roof debris removal | F | A | roof cleanup",
     "Gutter and downspout debris removal | F | C | gutter cleaning",
     "Balcony and terrace cleaning | F | C | balcony cleaning",
     "Solar array cleaning | A | X | solar panel cleaning",
    ]),
])

fam("Residue, Stain & Protective-Material Removal", [
  g("Residue removal",
    "Residues are the hardest items on a punch list; the wrong removal method damages new finishes and creates re-work.",
    "Least-aggressive-first method selection: mechanical and neutral options before solvents, and surface-tested before use.",
    ["Paint overspray removal | F | C | overspray removal",
     "Paint drip and splatter removal | F | C | paint spot removal",
     "Adhesive residue removal | F | C | glue removal; mastic removal",
     "Tape residue removal | F | C | painter's tape residue removal",
     "Caulk and sealant smear removal | F | C | sealant removal",
     "Grout and setting material haze removal | F | C | haze removal",
     "Stucco and plaster splatter removal | F | C | plaster removal",
     "Concrete and mortar splatter removal | F | C | cement splatter removal",
     "Spray foam overspray removal | F | A | foam overspray removal",
     "Fireproofing overspray removal | F | X | SFRM overspray removal",
     "Joint compound film removal | F | C | mud film removal",
     "Pencil, marker and layout line removal | F | C | layout mark removal",
     "Label, sticker and UPC removal | F | C | sticker removal",
     "Protective film removal from appliances and fixtures | F | C | blue film removal; protective plastic removal",
     "Rust stain removal from finishes | A | A | rust stain removal",
     "Water spot and mineral deposit removal | A | C | hard water spot removal",
     "Tar and roofing material removal | A | A | tar removal",
     "Fingerprint and smudge removal | T | C | smudge cleaning",
    ]),
  g("Protection install and removal",
    "Protection keeps finished work from being damaged; its removal and the dust under it are often left out of every trade's scope.",
    "Reusable protection where possible, and capture of dust trapped under protection before it spreads.",
    ["Floor protection installation | P | C | Ram Board install; floor protection",
     "Floor protection removal and disposal | F | C | floor protection removal",
     "Adhesive under floor protection cleanup | F | C | protection tape residue cleanup",
     "Elevator cab protection install and removal | P | C | elevator pad removal",
     "Door and frame protection removal | F | C | door protection removal",
     "Countertop and fixture protection removal | F | C | counter protection removal",
     "Window and glass protection removal | F | C | window film removal",
     "Carpet protection film removal | F | C | carpet film removal",
     "Temporary walk-off mat placement and removal | P | C | temporary mats",
    ]),
])

fam("Vertical Transportation & Circulation", [
  g("Elevators, escalators and stairs",
    "Elevators are inspected and used by every visitor; stairwells collect the most construction debris.",
    "Stainless-safe cleaners and HEPA vacuuming of sills and pits without solvents.",
    ["Elevator cab interior detailing | F | C | elevator cleaning",
     "Elevator door and sill track cleaning | F | C | elevator sill cleaning",
     "Elevator pit debris removal | F | A | elevator pit cleaning",
     "Escalator and moving walk cleaning | F | X | escalator cleaning",
     "Stairwell cleaning top to bottom | F | C | stair tower cleaning",
     "Stair nosing and tread detailing | F | C | stair nosing cleaning",
     "Corridor and hallway detailing | F | C | corridor cleaning",
     "Lobby final detailing | F | C | lobby cleaning",
    ]),
])

fam("Turnover, Punch & Closeout Support", [
  g("Final clean and turnover",
    "Final clean is required before Substantial Completion inspection; a failed walk delays the certificate and payment.",
    "Final clean with low-odor, low-residue products so the space is ready for occupancy without lingering chemical smell.",
    ["Final clean of entire building | F | C | final cleaning; phase 3 clean; sparkle clean",
     "Final clean by phase or floor | F | C | phased final clean",
     "Light clean (phase 2) | P | C | second clean; detail clean",
     "Touch-up clean before owner walk | T | C | touch-up clean; sparkle clean",
     "Punch-list cleaning | T | C | punch list cleanup",
     "Re-clean after punch work | T | C | after-trade re-clean; re-clean",
     "Pre-substantial completion clean | F | C | substantial completion clean",
     "Pre-certificate of occupancy clean | F | C | CO inspection clean",
     "Pre-health inspection clean | F | C | health inspection prep",
     "Pre-fire marshal inspection clean | F | C | fire inspection prep",
     "Owner move-in clean | O | C | move-in cleaning",
     "Tenant improvement final clean | F | C | TI cleaning; tenant buildout cleaning",
     "Phased occupancy cleaning | O | C | partial occupancy clean",
     "Post-furniture install clean | O | C | after FF&E clean",
     "Post-IT and AV install clean | O | C | after low voltage clean",
     "Model unit and show suite cleaning | O | C | model home cleaning",
     "Vacant space turnover cleaning | O | C | vacant tenant turnover",
     "Property management turnover cleaning | O | C | PM turnover",
     "Post-renovation reset clean | O | C | renovation cleanup",
     "Post-equipment installation cleaning | O | C | after equipment install clean",
     "Emergency or overnight turnaround clean | A | C | rush clean; overnight clean",
    ]),
  g("Closeout documentation support",
    "GCs need proof of cleaning for closeout packages, LEED documentation and dispute protection.",
    "Documenting products and methods used is what makes a green claim credible.",
    ["Before-and-after photo documentation | A | C | cleaning photo log",
     "Room-by-room cleaning checklist sign-off | F | C | cleaning checklist",
     "Cleaning product SDS and data sheet package | F | C | SDS binder",
     "Attic stock and spare material staging | F | C | attic stock staging",
     "Owner training area preparation | O | C | training room setup",
    ]),
])

fam("Multifamily & Residential-Scale Turnover", [
  g("Multifamily units",
    "Multifamily projects turn over dozens of identical units on rolling schedules; speed and consistency set the pace.",
    "Repeatable unit checklists with low-odor products for fast lease-up.",
    ["Apartment unit post-construction clean | F | C | apartment construction cleaning",
     "Condo unit final clean | F | C | condo cleaning",
     "Townhome final clean | F | C | townhouse cleaning",
     "Amenity space final clean | F | C | clubhouse cleaning",
     "Leasing office final clean | F | C | leasing office cleaning",
     "Appliance interior and exterior cleaning | F | C | appliance cleaning",
     "Range hood and microwave detailing | F | C | range hood cleaning",
     "Washer and dryer area cleaning | F | C | laundry room cleaning",
     "Dryer vent debris check | F | A | dryer vent cleaning",
     "Garage and storage unit cleaning | F | C | storage cleaning",
     "Mailroom and package room cleaning | F | C | mailroom cleaning",
     "Trash room and chute room cleaning | F | C | trash room cleaning",
    ]),
])

fam("Restoration & Regulated Work (Conditional)", [
  g("Restoration and regulated scopes",
    "These scopes carry licensing, testing and liability; they are listed so buyers can find them, but routed only to properly licensed providers.",
    "Regulated protocols govern products and disposal here — claims follow the license holder's protocol.",
    ["Water damage cleanup | A | X | flood cleanup",
     "Mold remediation | A | X | mold removal",
     "Fire and smoke residue cleaning | A | X | smoke damage cleaning; soot removal",
     "Asbestos abatement | A | X | asbestos removal",
     "Lead paint abatement | A | X | lead removal",
     "Biohazard and sharps cleanup on jobsites | A | X | biohazard cleaning",
     "Bird and pest dropping removal | A | X | guano removal",
     "Hazardous material spill cleanup | A | X | hazmat cleanup",
     "Disinfection service with registered products | A | X | disinfecting; EPA-registered disinfection",
     "Post-event facility restoration | A | X | post-storm cleanup; hurricane cleanup",
    ]),
])

# ---------------------------------------------------------------------------
PHASE = {"R": "Rough", "P": "Progress", "F": "Final", "T": "Touch-up / punch",
         "O": "Occupancy / turnover", "A": "Any stage / specialty",
         "M": "Recurring maintenance"}
TIER = {"C": "Core", "A": "Adjacent specialist", "X": "Conditional / regulated"}

def slug(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")

rows = []
for fi, (fname, groups) in enumerate(DATA, 1):
    for gi, (gname, why, green, tasks) in enumerate(groups, 1):
        for ti, line in enumerate(tasks, 1):
            name, ph, tier, aliases = [p.strip() for p in line.split("|")]
            aliases = [a.strip() for a in aliases.split(";") if a.strip()]
            rows.append({
                "id": f"BK-{fi:02d}{gi:02d}{ti:02d}",
                "family": fname,
                "group": gname,
                "task": name,
                "slug": slug(name),
                "phase": PHASE[ph],
                "tier": TIER[tier],
                "aelc_feed": "Yes" if fname.startswith("Overhead") else "",
                "aliases": "; ".join(aliases),
                "alias_count": len(aliases),
                "why_it_matters": why,
                "beyond_klean_method": green,
            })

# Overlap analysis: an alias that collides with another task's name or alias
names = defaultdict(list)
for r in rows:
    names[r["task"].lower()].append(r["id"])
    for a in r["aliases"].split("; "):
        if a:
            names[a.lower()].append(r["id"])
collisions = {k: v for k, v in names.items() if len(set(v)) > 1}
dup_slugs = [k for k, c in Counter(r["slug"] for r in rows).items() if c > 1]

for r in rows:
    shared = sorted({i for k, v in collisions.items() if r["id"] in v for i in v} - {r["id"]})
    r["overlaps_with"] = "; ".join(shared)

with open(OUT / "tasks.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader(); w.writerows(rows)
(OUT / "tasks.json").write_text(json.dumps(rows, indent=1))

stats = {
    "unique_tasks": len(rows),
    "families": len(DATA),
    "groups": sum(len(g) for _, g in DATA),
    "market_names_incl_aliases": len(rows) + sum(r["alias_count"] for r in rows),
    "by_family": Counter(r["family"] for r in rows),
    "by_tier": Counter(r["tier"] for r in rows),
    "by_phase": Counter(r["phase"] for r in rows),
    "aelc_feed_tasks": sum(1 for r in rows if r["aelc_feed"]),
    "cross_task_name_collisions": collisions,
    "duplicate_slugs": dup_slugs,
}
(OUT / "stats.json").write_text(json.dumps(stats, indent=1))
print(json.dumps({k: v for k, v in stats.items() if k != "cross_task_name_collisions"}, indent=1))
print("collisions:", json.dumps(collisions, indent=1))

# ---------------------------------------------------------------------------
# Semantic overlap clusters (hand-reviewed).
#   merge   = same work under two names -> one page, other name becomes an alias
#   variant = same method on a different surface/area -> parent page + sections
#   bundle  = distinct tasks normally bought together -> separate pages, cross-linked
CLUSTERS = [
 ("Grout haze", "merge", ["Grout haze removal", "Grout and setting material haze removal"]),
 ("Stair treads", "merge", ["Stair tread and nosing cleaning", "Stair nosing and tread detailing"]),
 ("Walk-off mats", "merge", ["Entrance mat and grate cleaning", "Entrance carpet and walk-off mat cleaning"]),
 ("Baseboards", "merge", ["Baseboard and wall base cleaning", "Fine dust removal from baseboards"]),
 ("Late-trade re-clean", "merge", ["Dust re-clean after late-trade work", "Re-clean after punch work"]),
 ("Parking garage floors", "merge", ["Parking garage floor scrubbing", "Parking garage washing"]),
 ("Rack dusting", "merge", ["Pallet rack cleaning", "Top of shelving and racking dusting"]),
 ("Quarry tile", "merge", ["Quarry tile cleaning", "Quarry tile kitchen floor degreasing"]),
 ("Caulk smears", "merge", ["Caulk smear and silicone haze removal", "Caulk and sealant smear removal"]),
 ("Final clean", "merge", ["Final clean of entire building", "Pre-substantial completion clean"]),
 ("Silica housekeeping", "merge", ["Silica-aware housekeeping cleanup", "Silica-aware wet sweeping"]),
 ("Refrigerated cases", "merge", ["Refrigerated case detailing", "Reach-in refrigeration cleaning"]),
 ("Wall smudges", "merge", ["Spot cleaning of painted walls", "Fingerprint and smudge removal"]),
 ("Interior glass walls", "merge", ["Glass partition and interior glazing cleaning", "Glass wall and back-painted glass cleaning"]),
 ("Glass film", "merge", ["Glass protective film removal", "Window and glass protection removal"]),
 ("Hardscape rust", "merge", ["Rust stain removal from concrete", "Rust and irrigation stain removal from hardscape"]),
 ("Concrete/mortar splatter", "variant", ["Concrete and mortar splatter removal", "Concrete and mortar splatter removal from glass", "Thinset and mortar splatter removal"]),
 ("Adhesive residue", "variant", ["Adhesive residue removal", "Adhesive residue removal from resilient floors", "Adhesive under floor protection cleanup", "FRP adhesive squeeze-out removal", "Tape residue removal"]),
 ("Paint residue", "variant", ["Paint overspray removal", "Paint drip and splatter removal", "Paint and coating drip removal from concrete", "Slab scraping of overspray and drips", "Drywall mud and paint removal from carpet"]),
 ("Efflorescence", "variant", ["Concrete efflorescence removal", "Masonry efflorescence removal"]),
 ("Protective film", "variant", ["Protective film removal from appliances and fixtures", "Stainless steel protective film removal", "Glass protective film removal", "Carpet protection film removal"]),
 ("Mineral deposits", "variant", ["Hard water stain removal from glass", "Water spot and mineral deposit removal"]),
 ("Labels and stickers", "variant", ["Label, sticker and UPC removal", "Window label and sticker removal", "Restroom fixture sticker and label removal", "Removal of sticker and label backing debris"]),
 ("Ceiling fans", "variant", ["Ceiling fan cleaning", "HVLS ceiling fan cleaning"]),
 ("Rough clean scope", "variant", ["Rough clean of entire building", "Rough clean by floor or phase"]),
 ("Final clean scope", "variant", ["Final clean of entire building", "Final clean by phase or floor", "Tenant improvement final clean"]),
 ("Natural stone", "variant", ["Natural stone countertop cleaning", "Natural stone floor initial clean", "Stone and tile wall cleaning"]),
 ("Equipment exteriors", "variant", ["Equipment exterior wipe-down", "Air handler exterior cleaning", "Chiller and boiler exterior cleaning", "Rooftop unit exterior and curb cleaning"]),
 ("Stainless surfaces", "variant", ["Stainless steel equipment exterior cleaning", "Stainless and metal wall panel cleaning"]),
 ("Rust stains", "variant", ["Rust stain removal from concrete", "Rust stain removal from finishes"]),
 ("Concrete dust", "variant", ["Concrete dust removal after grinding or saw cutting", "Silica-aware housekeeping cleanup", "Fine drywall dust removal from all horizontal surfaces"]),
 ("Window sills", "bundle", ["Window sill and opening rough wipe", "Window sill and stool cleaning", "Window track and frame cleaning"]),
 ("Punch & touch-up", "bundle", ["Touch-up clean before owner walk", "Punch-list cleaning", "Dust re-clean after late-trade work", "Trade-area cleanup between trades"]),
 ("Fireproofing", "bundle", ["Fireproofing overspray removal", "Spray-applied fireproofing area light dusting"]),
 ("Kitchen hoods", "bundle", ["Kitchen hood exterior cleaning", "Kitchen exhaust hood and duct cleaning"]),
 ("Ice machines", "bundle", ["Ice machine exterior cleaning", "Ice machine interior cleaning and sanitizing"]),
 ("Skylights", "bundle", ["Skylight cleaning", "Skylight well and light shaft cleaning"]),
 ("Dock area", "bundle", ["Receiving and loading bay cleaning", "Loading dock washing", "Truck court and dock apron sweeping", "Sectional and dock door cleaning"]),
 ("Flatwork washing", "bundle", ["Sidewalk pressure washing", "Paver and hardscape cleaning", "Curb and gutter cleaning", "Entryway and vestibule cleaning"]),
 ("Elevators", "bundle", ["Elevator cab protection install and removal", "Elevator cab interior detailing", "Elevator door and sill track cleaning"]),
 ("Carpet", "bundle", ["Construction carpet vacuuming", "Carpet extraction", "Carpet spot and stain treatment"]),
 ("Floor protection", "bundle", ["Floor protection installation", "Floor protection removal and disposal", "Adhesive under floor protection cleanup"]),
 ("Overhead MEP", "bundle", ["Duct exterior cleaning", "Overhead piping exterior cleaning", "Sprinkler pipe exterior dusting", "Cable tray exterior dusting", "Conduit run dusting"]),
 ("Ceiling plane", "bundle", ["Acoustic ceiling tile spot cleaning", "Ceiling grid cleaning", "Ceiling diffuser and grille face cleaning"]),
 ("Kitchen sanitation", "bundle", ["Food-contact surface pre-opening cleaning", "Food-contact surface sanitizing per label"]),
 ("Construction IAQ", "bundle", ["Return grille temporary filter media change", "Final HVAC filter replacement coordination", "Pre-flush-out final cleaning", "Construction IAQ photo documentation"]),
]

by_name = {r["task"]: r for r in rows}
missing = [n for _, _, ns in CLUSTERS for n in ns if n not in by_name]
assert not missing, missing

for r in rows:
    r["merge_into"] = ""; r["variant_of"] = ""; r["bundle"] = ""
for cname, ctype, ns in CLUSTERS:
    if ctype == "merge":
        for n in ns[1:]:
            by_name[n]["merge_into"] = by_name[ns[0]]["id"]
    elif ctype == "variant":
        for n in ns:
            by_name[n]["variant_of"] = "; ".join(filter(None, [by_name[n]["variant_of"], cname]))
    else:
        for n in ns:
            by_name[n]["bundle"] = "; ".join(filter(None, [by_name[n]["bundle"], cname]))

merged = sum(1 for r in rows if r["merge_into"])
with open(OUT / "tasks.csv", "w", newline="") as f:
    w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    w.writeheader(); w.writerows(rows)
(OUT / "tasks.json").write_text(json.dumps(rows, indent=1))

ctype_counts = Counter(t for _, t, _ in CLUSTERS)
stats.update({
    "raw_task_lines": len(rows),
    "true_duplicates_merged": merged,
    "unique_after_merge": len(rows) - merged,
    "tasks_in_any_overlap_cluster": len({n for _, _, ns in CLUSTERS for n in ns}),
    "cluster_counts": ctype_counts,
    "clusters": [{"name": c, "type": t, "tasks": ns} for c, t, ns in CLUSTERS],
})
(OUT / "stats.json").write_text(json.dumps(stats, indent=1))
print({k: stats[k] for k in ["raw_task_lines", "true_duplicates_merged", "unique_after_merge",
                             "tasks_in_any_overlap_cluster", "cluster_counts", "market_names_incl_aliases"]})
